### PR TITLE
Westleach Tea Addition

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request
Adding undried westleach to barrels will create westleach tea.

## Why It's Good For The Game
Adds another beverage to be served. Good for maids, innkeepers, nobles, and forest dwellers!

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by SaintBurgher** [comment]
I'm having an issue here and could use some help... Seems like no matter what the westleach turns into liquid nicotine. Anyone have any idea why?

**Comment by ThePainkiller** [comment]
Have you tried assigning it to DRIED westleach leaves instead? By all accounts it shouldn't distill into its reagents...

**Comment by ThePainkiller** [comment]
Found your issue. The `makeWine(fruit)` proc is transferring reagents regardless and making liquid nicotine. This should be rewritten to avoid this.

`/obj/structure/fermenting_barrel/proc/makeWine(obj/item/reagent_containers/food/snacks/grown/fruit)`
`	if(fruit.reagents)`
`		fruit.reagents.remove_reagent(/datum/reagent/consumable/nutriment, fruit.reagents.total_volume)`
`		fruit.reagents.trans_to(src, fruit.reagents.total_volume)`
`	if(fruit.distill_reagent)`
`		reagents.add_reagent(fruit.distill_reagent, fruit.distill_amt)`
`		reagents.add_reagent(/datum/reagent/water, 3)`
`	qdel(fruit)`
`	playsound(src, "bubbles", 100, TRUE)`

**Comment by lavillastrangiato** [comment]
I know I'm kind of riding your ass here, muh realism, but why not make a type of leaf that's more suited to tea, instead of what's ostensibly a tobacco leaf?

They're pretty easy to define and give reagents, at least in my experience.

**Comment by SaintBurgher** [comment]
> I know I'm kind of riding your ass here, muh realism, but why not make a type of leaf that's more suited to tea, instead of what's ostensibly a tobacco leaf?
> 
> They're pretty easy to define and give reagents, at least in my experience.

Mainly because I am not sure if diluting the resource pool in regards to bushes would be a good idea. If people would prefer a new leaf though I could maybe add it as a drop for cutting down bushes instead of searching?

**Comment by ThePainkiller** [comment]
Any updates on this one? Have you manage to solve the reagents issue?

**Pull request closed without merging**
