### PR TITLE
Fixes Templar Bugs

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

Fixes a bug with templars allowing for eoran ones

## Why It's Good For The Game

Eoran Templars dont match the lore, nor to they have a godhelmet. Their existence is a bug

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by Cre77** [comment]
alpha up and delete ravox and pestra templars too, champ

**Comment by lavillastrangiato** [comment]
It is very clearly deliberately coded in. I don't know why you think that it is so wacky and crazy that Eorans would have templars; holy warriors of a love goddess exist twofold in Dungeons and Dragons, paladins of Sune and Sharess. It's that shrimple. Removing it is dumb.

**Comment by SELFHELL** [comment]
> alpha up and delete ravox and pestra templars too, champ

alright bet.

**Comment by DovaKitty** [comment]
Ermmm? Gem PR perchance??? What the sigma?

**Comment by Mogelix** [comment]
This is hearsay but I think Guayo said there weren't Eoran templars because lore reasons?

**Comment by Ickysoup** [comment]
image

**Comment by sanshoom** [comment]
> image
> 
> Real Eorans protect beauty at all cost. Eoran templars are that to the extreme.

Eoran templars on their way to Not do their job (it goes against eora)

**Comment by Ickysoup** [comment]
> > image
> > Real Eorans protect beauty at all cost. Eoran templars are that to the extreme.
> 
> Eoran templars on their way to Not do their job (it goes against eora)

Killing murderers, heretics, and other foul things is well within bounds. Eora's Garden won't tend its self.

**Comment by sanshoom** [comment]
can't note this but I found that templars for some reason don't spawn with a coif in their satchel, but the keyring does spawn.

backpack_contents = list(/obj/item/keyring/priest = 1, /obj/item/clothing/neck/roguetown/chaincoif = 1)

**Comment by NPC1314** [comment]
Making the templar helmets  have neck protection too anyways so the reason for keeping coifs in backpack is soon gone.

On Eoran templars though, it strikes me as the obvious setup should be Ravox Templars + Eora Acolytes. Like every pantheon god needs a bit of muscle and while theres nothing wrong with Eoran templars, having an alliance between ravox templars + eoran acolytes just seems reasonable. Also an opportunity to design a templar thats a bit different from the standard template, I got some ideas. 

The pacifism goodie two shoes Eoran take is truly uninspired though and sucks, the motive to pair Ravox templar and Eora acolyte isnt pacifism or something dumb like that, its because it reflects the lore/pantheon roles a bit, and gives Temple tole for ravoxians, and a natural plot point to RP about, do the ravoxian templar really stand by the eoran when in conflict with the astratan?

At the same time, Dendor templars and acolytes should GTFO from the Temple and just be druids, they really dont fit in well for real

**Comment by Mogelix** [comment]
> At the same time, Dendor templars and acolytes should GTFO from the Temple and just be druids, they really dont fit in well for real
This is one element in which more christianization would be welcome. Nuns, monks being towners and then with drifter friars is really preferable to the nonsense lore of 'nature cultists who live in a stone building' which just ends up leaving both unhappy as dendorians have to submit to the church and the church has to deal with some of its limited slots being taken up by acolytes who don't really interact with the church part of the church. Not like our current map has room for them to cultivate a garden.

As for all other questions, Guayo has said they exist so they exist.

**Pull request closed without merging**
