### PR TITLE
Speedmerge this PR, fixes triumph buy + Totod tweaks

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Reverts triumph buy back to 20 triumphs, because you can now, no longer select the following classes, TOWNER/GARRISON/ADEPT and CONSORT. Only PILGRIM and ADVENTURER roles can be selected from pick-class.

Gives the Totod Helm a name and a sprite

Gives the Totod Emissary a satchel, because he was meant to spawn with a rich pouch but can't

## Why It's Good For The Game

Fixes all around.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
dont speedmerge this pr

**Comment by sanshoom** [comment]
totod emissary (a class with chainmail, a great helm, and other armor pieces aswell as a long sword) is given a RICH POUCH?? Holy shit

**Comment by ThePainkiller** [comment]
That was what triumph buy was supposed to do all this time, only pilgrim and adventurer role unlock
In practice, it even allowed me to spawn as captain when readying as an adventurer.

**Comment by BadAtThisGame302** [comment]
> That was what triumph buy was supposed to do all this time, only pilgrim and adventurer role unlock In practice, it even allowed me to spawn as captain when readying as an adventurer.
> 
> **EDIT:** Also, as per last admin meeting, we are trying to move away from triumph buy making it a universal unlock for everything, the next step is to actually remove this function and replace it entirely with something like just extra clothing pieces or utility stuff.
> 
> Note 2: Asking for a speedmerge on anything non-immediate or critical bugfixes has been statistically proven to prevent the PR from being speedmerged by 200% chance

Womp womp.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
