### PR TITLE
Bell dresses and stockings update

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Ports this https://github.com/Tree445/Hearthstone/pull/143 (excluding the fishnets and strapless dress)

And takes the bell dresses from these two, https://github.com/Tree445/Hearthstone/pull/619, https://github.com/Tree445/Hearthstone/pull/246

Adds silk stockings to Princess, Noble Pilgrim and Stewardess

~~Gives a new unique dress for the Queen,~~ aswell as silk stockings and gives her the decorated gold circlet because it never spawned in her backpack

Adds normal stockings to the sewing tab and silk~~/bell dresses~~ to weaving.

## Why It's Good For The Game

The Ladies of our game felt under-appreciated. And why not take a few things to make them feel like proper ladies of a medieval world? 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
Not sure its up to snuff quality wise tbh but waiting on more feedback

**Comment by lavillastrangiato** [comment]
Yo. I posted this in the staff spriter chat, but I figure I'll post it here too:
Pretty much the only thing I'm okay with full-merging in this pr are the stockings. Unfortunately, the rest have very saturated palettes, palettes that don't really go super well with our colour scheme. The sprite quality of the dresses themselves range from okay to just bad, with the Queen's dress being the worst.

I still appreciate your porting attempts. I am happy to task the spriters to make some better dresses that go with our style.

**Comment by BadAtThisGame302** [comment]
> Yo. I posted this in the staff spriter chat, but I figure I'll post it here too: Pretty much the only thing I'm okay with full-merging in this pr are the stockings. Unfortunately, the rest have very saturated palettes, palettes that don't really go super well with our colour scheme. The sprite quality of the dresses themselves range from okay to just bad, with the Queen's dress being the worst.
> 
> I still appreciate your porting attempts. I am happy to task the spriters to make some better dresses that go with our style.

Right, I really can't be asked to go through and delete the dress sprites. I'll just make them unweavable and unbuyable. They'll still be an item only through admin only. Sound fair?

**Comment by NPC1314** [comment]
Can you pick I dunno, two best dress sprites and maybe stockings and take them to the spriter team and start there?
They could probably improve them with minor effort and make it a solid addition instead of a mixed bag.

**Comment by BadAtThisGame302** [comment]
> Can you pick I dunno, two best dress sprites and maybe stockings and take them to the spriter team and start there? They could probably improve them with minor effort and make it a solid addition instead of a mixed bag.

If the PR is merged and the sprites are in the code but not the game, then they have all the time after to individually pick a dress and make it so that it fits out style. Then we can remove the current shit ones and replace them with the new ones.

**Comment by NPC1314** [comment]
> > Can you pick I dunno, two best dress sprites and maybe stockings and take them to the spriter team and start there? They could probably improve them with minor effort and make it a solid addition instead of a mixed bag.
> 
> If the PR is merged and the sprites are in the code but not the game, then they have all the time after to individually pick a dress and make it so that it fits out style. Then we can remove the current shit ones and replace them with the new ones.

I sort of doubt anyone will ever put in that work and it will just end up getting added wholesale by someone in the search for the illusory magic content bullet, but guess it doesnt matter. Conflicts though.

**Pull request closed without merging**
