### PR TITLE
Drow and Tiefling Garrison update

### PR DESCRIPTION
**Pull request by Plaguewalker**
## About The Pull Request
Finally, offers garrison roles barring captain and veteran to tieflings and dark elves.

## Why It's Good For The Game
Garrison guard itself is more of the fodder guards before the captain and RG are needed, they should be willing to take most bodies for the job rather than selective about who's in the garrison itself.
Tieflings
tief guard
Delf
delf guard

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I mean our lore clearly states that these people are ostricized from society as a whole, thus why Tieflings and Drow are the most limited races both in code and by in-game, where most view them as monsters, zizo worshipping hellspawn for tieflings and murdering, backstabbing thieves for the Drow. 

Adding them to the Garrison hardly seems like anything that the Lore would approve of.

**Comment by Stutternov** [comment]
Currently lore conflicts with this; will require project lead approval.

**Comment by Plaguewalker** [comment]
Updated upon guayo's request: No veteran

**Comment by guayitoo** [comment]
Guayo here,

Tiefling & Drow are supposed to be discriminated against in lore. Though this is more on suspiciousness & inequality rather than straight up slavery & or genocide - at least regarding Enigma.

Drow & Tiefling being used for their combative skills as fodder & archers are fine, guards aren't necessarily supposed to be chums.

For the roles mentioned, with the understanding that it would only be Garrison Guard & Garrison Archer, I feel that is sufficiently fine lore wise. Players will still be able to RP and follow discriminatory lore.

This would also be a test to see, if by allowing these races the roles, it would revitalize the lack of guard players.

**Review by Stutternov — APPROVED** [review]
While I'm not a massive fan of this, given I could see maybe archers due to their support role to guard, I do feel it is a bit odd.

Given project heads approval though going to merge it.

**Pull request merged**
