### PR TITLE
Big stupid code cleanup (PART 1)

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request
Deletes a lot (and I mean a lot) of old TG shit, from this https://github.com/Vanderlin-Tales-Of-Wine/Vanderlin/pull/7.

Might be some minor issues with sexcon because formatting is proccing some weird syntax errors in living.dm but I'm dumb so IDK.

- Adds *back*:
- Sexcon
- Grain filter
- Whitelist check

Edits:
- The way the players readied variable is handled (you can play if there's only one person now. Woah?)

## Why It's Good For The Game

Less bloat is good.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Did a git checkout, run compile on my end, it compiled in three fucking seconds with no errors, idk why our integration tests are being a bitch on this end.

**Comment by NPC1314** [comment]
> Did a git checkout, run compile on my end, it compiled in three fucking seconds with no errors, idk why our integration tests are being a bitch on this end.

If you wanna give it a spin when the conflict is fixed the queue is open.

**Comment by NPC1314** [comment]
Allright I guess Ill do the honors then.
Testing, we'll see if it breaks or not. The quest for purity must go on.

**Comment by NPC1314** [comment]
PR failed

**Pull request merged**
