### PR TITLE
Seamstress

### PR DESCRIPTION
**Pull request by Max-023**
## About The Pull Request
Ports a new role for towners, the seamstress, that is for those who just want to make clothing and other sewing based items. A female only role, they get much higher sewing skills and are rolling out with a more impressing roster of items that can be made with sewing. Due to their new existence, soilsons have been given a slight nerf as to emphasize the shift of sown goods to the seamstress. 

## Why It's Good For The Game
Not only will it remove the aggravating aspect of the soilsons, getting pestered with requests to make clothing items, but now the town has a dedicated person to seek out for cloth items. Her ability to make clothes and clothing parts would provide an artisan role for a town much deprived of artisans, thus improving roleplay.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Max-023** [comment]
> Any reason to not make this just a gender neutral tailor role or something instead?

I was planning on making a male counterpart in the future specifically to handle leatherworking and tanning. Because sewing is primarily a woman's skill (barring drow) from a traditional standpoint, it makes sense for the primary sewing role to be female. It's this way on Blackstone as well.

**Comment by BadAtThisGame302** [comment]
What are these map changes if I may ask.

**Comment by Max-023** [comment]
> What are these map changes if I may ask.

This is a holdover change I forgot to remove. It was just there to help with testing.

**Comment by Max-023** [comment]
Closing to reopen without the map stuff.

**Pull request closed without merging**
