### PR TITLE
Orc classes for eventmins

### PR DESCRIPTION
**Pull request by Dorodomki**
## About The Pull Request

adds new tiers of gear in different orcs, they aren't ambushable and are intended to be used by eventmins for different game modes, they are classified on 3 tiers i discussed with guayo and alco to make them balanced for the game and be lore friendly

orc tribal = Savage orcs armed with light armor and handmade weapons that range from a simple club to handmade spears, they are intended to be complicated fights but not a true challenge like the next tiers.

orc warrior = properly trained raider orcs, they wear chainmail armor and have different weapons like swords, flails, maces and stolen tools like axes, they are your average fighter enemy

orc marauder = chosen warriors that get even better armors and weapons, they are intended to be main fighters of the orcs similar to uruk hai to get a reference, they are more dangerous than an warrior.

orc warlord = champions of graggar who get extra str and steel weapons/plate armor to match the image of "mini boss" local war leaders of smaller orc warbands, they are intended to be used on low number since in the playtest they beat my ass if isn't an 1vs1 and im playing as a knight, the peasants aren't wining a fair fight against one of those.

other detail to have in mind is the rebalance of str in the orcs, i reduced it by two points that way they won't be punching people and sending them flying

other issue i had coding them was the lack of code work done on their species code, now they can wear proper humen armors but not helmets yet, is gonna be solved when i get time but right now they can be used as good enemies 

## Why It's Good For The Game

adds more fun for eventmins and opens the gates for more work on other enemies also getting different classes of gear

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Dorodomki** [comment]
holy shit what happened now the pr was fine when i finished it

**Comment by Stutternov** [comment]
Conflict again + changes.. tons of map files regarding flour etc. Seems like this needs to be fixed?

**Comment by Dorodomki** [comment]
how the hell a map file is conflicted with my pr for orcs holy hell

**Comment by Dorodomki** [comment]
closing this one since we got one up that doesn't have the error i can't fix

**Pull request closed without merging**
