### PR TITLE
Inhumen Pantheon Edits and New Demonic Patrons

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request

Tidies up some of the descriptions for Zizo, Graggar, and Matthios, and adds two new patrons:

- **Ananshor**, patroness of plots, torture, and lots of spiders. Figurehead of the dark elven "spider cult". "We have Lolth at home".
- **Zastaris**, demon queen of succubi and lust, but more lust for ambition and advancement than anything else.

## Why It's Good For The Game

Fixing awkward phrasing. Potentially adding some cool new lore stuff. I'll probably sprite some proper assets for Ananshor and Zastaris in the future.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Mogelix** [comment]
Just add Lolth. C'mon.

**Comment by lavillastrangiato** [comment]
@Mogelix I don't want the [Pinkertons](https://www.polygon.com/23695923/mtg-aftermath-pinkerton-raid-leaked-cards) sent to my house.

**Comment by BadAtThisGame302** [comment]
I love the unselectable inhumen pantheon!!!!!

**Comment by Mogelix** [comment]
> @Mogelix I don't want the [Pinkertons](https://www.polygon.com/23695923/mtg-aftermath-pinkerton-raid-leaked-cards) sent to my house.

Ah, shit. WoTC? Why not just name her the Spider Goddess. Take our Psydon approach. Who knows what people will call them? Better than an unneccesary, obvious expy to cause confusion.

**Comment by lavillastrangiato** [comment]
@Mogelix No, that's lame.

**Comment by ThePainkiller** [comment]
> @Mogelix I don't want the [Pinkertons](https://www.polygon.com/23695923/mtg-aftermath-pinkerton-raid-leaked-cards) sent to my house.

The least we want 'round 'ere are some pinkertons snoopin' on us.

image

**Review by Optimism333 — COMMENTED** [review]
Should be good to go once conflicts are resolved.

**Review by Optimism333 — APPROVED** [review]

**Pull request merged**
