### PR TITLE
Mass Blacksmithing QOL and more

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Ports three PRs (some in their entirety) 

First one ported is this entirely, https://github.com/Blackstone-SS13/BLACKSTONE/pull/1041 which seperates the smithable items in various "i_type" filters, i.e weapons/armor/valuables/tools/general making it easier to find what you're looking for and to avoid mass clutter.

Second one ported is this entirely, https://github.com/Blackstone-SS13/BLACKSTONE/pull/506 which grants the ability for the smith to make various golden/silver rings using the rontz/blortz/gemerald etc. Also taking the golden ring nerf along without the Terminus Est recipe

Last and certainly not least is this one, ported somewhat entirely, https://github.com/Blackstone-SS13/BLACKSTONE/pull/1004 avoiding the skill changes to the smiths and taking all the craftdiff and breakthrough code.

## Why It's Good For The Game

Massive Blacksmithing Update, makes Blacksmithing more engaging while also making it way easier to find what you're looking for, along with a variety of new rings to be made for any Noble worth their salt. (Including a slight economy nerf to the Golden Rings, God knows it's needed,)

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
> merge conflicts and then this one is going to undergo a hefty testmerge period

Fixed the conflicts.

**Comment by BadAtThisGame302** [comment]
> oops i did it again

Once again conflicts have been fixed

**Comment by UntoldTactics** [comment]
Currently this PR is TM'ed. When someone tries to select a recipe by hitting the heated ingot on an anvil, no menu pops up.

**Comment by ThePainkiller** [comment]
Many many things have to be brought on par with our recipes now that they're altered, and added things like Plate chausses.
Also please don't do recipe names too long, follow the standard convention we had, an item made of iron of course would require additional **iron** bars, same with steel.

- `(2)` or `(3)` depending on how many TOTAL bars it needs for the material it's done with
- `(s)` for a stick
- `(w)` for a log
- `(g)` for a gold bar
- For items that create multiple, put after item name, like `iron torches x5 (coal)`
- For the rings, no need to add to the name a repeating of the gem needed to craft. If I want to craft a "silver dorpel ring" I already know it's made with a silver bar otherwise I'd not be seeing it on this list, and of course I'd need to add a dorpel, no need to "dorpel ring (+dorpel)", it's already on the name and should be obvious.

**Comment by ThePainkiller** [comment]
Is this PR gonna keep being worked on? Pretty stale as it is rn

**Comment by BadAtThisGame302** [comment]
> Is this PR gonna keep being worked on? Pretty stale as it is rn

I can't get it to work since the i_type thing isn't appearing so probably not, someone else might want to take up the mantle or I'll just remove the extra.

**Comment by ThePainkiller** [comment]
Closing this one, as addressed functionally by #303 .

**Pull request closed without merging**
