### PR TITLE
Makes Assassins not trigger Ambushes

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request
Assassins will no longer trigger ambushes.

## Why It's Good For The Game
Bandits already don't since they worship Matthios. Assassins worship Graggar so why should Graggarspawn ambush them?

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
That's not where that line is supposed to go
Put it on [this file](https://github.com/Darkrp-community/OpenKeep/blob/main/code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/assassin.dm#L39), right below their reading skill

**Comment by SaintBurgher** [comment]
> That's not where that line is supposed to go Put it on [this file](https://github.com/Darkrp-community/OpenKeep/blob/main/code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/assassin.dm#L39), right below their reading skill

I am a fool. Thank you

**Comment by NPC1314** [comment]
makes some sense, but is making all antags immune to ambushes really a good thing? It does lessen the threat of moving in the wild, thats already been a bit too cuddled, maybe its better to remove bandit immunity instead?

Need to ponder this.

**Comment by Coastfront** [comment]
Bit of feedback; This should affect assassins & bandits, but if it affects cultists it shouldn't.

To uproot a flower and cast it to a rainless desert is to condemn it to die; Cultists are VERY dependent on organs, & the only-decent way to get enough guts/hearts to form a squad of skeletons/homunculi is via farming goblin ambushes.

If this fucks cultists out of goblin farming; An already-fairly difficult antagonist is just going to become weaker.

**Comment by NPC1314** [comment]
> removing bandit ambush immunity will only encourage people to mindlessly chase them through the woods all the way to their base. Bandits NEED the home ground advantage to compensate for the entire server having something to gain from killing them. That sorta goes for other antags as well, the moment you're spotted you're liable to have people chasing you - and between drifters, guards, churchmen and mercs, those people vastly outnumber you at any time.

I´ve tried banditing on other servers with zero ambush protection and it didnt prevent me fighting a whole bunch while also doing robberies, ransom, extortion, antag RP such as it is. Ambush immunity is very safe. very convenient, and thats what I don't love about it. 

This isnt a PR about removing bandit ambush immunity though so we aren't having a big debate about it, main point I want to make is that this is a another (small) increase in making the wilderness safer and less chaotic.

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
