### PR TITLE
Garrison Rebalancing (Skills)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
In line with the previous balance prs, brushes up the skills of various garrison roles. Garrison guards were falling a bit behind some of the basic combat classes, even with the mercenary rebalancing in #533 , so I buffed them a little bit, along with royal guards. I made garrison archer's melee skill consistent with the mercenary changes, and I added a few skills to Captain that were missing or lacking.

### Garrison Guard ###
- Garrison Guards no longer get +1 to Perception
- Garrison Guards get skilled (3) athletics instead of average (2)
- Garrison Guards get skilled (3) swords instead of average (2)
- Garrison Guards get skilled (3) shields instead of average (2)

### Garrison Archer ###
- Garrison Archer has had expert (4) knife reduced to skilled (3)
- Garrison Archer has had skilled (3) wrestling reduced to average (2)
- Garrison Archer has had tanning and crafting skills set to weak (1) instead of a chance of weak (1) or average (2)
- Garrison Archer has had bow skill reduced from master (5) to expert (4)
- Garrison Archer has been given average (2) swords, instead of a chance of none (0) or weak (1)

### Royal Guard ###
- Royal Guards get skilled (3) knives instead of average (2)
- Royal Guards get expert (4) athletics instead of average (2)

### Captain ###
- Captain starts with a metal shield, like Royal Guards
- Captain has expert (4) shield skill, previously had none
- Captain has expert (4) axes/maces, instead of skilled (3)
- Captain has skilled (3) bows and crossbows, previously only having average (2) crossbow skill
- Captain has higher climbing, swimming, and riding skill. Previously he was worse at all of these than a Royal Guard

### Misc Other ###
- Veteran has skilled (3) athletics instead of average (2)
- Dungeoneer has average (2) athletics, previously had none
- Squire has average (2) athletics instead of weak (1)

## Why It's Good For The Game
- Brushes up a lot of garrison stats, bringing them up to par with recently pr'd balance changes for other combat classes

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
In line with the general balance overhaul, ready to go.

**Comment by Stutternov** [comment]
Honestly I'm against the nerfing of knife skill given garrison archer doesn't have standardized melee capability besides the knife skill.

**Comment by ParadoxalObserver** [comment]
> Honestly I'm against the nerfing of knife skill given garrison archer doesn't have standardized melee capability besides the knife skill.

So, the closest adventurer class to garrison archer is ranger, let's compare for a bit!

Ranger has bow 3, Garrison has a staggering 5. A skill level that people had to argue for veteran to get Archer just gets.
Knives? Ranger has 3.
Crossbows 0 to 4.
Wrestling 0 to 3.

And I could keep going but I'm sure you see the trend. Oh, right, they can also get crafting and tanning. They actually have a chance to have higher tanning than Ranger.

Don't even get me started on the stats, either.

And before the: 'garrison is supposed to be stronger than your typical adventurer!' there's being stronger and then there's being a basic guard that inexplicably has master rank bow, expert crossbow, and an average +2 higher to their stats, along with insanely good melee, and have wrestling thrown in just to make sure you don't have to break a sweat in any fight ever.

Oh, right, and they can for some reason roll tanning high enough that they can almost compete with towner hunter? I'm out here having to cry myself to sleep about being unable to dodge basic mobs with my pitiful +1 agility and you get all this and have an issue with having your knife slightly lowered? smh.

**Comment by Stutternov** [comment]
Just putting this here: The bow and crossbow skill effects, mainly, draw times. And close to nothing else. The crossbow drawtime/reload is abysmal without strength bonus, as it does strength and skill / 1.2 or whatever the number is. Archers do not get this strength bonus; thus to remain competitive with, say, a royal guard - they literally need the higher skill. 

As for bows, it is draw time. You could reduce that one as it's not effected by any other stats to draw back, it's pure skill. Though my input would be the draw time isn't massive on bows as it is, it's a relatively minor change. It's not make-or-break but given the skill level adventurers are at + how many there are, and sentinel even has 5 as an example (thought it's limited), I'd say it's fine.

As for the knife skill - I didn't give my full opinion, I told Optimism it since I've had time. My reason is just that the level 4 knife skill is due to having worse other skills + no strength bonus. You need something given you don't have knife bonus. But I stated, for example, it can be fine to reduce knife skill to 3 if sword is buffed to 2; giving the option to at least be able to OKly use rapiers or the like; even if you don't use them as great as a knife prior. It at least lets you have some versatility and options.

I'd be fine with the knife reduction with the addition of a single point in swords to compensate. Bows, it's not make or break but honestly it's fine. Crossbows, they legitimately need it; It's barely better than that of Rogues. As for the other skills I'm in the opinion it should be standardized instead of 'pick'. The tanning and crafting should just be 1, not chance at 2 or stuff. But wouldn't touch that part for now, I got that fixed on another PR. 

I'll be just pulling whatever skills are decided here for that one and reflect it.

**Comment by ParadoxalObserver** [comment]
> Just putting this here: The bow and crossbow skill effects, mainly, draw times. And close to nothing else. The crossbow drawtime/reload is abysmal without strength bonus, as it does strength and skill / 1.2 or whatever the number is. Archers do not get this strength bonus; thus to remain competitive with, say, a royal guard - they literally need the higher skill.
> 
> As for bows, it is draw time. You could reduce that one as it's not effected by any other stats to draw back, it's pure skill. Though my input would be the draw time isn't massive on bows as it is, it's a relatively minor change. It's not make-or-break but given the skill level adventurers are at + how many there are, and sentinel even has 5 as an example (thought it's limited), I'd say it's fine. Only thing reducing bow skill is going to do is give people even more of a reason to just upgrade to crossbow instead of treating bows as fast-firing but low pen and opposite for crossbow.
> 
> As for the knife skill - I didn't give my full opinion, I told Optimism it since I've had time. My reason is just that the level 4 knife skill is due to having worse other skills + no strength bonus. You need something given you don't have knife bonus. But I stated, for example, it can be fine to reduce knife skill to 3 if sword is buffed to 2; giving the option to at least be able to OKly use rapiers or the like; even if you don't use them as great as a knife prior. It at least lets you have some versatility and options.
> 
> I'd be fine with the knife reduction with the addition of a single point in swords to compensate. Bows, it's not make or break but honestly it's fine. Crossbows, they legitimately need it; It's barely better than that of Rogues. As for the other skills I'm in the opinion it should be standardized instead of 'pick'. The tanning and crafting should just be 1, not chance at 2 or stuff. But wouldn't touch that part for now, I got that fixed on another PR.
> 
> I'll be just pulling whatever skills are decided here for that one and reflect it.

I didn't at all criticise them having crossbows, just them having 4 in Crossbows /plus/ everything else. My suggested re-balancing would still keep them at crossbows 4. Crossbows 4 is fine, what's not fine is Archer's John Wick level of combat variety and self-sufficiency. 

Every other class that has bows aside from Sentinel lacks a strength bonus. Archers are way ahead of the curve at 5. Having archery that high actually makes them incredibly good at ensuring crits which is massive. It also controls your melee skill with the bow which is better than it might sound if you're dodging or have a knife in your off-hand.

On the topic of knives: knives are an excellent weapon and I say this as someone that plays a lot of Ranger. They have two intents that inherently are swift, letting you easily break through defenses. Their parry is not the best but it's not bad either, especially if someone is fighting you with a lower skill level. If someone has an exposed body part you can swap to swift to make them attack even more crazy quick or aimed if you want a greater chance to just end a fight with a crit.

At skill 2 most knives (which have wdefense 3) have a 70% chance to parry most basic mobs (goblins, vulfs, etc) so still positive, but not great. The swords 2 would let an archer that wants more defense to go buy a high wdefense sword to swap their knife out or even use it for parrying in their offhand while using a knife in their mainhand.

On crafting: even at crafting 1 and tanning 1, especially with their INT boost, they'd be able to compete with Ranger at leatherworking and, again, incentivises archers to not do their job as guards and instead go out and hunt. Leatherworking 1 lets you craft heavy leather gloves, leather helmets, leather armour, bracers, and so on, and if there's a merchant they can even stray further from their duties and go make saddles and fur cloaks to sell at the merchant's. It's pretty much the same as if you were to give Garrison Guard a level in smithing. At /most/ in the crafting department they should /maybe/ get crafting 1 and that's it, to fit into the desc about them sometimes being used as scouts, since crafting has a lot of the 'wilderness survival' sort of recipes, but that's it, tanning's a massive no-no.

And, of course, wrestling should be 2 because guards should all have it but Archer should have it lower and their unarmed should be at /most/ 2, maybe even just 1.

**Comment by Optimism333** [comment]
I think the case against garrison archer is reasonable, they were a bit overtuned with skill and stats imo. I gave them average swords as the tradeoff for reducing their knife skill from expert (4) to skilled (3), but I also reduced their crafting skills, wrestling, and knocked off that +1 to Intelligence. They're still a good combatant, but they shouldn't be a direct competitor to archer classes with a crafting focus anymore.

### Garrison Archer ###
- Garrison Archer has had expert (4) knife reduced to skilled (3)
- Garrison Archer has has skilled (3) wrestling reduced to average (2)
- Garrison Archer has had tanning skill removed, and crafting set to weak (1) instead of a chance of weak (1) or average (2)
- Garrison Archer has had bow skill reduced from master (5) to expert (4)
- Garrison Archer has had its +1 to Intelligence removed
- Garrison Archer has been given average (2) swords, instead of a chance of none (0) or weak (1)

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
