### PR TITLE
Adds a small southern dungeon section to the Raytown sewers, as well as a small mine in the Village

### PR DESCRIPTION
**Pull request by bowlofcereal**
## About The Pull Request

Adds multiple unique locations in the underground sections of Raytown, since a lot of it was unused empty space that could easily fit some interesting spots. I'm leaving a lot of the rest of it empty though for any administrator that decides to use it for something ingame for an event or such- since I know some of these spaces were used for that.

Alchemy Lair, has a few potion ingredients + Skilled skeletons defending it. If you try to rush in there without preparation, you are going to die.
image

Taking inspiration from the Bogcave, there is now a skrallax nest in the sewers as well, adjacent to the alchemy lair. Its filled to the brim with mantraps and spiders, but if you make it to the end there is something interesting to grab.
image

The Village now has it's own miniature mine section for it to use-- it is nowhere near as valuable as the one next to the passage to Mt. Decap, but it serves as a nice little mine for towners. It also has a small little surprise for anyone who digs too deep.
image

The Entrance
image

I also took some time to tidy up parts of the sewers that were just not appealing and seemed like spots that had been missed.

## Why It's Good For The Game

𝙸̶ ̶𝚐̶𝚘̶𝚝̶ ̶𝚋̶𝚘̶𝚛̶𝚎̶𝚍̶ ̶𝚊̶𝚗̶𝚍̶ ̶𝚠̶𝚊̶𝚗̶𝚝̶𝚎̶𝚍̶ ̶𝚝̶𝚘̶ ̶𝚖̶𝚊̶𝚙̶ Adding more flavor to the below and giving people more things to do is fun, and its not like its going to be easy to just rush it and take everything for yourself in the dungeon sections, as the mobs in place are no pushovers.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by bowlofcereal** [comment]
This was made in TGM format on StrongDMM btw since I saw the PR that converted it all to TGM got merged. If this was a fuck-up let me know so I can go back and do it again on DMM.

**Comment by bowlofcereal** [comment]
Didn't seem to explode anything during testing on my end, but you never know in practice until its in action.

**Comment by ThePainkiller** [comment]
I am generally very against pre-mapping mobs, but these mobs all not have vitae except the goblins, and given the "surprise" awaiting on the mines, I do not mind the pre-spawned goblins in there tbh

**Review by Optimism333 — COMMENTED** [review]
If any maintainers or contributors have strong opinions on this one either way, make them known soon.

If there's no objections within about a day, I'll move to approve this.

**Review by Optimism333 — APPROVED** [review]
This has been sitting here for some time, there's been no major objections.

Going to move to approve it.

**Pull request merged**
