### PR TITLE
Eoran Worshippers no longer Virgin, and are thus exempt from the Chastity debuffs and tri-loss

### PR DESCRIPTION
**Pull request by saltprjak**
## About The Pull Request

As requested by the HEAD LORE-WRITER, PROJECT LEAD, HEAD DEVELOPER and ACCLAIMED MASTERMIND, Gua "Guayo" Yito
also fixes some roles getting the wrong psicross
## Why It's Good For The Game

For by fire and by His sword The LORD will judge all flesh; And the slain of the LORD shall be many.

...isn't it kinda weird this system only affects women, anyway?

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
finally, orgies can be much easier...

**Comment by SELFHELL** [comment]
-1 Here, they are still inside an Astrata lead church. Also better to not treat them as nitemaidens..

**Comment by Cre77** [comment]
> -1 Here, they are still inside an Astrata lead church. Also better to not treat them as nitemaidens..

all complaints to guayo, this is on request

**Review by ThePainkiller — APPROVED** [review]
If this was approved by Guayo already I see no reason to keep it on the backburner any longer, sorry it took too long.

**Pull request merged**
