### PR TITLE
Change Position Throne Command

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

A port from the RU Roguetown: https://github.com/Animusin/OpenKeep/pull/3

The King is able to change anyones position if they're at least two tiles next to the Throne, they can change them from Queen to Orphan, even roles that can't normally be accessed like Scribe, Docker, Magician's Apprentice.

Here's a trial run:
image 

## Why It's Good For The Game

Finally the King finally has the authority to change peoples positions for more immersion, not to mention if anyone's getting promoted, fired, hired, the King can show that through this system way better than the recruitment scrolls.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Stutternov** [comment]
I really like this given it encourages kings to do promotions, punishments, and the like. Is the job list all jobs enabled, or is it all jobs period? (I.e unused jobs appear on the list)

**Comment by BadAtThisGame302** [comment]
> I really like this given it encourages kings to do promotions, punishments, and the like. Is the job list all jobs enabled, or is it all jobs period? (I.e unused jobs appear on the list)

Yeah it's all the jobs, even unused ones that appear on the list.

**Comment by ThePainkiller** [comment]
There should be a way to just erase those unavailable "jobs" from that list...other than that, I absolutely love this PR.

Some extra verbose would be awesome, specially following the format

# The King Decrees
`Henceforth, the vassal known as [victim.real_name] shall have the title of [new_pos].`

**Comment by sanshoom** [comment]
Hooooly based.

**Comment by BadAtThisGame302** [comment]
> There should be a way to just erase those unavailable "jobs" from that list...other than that, I absolutely love this PR.
> 
> Some extra verbose would be awesome, specially following the format
> 
> # The King Decrees
> `Henceforth, the vassal known as [victim.real_name] shall have the title of [new_pos].`

Fancied it up for you.

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
