### PR TITLE
Adds Dwarves to Royal Family (Excluding Kings)

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request
Adds Dwarf Queen ~~& Elf/H-Elf/Dwarf King~~ as well as the accompanying sprites that are needed. This will also add Prince/Princess as well.

## Why It's Good For The Game
This change is accurate to the lore of Enigma as it is stated that Enigma is a relatively "diverse" setting and has been ruled by Dwarves, Elves, and Humens alike. These additions are to better follow the lore that was laid out by our team. ~~The addition of the family system also helps to explain how a Dwarf King may have a Humen "Progeny".~~

~~I will connect with InsightfulParasite to hammer out anything that needs to be changed within the family system once this PR is more fleshed out.~~ **DONE**

image
image
image
image
image
_Needed sprites supplied by Cre and Saint_

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.
- [x] Add Lord's Cloak Sprite for Dwarf Male/Female
- [x] Add Dress for Dwarf Queens
- [x] Add Dwarven Prince/Princess
- [x] Add Boots for Male Dwarf Prince 
- [x] Talk with Pawa to have Royal Family System changed to be "Ward/Visiting Prince(ss)"
- [x] Talk with Pawa to have Royal Family System updated to allow Dwarves

### CODE REVIEW

**Comment by Cre77** [comment]
HOLY BASEDBASEDBASED

**Comment by Cre77** [comment]
all who downvote me and this pr are thin blooded and likely follow elon musk on twitter

**Comment by sanshoom** [comment]
karak azgaraz will become real

**Comment by ThePainkiller** [comment]
Dwarf King 👍🏻 🔥 
Everything else 👎🏻

**Comment by SELFHELL** [comment]
Im going to **strongly** suggest you add a mechanic to keep the races of the royals consistent. Elf King and Human Queen with Dwarf Prince is way too scuffed

**Comment by Optimism333** [comment]
If we were going to get dwarf Kings / Queens I was hoping it'd come with a bit more fanfare and maybe an alternate "Underhill" map where the Kingdom was in caves.

As another aside thought, personally I wish the royal family had a bit more consistency and the ruler could choose whether or not to allow Princes / Princesses from species that would be considered "adopted" as well. Otherwise the species of the heirs would need to match the compatible species of the King (and Queen if one is present).

Those gripes aside, I'm fairly indifferent about this change. I just wish our royal families felt a bit more like families rather than bizarre amalgamations of random adoptions.

**Comment by BadAtThisGame302** [comment]
The Royal Family should not be called a Royal Family anymore... you could have Dwarves and Elves who hold millennia old grudges or full Humen couples with Elvish children (Half-Elf could at least be explained as a bastard) and overall it just reduces the dynamic of the entire Royal Family and all three roles. 

Dwarf should stay out and Elves and Half-Elves should just be added to King. Same as the Queen who can be solo ruler, so why not equalise those and see how it plays out first? Dwarves being added would be the fourth race in an already fractured Royal Family. Not to mention having Elvish Prince/Princesses with Humens or even Half-Elves would be scuffed. 

King and Queen being at Humen/Elf/Half-Elf is a better and less radical of an alternative than adding Dwarves to all three and Elves to Prince/Princess.

**Comment by SaintBurgher** [comment]
> Im going to **strongly** suggest you add a mechanic to keep the races of the royals consistent. Elf King and Human Queen with Dwarf Prince is way too scuffed



> If we were going to get dwarf Kings / Queens I was hoping it'd come with a bit more fanfare and maybe an alternate "Underhill" map where the Kingdom was in caves.
> 
> As another aside thought, personally I wish the royal family had a bit more consistency and the ruler could choose whether or not to allow Princes / Princesses from species that would be considered "adopted" as well. Otherwise the species of the heirs would need to match the compatible species of the King (and Queen if one is present).
> 
> Those gripes aside, I'm fairly indifferent about this change. I just wish there was an option for rulers to enforce a royal family that feels a bit more like a family rather than a bizarre amalgamation of random adoptions.



> The Royal Family should not be called a Royal Family anymore... you could have Dwarves and Elves who hold millennia old grudges or full Humen couples with Elvish children (Half-Elf could at least be explained as a bastard) and overall it just reduces the dynamic of the entire Royal Family and all three roles.
> 
> Dwarf should stay out and Elves and Half-Elves should just be added to King. Same as the Queen who can be solo ruler, so why not equalise those and see how it plays out first? Dwarves being added would be the fourth race in an already fractured Royal Family. Not to mention having Elvish Prince/Princesses with Humens or even Half-Elves would be scuffed.
> 
> King and Queen being at Humen/Elf/Half-Elf is a better and less radical of an alternative than adding Dwarves to all three and Elves to Prince/Princess.

I know at one point Pawa/InsightfulParasite (Creator of Family PR) said it was possible for the royal children to be excluded based on their race related to their parents. I will talk with them to see if that is still a possibility. That way we don't have Dwarf King/Elf Queen & Humen Princess.

**Comment by Optimism333** [comment]
> > Im going to **strongly** suggest you add a mechanic to keep the races of the royals consistent. Elf King and Human Queen with Dwarf Prince is way too scuffed
> 
> > If we were going to get dwarf Kings / Queens I was hoping it'd come with a bit more fanfare and maybe an alternate "Underhill" map where the Kingdom was in caves.
> > As another aside thought, personally I wish the royal family had a bit more consistency and the ruler could choose whether or not to allow Princes / Princesses from species that would be considered "adopted" as well. Otherwise the species of the heirs would need to match the compatible species of the King (and Queen if one is present).
> > Those gripes aside, I'm fairly indifferent about this change. I just wish there was an option for rulers to enforce a royal family that feels a bit more like a family rather than a bizarre amalgamation of random adoptions.
> 
> > The Royal Family should not be called a Royal Family anymore... you could have Dwarves and Elves who hold millennia old grudges or full Humen couples with Elvish children (Half-Elf could at least be explained as a bastard) and overall it just reduces the dynamic of the entire Royal Family and all three roles.
> > Dwarf should stay out and Elves and Half-Elves should just be added to King. Same as the Queen who can be solo ruler, so why not equalise those and see how it plays out first? Dwarves being added would be the fourth race in an already fractured Royal Family. Not to mention having Elvish Prince/Princesses with Humens or even Half-Elves would be scuffed.
> > King and Queen being at Humen/Elf/Half-Elf is a better and less radical of an alternative than adding Dwarves to all three and Elves to Prince/Princess.
> 
> I know at one point Pawa/InsightfulParasite (Creator of Family PR) said it was possible for the royal children to be excluded based on their race related to their parents. I will talk with them to see if that is still a possibility. That way we don't have Dwarf King/Elf Queen & Humen Princess.

If an option for consistency in the royal family gets added, my main gripe about this disappears and I'd be fine with it.

**Comment by 1N7Slayer** [comment]
BASEDBASEDBASED

**Comment by AceVX** [comment]
I like everything here except the addition of Elves and Dwavrves to the king slot. I like the idea of the kingdom being on the cusp of culturally blending, thus the elf
Or dwarf queen, but it is a human kingdom.

**Comment by lavillastrangiato** [comment]
I know Guayo said that this PR was fine, but personally I'm not in agreement with it.

We have long since passed being a "grimdark" fantasy setting and have settled comfortably into being just a dark/dung-ages aesthetic fantasy setting, and this, plus some player culture, encourages suspicion and xenophobia towards other races. This breeds a certain level of tension and conflict that is the bread and butter of roleplay.

I think a lot of this potential tension is lost if we suddenly make the royal family able to be part of at least three races. The previous mood of our setting begins to blur and become less distinct. I'm not saying that all fantasy racism RP is of the same calibre or quality, but it can create some very interesting conflicts.

I don't really want this server to turn into a homebrew D&D game IMHO, and even so, the Forgotten Realms settings I've RP'd in were pretty hardline that such-and-such race should be chased out of such-and-such community. I'm fine with the town in general remaining diverse in its population, as that also creates conflict, but in my ideal world the royal family would be exclusively human.

**Comment by SaintBurgher** [comment]
> > > Im going to **strongly** suggest you add a mechanic to keep the races of the royals consistent. Elf King and Human Queen with Dwarf Prince is way too scuffed
> > 
> > 
> > > If we were going to get dwarf Kings / Queens I was hoping it'd come with a bit more fanfare and maybe an alternate "Underhill" map where the Kingdom was in caves.
> > > As another aside thought, personally I wish the royal family had a bit more consistency and the ruler could choose whether or not to allow Princes / Princesses from species that would be considered "adopted" as well. Otherwise the species of the heirs would need to match the compatible species of the King (and Queen if one is present).
> > > Those gripes aside, I'm fairly indifferent about this change. I just wish there was an option for rulers to enforce a royal family that feels a bit more like a family rather than a bizarre amalgamation of random adoptions.
> > 
> > 
> > > The Royal Family should not be called a Royal Family anymore... you could have Dwarves and Elves who hold millennia old grudges or full Humen couples with Elvish children (Half-Elf could at least be explained as a bastard) and overall it just reduces the dynamic of the entire Royal Family and all three roles.
> > > Dwarf should stay out and Elves and Half-Elves should just be added to King. Same as the Queen who can be solo ruler, so why not equalise those and see how it plays out first? Dwarves being added would be the fourth race in an already fractured Royal Family. Not to mention having Elvish Prince/Princesses with Humens or even Half-Elves would be scuffed.
> > > King and Queen being at Humen/Elf/Half-Elf is a better and less radical of an alternative than adding Dwarves to all three and Elves to Prince/Princess.
> > 
> > 
> > I know at one point Pawa/InsightfulParasite (Creator of Family PR) said it was possible for the royal children to be excluded based on their race related to their parents. I will talk with them to see if that is still a possibility. That way we don't have Dwarf King/Elf Queen & Humen Princess.
> 
> If an option for consistency in the royal family gets added, my main gripe about this disappears and I'd be fine with supporting it.

After talking to Pawa about this; unfortunately, it's not possible. I will instead be pivoting this PR to do as AceVX said here:


> I like everything here except the addition of Elves and Dwavrves to the king slot. I like the idea of the kingdom being on the cusp of culturally blending, thus the elf Or dwarf queen, but it is a human kingdom.

I will keep King as Humen only but open Queen to Dwarf and open Prince/Princess to Dwarf as well (no more pure Elf Prince/Princess with this change). This will lead to less jumbling of the Nobles as it is my belief (and lore interpretation) that Humen and Dwarf marriages could result in "Half-Dwarves" that are effectively just Dwarves or Humen in game (I never thought I'd be typing anything like this).

I will instead talk to Pawa and see if for the royal family instead of "Adopted Progeny" those that do not fit their parents could be labeled as 'Ward" or "Visiting Prince/Princess".

**Comment by Ickysoup** [comment]
I support a Human only king of Enigma.

**Comment by SaintBurgher** [comment]
All needed sprites are in for Dwarf Queen, Dwarf Princess, and Dwarf Prince. I'm going to open this for review as the changes in the family system are going to need to be handled by Pawa.

This PR started very unpopular (adding species to King) but with the more limited scope that it is now everyone that I talked to has been fine with this change. King will remain Humen only and Dwarves are just getting added to the other family roles.

**Comment by NPC1314** [comment]
> All needed sprites are in for Dwarf Queen, Dwarf Princess, and Dwarf Prince. I'm going to open this for review as the changes in the family system are going to need to be handled by Pawa.
> 
> This PR started very unpopular (adding species to King) but with the more limited scope that it is now everyone that I talked to has been fine with this change. King will remain Humen only and Dwarves are just getting added to the other family roles.

Dwarf prince usurping his elf mom and humen king might get a little derpy but that door been open a while with the elf invasion of court. Could be good fun!

**Review by Optimism333 — COMMENTED** [review]
Most of my grumblings about the state of the royal family and how it functions still stand. And personally I'm not sure if this will make it any better... but putting that aside, there's no reason to ignore this pr.

I'll give it a day or two to see if there's any more major objections, and if not, I'll approve it.

**Addendum:** Approve it AFTER the conflicts get resolved, anyways.

**Comment by SaintBurgher** [comment]
@Optimism333 This is ready now

**Pull request closed without merging**
