### PR TITLE
Large Pack of Stuff (Roguelighting split, stew code and weaving additions)

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Firstly, ports this PR from Vanderlin, https://github.com/Vanderlin-Tales-Of-Wine/Vanderlin/pull/182, that improves on stew code.

Since I touched on food code, I also added/changed some pollutants, like having 2 sausage pollutants which was changed to be one wiener one sausage, or the bug that made the Zybantine honey cake smell like cheesecake, or the uncooked prezzel not using the prezzel pollutant.

Secondly, adds noc robes and hood into the crafting recipe along with the other ones, made no sense they were excluded for so long.

Thirdly, ports this commit, https://github.com/Vanderlin-Tales-Of-Wine/Vanderlin/pull/23/commits/346abdd4fd48bde69b17f205d8fb4c0caf8778f6 that splits roguelighting into 3 different files for easier changes and access. Along with that it touches upon maps only to remove fireplaces that now have been changed in their pathing.

## Why It's Good For The Game

Stew code is a QOL, Noc Robe crafting is also a QOL/Bugfix(?) and lastly the roguelighting split has not broken the game from my relatively small amount of testing, which is also a QOL change.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
Why delete the big fireplaces and exchange for the tiny ones? Its going to harm the inn and the vampire lord manor style, especially with VL manors easter egg thing.

**Comment by BadAtThisGame302** [comment]
> Why delete the big fireplaces and exchange for the tiny ones? Its going to harm the inn and the vampire lord manor style, especially with VL manors easter egg thing.

I'll bring those back, then.

**Comment by NPC1314** [comment]
My question is if the light part works without breaking even more stuff, vanderlin porting of the lighting system wrecked our sunlight and skull lamps, lighting in general really. If this can be confirmed to not break those light sources then sure.

**Comment by NPC1314** [comment]
stew has been a bit wonky for me in a small test, unable to add more than 1 ingrident to a full pot, then it boils down to 30 units or so. So the old but unable to do more than 1 and 70 odd units of water just disappearing. Can replicate?

**Comment by BadAtThisGame302** [comment]
> stew has been a bit wonky for me in a small test, unable to add more than 1 ingrident to a full pot, then it boils down to 30 units or so. So the old but unable to do more than 1 and 70 odd units of water just disappearing. Can replicate?

I tested it and that is weird indeed, best un-TM this for now until I see further about the pot stuff and lighting mentioned above.

**Comment by NPC1314** [comment]
I think I got a solution, lets go

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
