### PR TITLE
Tiefling Tweaks pt1

### PR DESCRIPTION
**Pull request by blackwolf5505**
## About The Pull Request

Adds the following Progenitors to teiflings

- Sun Stained
- Sundered
- Zarkana
- Zarconum
- Abyssium
- Ash

Removes the following Progenitors from teiflings
- Halfling
- Roza

## Why It's Good For The Game

More customization is good for roleplay, the current skintones for the tieflings were all nearly identical. Fluff.

## Pre-Merge Checklist

- [ x ] You tested this on a local server.
- [ x ]  This code did not runtime during testing.
- [ x ] You documented all of your changes.

### CODE REVIEW

**Comment by Plaguewalker** [comment]
MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE MERGE

**Comment by Wesreidau** [comment]
Not certain why you are pulling Halfling and Roza. There's really nothing to be lost in more fine tuning of your color options.

**Comment by NPC1314** [comment]
Kind of hard to judge without seeing the original skintone lineup with the "deleted" ones for comparison.
Should be included before consideration. Saturation looks ok at least

Generally not thrilled with full DnD tief, rainbow colors not my thing, but this sort of thing should probably be sent to Guayo.
If you add this you're not going to undo it without cost.

**Comment by Cre77** [comment]
maybe bump their perception or intelligence up by a point while you're at it? they have a constitution malus while otherwise have the same stats as half-elves - again, just worse by a point

**Comment by blackwolf5505** [comment]
> maybe bump their perception or intelligence up by a point while you're at it? they have a constitution malus while otherwise have the same stats as half-elves - again, just worse by a point

out of scope, make a PR for it if you think stats should be adjusted

**Comment by Plaguewalker** [comment]
> Kind of hard to judge without seeing the original skintone lineup with the "deleted" ones for comparison. Should be included before consideration. Saturation looks ok at least
> 
> Generally not thrilled with full DnD tief, rainbow colors not my thing, but this sort of thing should probably be sent to Guayo. If you add this you're not going to undo it without cost.

tiefshit

**Comment by Plaguewalker** [comment]
Replace the orange-yellow ones with the deleted skin tones.

**Comment by SaintBurgher** [comment]
Merge dis stuff ASAP

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
