### PR TITLE
Undermaider & Volftrap

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

Undermaiden got changed to Veiled Lady in a couple places at some point, most notably the gods description, making the references in various places like spells a bit odd. Undermaiden is the classic name for her, no need to change it IMO, so just returned it to the desc.

Mantrap been annoying since forever, its a classic name but whats annoying is CONSTANTLY hearing people mistake mantraps and maneaters. It does make a lot of sense to have them named volftraps, but maybe its not grimdark enough.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
I'm fairly certain it was changed to Veiled Lady because people keep calling necra a fucking NITEMAIDEN instead of UNDERMAIDEN

**Comment by NPC1314** [comment]
> I'm fairly certain it was changed to Veiled Lady because people keep calling necra a fucking NITEMAIDEN instead of UNDERMAIDEN

We're taffed whatever way we turn arent we?

**Comment by BadAtThisGame302** [comment]
Personally I don't see people confuse mantraps and maneaters and volftrap isn't doing it for me. 

The Necran change I am indifferent about, both names could be used, It doesn't matter much.

**Comment by NPC1314** [comment]
Lets not change mantrap then, Undermaiden will be done in a minor fix PR.

**Pull request closed without merging**
