### PR TITLE
Changes Amazon Class Loadout

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request
Amazons are now guaranteed to spawn in Chainkinis. They are also rebalanced towards spears instead of swords.

## Why It's Good For The Game
Amazons are unpopular as it is. Spawning in their iconic armor with a higher chance for spears is a needed change.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Cre77** [comment]
you could take this opportunity to buff them up overall - give them 1 more point of sword skill so they don't end up capped at 2 if they roll poorly, and dodge expert (and another point of speed? it's only human women). rn they're just the worse barbarian

**Comment by SaintBurgher** [comment]
> you could take this opportunity to buff them up overall - give them 1 more point of sword skill so they don't end up capped at 2 if they roll poorly, and dodge expert (and another point of speed? it's only human women). rn they're just the worse barbarian

If the maintainers are okay with it, I will!

**Comment by ThePainkiller** [comment]
> If the maintainers are okay with it, I will!
By all means that's an oversight, give them 1 more level on swords please.

**Comment by SaintBurgher** [comment]
> > If the maintainers are okay with it, I will!
> > By all means that's an oversight, give them 1 more level on swords please.

Updated

**Review by DovaKitty — APPROVED** [review]
Looks good to me. I'll be making bigger changes to amazon/barb likely in a bit, but this is a good start and I would have done it eventually anyways.

**Review by ThePainkiller — APPROVED** [review]

**Pull request merged**
