### PR TITLE
commented out whitelist check we dont use that shit

### PR DESCRIPTION
**Pull request by ThePooba**
## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Very funny PR, glad to have some comedians among us.

**Comment by Cadet00** [comment]
+1, Good PR.

**Comment by 1N7Slayer** [comment]
@ThePooba Bro make sure your upstream is quoted up at the codebase you're actually using

**Comment by ThePooba** [comment]
dont pr drunk

**Pull request closed without merging**
