### PR TITLE
Lamias and Headless Appear in Rockhill [Good for Testmerge]

### PR DESCRIPTION
**Pull request by InsightfulParasite**
## About The Pull Request
We had lamia and headless sprites just laying around so i decided to make them into coded monsters.
Both Lamias and Headless are aligned with the Orc faction currently but due to their unnatural natures this is subject to change.
image

Lamias are creatures that sneak (become transparent) when in darkness.
- When their sneak is broken they will go on a 30 second cooldown before they can sneak again.
- Lamias will check their environment every 3 seconds to see if its dark enough to sneak. This is here so that even if the sneak cooldown is up they wont be constantly checking their well lit enviorment.
- Their sneak is broken when they attack a monster.
- I have not figured out a way to make them sneak normally so that perception bonus's can see them. I tried making them use the sneaking move_intent but i got errors due to a skill required.
- Their alpha while sneaking is reduced to 100.
- Theoretically if a Lamia spawned in the wild or through bait they would suddenly vanish in the dark before locking onto their target. A farmer with bad eyes will lose the chance to escape as the Lamia gets close enough for a initial attack.
- Ill need someone to look at their stats in order to figure out how to make them balanced.
- Play controlled Lamias will be unable to sneak since the sneak is connected to their automated action AI.

The Headless are horrible vore monsters. 
- Has the ability to swallow mobs during combat.
- While swallowed the mob will take 20 fire damage per second. This is increased to 50 fire damage if the captive is unconscious. (Strangely this is in order to fight back against the heal from sleeping.)
- When the mob dies the Headless will dust the corpse dropping all of its equipment on the floor before rapidly healing for 50 health.
- To save someone who is swallowed you must deal 40 damage to the headless to make the beast vomit.
- While swallowed the captive can still hit the headless in order to save themselves.
- Cooldown on swallow ability is 30 SECONDS and is applied upon spitting up their captive
- Instead of feasting on limbs, organs, and meat like the Lamia the Headless will use their swallow ability to instantly heal from wayward corpses. Dont worry they will prioritize consuming living enemies first.

Headless and Lamia are very simple creatures but give way to more complex monsters.

Ill need someone to check the stats since i dont really know how Str on monster balancing works.
image
Testing

## Why It's Good For The Game
Adds unique nightmare mobs to the game.

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
Millions will use silver against monsters.

**Comment by InsightfulParasite** [comment]
Essentially works but should be test merged or have comments on how to balance the stats.

**Comment by anything86** [comment]
Right now they have the damage of a volf, but four times as much health (and 1.5x as much health as a bogtroll)
My suggestion would be: Headless - 13 STR, 10 SPE, 25-35 damage, 350 health. A bit meatier than a bogtroll, but significantly weaker in damage and average speed.
Lamia - 11 STR, 12 SPE, 35-50 damage, 200 health. Basically a very mean volf, ambush predator with high attack but not as much health as other monsters of its caliber.

This is assuming that neither spawn in packs during ambushes. At most two Headless could spawn, but make sure Lamias spawn alone since bogtroll damage with volf speed would be problematic in groups.

**Comment by ThePainkiller** [comment]
Do we have permission from Monochrome to use his sprites btw? Asking because I recognise these as palette swaps from monsters we had back in Liberty, our joined project.

**Comment by InsightfulParasite** [comment]
> Do we have permission from Monochrome to use his sprites btw? Asking because I recognise these as palette swaps from monsters we had back in Liberty, our joined project.

Are they the monochrome in the discord because then ill just ask them real quick.

**Comment by NPC1314** [comment]
> > Do we have permission from Monochrome to use his sprites btw? Asking because I recognise these as palette swaps from monsters we had back in Liberty, our joined project.
> 
> Are they the monochrome in the discord because then ill just ask them real quick.

Any more tweaking you want to do before it goes in?

**Comment by InsightfulParasite** [comment]
> > > Do we have permission from Monochrome to use his sprites btw? Asking because I recognise these as palette swaps from monsters we had back in Liberty, our joined project.
> > 
> > 
> > Are they the monochrome in the discord because then ill just ask them real quick.
> 
> Any more tweaking you want to do before it goes in?

Should be all good to go. I got permission from Monochrome too.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
