### PR TITLE
Map: Dun Manor

### PR DESCRIPTION
**Pull request by spartanbobby**
About The Pull Request
This PR adds the map "Dun Manor" a small coastal town protected by a wall.
[I listened to this song the entire time I mapped](https://www.youtube.com/watch?v=ra8a_j9UPUk)
The name comes from me google translating what "Fort" is in scots gaelic then putting Manor after it 

The map uses the already existing area code used in Roguetown.dmm and maintains the same Mountdecap, forests, and bog. The general idea I was going for was something a bit more "tight" in the sense that I wanted a lot of the hotspots to be quite close together with the general idea being if everything is closer together people are more likely to bump into each other and interact as well everything being closeby hopefully helps lower pop not feel so empty.

Why It's Good For The Game

Aesthetically I believe the map to be an improvement over Roguetown.dmm I tried to go hard on the "This is a backwater shithole" with lots of muck ditches around the town's outer walls filled with stakes, mantraps, and dirty leech-filled waters. The wall isn't entirely stone the majority is wooden battlements connected to mossy stone pillars probably built before the time of your nans nan and only the king (and a little outside of the church) is blessed with actual stone-paved road

Things that are majorly different from Roguetown.dmm

The market stalls have keys they spawn in the merchants so anyone wanting to start a small business is going to have to buy them from him or out some sort of kickback Also the stalls are not positioned at the center of town hopefully making them get more traffic

The spare houses are now also keyed the Steward gets those keys so if you wanna buy a property you'll need to talk to him (The dorm rooms remain deadbolts.)

The veteran has his own house north of the feldshers, I wanted to give the veteran more room to RP a disconnect between him and the garrison if they felt like it and the vet doesn't have a place of their own as it currently stands so I felt it was appropriate to give them someplace.

Jester has their own quarters in the basement of the keep next to the RG chambers, felt weird he didn't have someplace of his own to stay since the Jester should be one of the kings top blokes. The bedroom is humble in size but it should suit him nicely.

Archivist now maintains their own office. Again felt weird this guy didn't have a place of his own in the keep so I've seen fit to outfit him with a bedroom

Both princes now have their own rooms, Lannister LARP must be stopped.

The church: I feel like the church I have at the moment might be a bit too small but I'd like to see it tried out before I go ahead with any changes. I saw fit to give the church a vault of its own (It doesn't generate money or anything) with some starting coinage in the hopes this gives the church the ability to hire mercs or wondering adventurers or issue bounties on churchly things or however, the priest wants to use it

Tavern: Hasn't changed much you go downstairs instead of up to get to bedrooms and there's a lock on the carpeted sideroom so people can so private stuff in there and it also connects back to the kitchen. Oh and also a small stage for bards to maybe enjoy

Bathouse: To get into the bath house you'll first have to get round the back of the tavern down an alleyway. I gave the ladies of the nite their own bedrooms and added a small changing room for visiting guests who want to spend time in the pool, the bathhouse lacks a kitchen but there is a tunnel to connect it back to the tavern meaning that if you want food you'll need to make a deal with the innkeeper

Weaponsmith and Armourer: these guys get a lovely spot bang center of town next to the keep. They share a smithy area and have a staircase that goes down to their forge right next to where they'll work. They also have their bedrooms above them connected to the smithy via a ladder for ease of sleeping

Feldsher: Largely phoned it in with the feldsher their place of work isn't much different apart from it now has a small examination room on the first level if you feel like doing GP larp

Stewards: Not much different has a door connecting it to the haulers area so you can yell at them.

Haulers: You guys start in a small dorm above the warehouse 

Garrison: You guys are now on the keeps side of the poverty gap your home is built into the wall all the stuff you get in the armory is largely the same as I didn't want to upset the balance. The jail cells face out over the moat and are open so the public can speak to the prisoners and such.

Soilers, mayor, and butcher: You guys are a lot closer to the town and hopefully by proxy the action at the butcher's house has been made a bit bigger but for the most part aside from you guys being closer it should be much the same (I also put down this cool scarecrow sprite I found)

I'm quite forgetful and am running out of things to type so I'll probably update this a bit later on to be less shit

Photos: If anyone wants to take a closer look feel free to @ me on discord where I can just provide the mapfile or you can checkout the branch if you know how :>
[ZLevel-1](https://i.imgur.com/1fjDJhS.jpeg)
[ZLevel-2](https://i.imgur.com/TGb9XWi.jpeg)
[ZLevel-3](https://i.imgur.com/akSWdje.jpeg)
[ZLevel-4](https://i.imgur.com/coW4YeT.jpeg)

Pre-Merge Checklist

[X] You tested this on a local server. 
[X] This code did not runtime during testing.
[X] You documented all of your changes.

The map was tested locally over a week with multiple people checking for bugs that include
audi_gzz
robotic_Potato
st.aldrich
chainsaw_mullet
wizardvalk
badatthisgame
saintburgher
Mojave
myself

I highly doubt we found every bug or mapping error and if able would like to request that if this PR is approved it first be played on a testmerge on a lower population to ensure any critical errors found can be ironed out properly

### CODE REVIEW

**Comment by Mojamble** [comment]
I LOVE THIS MAP, PUT IT IN RIGHT NOW, NOOOOOOW!!!

**Comment by spartanbobby** [comment]
[I felt the church was perhaps a bit too small so I've added this meeting room for the priest and his church members in an attempt to give them more private space of their own](https://i.imgur.com/jYVDGud.png)

**Comment by BadAtThisGame302** [comment]
[This map has been map-checked by real American patriots.](https://media.discordapp.net/attachments/913505492461043773/959296767814426684/factchecked.gif?ex=66a909fc&is=66a7b87c&hm=4e64bb31897595c309a1243bcad0753d5cca2958d0cf0bb52c066d8e5f384f9f&)

**Comment by Stutternov** [comment]
Right, **THIS WEEKEND** this will be going live. I'm fucking excited.

**Comment by ThePainkiller** [comment]
Scheduled for testmerging, going to be tested live this weekend. Real hype for a community-driven map with such extended testing.

**Comment by Cre77** [comment]
incredible map, absolutely in love. although just like with the old one, the elder's house and armory being unlocked results in adventurers vacuuming up the old sword and anything else of value within 5 minutes of roundstart

**Comment by spartanbobby** [comment]
The latest commit adds some little caverns in the mountains for people to hide out inside and a secret area that I don't wanna outwardly comment on but should be fairly obvious if you check mapdifbot

**Comment by Stutternov** [comment]
Going to full-merge this instead of keeping testmerge as it seems most bugs are ironed out unless you have any final parts to push.

**Pull request merged**
