### PR TITLE
Merchant Update, Alot of new items and more.

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Added alot of new Merchant items.

Apparel: ~~Silver Psycross, Golden Psycross~~ and a Tunic

Armor: Steel Bracers, Cloth Coif, Steel Coif, Steel Mask, Chainmalle, Hauberk and ~~Full Plate~~

Food: Added all the bottled beers styled for Roguetown and Zybantu Wine

Luxury: Spice, Ozium, Silver and Golden Rings

Weapons: Iron Mace, Short Sword, Dagger, Axe, Spear(Replaced the Copper one) and Flail

Replaces the Psycross sprites with news ones already on neck.dmi 
image image

Fixes spelling in the wine/beer bottles.

## Why It's Good For The Game

Merchant has alot of stuff, nothing too powerful or strong and overall pretty normal gear.

These Psycross sprites are better than the current ones IMO and that is why I changed them.

And capitalized the G and replaced volfberries with jackberries.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Dorodomki** [comment]
absolutely no to the full plate armor, the merchant already has the munition armor for heavy things to sell

**Comment by Mojamble** [comment]
I'd say fuck yes to all of it, including the full place, but it's price needs to be ABSURD. I look forward to selling more booze!

**Comment by BadAtThisGame302** [comment]
> absolutely no to the full plate armor, the merchant already has the munition armor for heavy things to sell

Removed full plate from the selection.

**Comment by BadAtThisGame302** [comment]
> I'm pretty sure psycrosses, especially silver ones, are going to be eventually more linked to anti-antag stuff and that they're not supposed to be easily obtainable. Merchant probably also shouldn't sell full-plate as that may make it too easy to get since it will bypass the scarcity of steel and manpower much more easily than importing iron would.

When they are more linked to anti-vampire stuff, then they can be removed/price jacked, until then they are fine decorative pieces.

And for your second point, I removed full plate.

**Comment by ThePainkiller** [comment]
Either remove hauberk or replace with haubergeon please.

**Comment by BadAtThisGame302** [comment]
> Either remove hauberk or replace with haubergeon please.

There's already a haubergeon so I just removed the hauberk.

**Comment by ThePainkiller** [comment]
People have expressed a discontent about importing psycrosses, can you please remove them?

I'll think about making acolyte-specific rituals to be able to fashion psycrosses with either gold or silver and bless them with effects in the near future

**Comment by BadAtThisGame302** [comment]
> People have expressed a discontent about importing psycrosses, can you please remove them?
> 
> I'll think about making acolyte-specific rituals to be able to fashion psycrosses with either gold or silver and bless them with effects in the near future

The now wooden psycross was already importable, you want that removed too?

**Comment by ThePainkiller** [comment]
The wood psycross can stay if you wish, honestly that one should be able to be carved out of a small log with a knife if possible since it's just "symbolic"

**Comment by Mojamble** [comment]
I see no issue with anything that's been axed as someone who plays merchant quite often. Unless someone shows up rolling in gold, you often don't have all that much coin. As long as things are priced properly, I just don't see an issue. Especially axing the amulets seems kinda off, given there's no real way to obtain them otherwise.

**Comment by Stutternov** [comment]
It's good that others reviewed this given my input would have been 'lol fuck vampires L' - changes seem to have been made, devs seem to agree with it, will set for merger.

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
