### PR TITLE
Marriage for All Couples [DONE]

### PR DESCRIPTION
**Pull request by InsightfulParasite**
## About The Pull Request
The gods will no longer curse you if your marrying someone of the same sex. Though now you will have to bite the apple first for your bride to take your surname.
**The above fact may be more important for nobles or the king**

I also added some more considerations for viable marriage candidates. Such as making sure they are alive and not SSD.

Notice: If two people at the wedding share the same real_name then the person being married will be selected randomly out of the two existing creatures. Dont know how much of a issue this is since im pretty sure there is safegaurds in place to prevent duplicates but i guess maybe goblin marriage will be weirder.

Additionally i noticed there was code that prevented surnames from being titles like " the wolves" or " of wolves". I placed a comment on where this code is if you ever want a marriage to share the same title.

## Why It's Good For The Game
If people want to ban gay marriage they could just do it in game. If 3 people are fine with the marriage then it should be allowed. Unless there is a solid canon lore that the divine creature officiating this union of souls hates gays.

If this also seems too easy of a way to get triumphs we can put in more hoops such as preventing nobles from marrying peasants or requiring a ring to be present since rings are made from a uncommon material and the idea of the king scouring the land for gold so he can marry seems humorous.

tweak: fluff.dm /obj/structure/fluff/psycross

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
So... we've become... 
### **_Woke._**

**Comment by sanshoom** [comment]
The #WOKEMOB is here. (this must be added)

**Comment by InsightfulParasite** [comment]
Still testing to make sure things dont explode when people are married and it works like i described.

**Comment by InsightfulParasite** [comment]
Im marrying Vivian of Rivia to Lilian to Givia to test the surname thing. Apparently if you have a title such as "of hellmires" then it will be thrown out.

**Comment by InsightfulParasite** [comment]
I married a goblin to a werewolf i think that means it works.

**Comment by zeratino** [comment]
@maaacha HEEEYYYYYY... LET'S GET MARRIED...

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
