### PR TITLE
swordmaster is now a master at swords

### PR DESCRIPTION
**Pull request by messagecypher**
## About The Pull Request
gives swordsmaster rare adventurer role skill 5 (master) in swords

## Why It's Good For The Game
swordmaster is currently grenzelhoft mercenary with plate armor and a nicer sword
also he's literally called "swordmaster" but has an expert skill in swords
hopefully it makes him a viable alternative to the captain(sheriff) and veteran who are the only two roles that can have master in swords

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by messagecypher** [comment]
please dont kill me with hammers this is the first time ive ever done a PR

**Comment by casualspacestation14enjoyer** [comment]
just call him a swordexpert :ohyea:

**Comment by ThePainkiller** [comment]
May I suggest upping the age requirement to Adult at least? Nobody becomes a swordmaster at young adult unless they're like some sort of prodigy.

**Comment by Optimism333** [comment]
In my humble opinion, a sword MASTER should at least be middle-aged, if not old.

**Review by ThePainkiller — APPROVED** [review]

**Comment by Optimism333** [comment]
I have to be frank. I think if you're going to touch the balance of this role, you may as well make a few more changes rather than just making it more powerful. Here's a few suggestions:

- Give swordmaster reading skill, he/she should be well-read and know plenty about martial literature on swords
- Now that you've given the role master level skill in swords, change the plate armor for something else. A role with sword mastery and also full plate is fucking absurd. Should have much less armor.
- Give some of the role's other stats buffs, such as endurance and intelligence +2
- See if you can figure out how to make it so signups have to at least be middle-aged
- Swap out the greatsword for a more balanced and practical steel bastard sword

As it is, I'm not a fan of just buffing the role's sword skill with no other changes

**Comment by ThePainkiller** [comment]
For the time being we can merge this as it's just a change that makes sense for them to be a RARE class, the balance touches can be addressed on a different PR with no issue. Rebalancing the class is outside the scope of this PR that is just a "this make sense" change.

**Comment by Stutternov** [comment]
Hasn't been updated; basically being-semi-addressed in more recent PRs.

**Pull request closed without merging**
