### PR TITLE
Old Psydonian Speech for Grenzelhoftians

### PR DESCRIPTION
**Pull request by Marmio64**
## About The Pull Request

Adds a unique old psydonain language available to only Grenzelhoft roles. Mostly designed to be put into use alongside #469 

Grenzelhoft roles would be all the ones defined in that PR-

Inquisitor/Puritan
Adepts/Confessors
Swordmasters
Grenzelhoft Mercs
Grenzelhoft Counts

Old Psydonian is an ancient language from before the Grenzelhoft empire had ever split, and is known chiefly by the clergy and inquisitional lodges.  Noblemen and devout soldiers often take lessons in the language as part of their theological classes, hoping to someday bring back the greatness of their former empire.

example of the font and language gibberish-
image

## Why It's Good For The Game

I think it would be interesting to make Grenzelhoftian roles seem more cohesive and solid, like they're all part of the same faction and speak the same language. In addition, allowing them to scheme together seems interesting and might open up unique opportunities, perhaps a dedicated grenzelhoft spy antag in the future?

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
This can either go well for characterization, or horribly wrong/cringy for very, **very** obvious reasons.

I like it, and I'd no trouble approving, but I'd like other devs to chime in and judge too because, well, you know how it usually goes when including german as a language

**Comment by guayitoo** [comment]
Hey, Guayo here!

I don't think Grenzelhoft requires it's own language.

Alternatively, would you think that perhaps a stand in for a latin, perhaps even calling it Old Psydonic would be a good stand-in? Perhaps known only by the church and it's affiliates?

Likewise, a Zybantu language would be more appropriate considering their cultural differences is far more significant!

Let me know what you think!

**Comment by guayitoo** [comment]
> > Hey, Guayo here!
> > I don't think Grenzelhoft requires it's own language.
> > Alternatively, would you think that perhaps a stand in for a latin, perhaps even calling it Old Psydonic would be a good stand-in? Perhaps known only by the church and it's affiliates?
> > Likewise, a Zybantu language would be more appropriate considering their cultural differences is far more significant!
> > Let me know what you think!
> 
> I think it's neat but also having it known by the Church seems kind of weird since they don't like to talk about psydon, and a zybantu language would be even more limited since only a single zybantine role exists.
> 
> I think Grenzelhoft really should have a unique language and be more and more integrated as a somewhat hostile but at the same time helpful faction since we already are getting some cool dynamics with visiting counts and the inquisitorial lodge. At the moment there isn't really any comparable outside forces other than grenzelhoft because the other factions only really have a single role associated with them (zybantine merc, elven sentinels/bladesingers, Dwarven longbeards) so to deny them more unique things seems like a lost opportunity.

We plan on expanding the Zybantu influence with more unique subcategories similar to Zybantu themed mercs, we're hoping to do this for things like Inquisitor, Merchant and other roles! So I don't think it's a waste.

Remember that, at least in lore, Grenz and Zybantu BOTH have big influence on the isle of Enigma. It may not reflect that in-game currently, but it is the plan to do so moving forward, you'd be contributing by committing to the idea as I've listed above.

As for why Grenz would use something like "Old Psydonic"? They used to be a mega empire similar to the Roman Empire back in the day, before collapsing and fracturing, the Grenzelhoft Empire is more reminiscent of the HRE trying to recuperate a lost glory.

Meanwhile Zybantu has always been more unified due to tyrannical methods and the fact that culturally almost all the rulers rejected the Pantheon, therefore, they should have a unique language to associate that foreignship from the mainland.

Hope this helps!

**Review by ThePainkiller — APPROVED** [review]
Approved by Loreholder, and that font goes hard af.

**Pull request merged**
