### PR TITLE
Food Module

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

Total cooking rework, no more menu craft for food, you use your hands, tools and ingridients.
Being so massive its hard to document in detail, but basically
* Food recipes gone
* Food making system added
* Assets modularized
* Water barrels easier to identify

New food art credit to Takyon for breads, meat, chicken, butter, cheesewheels.
Cheesemaking sprites, onion, plates, tatocuts, buns, new pies by me,.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by AceMcLazer** [comment]
I really like the cooking system (minus the current bugs.) I think using item interactions is way more elegant and immersive than boring crafting menus. A+

there doesn't seem to be any impact by the cooking skill though, other than the cook time?

**Comment by NPC1314** [comment]
> I really like the cooking system (minus the current bugs.) I think using item interactions is way more elegant and immersive than boring crafting menus. A+
> 
> there doesn't seem to be any impact by the cooking skill though, other than the cook time?

Yeah its just cooktime atm, some more functionality to the skill will be added, prob locking more exotic or "powerful" recipes

**Comment by Optimism333** [comment]
Bit of feedback, wooden spoons need to be added to a lot more locations. The butcher doesn't have any, despite being one of the main sources for milk, and neither does the soilson farmhouse.

Alternatively, there should be a way to craft them.

**Comment by NPC1314** [comment]
Some more updates in the last commit, crafting rolling pins, spoons, butcher spawns with one, milling sounds & timer add, frybread added, some cleanup, cheese straining fixed properly so cloth can be used as intended (tho heating still not in), mince beef amount increased

**Pull request merged**
