### PR TITLE
Locks the Royal Family to Humen-Only

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request

The Queen and Prince/ss roles can now only be humens. Sorry, Chichii.

## Why It's Good For The Game

I don't really consider Stonekeep a "grimdark" setting, but this definitely is a setting where there are big divides between the sapient races and it's hard to make your way up to the very top of the humen hierarchy if you're, say, an elf.

With that in mind, I think making the royal family humen-only would a) tie in more with themes of IC discrimination and social divides between the races b) make it so you don't have to awkwardly explain why your half-elf child has two humen parents (admittedly it's not like adoption doesn't exist).

I loosely polled the community on this, and the opinion was generally neutral to positive. If this proves to be a very controversial change, I would suggest it be test-merged so we can see if we suddenly get a massive drop in Queen players.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
based

**Comment by BadAtThisGame302** [comment]
This is peak

**Comment by guayitoo** [comment]
Hello, Guayo here!

I would prefer you did the following:

If King Humen & Queen Humen -> Humen Children

If King Humen or Elf & Queen Humen or Elf -> Half Elf Children

If King Elf or Queen Elf -> Elven Children.

The concept of humenity intermingling with the remaining elven population is present since the beginning of Stonekeep, and in lore, the more progressive elves are desperate to cling to whatever they can to earn political power and likewise ensure the survival of their race by intermingling with the humens.

Might be more of a hassle to code, but I would prefer this over completely eliminating elves and half elves from the ruling class.

Thank you!

**Comment by lavillastrangiato** [comment]
@guayitoo 
> I would prefer you did the following:
> 
> If King Humen & Queen Humen -> Humen Children
> 
> If King Humen or Elf & Queen Humen or Elf -> Half Elf Children
> 
> If King Elf or Queen Elf -> Elven Children.
silly guayo, kings could never be elves...

> Might be more of a hassle to code, but I would prefer this over completely eliminating elves and half elves from the ruling class.
> 
> Thank you!

I am not sure this is within my power to code; it would require running "checks" on ready-ups and late-joins. I would, however, be totally willing to close this PR in favour of that PR, when the time comes.

LMK if you would prefer I just close the PR and leave it for now.

**Comment by guayitoo** [comment]
> @guayitoo
> 
> > I would prefer you did the following:
> > If King Humen & Queen Humen -> Humen Children
> > If King Humen or Elf & Queen Humen or Elf -> Half Elf Children
> > If King Elf or Queen Elf -> Elven Children.
> 
> silly guayo, kings could never be elves...
> 
> > Might be more of a hassle to code, but I would prefer this over completely eliminating elves and half elves from the ruling class.
> > Thank you!
> 
> I am not sure this is within my power to code; it would require running "checks" on ready-ups and late-joins. I would, however, be totally willing to close this PR in favour of that PR, when the time comes.
> 
> LMK if you would prefer I just close the PR and leave it for now.

For now, I'd close this PR, I understand its a complex request. But yes, as mentioned before, I don't want to deny an entire race of players for the roles of Queen and Princes/Princesses.

Apologies for wasting your time coding this, perhaps in the future it can be revisited or modified depending on the desires of the server.

**Comment by lavillastrangiato** [comment]
Nah it took me about a hot minute, it's no big deal. 😃

**Pull request closed without merging**
