### PR TITLE
Bathwater Fishing Begone (Bugfix)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
Does what it says in the title: you can't use a fishing rod on bathwater tiles to reel in a carp anymore.

## Why It's Good For The Game
Fishing sanity, better immersion.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
I weep.

**Comment by AceVX** [comment]
Is bath water still drinkable? Can you fix that too?

**Comment by Optimism333** [comment]
> Is bath water still drinkable? Can you fix that too?

I'm gonna call that interaction a feature, tbh. Make fun of people IC if they drink the bathwater, but I don't see that as a huge issue.

**Review by NPC1314 — APPROVED** [review]
Ofc people drink the bathwater, makes perfect sense, thank you.

**Pull request merged**
