### PR TITLE
Hopefully fixes indoor weather?

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

I haven't tested it in-game cause I did this PR at 2 AM soo bare with me.

## Why It's Good For The Game

Title

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
I pray

**Comment by NPC1314** [comment]
Wont compile on box, got issues.

**Comment by BadAtThisGame302** [comment]
> Wont compile on box, got issues.

I'm on the game right now it's got no issues, idk why it's doing that.

**Comment by NPC1314** [comment]
It never could be deployed, it failed to compile on the server.
You done a localtest?

**Comment by NPC1314** [comment]
If it can be confirmed to work it gets a merge.

**Comment by BadAtThisGame302** [comment]
> If it can be confirmed to work it gets a merge.

It does work.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
