### PR TITLE
[Port] Mentorhelp/Voice System

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request
This allows players to opt-in to the "Voice" system in character creation. Those who opt-in will receive meditations/help requests from players who use the mentorhelp/meditate verb. Anyone can opt-in and anyone can send in mentorhelps.
(Ported from Ratwood)

## Why It's Good For The Game
This allows experienced players to fill a pseudo-mentor role and help individuals who may have questions about the game. This also allows newer players to ask their questions in a place that isn't discord; and hopefully get a quicker answer.

image
image
image
image
(Admin View includes ckeys | Non-admin does not)

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
“How do I use verbs.”

**Comment by ThePainkiller** [comment]
Hey this is quite unintrusive, and nice, **I seriously hope it is adminlogged so that people don't use it to meme or bypass admin observation**

**Comment by bowlofcereal** [comment]
This was an absolute broken mess of issues on Blackstone, but I guess giving it an attempt doesn't hurt.

**Review by Stutternov — APPROVED** [review]
Normally I'd wait for review properly but imo this is a very good addition.

It's not intrusive, and gives a means of gaining PQ for helping players (staff can do so easily from what I can see), plus allows for anonymous helping people without breaking immersion. 

I would like some QOL ports for it I've seen but hell it's good enough as is.

**Pull request merged**
