### PR TITLE
Removes useless code, allows latejoin on Hand and renames the Garrison .dms

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Removes the useless spell recruit code from the King/Queen/Captain, now that the Throne can Change Position.

Renames the gatemaster/manorguard/townguard/sheriff .dms to their proper and actual titles garrisonarcher/royalguard/garrisonguard/captain .dms (Also grants the RGs a Knight's Tabard)

Added the Dame female subtype to the Captain too.

Fixed Hand not being latejoinable even though they were meant to.

Added Puritan and Mayor to the job list, since they were missing.

~~Allowed the Queen to be latejoined (I tested and she never spawns as a ruler, with or without a round-start King)~~

Removed the useless Hand selection code.

## Why It's Good For The Game

Hand selection code is not used, clutter.

Recruit Spells were barely if never used, clutter.

Let the Hand/~~Queen~~ be latejoined, leaving only the King himself and the Queen not being allowed to now.

Fixes Puritan/Mayor not being on the job list.

Standardizes the Ser/Dame honoraries to the Captain finally.

Gives the RGs a Knight's Tabard for they are officially Knights with a title.

Updates the old .dms to their appropriate name.

## Screenshots

~~Queen~~/Hand latejoinable.
image

Dame Captain.
image

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by AceMcLazer** [comment]
having surprise kids latejoin as king/queen is fine but, latejoin queen when i'm spending the entire round looking for a wife is lame. Hand should be hand picked in lobby by king IMO.

**Comment by BadAtThisGame302** [comment]
> having surprise kids latejoin as king/queen is fine but, latejoin queen when i'm spending the entire round looking for a wife is lame. Hand should be hand picked in lobby by king IMO.

I personally think it's way more fun for a Queen to latejoin and create interesting scenarios that may spice up a boring round.

**Comment by Wesreidau** [comment]
I am also against a latejoin Queen or the removal of hand selections.

The king is often undermined by a queen/hand who he doesn't have the required trust with. If anything the King should select his Hand and Queen, and if he does not want the characters offered, that's that. Nobody wants to be at odds in their own royal court.

If a latejoiner wishes to join as Hand or Queen, the King should get a prompt to accept or decline the request. That would be a great way to allow latejoin queens and hands, since sometimes you've got 'mother is dead' or might not want the given character.

This solves some of our 'always the same character' problems.

We need a more robust hand selection code so if king A and king B pick hand A and hand B respectively, we always stick with AA or BB pairings, not the AB pairings that made hand selection code useless.

Renaming the DMs is some good housekeeping however. I just hope there's no broken spaghetti.

**Comment by BadAtThisGame302** [comment]
> I am also against a latejoin Queen or the removal of hand selections.

I'm sorry to say but the code is completely useless, it's not a removal of Hand selections, because there never truly was one. The fact the King could pick a Hand and another joining is a prime example on why the * around their name makes 0 difference.

**Comment by ThePainkiller** [comment]
Recruit code is mostly used for rebellion gamemode or to give pilgrims an officialization under the crown, please don't remove any "clutter code" that doesn't optimize anything just because "players don't use this, ever".

**Comment by BadAtThisGame302** [comment]
> Recruit code is mostly used for rebellion gamemode or to give pilgrims an officialization under the crown, please don't remove any "clutter code" that doesn't optimize anything just because "players don't use this, ever".

Recruit spell code for Guardsman/Servant, I didn't touch any rebel recuritment things... as shown in the files.

**Comment by BadAtThisGame302** [comment]
> I don't think this would be as good as you think it is.
> 
> Hand and Queen are two roles that rely on trust and both have the freedom to deceive or plot against the King. They are best when they have the full timespan of a round of Stonekeep to play their games.

And yet Queen, not to mention Hand is rarely filled. Adding it to the latejoin (which, given it has total_positions = 1 means it was meant to be a latejoinable job)
I guess it can be TM'd and we can see.

**Comment by Stutternov** [comment]
Tbh remove Queen from late join and I'd be in support of this. Latejoin hand is honestly totally fine but late join queen can really sour round roleplay of a king finding a wife or the like.

**Comment by BadAtThisGame302** [comment]
> Tbh remove Queen from late join and I'd be in support of this. Latejoin hand is honestly totally fine but late join queen can really sour round roleplay of a king finding a wife or the like.

Removed Queen from latejoin.

**Comment by BadAtThisGame302** [comment]
> Also, with the renamed guard stuff, are their spawns for round start fine? Just confirming before merger.

Yes, tested the RG, Garrison Archer, Captain and Garrison Guard and they spawn in their appropriate places.

**Comment by ThePainkiller** [comment]
I'm still very against the removal of the recruitment spell, it was good for roleplay or recruiting pilgrims into defending the town during siege events or vampire rounds, or at least symbolic during Rebel rounds.

**Comment by BadAtThisGame302** [comment]
> I'm still very against the removal of the recruitment spell, it was good for roleplay or recruiting pilgrims into defending the town during siege events or vampire rounds, or at least symbolic during Rebel rounds.

Nobody ever uses it, like not a single soul, plus the Throne's Change Position does what the recruitment spell does + more.

**Comment by ThePainkiller** [comment]
> Nobody ever uses it, like not a single soul, plus the Throne's Change Position does what the recruitment spell does + more.

Solid argument ngl, alright no issues with this then

**Review by ThePainkiller — APPROVED** [review]

**Pull request merged**
