### PR TITLE
Preserves the ETERNAL SOUL of Stonekeep by changing how autovotes work.

### PR DESCRIPTION
**Pull request by 1N7Slayer**
## About The Pull Request

Restart votes should no longer occur automatically - and are instead replaced by endround prompts, automatically. Instead, the round votes to end approximately as stated in the code (look, BYOND ticks work according to however BYOND fucking counts it). Time since last vote also adjusted accordingly. Changed a little fluff thing as well.

Worth noting that the game will also attempt to endroundvote in 15 mins naturally late into the round if no antags exist, or their objectives are complete, et cetera. Some numbers were tweaked there too, namely to have a normal gap between round votes. The round will also attempt to restart naturally after 3 hours, according to the code.

## Why It's Good For The Game

Restart votes don't accrue triumphs, make it harder to audit a player who griefed in a round by virtue of the round end screen never occurring during a server restart and therefore you/the Discord bot can't showlads a player, et cetera. Also they just really fuck up the end of the round and prevent you from tying up loose roleplay ends, leading to, overall, an extremely negative outcome for a majority of players dealing with restart votes.

~~Please actually TM and test this. Nothing was commented out this time, just a few variable changes.~~ nope we're good

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
# Localtest, please.

We've done this in the past and it caused actual roundend votes to:

1. Brick themselves (they didn't end the round and we've had to ask admins to force restart)
2. Cause another vote to happen 15 minutes after the roundend vote had passed

**Comment by NPC1314** [comment]
> # Localtest, please.
> We've done this in the past and it caused actual roundend votes to:
> 
> 1. Brick themselves (they didn't end the round and we've had to ask admins to force restart)
> 2. Cause another vote to happen 15 minutes after the roundend vote had passed

If I recall these issues never appeared on localtests so might be some box side config stuff, anyways uhhh.....
just be prepared for unexpected major issue, testmerge on off hours might be the only way to check

**Comment by 1N7Slayer** [comment]
localtested, works on my local copy

also the config on the Stonekeep live server likely disables player-initiated votes, all votes are automatic or admin started

**Comment by Stutternov** [comment]
Will test merge later today/tomorrow

**Comment by 1N7Slayer** [comment]
deprecated the old voting system. fuck you

**Comment by Stutternov** [comment]
So, PR was tested on server. Dunno if you got feedback as I asked people keep doing.

But yeah the voting broke the server like twice. Basically kept doing votes and not ending even in a vote passed. Tell me if you think you can fix this for re-adding to test merge.

**Comment by Stutternov** [comment]
Tell me when you get this PR working so it can be test-merged again.

**Comment by Stutternov** [comment]
Will test merge this soon; I want to test it when I am home to verify it's working incase of needed revert.

**Pull request closed without merging**
