### PR TITLE
Adds the Old Age to Bathmaids

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request
Title

## Why It's Good For The Game
(G/D)ilfs.

Requested by Guayo

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by guayitoo** [comment]
Guayitoo here, I approve!

**Comment by sanshoom** [comment]
Based.

**Review by ThePainkiller — APPROVED** [review]
Imagine being Revan's player in that bathouse scene and having to be all like _"https://chatgpt.com/c/4cd7b615-f704-4e99-92bb-415d14f10a5f#:~:text= damn, Old Dwarven Bathwench, you fuckin' fine, all sexy with your tight body and horrific androgynous monster face. I would totally have sex with you, both my character and the real me."_ when all he really wants to do is harass another female elf in his dressing room. Like seriously imagine having to be Revan and not only sit in that chair while that granny bathwench flaunts her disgusting body in front of you, the favorable lighting barely concealing her stretchmarks and leathery skin, and just sit there, text after text, hour after hour, while she perfected that dance. Not only having to tolerate her monstrous fucking visage but her haughty attitude as everyone on the server tells her she's **STILL GOT IT** and **DAMN, DWARVEN HAGS LOOK LIKE THAT??** because they're not the ones who have to sit there and watch her mannish fucking goblin face contort into types of grimaces you didn't even know existed before that dae. You've been ERPing nothing but a healthy diet of elves and princesses and later alleged zape victims for your **ENTIRE CAREER** coming straight out of the Murderwoods in Ratwood. You've never even seen anything this fucking disgusting before, and now you swear you can taste the sweat that's breaking out on her dimpled stomach as she sucks it in to writhe it suggestively at you, smugly assured that you are enjoying the opportunity to get paid to sit there and revel in her _"petite (for that is what she calls herself) beauty"_, the beauty she worked so hard for with bathouse patrons in the previous yils. And then the Niteman calls for another scene, and you know you could kill every single person in this room before the town guard could put you down, but you sit there and endure, because you're fucking Revan. You're not going to lose your future professional roleplayer career over this. Just bear it. Hide your face and bear it.

**Comment by Catalaria** [comment]
gundam can i cum?

**Pull request merged**
