### PR TITLE
The Combat Music-ening (Music to my ears)

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

It's alot of commits and PRs but all of this music comes from Blackstone. (txt file gives credit)

The roles that get unique/shared/new combat music are as follows:
Jester
Maniac
Vampires
Zombies
Vaquero
Grenzelhoft Mercenary and Count
Dungeoneer, Skeleton and Death Knight
Mayor
Feldsher
Merchant
Garrison Guard/Archer, Veteran and Royal Guard
Zybantu Mercenary
Beggar and Prisoner
Amazon and Barbarian
Werewolf

## Why It's Good For The Game

It's a shame for the music to go to waste and from the sounds I've had it is pretty amazing, plus gives more flavor to various underappriciated roles and more banger music as you get greater firedballed by the Court Magician.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by assortedbeads** [comment]
Is any of this set to preload?

Sounds in general lag in my experience and preloading which connecting would be preferable to freezing ingame

**Comment by BadAtThisGame302** [comment]
> Is any of this set to preload?
> 
> Sounds in general lag in my experience and preloading while connecting would be preferable to freezing ingame

I don't know if it is or if it isn't.

**Comment by Cre77** [comment]
> I don't know if it is or if it isn't.

your prs in a nutshell
image
at least compress some of these

**Comment by BadAtThisGame302** [comment]
> 
> 
> > I don't know if it is or if it isn't.
> 
> 
> 
> your prs in a nutshell
> 
> image
> 
> at least compress some of these
> 
> 

Cool.

**Comment by ThePainkiller** [comment]
Why the fuck do non combat classes have combat bgm??
Merchant??? Mayor??? **FELDSHER???????**

**Comment by BadAtThisGame302** [comment]
> Why the fuck do non combat classes have combat bgm??
> 
> Merchant??? Mayor??? **FELDSHER???????**

Because Blackstone had it so I ported it, why not? Doesn't matter that they are non combat classes they can still get cool music.

**Comment by ThePainkiller** [comment]
> Because Blackstone had it so I ported it, why not? Doesn't matter that they are non combat classes they can still get cool music.

Because people will hang up on this to justify them having combat stats, which I will personally never allow, so I don't plan on giving idea guys even an inch on it :)
We've already people saying that noble trait is a justification for skilled swords skill, can you imagine what giving them snowflake combat music will do? We're not fragtown like Blackstone, please keep that in mind

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
