### PR TITLE
Troll Update

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

Resprites + Partially Reworks Trolls,

Trolls now have rapid health regeneration, their healing only stopping when being lit on fire. 

Trolls will be sneaky when not actively hunting someone down.

Trolls Look Cooler Now.
troll2
troll1

Credits: 
Infrared Baron: Making the Troll Sprites
lgrsupreme: Commissioning/sharing the sprites

## Why It's Good For The Game

Trolls looked ugly, now they dont. Also makes them more interesting both mechanically and visually

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
# **INFRARED BARON SPRITES SPOTTED**
## **ACTIVATING INSTAMERGE PROTOCOLS**

**Comment by SELFHELL** [comment]
On update, the troll heart is out of scale for this PR. Ill just add it at a later date, PR should be ready now

**Comment by NPC1314** [comment]
Lets see how it fares

**Comment by NPC1314** [comment]
uses sitting icons for movement, you gotta fix that

**Comment by SELFHELL** [comment]
Problems addressed, Cave Trolls shouldnt look weird anymore.  Also SEVERELY bumps up the regen since a single dude can outdps it

**Comment by NPC1314** [comment]
Allright updated the TM if nothing new pops up a fullmerge going in later today

**Comment by NPC1314** [comment]
I had in mind to shift trolls over to slower lumbering type, reduce move speed and crit vulnerability, but bit outside the scope of the PR I suppose. Worth keeping in mind

**Comment by ThePainkiller** [comment]
### ONLY *AFTER* decreasing their movespeed and testing that it is lowered, ONLY THEN we'll take away crit weakness.
As it stands these fuckers are fast as a fucking vulf. After that gets solved, we'll remove the crit weakness trait so that trolls are the slow, bulking menaces they always ought to be, but not fast as fuck Eris Emperor spider speed fuckers with massive healthpools and health regen.
Sidenote: Would be a good idea to make it so they don't regenerate health if they're lit on fire.

**Comment by SELFHELL** [comment]
They already dont regen when aflame, but ill slow the movespeed

**Comment by NPC1314** [comment]
If you gonna test making them slow and remove crit weakness please update the description, 
its not a problem just so its clearer
Start with the move and lets get that right before touching crit bit, diff commits, ez.

**Comment by SELFHELL** [comment]
Alright, slowed them down + Removed Critvuln. Decided to do both at the same time in the interest of time

**Comment by NPC1314** [comment]
Allright lets see how it does

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
