### PR TITLE
DakkaTownKeepMap the Third

### PR DESCRIPTION
**Pull request by DAKKA-WAAAGH**
## About The Pull Request

The long-awaited map by yours truly, with the much-needed help of our gracious host, our genius coders, and our wonderful community. **It's ready for testmerging**, but it's lacking a few of the features I would have liked to ship with it (such as "cryo"). Those things can be added later because I sure as hell don't know what I'm doing with them.

As for the design of the map, it's got a lot awaiting you:
- FOUR neighboring maps:
    - West: Forest - Three zlevels and a WHOLE lot of trees, you can find the Village ran by the Elder here
    - North: Mountain - Three zlevels and tons of good ore deposits, there's barely any amenities here but you can find a small camp
    - East: Swamp - Two zlevels and a fuckload of spiders... so many spiders; there are a few places to seek refuge in but you'll have to look for them
    - South: Coast - Two zlevels and a BOAT for latejoiners, owned by the much renowned Merchant's Guild... don't break or take anything if you value your life

- Plenty of buildings to do with as you please, including apartments, houses, and the occasional abandoned hut here and there
- A full-fledged sewer system (which could use some more fluff in the future), be wary of the rats...
- So Much More™

### Map Previews (as of 6/24/2024)
<details>
  <summary>Town zLevels 1-4</summary>
  <div align="center">
  
image
image
image
image

  </div>
</details>

<details>
  <summary>Forest zLevels 1-3</summary>
  <div align="center">
  
image
image
image

  </div>
</details>

<details>
  <summary>Mountain zLevels 1-3</summary>
  <div align="center">
  
image
image
image

  </div>
</details>

<details>
  <summary>Swamp zLevels 1-2</summary>
  <div align="center">
  
image
image

  </div>
</details>

<details>
  <summary>Coast zLevels 1-2</summary>
  <div align="center">
  
image
image

  </div>
</details>

## Why It's Good For The Game

I'll be taking the free PR Bingo space of "Variety is nice!". I've been designing this thing since sometime in March and have only gotten neutral or positive feedback on it, suffice to say that there's a desire for new stomping grounds.

This will take some maintaining, and, of course, I can do the majority of maintaining as needed... long as it doesn't involve fancy coding.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Personal Checklist
- [x] Get MapGen working (on ALL levels)
- [ ] Get "Cryo" working (on boat, in Coast level)

### CODE REVIEW

**Comment by Optimism333** [comment]
## Sewer Addition Ideas ##

- Shitty makeshift kitchen with rotten food and one beer barrel, a few rats
- Sewer troll lair (beware the trooooooll). Filled with knick knacks the troll has hoarded and maybe bones or blood as a warning that the player is getting close

**Comment by CormanQuewye** [comment]
Not to be 'that guy' but why a big boat and why is it owned by the merchant's guild? Not everything that has to do with moving cargo and trade is 'merchant's guild'. People arriving to Rockhill are either doing it by foot (drifters) or are ferried in from Kingsfield Plains, by a river, from the North. Why there's an area to the South where the Boglands are meant to be, that's suddenly by the coast, and carrying people in a big boat from who knows confuses me and feels not thoroughly thought through.

To make this even more confusing, what then is the point of the Merchant Guild's Balloons if they apparently have a big boat parked in a wheelbarrow's distance? My advice is move the swamps back to the South, have the swap point be a small ferry boat on river docks, in the town map (as it already is) since that also lessens the chance of bandits setting up camp at the 'spawn point' (another thing I'd think the town planner would take into account) and get rid of the boat.

**Comment by DAKKA-WAAAGH** [comment]
> Not to be 'that guy' but why a big, seaworthy boat and why is it owned by the merchant's guild? Not everything that has to do with moving cargo and trade is 'merchant's guild'. People arriving to Rockhill are either doing it by foot (drifters) or are ferried in from Kingsfield Plains, by a river, from the North. Why there's an area to the South where the Boglands traditionally were swapped withwhat's suddenly coastline, and carrying people in a big boat from who knows confuses me and feels not thoroughly thought through.
> 
> To make this even more confusing, what then is the point of the Merchant Guild's Balloons if they apparently have a big boat parked in a wheelbarrow's distance? Why is the town not in the coast map to take advantage of the economic advantages the sea gives such as fishing and easy trade access? My advice is move the swamps back to the South, have the spawn point be a small ferry boat on river docks (which doubles as cryo, people are just going back to Kingsfield, not half the world away), in the town map (as it already is) since that also lessens the chance of bandits setting up camp at the 'spawn point' (another thing I'd think the town planner would take into account) and get rid of the big boat.
> 
> EDIT: Hell, alternatively, just put the current boglands map in the South replacing the coast and your new swamp map left where it is. That even gives some _environmental storytelling_ to why the Isle of Enigma, being as small as it is, is able to retain political independence. It's got some ancient technology, well defended economic areas (Kingsfield), and its political and military centre (Rockhill) is surrounded by swamp land and the murderwoods. Good luck setting siege when your forces keep dying to leeches and malaria.

I appreciate the feedback, but the neighboring maps are placed there because the original intention was to just revamp roguetown.dmm where the forest was to the west, mountain was to the north, swamp was to the east, and now -- a coast to the south. At this point, I'm settled in on the shape the map is taking and moving things around would take more effort than it's worth.

As for the boat... it's just the most convenient place to put non-combat latejoins and cryo in lol. Don't worry about bandits camping there, because it's already a rule violation to camp latejoin spawns.

If you have any more feedback, please let me know. I love to implement peoples' ideas.

**Comment by DAKKA-WAAAGH** [comment]
> Do bandits and vampires still have their exits/entrances in the forest? The forest seems way more difficult for them to do stuff in because a large and well defended village takes up a significant portion of it while also blocking the only exit to the town. In addition to that, the forest now has rather orderly pathways and the gigantic amount of trees makes the walkable space seem tiny and hard to move about stealthily.

The Bandits still spawn in the forest, the Vampires do not (they spawn in the Mountains now). Make no mistake, the village is hardly well-defended; a few palisades here and there will barely make a difference without a gate being built and without cutting down all the trees that will hang over them. The single entry/exit is fine, given that nobody is allowed to camp the travel tiles. Any fights on those would be happenstance and out of my control.

The "rather orderly" pathways will be covered in traps and ambushes (with mapgen, eventually), and climbing trees will almost certainly be the go-to method of traveling the forest for those with the climbing skill (rendering traps and ambushes null).

The narrowness of the pathways will be deadly for ambushes, and that's intended I can assure you.

Above all, playtesting will point out any flaws in the design better than any review of the map file and I look forward to it (eventually).

**Comment by Stutternov** [comment]
Tonight - the test mergening.

**Review by Stutternov — APPROVED** [review]

**Comment by Stutternov** [comment]
can't do vote maps due to modular multi-z code; sooo guess we're not having  map voting.

due to how annoying the playerbase is spamming me with 'add the map!!!' im not even gonna bother wasting my time doing map rotation code. if the map feels empty due to low player count cope i guess

**Pull request merged**
