### PR TITLE
Family Subsystem[GOOD FOR TESTMERGE!]

### PR DESCRIPTION
**Pull request by InsightfulParasite**
## About The Pull Request
Adds the family tree subsystem which keeps track of who is related to who and the familial drama.
Adds a preference option for the family system. 
Adds setspouse option for parents and newlyweds so that they are set up with a preferred character.
NOTE: Family system is overridden/disabled for some roles such as king, queen, inquisitor, and acolyte.
- None: Disables the family system except for when your king and your hardcoded to be the prince's dad.
- Siblings: Assigns you to a family based on your species. Low chance of adopted status and being placed in a family of another species.
- Parent: Assigns you as Patriarch or Matriarch of a family. If empty initialized families are full then it will create a new family for you to fill.
- Newlywed: Simply marries you to another player without all the family subsystem jargen.

Adds ListFamily and Toggle Family UI under the Memory tab.
Marriage assigns someone as your spouse.
Screenshot 2024-08-25 145926

add: Familytree subsystem

## Why It's Good For The Game
I was told that familial relation, bastard or otherwise, would assist in RP.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.
- [x] Calculatespecies system was tested.
- [x] Calculatespecies is overrided by family pref.
- [x] Marriage was done successfully

### CODE REVIEW

**Comment by Ickysoup** [comment]
Thoughts on being able to choose who your family is?

**Comment by InsightfulParasite** [comment]
> Thoughts on being able to choose who your family is?

I mean it is possible. I would have to put the prompt on your family after a person spawns.
The real question is if the maintainers are okay with it because it may lead to metagangs.

**Comment by InsightfulParasite** [comment]
I should also ask if we need the parent system for normal villagers.
In summary how the system works is that one person sets their family preference as Siblings or Local (Names are up for debate)
Siblings are added to a first gen list and locals are sorted into 3 lists based on their species. 
What happens when there is no locals is that first gens will be assigned a text variable family based on their species and a rand(1,3). So if there is no parents theres a 1/3 chance of being in the same family as another based on random chance. Dwarves would not be related to elves since "unknown_dwarf_1" is not the same as "unknown_elf_2".

**Comment by InsightfulParasite** [comment]
Alternatively we can just have the preference be on and off with random chance being how you get siblings. Though you may get some situations where a uncomfortable number of people in rockhill are related to eachother.
A flaw i just noticed is that the 1-3 default families dont apply to people if there is a parent in the parents list so already that could cause half the town to be related to one guy who chose parent. Ill fix this later.

**Comment by InsightfulParasite** [comment]
if(ishuman(user))
			/*
			* Familytree Subsystem Recognition
			* H is who examines us so the
			* perspective is H looking at src.
			* This all could honestly be
			* turned into its own proc.
			*/
			var/mob/living/carbon/human/H = user
			//Relation of examiner to them H --> src
			if(H.family[FAMILY_SPOUSE] == src)
				. += "<span class='love'>It's my spouse.</span>"
			if(H.family[FAMILY_MOTHER] == src)
				. += "<span class='info'>It's my mother.</span>"
			if(H.family[FAMILY_FATHER] == src)
				. += "<span class='info'>It's my father.</span>"
			//Parent src --> H
			if(family[FAMILY_FATHER] == H || family[FAMILY_MOTHER] == H)
				. += "<span class='info'>It's my progeny.</span>"
			if(src != H)
				//Sibling, if both are true you are full blooded siblings, otherwise half blooded.
				if(family[FAMILY_MOTHER] == H.family[FAMILY_MOTHER] && family[FAMILY_MOTHER] != FALSE)
					. += "<span class='info'>We share the same mother.</span>"
				if(family[FAMILY_FATHER] == H.family[FAMILY_FATHER] && family[FAMILY_FATHER] != FALSE)
					. += "<span class='info'>We share the same father.</span>"

**Comment by InsightfulParasite** [comment]
/*
* For altering the species of the
* offspring based on their parentage.
* Used mostly for princes.
* Its 3:16 AM when i coded this
* but its no excuse for it being
* a mess.
*/
/datum/controller/subsystem/familytree/proc/CalculateSpecies(mob/living/carbon/human/H)
	var/datum/species/new_species
	var/mob/living/carbon/human/dad = H.family[FAMILY_FATHER]
	var/mob/living/carbon/human/mom = H.family[FAMILY_MOTHER]
	var/datum/species/offspring_species = H.dna.species
	var/datum/species/father_species = dad.dna.species
	var/datum/species/mother_species = mom.dna.species
	//If mother and father arnt present
	if(!father_species && !mother_species)
		return
	if(offspring_species != father_species)
		new_species = father_species ? father_species : mother_species
	if(father_species && mother_species)
		new_species = CalculateMix(offspring_species, "[father_species.id] [mother_species.id]")
	if(!new_species)
		return
	H.set_species(new_species)

//Calculate mixture.
/datum/controller/subsystem/familytree/proc/CalculateMix(offspring, mixture)
	var/heritagehuman = findtext(mixture, "human")
	var/heritageelf = findtext(mixture, "elf")
	var/heritagedwarf = findtext(mixture, "dwarf")
	var/heritagetiefling = findtext(mixture, "tiefling")
	/*
	* Teifling blood is infused with
	* otherworldly energy so their
	* offspring are always born with
	* horns.
	*/
	if(heritagetiefling)
		return /datum/species/tieberian
	/*
	* So far humans are the only race that can
	* produce viable offspring with elves and dwarves.
	*/
	if(heritagehuman)
		if(heritageelf)
			return /datum/species/human/halfelf
		if(heritagedwarf)
			return pick(/datum/species/human/northern, /datum/species/dwarf/mountain)

**Comment by InsightfulParasite** [comment]
/*
	* Teifling blood is infused with
	* otherworldly energy so their
	* offspring are always born with
	* horns.
	*/
	if(heritagetiefling)
		return /datum/species/tieberian
	/*
	* So far humans are the only race that can
	* produce viable offspring with elves and dwarves.
	*/
	if(heritagehuman)
		if(heritageelf)
			return /datum/species/human/halfelf
		if(heritagedwarf)
			return pick(/datum/species/human/northern, /datum/species/dwarf/mountain)

**Comment by InsightfulParasite** [comment]
This is the code i used initially for making the lord and lady spouses. Should i readd this?
	var/mob/living/carbon/human/R = SSticker.rulermob
	var/mob/living/carbon/human/H = L
	//If the ruler isnt you and it isnt nothing and you lack a spouse this is now your spouse.
	if(R != src && R != null && R.family[FAMILY_SPOUSE] == FALSE)
		R.family[FAMILY_SPOUSE] = H
		H.family[FAMILY_SPOUSE] = R

**Comment by InsightfulParasite** [comment]
I cant seem to test it locally anymore due to this error 
Screenshot 2024-08-22 003600

**Comment by NPC1314** [comment]
The questionmark after done is a bit concerning, did it pass localtesting and actually work?

**Comment by InsightfulParasite** [comment]
> The questionmark after done is a bit concerning, did it pass localtesting and actually work?

I have a video of it working before the error occured. I dont know why mutable_overlays is erroring because i havent touched it at all. I went to another branch and the error was still occuring so its not my code. Ill check again.

**Comment by InsightfulParasite** [comment]
image
Is this because i updated my byond client?

**Comment by InsightfulParasite** [comment]
I dont even know who to ask about this because its all my branches.

**Comment by NPC1314** [comment]
Theres been a fix applied to a BYOND issue to the repo, update and see if it solved your problem

**Comment by InsightfulParasite** [comment]
> Theres been a fix applied to a BYOND issue to the repo, update and see if it solved your problem

Thanks, im certainly going to avoid neurotically updating my byond client now after this. Ill send some screenshots of the latest local test to show it works.
This is a general screenshot im putting this PR on draft until i fix some more problems i encountered in the latest test.
image

**Comment by InsightfulParasite** [comment]
image
Calculate species works. But the human daughter is not related to the king due to her family prefrences being set to none.

**Comment by InsightfulParasite** [comment]
After feedback i now have more of a direction.
- [ ] Remove the changing race on spawn as prince, rework the code for other kinds of logic
- [ ] Add "adopted" progeny as examine text. Might be a bit more tricky.
- [ ] Test Above Code.

**Comment by InsightfulParasite** [comment]
Im going to hold onto the old code as a individual commit since i do think its simplier functions could be useful for anyone who doesnt want this to be so complicated with datums and helpers.

**Comment by InsightfulParasite** [comment]
Next Goal.
- [ ] Set spouse option
- [ ] admin verb to see all families.

**Comment by Ickysoup** [comment]
I don't if it's outside the PR, but having languages passed down from parents to children would be nice. I imagine parents would pass on their native language onto their children. If the Archivist is able to speak every language, I don't think there would be any IC reasons why children couldn't. At the very least, be able to understand their parents' language. P.s great addition to the game thanks for making it.

**Comment by InsightfulParasite** [comment]
> I don't know if it's outside the PR, but having languages passed down from parents to children would be nice. I imagine parents would pass on their native language onto their children. If the Archivist is able to speak every language, I don't think there would be any IC reasons why children couldn't. At the very least, be able to understand their parents' language. P.s great addition to the game thanks for making it.

I might be able to do that but only on roundstart or children born after the archivist is in.
NEXT GOALS
- [ ] See if i can code visual overlays for family members.
- [ ] Language inheritance, may ask admins if its okay or have the languages past down be randomly picked out of all of them. "Dad only taught me to speak infernal"

**Comment by NPC1314** [comment]
Noticed some runtimes that I suspect has to do with this one?
https://pastebin.com/1KFEZDF6

**Comment by InsightfulParasite** [comment]
> Noticed some runtimes that I suspect has to do with this one? https://pastebin.com/1KFEZDF6
Its when two people without families examine eachother. Because i foolishly made if(family_datum == stranger.family_datum) succeed on 2 people without families. It should be fixed now.

**Comment by NPC1314** [comment]
Good updates, the issues are being ironed out nicely.

I'm not sold on the HUD thing thoug,, a similar style feedback as when bandits examine each other would be preferable.
Theres almost no HUDs anywhere else for a reason, they got utility but it has a cost.

**Comment by Stutternov** [comment]
Right, given this is fully working this is getting full merged.

If more work is needed on its systems, continue it on new PRs - doing this to avoid conflicts if anyone touches the same files for whatever reason.

**Comment by InsightfulParasite** [comment]
> Right, given this is fully working this is getting full merged.
> 
> If more work is needed on its systems, continue it on new PRs - doing this to avoid conflicts if anyone touches the same files for whatever reason.

Gotcha gotcha!

**Pull request merged**
