### PR TITLE
graveyard and waterrfont district (Now actually in the right format)

### PR DESCRIPTION
**Pull request by YuiY1997**
pleasepleasepleasepleaseplease

## About The Pull Request

redoes the graveyard
no longer has 100,000 additional lines
redoes the empty lot replacing it with the waterfront district
no longer has 100,000 additional lines
adds keys for the new houses
no longer has 100,000 additional lines

## Why It's Good For The Game

More places to roleplay, doesn't kill the mapgen

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by YuiY1997** [comment]
ROGUEWORLD (18+) 2024-07-07 055731
ROGUEWORLD (18+) 2024-07-07 055758
ROGUEWORLD (18+) 2024-07-07 055806

**Comment by DAKKA-WAAAGH** [comment]
There were a lot of issues with this PR, but I'm glad they're resolved lol.

I would prefer if this were split into two separate PRs, but this has sat long enough in my opinion.
I would also prefer if the underground portion was shown in the previews too!

Otherwise, these are acceptable changes to me.

**Comment by Stutternov** [comment]
Recent map merger on the map, update your branch and check for conflicts. Confirm when sone for review/merger.

**Comment by Stutternov** [comment]
Hasn't been updated in weeks; re-open when able to update map and fix conflicts.

**Pull request closed without merging**
