### PR TITLE
Noncombatant Rebalancing: (Craftsmen, Commoners, Churchmen, Some Nobility) (Combat Skills)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
There's been a lot of concern about the falling behind of noncombatants since the Malum pr, so a broad but simple compromise has been reached.

Almost all noncombatant roles will get at least average in a combat skill relevant to their work or what could otherwise be reasonable. In many cases this was just changing a value from 1 to 2.

However, as balance compromise for this, training dummies can no longer increase weapon skill levels past average (2) either. Many combat classes (mercs, clerics, basic garrison) have been pulled down to 3 as a baseline, and 3 and beyond will be the levels that will require actual combat experience to reach. Whether that be by sparring or fighting.

### Craftsmen ###
- Smiths (pilgrim and town) have had axes/maces increased from weak (1) to average (2)
- Woodcutter has had axes/maces increased from weak (1) to average (2)
- Carpenter has had axes/maces increased from weak (1) to average (2)
- Mason has had their axes/maces set to average (2), instead of a chance between weak (1) and skilled (3)
- Legendary Carpenter has had axes/maces increased from weak (1) to average (2)
- Legendary Mason has had axes/maces increased from weak (1) to average (2)
- Legendary Smith has had axes/maces increased from weak (1) to average (2)
- Apprentice has had axes/maces increased from weak (1) to average (2)

### Nobility ###
- Niteman has had knives increased from weak (1) to average (2)
- Noble (Pilgrim) has had bows increased from weak (1) to average (2) if female, and swords increased from weak (1) to average (2) if male
- Merchant (Pilgrim) has had knives increased from weak (1) to average (2)
- Feldsher has had knives decreased from expert (4) to average (2)
- Merchant has had swords increased from weak (1) to average (2), and been given a rapier and a satchel
- Prisoner has had swords increased from weak (1) to average (2)
- Steward has been given average (2) in knives

### Commoners/Serfs ###
- Butcher has had knives increased from weak (1) to average (2)
- Cheesemaker has been given average (2) knives
- Fisher has had knives increased from weak (1) to average (2)
- Miner has had axes/maces increased from weak (1) to average (2)
- Peasant has had axes/maces skill removed, and has had polearms increased from weak (1) to average (2)
- Physicker has had knives increased from weak (1) to average (2)
- Legendary Chef has had knives increased from weak (1) to average (2)
- Legendary Fisher has had knives increased from weak (1) to average (2)
- Legendary Miner has had axes/maces decreased from skilled (3) to average (2)
- Weaver has had knives increased from weak (1) to average (2)
- Nitemaidens have been given average (2) in unarmed and wrestling, to push troublesome clients out of the baths
- Butler/Maid has been given average (2) in knives
- Cook has had knives increased from weak (1) to average (2)
- Gravedigger has had polearms increased from weak (1) to average (2)
- Jester has had knives increased from weak (1) to average (2)
- Innkeep has been given skilled (3) wrestling, and has had their swords set to average (2), instead of a chance between weak (1) and average (2)

### Churchmen ###
- Acolytes have been given +1 to strength
- Acolytes have been given average (2) in polearms, and a wooden staff
- Acolytes have had their unarmed reduced from expert (4) to skilled (3), and their wrestling reduced from master (5) to skilled (3)
- Acolytes have been given average (2) athletics
- Acolytes have a new description: "Chores, exercise, prayer... and more chores. You are a humble acolyte at the temple in Rockhill, not yet a trained guardian or an ordained priest. But who else would keep the fires lit and the floors clean?"
- Priest has had their stat negatives removed and now has: +1 strength, +2 intelligence, +2 endurance, and +1 speed (A much more fitting set of stats for an important single-slot leadership role)
- Priest has had polearms increased from average (2) to skilled (3), a privilege of being the second biggest target for antagonism besides the King, and it can be increased to expert (4) if the priest is old
- Priest has been given skilled (3) unarmed and wrestling
- Priest has been given skilled (3) athletics
- Priest has a new description: "The divine is all that matters in an immoral world. The Sun Queen and her pantheon rule over all, and you will preach their wisdom to Rockhill. It is up to you to shepard the flock into a god-fearing future."

### Misc Changes ###
- Training dummies will not teach weapon skills past average (2)

### What has not been touched by the pr? ###
- Haulers, as Dromkii is doing work on them
- Bards, because Nicholas has his own pr up for them
- Archivist is getting a rework soon, so I'm not touching them in this pr either

Open to feedback and suggestions, as always.

## Why It's Good For The Game
Puts most noncombatants at a higher skill level so they can defend themselves from basic threats, enforces the new skill floor for classes that are combat-based or assumed to have seen combat at skilled (3) as a minimum.

Reaching skilled (3) in a combat skill will now REQUIRE sparring or actually fighting.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Watch as people seethe and cry because the mannequin has one less level of skill traineable....Godspeed Opti, I hope they're less aggressive towards you like they've been towards me for this.

**Comment by Optimism333** [comment]
As of yet untested. I'll make sure it compiles tomorrow.

**Comment by Optimism333** [comment]
> Watch as people seethe and cry because the mannequin has one less level of skill traineable....Godspeed Opti, I hope they're less aggressive towards you like they've been towards me for this.

Well, it remains to be seen what the feedback will be. Hopefully it will generally be positive, but maybe not.

Now the sum of the state of things is as follows:
- Most noncombatants have at least one average (2) combat skill, which they cannot increase without seeing combat. That means that most fights of noncombatant vs noncombatant will come down to stat differences, skill, and luck.

- A noncombatant vs a basic combatant (merc, guard, common drifter) will be a bit more interesting. The noncombatant may have a chance if aiming for weak points and they manage to get the first hit and avoid being hit. The basic combatant has the advantage of 1 extra skill level that the noncombatant cannot reach with a training dummy, armor training, and better gear/weaponry. Still there is a decent chance for either to win depending on robustness and who plays smarter.

- Noncombatants vs rare combatants and powerful antagonists? It will still very much be an uphill battle, though maybe they will stand a LITTLE more of a chance than before. A noncombatant will have to be even more robust and play more intelligently to deal with this challenge. But in an even match, it is very unlikely that the noncombatant will win this.

Personally I think this state of affairs is reasonable as it stands. But feedback and time will tell, I suppose.

**Comment by Optimism333** [comment]
Added a section revamping acolytes and the priest into what I believe is a better state. Acolytes are reduced in their ability to fight unarmed and to wrestle, but have average polearms and a wooden staff to defend themselves.

The priest is no longer physically weak and has a much stronger statline befitting a single-slot leadership role and the second largest target for antagonism, as well as slightly better combat stats.

**Comment by Optimism333** [comment]
Per request by Dromkii, added minor polearms to masons so they can wield a shovel, though not as well as a hammer. And since it's only minor, it seemed fair.

**Review by NPC1314 — APPROVED** [review]
Lets try it, I'm pretty sure there wll have to be some tweaking down the line though.

Some roles have different contexts, a maid in the Keep where theres theoretically guards and stuff on their side to keep them safe is fine while very weak,
Soilers thats on the outskirts and has a lot of resources people want need more combat power for gameplay reasons IMO, and churchies having expert unarmed wa AFAIK not really an issue before gameplay wise.

People tend to not play the noncombat churchies already and need ways to defend themselves, they're worthy of consideration (not the same situation as keep maid, a lot more high profile and more exposed to infighting vs templars etc)

Maybe miracles, gear and other ways can fix these issues but its going to be a topic.

**Pull request merged**
