### PR TITLE
Unlocks all Hairstyles for all Races

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request

Allows all races to use all hair/facialhair styles (Guayo Approved)

image

## Why It's Good For The Game

This is following the collective vision that staff has for the server. 
Some examples below:

image
image
image
image

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Optimism333** [comment]
I don't like beards on aasimar. I've been trying to move them further away from facial hair by removing their stubble in #454 , the lack of it being one of the things that sets them apart visually from the other races, aside from their unique body colors and the new bodytype for their females.

Adding facial hair for them feels like it homogenizes them with the rest of the races... and in my opinion it really doesn't look good:
assimar

**Comment by SaintBurgher** [comment]
> I don't like beards on aasimar. I've been trying to move them further away from facial hair by removing their stubble in #454 , the lack of it being one of the things that sets them apart visually from the other races, aside from their unique body colors and the new bodytype for their females.
> 
> Adding facial hair for them just homogenizes them with the rest of the races... and in my opinion it really doesn't look good: assimar

If Guayo agrees then I have no issues with restricting facial hair from Aasimar. I'll message him on Discord for his thoughts.

**Comment by Optimism333** [comment]
I see

**Comment by sanshoom** [comment]
Aasimar with facial hair is lame as fuck TBH.

**Comment by SaintBurgher** [comment]
Aasimar can now only have things like goatees, mustaches, and sideburns. No long or big beards.

**Comment by ThePainkiller** [comment]
tbh I don't see why it's a big issue when facial hair is like, _optional_
You can just have it shaven by default

**Comment by SaintBurgher** [comment]
> tbh I don't see why it's a big issue when facial hair is like, _optional_ You can just have it shaven by default

Guayo is good with this compromise. Should be all set now!

**Review by ThePainkiller — APPROVED** [review]
Approved by loreholder and finetuned.

**Pull request merged**
