### PR TITLE
Qatil merc class

### PR DESCRIPTION
**Pull request by Marmio64**
## About The Pull Request

Adds the 'Qatil' as a mercenary class. (I'm conflicted if they should be a mercenary, or slightly buffed and moved to that of a rare drifter status, or maybe nerfed and added as a common drifter? Please give your opinion in the comments.)

The Qatil are zybantine assassins that add to the merc roster by fulfilling the previously empty role of speedy, knife wielding assassins.

They're moreso suited to direct killing as they are slightly less good at being stealthy compared to something like a rogue or antag assassin, but are able to fulfill the role of stealth regardless.

Both sexes can play this class.
Humens, Elves, Half-elves, Tieflings, and Dark Elves are the allowed races.

They get +2 to Speed for their stats and +1 to Endurance.
Dodge Expert and Steel Hearted for their traits.

Expert Athletics, Climbing, and Sneaking.
Skilled Lockpicking, Knives, and Wrestling
Average Swords, Crossbows, Bows, Unarmed, Swimming, and Stealing.
Weak Reading and Trapping.

They come equipped with a steel knife as their weapon.

Their protective armor is: Leather Trousers, Heavy Leather Gloves, Studded Leather Armor, and a Leather Coif.

They will also be able to speak Zybantine once #519 is merged.

A picture of a tiefling Qatil in full gear.
image

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Perhaps locking them to 1-2 per round?

**Comment by Optimism333** [comment]
I'm trying to drop merc melee skills to skilled (3) at maximum in #533 , so they don't overshadow garrison guards.

I would suggest dropping expert (4) knives to skilled (3), and maybe buffing one of their ranged skills or giving them an extra stat point (like endurance).

**Comment by sanshoom** [comment]
based

**Comment by NPC1314** [comment]
Sounds very exotic, rare adv seem more appropriate

**Comment by ThePainkiller** [comment]
tbh if we add a literal "assassin class merc" based on knife skill, I'd rather have them as drifters than a merc with their own guild building and all, they feel more like wandering cutthroats for hire than an established fighter like the rest of the merc types, but that's just my opinion on flavor, skill wise they're fine, except for the shield skill. Why would a rogue type use a shield?

**Comment by ThePainkiller** [comment]
ngl these stats do not strike me as "rare class equivalent", unless you bumped that knife skill to like 4
This feels like just dodge warrior with knife skill, an average drifter class more than a rare

**Comment by Optimism333** [comment]
Sorry for taking a while. Add a minimum PQ of 0, and I think this should be ready to go.

**Review by Optimism333 — COMMENTED** [review]
Sorry for taking a while. Add a minimum PQ of 0, and I think this should be ready to go.

**Pull request merged**
