### PR TITLE
Hand Subclasses

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Adds 3 subclasses for the Hand of the King/Queen

Duelist: Basically gives the Hand medium armor, some STR and his 4 swords skill back, basically the Hand pre-nerf except it is still nerfed in some spots (like no heavy armor)

Spymaster: Losses alot of the combat skills duelist has in exchange for lockpicking/stealing/sneaking and keeps the current dodgeexpert light armor speedy build the Hand now has. Also has 3 pairs of lockpicks.

Advisor: Heavily nerfed combat skills in exchange for reading/alchemy/medicine and more INT and a bottle of poison. 

## Why It's Good For The Game

Now, I understand these might be a bit OP. I was never really good with finding a good balance with stats/skills so I implore anyone who wants to dumb down certain aspects of the subclasses to make them ALL viable (duelist included) 
So I would really appreciate if this wasn't closed like my Squire subclasses PR.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
I already know that everyone is going to pick Duelist.

**Comment by messagecypher** [comment]
this is never gonna pass anyways

**Comment by SaintBurgher** [comment]
If this doesn't pass I'd like to just move away from Spymaster to Duelist anyways. the GoT LARP is too much.

**Comment by DovaKitty** [comment]
Coal, this PR is very bad kitten. Erm...we moved Hand down to 3 knives for a reason...they should not be getting great combat skills, stats, infinite access and basically infinite money again. Giving them 3 knives instead of 2 was a compromise that I made to not overnerf them, but that may have been a mistake since somehow people still think that the court advisor should also be a royal guard.

**Comment by ThePainkiller** [comment]
This whole class selection code is, pun intended, getting quite out of _hand_.

No medium armor. No combat role. No combat stats, skills, weapons. This is a towner pencil pusher with some dagger skill just to symbolize a backstabber when convenient. Play Captain. Play Veteran. Play duelist town guard. The Hand is a political advisor, not town guard 2 with absolutely zero way into subterfurge because there's nobody to spy upon.

> Giving them 3 knives instead of 2 was a compromise that I made to not overnerf them, but that may have been a mistake since somehow people still think that the court advisor should also be a royal guard.

People may hate me. They may disagree with me. And they'll hate me even more every time an "I told you so" moment happens, but by god if it hasn't proven right time and time again, that you give people an inch and they take a mile.

**Comment by Coastfront** [comment]
Ahem; Spymaster is functionally current hand, no statement.
Duelist; For few eagles is there room on a trainers shoulder, Swordsman hand both isn't extremely welcome, & semi becomes a shittier-guard captain with more authority. In my opinion he shouldn't wind up a medium/stand your ground combatant.

Advisor; 10/10, Actually plays into the fucking "Advisor/Mentor" angle as hand as mentioned in the PR. Having a more-supportive hand who can act as a tutor/sagely studied mentor for the king instead of simply-being game of thrones larp is a great direction to be able to point a hand mechanically.

**Review by Optimism333 — COMMENTED** [review]
I don't even really know where to begin with this. I gave approval to #851 as an olive branch, since Hand did get hit pretty hard with the nerf hammer.

But now I see here... just one week later... let me make a list:

### Duelist ###
- A subclass that gives the Hand expert swords back, medium armor training. and says in a comment that it is basically intended to revert the old nerf.

No, just no. We aren't making the Hand the third royal guard. Allowing skilled swords would be the most I would personally allow, but I don't think Nicholas or Dova would be happy with that.

### Spymaster ###
- A subclass that gives the Hand expert knives, master climbing (the threshold for not taking fall damage when climbing), expert crossbows, a big speed boost, and dodge expert.

What even is this? A Hand that's on par, maybe better than an assassin? Definitely better than a Rogue. Is this Hand the protagonist of an Assassin's Creed game?

### Advisor ###
- A subclass that reworks the Hand into a more intellectual/advisor role. Not a bad concept, tbh. Though skilled crossbows is a bit much.

This is only subclass of the bunch that I think is mostly alright. I would even allow it to retain the skilled knives skill that the Hand currently has.

### Summary ###
All in all, this needs work. I can't say I approve of either of the first two subclasses in their current state, they're just too insane.

Sorry.

**Comment by BadAtThisGame302** [comment]
@Optimism333 

Removed medium armor training from duelist
Nerfed duelist swords by 1
Nerfed crossbows on spymaster by 1
Nerfed climbing on spymaster by 1

Funny you mention speed boost and dodge expert, since that is what they currently have right now? How's that an issue exactly.

**Comment by Zoeycore** [comment]
I hope this gets through!

Hand has always had an identity crisis, and I think Subclasses would help guide players into the role whilst also allowing them to express their characters how they wish.

Ultimately, the 'Hand of the King' is the Man ordained to perform the King's will whilst he is busy with court politics - but currently, he's an incredibly unskilled class to do this :(

It makes perfect sense that the King may wish for a skilled blade to be his Hand, I don't see the issue with at least one subclass having combat skill - it's cool.

The Spymaster seems to be where the current Hand is, but despite that, the current Hand does not have access to basic skills like pickpocketing, no lockpicks, or disguises (unless bought). He feels gimped and boring.

Advisor feels a bit weak, and I imagine it'll be overshadowed until something better comes along. I was thinking maybe a 'huntmaster' or even a 'spellblade' might work - but that's quite a shift from what people expect rn.


Hand really fills no power fantasy outside of "King's Bitch" currently.

**Comment by Zoeycore** [comment]
Duellist balance too - as a niche, good in 1v1 duels (high skill for parries), but terrible in open combat (No armor, maybe no dodge too?)

Seems like you'd get the best of both worlds, with a combat viable Hand in 1v1 Courtly disputes, but not a Titan who can become a killing machine in war.

**Comment by ThePainkiller** [comment]
Still can't find it in myself to turn Hand into a combat class in any shape or form

**Comment by ThePainkiller** [comment]
> Advisor; 10/10, Actually plays into the fucking "Advisor/Mentor" angle as hand as mentioned in the PR. Having a more-supportive hand who can act as a tutor/sagely studied mentor for the king instead of simply-being game of thrones larp is a great direction to be able to point a hand mechanically.

Wholeheartedly agree with this one.

**Comment by Tipy1802** [comment]
> Advisor; 10/10, Actually plays into the fucking "Advisor/Mentor" angle as hand as mentioned in the PR. Having a more-supportive hand who can act as a tutor/sagely studied mentor for the king instead of simply-being game of thrones larp is a great direction to be able to point a hand mechanically.

There are already TWO roles tailor made for a sage/tutor niche - the court mage and the archivist, we don't need a third. (Not to mention that the steward can play this part as well).

Overall I like the PR because hand is way too weak at the moment but the advisor role just seems not worth picking ever. Your are gimping your combat skills for... more reading which doesn't do anything bast level one and alchemy which if I am not mistaken flat out does nothing as well. But I understand that it is hard to give non-combat bonuses because advice is not something you can translate into the game system.

I do remember Blackstone giving their Ballif(?) role the ability to make laws if the king is dead and no new king has been crowned yet. It might be worth looking into that for either the advisor sub role or for the hand role in general

**Comment by NPC1314** [comment]
Moe rare combat  class adventurer triumph buys will result. Aasimar hoplite garrison already happens, now it will be Hand too.

Until that is fixed, not a fan of subclasses being added, its buggy, was only meant for adventurer/pilgrim and it shows.

**Comment by Optimism333** [comment]
Can't bring myself to approve this in its current form, sorry. Most of the devs do not approve, and then there's the issue Pig just brought up with subclasses and triumph buy.

A revamp of Hand that makes it more of an advisor/mentor could be cool, but this isn't the way.

**Pull request closed without merging**
