### PR TITLE
Slight Ranger and Hunter Changes

### PR DESCRIPTION
**Pull request by CormanQuewye**
## About The Pull Request

Makes some minor changes to the skills of Ranger and Hunter:
- Ups Hunter's Crossbows from pick(1,2) to 2 because I have an intense dislike to random skill rolls;
- Ups Hunter's tanning to 4, as at 3 jobs like weaver and tailor had a chance of rolling tanning higher than them and it lines up with specialized towners;
- Ups Ranger's Unarmed to 2;
- Ups Ranger's tanning to 2 to cement them as a combat-focused hunter;
- Gives Ranger wrestling 2 due to its importance in melee combat and Ranger's existence as mixing melee and ranged but mastering neither;
- Removes Ranger's Riding skill altogether (why did they have riding to begin with?);
- Gives Ranger Taming 2 to line up with Hunter's skills (hunter has taming 3);
- Gives Ranger Sneaking 2 to line up with Hunter's skills (hunter has sneaking 2);
- Gives Ranger Trapping 2 to line up with Hunter's skills (hunter has trapping 2);
- Gives Ranger Athletics 2 to line up with Hunter's skills and the fact that every other adventurer has athletics;
- Gives Ranger Swords 2 as opposed to Swords pick(0,1,1).

## Why It's Good For The Game

I'll start by clearly stating that Ranger is easily my most played Adventurer class and probably job role altogether so I am obviously biased. These changes slightly buff Hunter, primarily making them a more distinguished tanner and buff Ranger quite a bit in areas they were, for some reason, lacking.

Ranger is intended as a more combat focused survivalist so their skills should (for the most part) line up with Hunter. There are areas I think they shouldn't, such as butchering, where Ranger has 0 to Hunter's 2, but in other sectors such as sneaking and taming, this makes a lot more sense given their class instead of something that felt rather random in the form of riding.

Giving them Athletics 2 puts them 1 point beneath the heavily body-focused classes such as warrior and barbarian, without making the class that spends a lot of time walking through the wilderness for some reason totally lacking in athleticism. Giving them wrestling 2 just cements them in their role as intended to mix melee and ranged without being ideally specialized in either.

Tanning 2 was given so they're able to craft hide armour (the armour they start with) and so I don't have to cry everytime I remember Garrison Archer has tanning.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Optimism333** [comment]
Changes look alright overall. You could probably give ranger at least the same sneak level as hunter, average unarmed and wrestling, and average swords.

I was intending to give them those buffs myself, if anything. But if this is where you want to leave them, that's fine as well.

**Comment by Cre77** [comment]
how about giving them trapping so they can reuse mantraps found in the wild more consistently?

**Comment by CormanQuewye** [comment]
> how about giving them trapping so they can reuse mantraps found in the wild more consistently?

My bad as I actually forgot to put that I gave them trapping 1 in the change notes!

> Changes look alright overall. You could probably give ranger at least the same sneak level as hunter, average unarmed and wrestling, and average swords.
> 
> I was intending to give them those buffs myself, if anything. But if this is where you want to leave them, that's fine as well.

Sure! I'll do that in a bit. If someone who commonly contributes is for it, I don't have to feel guilty of my own personal bias! :^)

**Comment by Optimism333** [comment]
Two more things I think I do have to add, unfortunately.

If ranger is gonna get the combat skill buffs, I don't think their tanning needs to be buffed, nor does hunter's tanning really.

Ranger is already kinda creeping up on garrison archers with these changes and hunter has plenty of tanning to do most of the good stuff at skilled (3). They don't need expert tanning, imo.

**Comment by CormanQuewye** [comment]
> Two more things I think I do have to add, unfortunately.
> 
> If ranger is gonna get the combat skill buffs, I don't think their tanning needs to be buffed, nor does hunter's tanning really.
> 
> Ranger is already kinda creeping up on garrison archers with these changes and hunter has plenty of tanning to do most of the good stuff at skilled (3). They don't need expert tanning, imo.

Hunter I'd say primarily because they should have a more distinguished tanning. Ranger I think should have higher tanning than Archer considering they're survivalists. I've always found it weird that they start with nothing but tanned armour but are incapable of making the hide armour they start with.

**Comment by Optimism333** [comment]
> > Two more things I think I do have to add, unfortunately.
> > If ranger is gonna get the combat skill buffs, I don't think their tanning needs to be buffed, nor does hunter's tanning really.
> > Ranger is already kinda creeping up on garrison archers with these changes and hunter has plenty of tanning to do most of the good stuff at skilled (3). They don't need expert tanning, imo.
> 
> Hunter I'd say primarily because they should have a more distinguished tanning. Ranger I think should have higher tanning than Archer considering they're survivalists. I've always found it weird that they start with nothing but tanned armour but are incapable of making the hide armour they start with.
> 
> If Ranger has tanning 1 and Hunter 3, then the guy patrolling the walls suddenly with their extra INT can inexplicably compete with the people wandering the woods all the time. Reminder that tanning is the one crafting skill of note hunter has. And while Ranger does start to get to trail on Archer's heels a bit, while Garrison should be combat-wise stronger they shouldn't be so far ahead that they're leaving everyone else in the dust, Archer still has +2 more in stats, 4 levels of crossbow, and an extra level of Archery, despite their loss of one level of knife. From 3 bows to 4 is a massive difference in critrate, so while these changes will make Ranger close to Archer in combat, Archer edges out noticeably in their niche.
> 
> And furthermore, even if you compare Hunter's expert to other towners who start with skilled, a reminder that leatherworking is incredibly difficult to level compared to something where you're more consistently crafting such as smithing or sewing, for example! It's relatively easy to level your crafting, but it takes a LOT of bait to **maybe** have enough leather for just one level.

- Hunter doesn't need more tanning, skilled (3) is fine for most of their bushcraft. Skill creep is a thing, and if they don't NEED more of the skill, they shouldn't get it just because it'd be nice to have.
- Garrison Archers being stronger than rangers is completely fine, I think garrison roles should be stronger than drifters and mercenaries that fill the same or a similar niche, even if they generally occupy a similar tier. It's a consolation prize for picking a role with more responsibilities to the town.
- The ranger occupies the gap between hunter and garrison archer just fine with the stats allotted. They're stronger than a hunter in melee combat, and have a decent diversity of crafting skills, though not quite as many as hunter. But they're also not as good as a garrison archer.
- Rangers having hide armor that they can't craft is a moot point, imo. Barbarians have a chance to start with hide armor, and they also only get skincrafting level 1. If it bothers you, it can be replaced with a padded gambeson.

This is simply the give and take of balance. I agree that rangers could use a bit of a buff, but giving them another point of tanning is taking too many cookies out of the jar. If you don't want to pull tanning back down, then I would say get rid of their sword skill entirely. A sacrifice of combat versatility for a little bit better crafting is fine.

Extra skincrafting for hunter is an absolute no-go from me, though. They are fine where they are.

**Comment by CormanQuewye** [comment]
> > > Two more things I think I do have to add, unfortunately.
> > > If ranger is gonna get the combat skill buffs, I don't think their tanning needs to be buffed, nor does hunter's tanning really.
> > > Ranger is already kinda creeping up on garrison archers with these changes and hunter has plenty of tanning to do most of the good stuff at skilled (3). They don't need expert tanning, imo.
> > 
> > 
> > Hunter I'd say primarily because they should have a more distinguished tanning. Ranger I think should have higher tanning than Archer considering they're survivalists. I've always found it weird that they start with nothing but tanned armour but are incapable of making the hide armour they start with.
> > If Ranger has tanning 1 and Hunter 3, then the guy patrolling the walls suddenly with their extra INT can inexplicably compete with the people wandering the woods all the time. Reminder that tanning is the one crafting skill of note hunter has. And while Ranger does start to get to trail on Archer's heels a bit, while Garrison should be combat-wise stronger they shouldn't be so far ahead that they're leaving everyone else in the dust, Archer still has +2 more in stats, 4 levels of crossbow, and an extra level of Archery, despite their loss of one level of knife. From 3 bows to 4 is a massive difference in critrate, so while these changes will make Ranger close to Archer in combat, Archer edges out noticeably in their niche.
> > And furthermore, even if you compare Hunter's expert to other towners who start with skilled, a reminder that leatherworking is incredibly difficult to level compared to something where you're more consistently crafting such as smithing or sewing, for example! It's relatively easy to level your crafting, but it takes a LOT of bait to **maybe** have enough leather for just one level.
> 
> * Hunter doesn't need more tanning, skilled (3) is fine for most of their bushcraft. Skill creep is a thing, and if they don't NEED more of the skill, they shouldn't get it just because it'd be nice to have.
> * Garrison Archers being stronger than rangers is completely fine, I think garrison roles should be stronger than drifters and mercenaries that fill the same or a similar niche, even if they generally occupy a similar tier. It's a consolation prize for picking a role with more responsibilities to the town.
> * The ranger occupies the gap between hunter and garrison archer just fine with the stats allotted. They're stronger than a hunter in melee combat, and have a decent diversity of crafting skills, though not quite as many as hunter. But they're also not as good as a garrison archer.
> * Rangers having hide armor that they can't craft is a moot point, imo. Barbarians have a chance to start with hide armor, and they also only get skincrafting level 1. If it bothers you, it can be replaced with a padded gambeson.
> 
> This is simply the give and take of balance. I agree that rangers could use a bit of a buff, but giving them another point of tanning is taking too many cookies out of the jar. If you don't want to pull tanning back down, then I would say get rid of their sword skill entirely. A sacrifice of combat versatility for a little bit better crafting is fine.
> 
> Extra skincrafting for hunter is an absolute no-go from me, though. They are fine where they are.

I would argue that Hunter does need it! They find themselves in an odd position relative to specialty. The Butcher has higher crafting and higher butchery along with tanning 1. So, Butcher produces a lot more meat than them along with hides.

The weaver has a a 50% chance to start with tanning 4, making them better or at least on par with Hunter as far as it goes with tanning.

So, really, as far as producing resources, Hunter is the worst possible choice. Other towners outdo them in their supposed areas of expertise. The one thing of notice they have is Bows 4.

And sure, I can remove Ranger's swords for tanning. I do stand by the thought that Garrison Archers should simply not have tanning at all, since that doesn't feel like it makes any sense with their background nor applicable to their duties (and really them having a level in it is my primary reason for feeling like Ranger should have tanning 2).

**Comment by CormanQuewye** [comment]
> Well, I'm glad we can compromise on ranger. I think the changes are acceptable there now.
> 
> Again however, I'm afraid that hunter being bumped to expert tanning will meet with a no from me. And the other maintainer concerned with balance has agreed that it's skillcreep.
> 
> Weavers do not in fact have a chance of expert (4) tanning, they get skilled (3), same as a hunter.
> 
> It's just not true that there are many other towner roles that outdo hunter in the specialty of tanning. Butcher gets weak (1) tanning, Weaver gets skilled (3). If anything hunters have very high tanning compared to most towners. The highest that you see across many roles is weak (1), with weaver being ONE exception to the rule.
> 
> Maybe you're thinking of tailor? Which has no slots and currently cannot spawn.

You win this time, Big Archer Inc.

**Comment by Optimism333** [comment]
> > Well, I'm glad we can compromise on ranger. I think the changes are acceptable there now.
> > Again however, I'm afraid that hunter being bumped to expert tanning will meet with a no from me. And the other maintainer concerned with balance has agreed that it's skillcreep.
> > Weavers do not in fact have a chance of expert (4) tanning, they get skilled (3), same as a hunter.
> > It's just not true that there are many other towner roles that outdo hunter in the specialty of tanning. Butcher gets weak (1) tanning, Weaver gets skilled (3). If anything hunters have very high tanning compared to most towners. The highest that you see across many roles is weak (1), with weaver being ONE exception to the rule.
> > Maybe you're thinking of tailor? Which has no slots and currently cannot spawn.
> 
> You win this time, Big Archer Inc.

backrank-checkmate-gif

Good game. Till next time...

**Comment by ThePainkiller** [comment]
Couple things to address:

1. Try not to make Ranger a sidegrade to Hunter by comparing skills ("because Hunter has <skill>, Ranger gets <skill>".
2. Equally, do not give Hunter insane leatherworking, as weaver is supposed to be the usual clothesmaker and you're powercreeping into their niche. Just because they hunt their pelts to sale doesn't mean they should be experts at crafting clothing and armor out of them. Butchering would be better.
3. Ranger riding skill was the one difference they had with Hunters, without it, they feel like a sidegrade to Hunters as a more PVP oriented Hunter rather than scouts of the land. If they have to travel long distances, they should be able to at least ride a Saiga if needed. Riding skill should remain.

**Comment by CormanQuewye** [comment]
> Couple things to address:
> 
> 1. Try not to make Ranger a sidegrade to Hunter by comparing skills ("because Hunter has , Ranger gets ".
> 2. Equally, do not give Hunter insane leatherworking, as weaver is supposed to be the usual clothesmaker and you're powercreeping into their niche. Just because they hunt their pelts to sale doesn't mean they should be experts at crafting clothing and armor out of them. Butchering would be better.
> 3. Ranger riding skill was the one difference they had with Hunters, without it, they feel like a sidegrade to Hunters as a more PVP oriented Hunter rather than scouts of the land. If they have to travel long distances, they should be able to at least ride a Saiga if needed. Riding skill should remain.

1. Ranger and Hunter share a theme. It's impossible not to compare them to one another.
2. While I'd still argue that 4 is totally reasonable, I left it at 3 as per the above discussion.
3. Riding doesn't make sense for Ranger, thematically nor mechanically. Ranger is meant to be a woodland survivalist with a leaning toward adventuring and combat and quite often are portrayed as being good at dealing with natural forces. The ability to avoid hostilities with local wildlife (taming) makes far more sense than... riding? Why and where do they get riding from? How are they even meant to obtain a steed if they can't tame them to begin with?

While it's fair to say 'these two classes need not be similar' I think it's also fair to argue that giving a class stuff 'just to be different from this other one' is far sillier than comparing two thematically similar classes. It'd be like saying 'pilgrim blacksmith doesn't necessarily need to be similar to the town blacksmith! Sure, they're thematically equal but let's give them this random assortment of skills just to be different!'

**Review by ThePainkiller — APPROVED** [review]

**Pull request merged**
