### PR TITLE
Tweaks areas of the Castle, as well as completely overhauls the Magicians Tower

### PR DESCRIPTION
**Pull request by bowlofcereal**
## About The Pull Request

**!!I AM FINISHED BUT AM STILL OPEN TO SUGGESTIONS!!**

I got bored and decided that I wanted to re-map the Keep, so that's what i've done. I will be posting all images here as well-- be warned of the textwall.

Completely revamps portions of the Keep that are relatively unused while modernizing some other sections (bring it up to par with dakka and hamlet) such as the princes room being divided into two for both heirs, an area for keep-farm preparation, and a full overhaul of the wizard tower so the magician can have more fun being a mage.

## Why It's Good For The Game

The RogueTown keep honestly is very mid compared to some of the other maps people are cooking up, and if map rotation is ever to come out I think it would be nice to atleast have this be modernized since we are currently using the map. Also the new stuff for the mage tower lets them LARP more as an actual wizard and alchemist rather than just a glorified superpowered spellcaster.

Main View
keep1
Second Floors
keep2
Third Floors
keep3
Underground Area
keepunder

**Mage Tower**

Underground - sneaky drug storage, extra book storage, sneaky little "experiment" room
toweru
Main Floor - main office, alchemy lab
tower1
Second Floor - scroll and feather area, for book crafting and writing cool things
tower2
Third Floor - apprentice room, mage bedroom, trophy room (for any cool dungeon loot in the future, the mage could store it here to flex)
tower3

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I believe it best instead of a single door on the Throne Room carpet, it be a 3 wide gate with the side door back in it's place or no side door at all, simply because it could get very tight with that 1 tile leaving/entering and a gate looks much more cool than walls on the carpet.

**Comment by bowlofcereal** [comment]
turned the hedge maze area into a garden because it goes relatively untouched throughout the round and i think it'd be nice since i wiped the original "garden" area

keepgarden

**Comment by ThePainkiller** [comment]
Need opinions on the rest of the dev team, have you posted advances of this on the discord to hear some player feedback as well?

**Comment by bowlofcereal** [comment]
image

might touch on this more when im not busy but heres a few changes to these rooms

1. the private library room almost saw no use-- so im making it a guest room, perfect for a heartfelt lord or any other visiting noble
2. added the Kings blade to his locker and removed the sabre as a compromise, this is the only map that doesnt have it after all
3. got rid of the empty lords locker in the war room, it had nothing in it yet had master key access only

**Comment by bowlofcereal** [comment]
image

better vault layout because i had the spare time on hand and we aren't merged yet, so why not

this is the last addition im going to do besides fixing any errors on the map to avoid bloating the PR, the rest will be done in a later PR

we should be good for review and merge

**Review by ThePainkiller — APPROVED** [review]
Overall good changes, makes the manor a bit more accessible for Manor role players.

**Pull request merged**
