### PR TITLE
Mercenary Tokens

### PR DESCRIPTION
**Pull request by saltprjak**
## About The Pull Request

Adds a new "Luxury" item for Merchants and gives them one in their loadout. Mercenary Tokens are paper-like items that can be signed ONLY by the Merchant, then sent by any Mercenary through a mailbox for a one-time reward of three triumphs and a background-specific vanity item.
image

image

## Why It's Good For The Game

Gives mercenaries a more or less end-game objective to work towards via an item that they cannot acquire by themselves. Merchants now play a more direct role as their handlers, and can choose to sell pre-signed tokens for nobles to do their own recruiting, or send mercenaries on jobs and reward them only when those jobs are completed.
Gives another non-antag way to earn triumphs - an equivalent of half a round's worth that does not require you to survive its entirety.
Tokens can only be signed by the Merchant to prevent Lords rushing their shop and then buying their own mercs out.
The price is a little on the cheaper end - but the intention is for Merchants to jack it up depending on customer or mercenary.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Cre77** [comment]
okay, conflicts resolved
pestrans i swear

**Comment by ThePainkiller** [comment]
Unfortunately cannot Testmerge as it conflics with #628 , due to both modifying `icons/roguetown/items/misc.dmi`

Will be on the backburner of TM once nets can be fine-tuned with player input.

**Comment by ThePainkiller** [comment]
Now that nets are fullmerged, we can give this one a try, as promised.

**Comment by ThePainkiller** [comment]
Welp, fml, Dromkii's copper PR made conflicts with this one again... please fix the icon issues so I can testmerge it back...I'm really sorry about this happening twice already.

**Comment by crunchypretzels** [comment]
Can't use the token as a Boltslinger; it just gives the 'I do not belong to the Guild' !merc and !merchant message. It may not have been signed, though.

**Comment by Cre77** [comment]
> Can't use the token as a Boltslinger; it just gives the 'I do not belong to the Guild' !merc and !merchant message. It may not have been signed, though.

weird, i'll test it

**Comment by Cre77** [comment]
> Can't use the token as a Boltslinger; it just gives the 'I do not belong to the Guild' !merc and !merchant message. It may not have been signed, though.

thank you for pointing this out <3
it was me not testing things properly, it should work now whenever it's updated

**Review by NPC1314 — APPROVED** [review]
Looks in order, mail fix worked by all accounts.

**Pull request merged**
