### PR TITLE
Cabbits: The most foul, cruel and bad tempered feline rodent you ever set eyes on

### PR DESCRIPTION
**Pull request by ThePainkiller**
## About The Pull Request

- Adds the Cabbit, a strange yet adorable hybrid of cat and rabbit, ~~only spawnable by admins for now~~. Given proper butchering results, pelt, verbs, and made a child of normal cat.

- Also adds the Cabbit of Cairne Bog, a vicious, troll-level-of-strength cabbit that will surely ruin your dae if you ever dare come close enough. It is distinguishable from the tame cabbit out of his bloodshot red eyes and thirst for blood. If you see it, RUN AWAY!! **RUN AWAY!!!!!**

image

image-1

Cabbits are summonable with bait, sweetbait (at higher chance), and the cabbit of Cairne Bog summonable by the bloodbait at a low chance.

This PR also rebalances some of the baits summonable pools to adjust for the new mobs added to their lists.

## Why It's Good For The Game

cabbit-gorbsniffle96

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Review by Optimism333 — COMMENTED** [review]
More small critters... hooray!

**Comment by sanshoom** [comment]
Is it possible to add the inn cats racism code to the cabbit?

**Comment by ThePainkiller** [comment]
> Is it possible to add the inn cats racism code to the cabbit?

They're children of cats, much like the Inn Cat is, so they should still be racist towards dark elves and vampires alike.

**Comment by NPC1314** [comment]
The TODO confuses me a little, will you make a new cabbit file in this PR or is it for another and this PR is complete as is?

**Comment by ThePainkiller** [comment]
> The TODO confuses me a little, will you make a new cabbit file in this PR or is it for another and this PR is complete as is?

The TODO was to avoid a speedmerge as I was waiting for dead sprites, it should be good to go now.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
