### PR TITLE
Shortens everyone else

### PR DESCRIPTION
**Pull request by saltprjak**
## About The Pull Request

Moves human, half-elf and tiefling men to the "medium" bodytype. Fixes medium male bodytype head being too low and makes their body hair invisible to not stick out like hairy monkeys compared to the other updated bodies. Tested - clothes, injuries and skeleton mobs work. Aasimar are still towering chads, dwarves and elves untouched.
 image

Additionally removes "halfelven" force from half-elf name generation, since they look distinct enough, and are no longer a singled out patron-only race.

## Why It's Good For The Game

Minor visual tweak to make races a bit more distinct, and elves seem actually tall. Makes use of unused custom-tailored sprites, for a change.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
So humen men and women are now on par with one another?

**Comment by BadAtThisGame302** [comment]
Also I believe something might have gone wrong with making Elvish women taller? This was posted on the discord maybe you can investigate?
image image

**Comment by Cre77** [comment]
> So humen men and women are now on par with one another?

no, all women (except the updated aasimar in a different pr) are still a pixel shorter than same-height men


> Also I believe something might have gone wrong with making Elvish women taller? This was posted on the discord maybe you can investigate? image image

i'll check it out, might be an icon issue

**Comment by Cre77** [comment]
> > So humen men and women are now on par with one another?
> 
> no, all women (except the updated aasimar in a different pr) are still a pixel shorter than same-height men
> 
> > Also I believe something might have gone wrong with making Elvish women taller? This was posted on the discord maybe you can investigate? image image
> 
> i'll check it out, might be an icon issue

found to be a non-issue. the boobs look weird on all women because the satchel's belt is a straight line across the front of the chest, without accounting for boobs; and the face seems to be some screen resizing shenanigan issue that's not related to sprites or code

**Comment by ThePainkiller** [comment]
>Manletifying humen

It's so over.

**Pull request closed without merging**
