### PR TITLE
Nukes Repulse

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

Deletes Repulse on player request
bad spell

## Why It's Good For The Game

The spell is an SS13 Asset in the literal sense, balanced around Space Wizard.. not land wizards?
Also jaunt already serves as a get out of jail free card and a much better balanced one,

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
court mage main gives this a thumbs down.. that's all u need to know.

**Comment by ThePainkiller** [comment]
Noc nerds will run out of spells to even cast at this point, so much for the god of knowledge

**Comment by Cre77** [comment]
agreed- it's either this or nerfing it into the ground along with putting on a cast time. right now it's pretty much an uncounterable "win button" stun that turns any given altercation with a mage into "who instakills who first". which leads to both stale, fraggy gameplay, and mages that are really vocal abouy how good they are at the game

**Comment by 1N7Slayer** [comment]
I agree that repulse is just way too strong. I wish we had more avid attempts to code interesting or a myriad larger amount of spells in the game.

AOE featherfall would be so cool.

**Comment by 0nemore** [comment]
I agree with this as long as the court mage gets a spell to replace this.

**Comment by ThePainkiller** [comment]
> AOE featherfall would be so cool.

Not hard to do after I laid the groundwork for falling while not taking damage! Good idea for a spell actually, we'll see what we can make wizards able to play with other than tg spells

**Comment by 0nemore** [comment]
Court mage should get more utility spells. This would be cool.

**Review by Optimism333 — COMMENTED** [review]
Largely in agreement with the feedback, don't simply delete the spell. Replace it with something.

**Comment by ThePainkiller** [comment]
Will be obsoleted by #839 with a much better solution than just erasing a spell with no replacement.

**Pull request closed without merging**
