### PR TITLE
Aasimar Rare Drifter: "Immortal Bulwark"

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
This adds a very rare drifter type that can exclusively be aasimar. The pr was inspired by art, lore, and the need to actually develop this race.

Spritework was done by Count Monochrome, who is awesome. Much of the inspiration came from Guayo's artworks of aasimar soldiers, so a thanks to him as well.

### Armor pieces and weapon sprite (loadout preview) ###

Screenshot (190)

### Preview of how it looks in-game ###

Screenshot (191)

### Armor Sprites ###

image

### Khopesh Sword Sprite ###

image

### What is done ###
- Class page and stats have been made
- Armor items have been added
- Their one-handed sword has been added

### What still needs to be done ###
- Balance still isn't locked in completely, further tweaks will likely have to happen
- Spear is not yet added, it may have to wait for an additional update
- Unique shield is not yet added, hopefully will be added soon
- Might possibly search for a unique combat music for them (depends how ambitious I feel)

### Some Details ###
- The overall theme of the class is a one-handed sword or spear user that makes use of a shield and heavy armor to hold the line
- Not as threatening in terms of damage as the other rare classes with two-handers, but more than makes up for it with powerful stats (on top of the aasimar bonuses), and 5 skill in shields
- This class is very rare, having an even lower selection chance than a sword master. And only 1 slot is available

image

## Why It's Good For The Game
- Further fleshes out the identity of aasimar and their presence in the setting, thus adding lore to the game
- Adds some cool new toys for players to try out

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Cre77** [comment]
could give them some weak crafting and sewing for entrenching? making spades, palisades, tents, etc. 
maybe weaker skills across all other weapon types? more to cement them being long-lived and with vast combat experience flavor-wise, not like they'll have any reason to switch off their main weapons. five shields might also be a tad much - nicholas mentioned RG stats should be the absolute ceiling for when it comes to combat roles

**Comment by Optimism333** [comment]
> could give them some weak crafting and sewing for entrenching? making spades, palisades, tents, etc. maybe weaker skills across all other weapon types? more to cement them being long-lived and with vast combat experience flavor-wise, not like they'll have any reason to switch off their main weapons. five shields might also be a tad much - nicholas mentioned RG stats should be the absolute ceiling for when it comes to combat roles

When Nicholas saw the initial stats he seemed alright with allowing them to have 5 shield skill. What he did take issue with was them having 4 in swords and 4 in polearms, and so I changed that.

I've removed the polearm skill for now, and if the spear gets added before I finalize this, I'll make it so that they have a chance to spawn with either a spear or a sword to pair with their shield, and that's what they will get their main weapon skill in. But they will not have high skill in both categories.

I don't want to give this class crafting skills, it doesn't make sense for it to be self-sufficient. The background is an aasimar who has fought in armies throughout its existence, where others would have been present to do the sewing, crafting, and weapon repairs. If anything. I actually want this class to be encouraged to find a noble or someone to serve alongside. The lack of starting money and anything of value besides their equipment cements that.

As far as giving other minor weapon skills? Maybe... I am willing to listen to more input on that.

**Comment by Plaguewalker** [comment]
Replace the helmet please, it looks out of place

**Comment by Optimism333** [comment]
### Status Update: ###

Still on standby here pending the addition of the new shield sprite. Once it's ready to be added, I will code its stats and remake this pr to resolve conflicts.

**Comment by ThePainkiller** [comment]
Really really hyped for the spear and shield sprites.

**Comment by Optimism333** [comment]
Added spear and shield sprites (class pick chance also got changed to 100, is only for testing and will be removed before final changes).

Will likely remake this pr soonish.

There is a blood overlay issue with the helmet that turns it white, which also applies to all other 64x64 helmet sprites and is very annoying

**Comment by Optimism333** [comment]
Going to remake this pr shortly to fix conflicts, and add the shield and spears.

**Pull request closed without merging**
