### PR TITLE
Renames Rogue to Thief, gives them better lockpick skill, swaps their crossbow for a bow.

### PR DESCRIPTION
**Pull request by 1N7Slayer**
## About The Pull Request

I know, I'm eliminating soul from the game and replacing it with different soul. Also removes their steelhearted trait - thieves aren't murderers.

## Why It's Good For The Game

*Thieves* did not get master lockpick skill as a dedicated THIEF ROLE for some reason, meaning the ONE lockpick they spawned with would rapidly break because having tier 3 in lockpicking is not very good and you will, according to probability, lose that lockpick and break it within 5 doors. And who is going to replace that lockpick? The smith or the merchant, dealing with an outlander criminal? That's a funny joke.

Also grants the rogue-- fuck -- thief, a bow/set of arrows instead of their old crossbow, adjusts their skill accordingly.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Cre77** [comment]
could do way with their crossbow, in that case? as it stands, they're kitted out as killers more than anything.
otherwise, love it - i think they should have gotten more skill to begin with as the designated crook role

**Comment by 1N7Slayer** [comment]
> could do way with their crossbow, in that case? as it stands, they're kitted out as killers more than anything. otherwise, love it - i think they should have gotten more skill to begin with as the designated crook role

Garrett from thief didn't have a crossbow, he had a bow, so I will comply to this. In the future it'd be neat to have more craft ideas, like water arrows that extinguish firepits.

**Comment by Optimism333** [comment]
There's no more rogues in roguetown... it's so over...

**Comment by ThePainkiller** [comment]
Oh hell no. Massive nerf, and thief feels not only niche standard party composition, it even further drives the class in being a soft a tag.

**Comment by Ickysoup** [comment]
Go even farther. Replace their dagger with a blackjack(buffed up cudgel)

**Comment by sanshoom** [comment]
> > could do way with their crossbow, in that case? as it stands, they're kitted out as killers more than anything. otherwise, love it - i think they should have gotten more skill to begin with as the designated crook role
> 
> Garrett from thief didn't have a crossbow, he had a bow, so I will comply to this. In the future it'd be neat to have more craft ideas, like water arrows that extinguish firepits.

partially related note, but perhaps give a crossbow to qatil in another PR since they are supposed to be zybantine assassins (but for some reason they only have a dagger??)

**Review by DovaKitty — CHANGES_REQUESTED** [review]
I don't really like anything about this PR, and they are restricted changes. Increasing Rogue's lockpicking to 4 would be fine, but the rest of this PR's content would have to be removed imo. Recommending author closes and makes a new PR with that one change.

**Pull request closed without merging**
