### PR TITLE
PR THAT FIXES BROKEN INHANDS AND ADDS NEW SPRITES

### PR DESCRIPTION
**Pull request by Dorodomki**
## About The Pull Request

adds the new sprites for the swords, slighly upgrades the steel axe and fixes every other broken sprite that is two handed being off centered

## Why It's Good For The Game

heals my eyes and fixes some errors

image
image
image
image

### CODE REVIEW

**Comment by cornercube** [comment]
#132 
short sword and messer got merged before balance update did, so they were not taken into account

**Comment by Dorodomki** [comment]
> #132 short sword and messer got merged before balance update did, so they were not taken into account this brings their damage up to slightly higher when stabbing and fairly lower when slashing but wihout wield bonus

fixed it and deleted the codework

**Comment by Dorodomki** [comment]
damn bro delete code was ALL THE SWORD.DM AND NOT THE CHANGES I MADE

fixed lmao

**Comment by ThePainkiller** [comment]
Can you post screenshots of how the weapons look like IN HAND on mobs? We've received complains of various 2h weapons and some 1h weapons to not allign with character sprites.

**Comment by Dorodomki** [comment]
the sprites have been updated to fit their previous 64x64 versions, they use the exact same pixel position while things like the billhook just needed a proper dmi name instead of "bilhook"

**Pull request closed without merging**
