### PR TITLE
Warrior Changes and Rebalance (Stats, Armor Training, Weapon Skills)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
Warriors were in a strange place, only having a chance to roll weapon skill 3 (skilled) on a single weapon stat.

I decided to give a pass at rebalancing them to be more consistent, but also a bottom tier combat role (which is what they should be).

### Significant Changes ###
- Warriors roll on start and get either an iron axe, iron mace, iron sword, iron messer, or iron flail. The weapon they get bumps their skill in its respective category up by 1, which guarantees they will start with level 3 (skilled) in whatever skill their starting weapon is associated with.
- Warrior average skill in polearms has been swapped for average skill in flails.
- They no longer have a chance to get a steel shortsword.
- They have slightly higher shield skill rolling, instead of a chance of 1 or 2, they have a chance of 2 or 3.
- They no longer have heavy armor training, they get MEDIUM, same as a garrison guard. I checked all the armor that can spawn on them, none of it is heavy. There is no reason for them to have heavy armor training, they are not a rare drifter class.
- They get +1 Constitution instead of Speed. 
- They start with a poor coin pouch now.
- Their description has been changed to something more fitting: "Wandering sellswords, foolhardy gloryhounds, deserters... many and varied folk turn to the path of the warrior. Very few meet anything greater than the bottom of a tankard or the wrong end of a noose."

## Why It's Good For The Game
- Rebalances warriors to be more consistent with what a bottom tier combat class with no slot limits should be.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Optimism333** [comment]
Need to test this locally, but it's probably fine.

**Comment by sanshoom** [comment]
Ohhh my goddd they are fucking up the class nobody plays AGAIN!!! FUCK!!

**Comment by Optimism333** [comment]
> Ohhh my goddd they are fucking up the class nobody plays AGAIN!!! FUCK!!

I know, I'm terrible...

**Comment by sanshoom** [comment]
I do not see the point in nerfing a starter class that nobody plays. At BEST, if you rolled well, you could spawn with a steel coif, a haubergon, iron chausses and a steel shortsword.

Nerfing their stats aswell doesn’t make sense cause then people will just.. play as literally anything else, like a fullplate drifter or a barbarian. Playing literally any other starter class is better than being a base warrior.

**Comment by Optimism333** [comment]
Addressed some feedback.

- Warrior strength will remain at +2
- The best armor combo they can roll is an iron breastplate over chainmail

The other changes are the same.

**Comment by Optimism333** [comment]
Few more changes:
- Warriors have average flail skill, and lose average polearm skill
- They have a very small chance of spawning with an iron flail, a very good weapon to pair with their shield
- Warriors start with a poor coin pouch

**Comment by ThePainkiller** [comment]
> I do not see the point in nerfing a starter class that nobody plays. At BEST, if you rolled well, you could spawn with a steel coif, a haubergon, iron chausses and a steel shortsword.

This is not a nerf at all other than no longer being able to be decked on full plate armor without falling
Medium armor is still fairly good when and if they can afford a full suit, and the big roller gets a haubergeon AND halfplate? This ain't a nerf at all
 
> Nerfing their stats aswell doesn’t make sense cause then people will just.. play as literally anything else, like a fullplate drifter or a barbarian. Playing literally any other starter class is better than being a base warrior.

Stats are mostly untouched and it's just losing 1 bonus SPD they had for...whatever reason. Full plate drifters are literal rare picks too

**Review by ThePainkiller — APPROVED** [review]

**Pull request merged**
