### PR TITLE
Adds all but one legendary class to towner (No smith)

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

The 1 minute walk doesn't really make sense and excluding the smith none of these are so bad that them spawning in the town is going to cause an uproar. After all a 15% on a single slot.

## Why It's Good For The Game

More variety to towners without impacting the game too much with legendaries round-start on town.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Blacksmiths oppressed as usual......
(jk after the dromki pr they'll spawn with at least a 2h hammer for self defense this is not an issue and I do not mind)

**Review by Optimism333 — COMMENTED** [review]
Worth giving a try, at least. Let's see how it goes... maybe we'll actually see a legendary chef.

**Review by Optimism333 — APPROVED** [review]
No one doth protest too much, so I'm giving this the okay. If any object, say so within the day.

**Comment by ThePainkiller** [comment]
No objections from me!

**Pull request merged**
