### PR TITLE
Convert maps to TGM format, fixes map generation

### PR DESCRIPTION
**Pull request by noelle-lavenza**
## About The Pull Request
Fixes map generation with TGM-formatted maps by changing `/New()` to `/LateInitialize()`. Basically, TGM-formatted maps load in a different order/in smaller sections than base BYOND maps, meaning that map generation would begin before the rest of the map had even loaded. Now, it waits until initialisation is complete (and maploading is done) to begin generation.

Also converts all the maps to TGM and fixes some compilation issues with them.

Oh, and it deletes a ton of base SS13 maps we don't need.

## Why It's Good For The Game
Maps should be TGM to reduce merge conflicts. Split out of #827 for easier review.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
Planned for testmerge during low-pop in 12 hours or so, TGM my beloved

**Comment by lavillastrangiato** [comment]
mashallah the old shitmaps are deletes

**Review by NPC1314 — APPROVED** [review]
Can't find any issues, good for merge.

**Review by Optimism333 — APPROVED** [review]
Thank you very much for fixing this. Let's get this show on the road...

**Pull request merged**
