### PR TITLE
Revenge of the Forgotten

### PR DESCRIPTION
**Pull request by DovaKitty**
## About The Pull Request
* Replaces the Puritan with the Inquisitor, a guest from Grenzelhoft that has been sent to help Rockhill with its monsters and cultists. What he lacks in magic he makes up for with knowledge and skill.
* Adepts do not serve the Forgotten God as readily as the Inquisitor as recent hires. They have lost their ability to cast spells and have gained in reward a needle, a silver dagger and one intelligence.
* The Forgotten God's worship now stretches to the Isle of Enigma. Those hailing from Grenzelhoft, including mercenaries, Counts, Inquisitors and Swordmasters worship the Last Hero.
* Grenzel titles of knighthood are added. Instead of 'Ser', those in the East use the title 'Retter', being a cross for the words 'Rider' and 'Savior' in the old tongue. Swordmaster and Inquisitor start with this confusing title.
* Torture has never been so fun! Torture mechanics have been fixed, allowing you to wrench sin out of both heretics and villains. Make sure to rough up your targets before you take them onto the pain train.
* Confessions have been reworked. Offering a confession to a heretic or villain will allow them to sign it voluntarily. Holding a confession in your other hand while you torture a heretic or villain will let the magical ink do its work and sign the confession on their behalf. Put these signed confessions in a mailbox as an Inquisitor to complete your objective and gain you and your adepts a TRIUMPH!
* Silver weapons have been added and standardized. While doing less damage and having less durability than steel, silver weapons are the BANE of vampires. In the future they will be more useful on more enemies. Ask your local weaponsmith to craft you some, and make sure to bring them silver ore.
* Grenzelhofter mercenary has had their dodge expert trait removed and their armor now counts rightly as medium armor. There was not much reason to give a class with +0 SPD super-special light armor and a trait for unarmored fighters.

## Why It's Good For The Game
Introduces a proper antag-hunting class, with some unique backing and mechanics. Makes the world a little more interesting and flavorful.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by DovaKitty** [comment]
Test merge my PR.....

**Comment by Mogelix** [comment]
I would prefer the Inquisitor wasn't an enforced kraut but alright.

**Comment by Optimism333** [comment]
I do not think you should bump the pick probability of swordmaster from 15 to 100

image

**Comment by DovaKitty** [comment]
> I do not think you should bump the pick probability of swordmaster from 15 to 100
> 
> image
> 
> You didn't mention this in the pr body, and it's a very powerful drifter class.

Accident. Turned it up so I could test it and forgot to put it back to 15. Should be good once the server re-pulls.

**Comment by DovaKitty** [comment]
8th of August Update:
* Silver rapiers are now obtainable! Rejoice!
* Witch Hunters now spawn with a silver rapier as opposed to their old steel one. This was the original intention when making the sprite.
* Inquisitor's climbing skill is increased to 4 to match their adepts. This was largely an oversight, as climbing is required for their light-armor and stealth focus as investigators.
* Antags (and those labeled as antags such as King and Inquisitor), are now able to gain triumphs while sleeping along with the rest of the server.

**Comment by DovaKitty** [comment]
8/13/24 update:
* Inquisitor has had axe/mace and flail/whip skill removed. They did not use these weapons anyways. They have gained 2 lockpicking skill in anticipation of that PR.
* Adept has lost their flail/whip and bows skills. They have gained 1 lockpicking skill.

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
