### PR TITLE
Minor Cooking QOL Changes

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request

Adds a potato, an extra item of grain, and two trays to the Keep kitchen. Adds a potato to the inn.

## Why It's Good For The Game

It really gets my gears grinding when I play maid and I cannot do two things:

1. Serve foods to my lords on a tray, and instead have to store multiple food items in a sack or some other heinous, LRP shit
2. Not have enough grain to make two doughs

Personally, I believe that even just having some extra grain would make maid gameplay slightly less annoying, as it means you could make two pies with your roundstart supplies.

With the addition of a potato to the larders, you can even make slightly more varied dishes with your chicken and whatnot!

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Stutternov** [comment]
This updated to current map changes made?

**Comment by lavillastrangiato** [comment]
@Stutternov it is now :]

**Comment by Stutternov** [comment]
> @Stutternov it is now :]

Once it compiles it'll be merged.

**Comment by Mojamble** [comment]
I WASNT THE ONLY ONE THIS BOTHERED??????

**Pull request merged**
