### PR TITLE
Stockpile additions and removal of iron

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Adds a whole lot of things to the stockpile to better flesh out the system and in exchange removes iron completely.

Oats.
Meat/Bird Meat
Fat
Eggs
Butter
Cheese
Apples
Berries
Onions
Cabbage
Potatoes

## Why It's Good For The Game

I think it's finally time we stop pampering the local smith and make them INTERACT with a Mason or a drifter to hire and get them to go mine or go themselves instead of ordering it and everyone having plate armor no issue. This has been an issue imo for a while and this will make a dent in it which is better for the longevity of the community and pop.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
Could work out, but theres a couple issues with adding lots of stuff to stockpile
- More PITA to scroll through. Honestly, its pain.
- More focus on putting stuff into cash machine instead of refining and trading it with other players. Its not a binary, but its worth thinking on this one a bit. (if its bad for smith to over-rely on stock its bad for soilsons too, Ive been thinking on making much better/long lasting food buffs or something as other ways to increase meal value but thats not done yet)

**Comment by ThePainkiller** [comment]
I have never, and I mean, except one sole ocassion in which I saw a pilgrim deposit iron ore on the stockpile and I was desperate for ore, ever had to buy iron from the stockpile lmao, seriously a non issue to see it gone from the stockpile, if anything I'm grateful — pilgrims will no longer just mindlessly sell iron to the stockpile and will have to at least barter it with me :)
But I do agree with Pig. I wish we had a better system, like a neat TGUI window, to sort all of these into categories, to reduce scrolling of so many items every time we want to purchase something from it.

**Comment by Technobug14** [comment]
Stockpile is already bloated and hard to navigate, not to mention importing in bulk is obnoxious due to it putting you back at the top of the scroll bar after every click. And to tack onto what Painkiller said, it's extremely rare anyone actually puts iron in the stockpile and ever since the changes to the treasury interest rates at most the Steward will toss you like, one import before being broke.

In my personal experience doing a lot of smithing, most of the time I am already mining my own ore, or a mason is around.

**Comment by BadAtThisGame302** [comment]
@Technobug14 @ThePainkiller @NPC1314 maybe I'll port this compact mode or what have you so your concerns about "bloat" are over and done with.

**Review by Optimism333 — COMMENTED** [review]
I am wondering if stacking the removal of iron imports on top of the reduction to the vault's passive income generation might be a bit much?

The crown can import a bunch of iron sure, but given that the vault isn't a money printer by default anymore, that will pretty rapidly eat at the kingdom's savings unless effort has been made to make the vault generate a decent income.

**Comment by BadAtThisGame302** [comment]
> I am wondering if stacking the removal of iron imports on top of the reduction to the vault's passive income generation might be a bit much?
> 
> 
> 
> The crown can import a bunch of iron sure, but given that the vault isn't a money printer by default anymore, that will pretty rapidly eat at the kingdom's savings unless effort has been made to make the vault generate a decent income.

IMO they still import iron and you see them buy circlets or rings to pump up the vault most rounds. I think removing iron was long overdue.

**Comment by BadAtThisGame302** [comment]
Okay the compact mode is on a new machine that's called withdraw and not on stockpile or some weird stuff like that.

**Review by Optimism333 — COMMENTED** [review]
If there's no further feedback on this, it should be moved to a test soon. We can see how it goes.

**Comment by Tipy1802** [comment]
>remove gold imports
>nerf vault so is useless
>remove ability to import iron
>wonder why nobody plays steward

Seriously what is the steward's gameplay loop supposed to be? Just wait for farmers to sell crops and click a button to export them? Gosh I wonder why nobody plays steward, remove even more functions and alternative money generating schemes from him, please!

At least blackstone had a solid loop where you would import gold, get smiths to refine it into rings or statues and then either export it via the merchant or invest it in the vault. Which was fun, required the involvement of multiple parties and was an investment that could fail (smiths or merchants asking for high fees, goods getting stolen from the vault or during the process etc)

**Comment by Gunnarrecall** [comment]
Just to add to the thread here discussion I had mentioned in the discord. While I understand the motivation behind the changes, a compromise for Underdwellers/Miners/Smithies would be nice. Mining subclasses with a bit more potential in smithing their own components by hand or giving the smithies average or skilled mining instead of weak would make the gameplay loop in the absence of the opposite job role much, MUCH less painful.

**Comment by ThePainkiller** [comment]
> Mining subclasses with a bit more potential in smithing their own components by hand or giving the smithies average[...]

As long as I live I won't allow anyone but the smiths to have _any_, at all, smithing proficiency, I'm sorry, but it's gonna be a big flat and rotund no on this one.

> or skilled mining instead of weak would make the gameplay loop in the absence of the opposite job role much, MUCH less painful.

With the changes to pick qualities now **properly** affecting the amount of hits required to mine rocks (by yours truly), and the ease of leveling mining skill, this is not really an issue for smiths, and I say this as a pilgrim smith gamer that mines his own ore with just a fine iron pick crafted by, well, myself :)

**Comment by NPC1314** [comment]
When was gold imports removed?

**Comment by NPC1314** [comment]
> > Mining subclasses with a bit more potential in smithing their own components by hand or giving the smithies average[...]
> 
> As long as I live I won't allow anyone but the smiths to have _any_, at all, smithing proficiency, I'm sorry, but it's gonna be a big flat and rotund no on this one.
> 
> > or skilled mining instead of weak would make the gameplay loop in the absence of the opposite job role much, MUCH less painful.
> 
> With the changes to pick qualities now **properly** affecting the amount of hits required to mine rocks (by yours truly), and the ease of leveling mining skill, this is not really an issue for smiths, and I say this as a pilgrim smith gamer that mines his own ore with just a fine iron pick crafted by, well, myself :)

Played smith with the current TMs in? Could have more impact ingame than it does on paper, just a thought.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
