### PR TITLE
Reduces the amount of assassins in a round down to 1.

### PR DESCRIPTION
**Pull request by 1N7Slayer**
## About The Pull Request

For our current server pop, 2 assassins is a bit too much now that we have a 100% pick rate 5 man bandit gang that can be present in every single round whether or not its putsch or Vampires.

## Why It's Good For The Game

Reducing obnoxious gameplay situations without entirely removing or crippling the roles the moment someone does get a chance to play them, that's all.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Cre77** [comment]
one-slot is fine to me, but making it a pickchance would, imo, only harm the overall play quality. people who wouldn't normally pick assassin will pick it as typical rare drifter FOMO (and arguably either play worse, or just play drifter+), while those that run with dedicated plans and assassin-based characters (meee <3) will be practically locked out of going into the round with playing assassin in mind.

**Comment by 1N7Slayer** [comment]
> one-slot is fine to me, but making it a pickchance would, imo, only harm the overall play quality. people who wouldn't normally pick assassin will pick it as typical rare drifter FOMO (and arguably either play worse, or just play drifter+), while those that run with dedicated plans and assassin-based characters (meee <3) will be practically locked out of going into the round with playing assassin in mind. i also had fun spy vs spy interactions with other assassins, either making competitions, or fighting over who gets to kill someone for the triumph (usually to the death)

Disagree regarding your first point because there has already been a shared experience of one particular person that "mains" assassin that has pretty atrocious roleplay quality. That you have a lot of time in the role doesn't actually mean you're good at the role gameplay-wise or a good roleplayer. >Looks at CM MPs.

**Comment by Cre77** [comment]
> > one-slot is fine to me, but making it a pickchance would, imo, only harm the overall play quality. people who wouldn't normally pick assassin will pick it as typical rare drifter FOMO (and arguably either play worse, or just play drifter+), while those that run with dedicated plans and assassin-based characters (meee <3) will be practically locked out of going into the round with playing assassin in mind. i also had fun spy vs spy interactions with other assassins, either making competitions, or fighting over who gets to kill someone for the triumph (usually to the death)
> 
> Disagree regarding your first point because there has already been a shared experience of one particular person that "mains" assassin that has pretty atrocious roleplay quality. That you have a lot of time in the role doesn't actually mean you're good at the role gameplay-wise or a good roleplayer. >Looks at CM MPs.

why punish the entire group of people that enjoy assassin over a few bad eggs? if they are such a big point of contention, you can just up the PQ requirement a little, and/or then report their behavior to the moderators for liberal PQ-dunk application

**Comment by 1N7Slayer** [comment]
Changed the scope of the PR upon discussion.

**Comment by 1N7Slayer** [comment]
I'm going to close this for now actually since some of my fundamental issues with assassin is due to Dodge Expert, which will be addressed in a feint buff PR

**Pull request closed without merging**
