### PR TITLE
Armoring

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

Basically gives the Hats treatment to Armor
* Studded leather changed to splint mail
* Repairs some vandalism
* Couple new colors added to clothes defines
* Value formula applied to armors
* The new gambeson values added
* Defines introduced overall, the era of random is over, its going to be clearer how good each item is in comparison with each other and weird outliers fixed.

* Iron maille armor values more in line with other lights
* Chainkini likewise adjusted down
* Iron plate armor is now plate child and not scalemail
* various coats and jackets are now subtypes of jacket, not vests
* some padded clothing is now subtypes of gamb instead of unique path
* Vamp plate remains medium, vamp maille goes light like its paretn the iron maille, otherwise its pretty pointless.
* Structures the icon files so you can navigate and identify the right sprites more easily

* vests are now defines as got no sleeves and can be worn on armor slot or shirt slot
* jackets defined as leather derivate with pockets 
* gamb get tiny help vs arrows but retain low melee armor, to make them different from leather that has higher melee but no arrow protection
* Entire robe section was duplicated and a mess. Fixed. Collected all robes in the armor file and gave them a whopping 5 melee and twist protection, so the fact theyre in armor slot means a little at least.

Most of this should not be very noticeable, some price changes, new pockets for couple coats, a few items
like iron maille and iron plate will be slightly different.
gambs
Made sprites for light and padded gamb, based on regular gamb sprotes
A few uninspired armor descriptions updated Iron Breastplate desc being "Its a breastplate of iron" is not only redundant 
its kinda boring. At most one of the two two words in the name of an item should be repeated, preferably none, people see the title when clicking the item, they know its a X kind of armor already.

New chainkini too, based on Edhargs sprite (top his, skirt mine, inventory icon mine)
chainkin

fixed niteman jacket sleeves and made a new splint too based on old one
splint

Testing a cap of 95 armor on light & medium values

Remembered the codersprites I threw in to enable knigh visor & sallet visor, made proper verisions of them and added.
helmets_old
helmets

Made new armored surcoat sprites, replacing the heartfelt ones, basically a tabard-looking thing with riveted armor on the inside, medium. Useful for colored medium armor maybe.

New type of helmet added, the necked one. Basically a version of heavy helmet with integral neck protection. Only used on temple unique helmets. Lets you wear a psycross on your neck while not being unarmored, a little neat Temple bonus sort of.
The principle is the same as wearing a coif on your head slot so nothing fundamentally new.
Priesto
Several spirtes added, alternative hats for priest, several acolytes, icon for courtier hat that did not exist.

Sleeves added to niteman jacket, to various acolyte and priest clothes etc etc

New subtype /padded gets symbolic protection, for roles where you want them to keep their unique style yet give a little cover, ie temple roles.
Grenzel plumed hat now has a skullcap under it to make it more useful.

Armor & Headwear are massively structured by this this. This has to be the final commit tho, time to merge this.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Review by Optimism333 — COMMENTED** [review]
After the back and forth between Nicholas and I, we settled on THICC gambeson having the same protection tier as the bottom tier of leather armor.

So 40 melee protection and 20 bullet. Other than that, the rest of the values look fine. And thank god we are renaming studded leather to splint mail.

**Review by Optimism333 — COMMENTED** [review]
Armor values overall look alright, rest of the changes look sensible. I'll give it a bit to see if Nicholas has any more feedback, but I don't have any issues with this as is.

**Comment by sanshoom** [comment]
Hey I gotta ask, was the new chainkini sprite made to also work on aasimar?

**Review by Optimism333 — APPROVED** [review]
Been in testing a long time, I think it's a good step towards a better method of having our armors coded.

**Pull request merged**
