### PR TITLE
Random Psicross Fix

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

Fixes an issue with people getting random psicrosses on spawn

## Why It's Good For The Game
There is SO many reasons why everyone getting a psicross is bad, it completely cucks zizoids, devalues the item, and messes with loadouts that use wrist armor.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
IT would be easier to just outright delete the code block than commenting it out, as it's a copypaste of what is on [character_flaw.dm](https://github.com/Darkrp-community/OpenKeep/blob/9f13b3350bbb2779e5dd254f1c5aa4f8f44d6a33/code/datums/character_flaw/addiction.dm#L140)

**Comment by ThePainkiller** [comment]
Wait hold on, this is more a nuclear option, and just outright deletes it from even faithful.

Why not gate the entire thing **PROPERLY** behind a `if(owner.has_flaw(/datum/charflaw/addiction/godfearing))` ???

**Comment by SELFHELL** [comment]
On update, theres NO reason why this flaw should be giving out free Psicrosses. Makes you nearly immune to zizoids for zero cost or effort. As such, im just removing that bit

**Review by ThePainkiller — APPROVED** [review]
Until not tending to your flaws does something actually punishing, handing out free psicrosses is gonna be a no, yeah.
Besides you can always craft them with wood, lazy bums.

**Pull request merged**
