### PR TITLE
Pilgrim Noble Touchup (Stats, Skills, Titles, Gear)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
The idea behind this pr was to attempt to revitalize the generic nobles (the 2 slot pilgrim role without a defined background like the Zybantu Emir and Grenzelhoft Noble). I also touched up Princess, to bring their knife stat in line with other noncombatant classes.

### Noble Changes ###
Screenshot (333)

Screenshot (331)

- Gave generic nobles new clothing more fitting of their status, female noble gets a randomly colored silk dress, male noble gets a randomly colored tunic
- Female noble and male noble both get average (2) bow skill, female nobles get average (2) knives and a dagger, male nobles get average (2) swords and a rapier. Previously only female nobles got a bow, and only had minor (1) knives skill
- Male nobles get the title of "Lord" and female nobles "Lady"
- These generic nobles can now spawn in the town on round start (Personally I think this is fair given that they're significantly weaker than the pilgrim nobles, they have no armor training or weapon skills greater than average (2) and are limited to 2 slots)
- Any race can now be these nobles, except aasimar
- Their stats have been changed. Instead of -1 to Strength and +1 to Intelligence, they have +1 to Intelligence and +1 to Constitution (if male) or +1 to Speed (if female)
- Most of their skills outside of combat skills have been changed to those that would be reasonable for a noble (and are seen in other noble roles): average (2) reading, average (2) riding, average (2) sneaking, minor (1) unarmed, minor (1) wrestling, average (2) athletics, and minor (1) or average (2) music skill
- Their satchel now contains a bottle of generic red wine and a silver goblet
- Updated the assassin noble disguise with the above changes
- Gave the noble role description a retouch: "The blood of a noble family runs through your veins. Perhaps you are visiting from some place far away, looking to enjoy the hospitality of the ruler of Rockhill. You have many mammons to your name, but with wealth comes danger, so keep your wits and tread lightly..."

### Princess Changes ###
- Increased knife skill from weak (1) to average (2), to mirror other noncombatant classes

## Why It's Good For The Game
Round start nobles in the town could be interesting for courtship and intrigue, and the role as a whole needed touching up given that there were much better thought out pilgrim noble roles. Now it should serve as a good blank template for players who want to play a noble in town who isn't a member of the court and make up their own backstory.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
You can give them Athletics 2, also good attention to detail on editing noble disguise for Assassin

**Comment by Optimism333** [comment]
Updated athletics. And yeah, when I was collecting feedback before making the pr, Dova let me know that assassin could have some issues if not updated.

Should also be noted that this pr will conflict with #716 since that one also touches the assassin code.

**Review by DovaKitty — APPROVED** [review]
Assassin wise, I think the changes are fine, except for the fact that assassin nobles will spawn away from town while towner nobles wont. I'm not a huge fan of nobles spawning in town, but considering the rare nobles are better, it seems like a decent tradeoff. In the future, I'd like to see this class move into the King's 'guest', in and around the court if this trend continues.

**Comment by Optimism333** [comment]
> Assassin wise, I think the changes are fine, except for the fact that assassin nobles will spawn away from town while towner nobles wont. I'm not a huge fan of nobles spawning in town, but considering the rare nobles are better, it seems like a decent tradeoff. In the future, I'd like to see this class move into the King's 'guest', in and around the court if this trend continues.

Nobles can be pilgrims OR spawn in town, to be precise. This simply adds them to the towner list. If people meta a Noble coming from afar as a potential assassin, that's a player issue.

**Comment by ThePainkiller** [comment]
Basically:

- Latejoin pilgrims can choose to be Nobles, which puts them on par with assassin disguise
- Roundstart towners can choose Noble, and these will spawn at town, as with every other towner role

The uncertainty is still there, it could be a latejoining noble, or it could be an assassin. I've no issue with it tbh, it feels like even if not all bases are covered, the benefit of doubt is still there

**Review by ThePainkiller — APPROVED** [review]
For the love of god did I fucking forget to approve and merge this oh my god.

**Pull request merged**
