### PR TITLE
Towner Housing Changes + Keep Guest Housing + Road Changes + Spawn Changes

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request

- Gives the keep a Guest Room
- Changes the houses to be fairly functional
- Removes roof planks between houses
- Makes Shops/Housing more affordable
- Removes a lot of the dark cobble roads and replaces them with red cobble
- Move spawns to morning (beds) positions by popular request (no more CSGO lobby starts)

## Why It's Good For The Game

- Manor locked guest room so people don't need to sleep in the prince's room anymore (it can be found outside the manor directly south of the entrance)
- Changes the towner houses to be more functional by giving them workable kitchens and rooms
- Removes a lot of the uniformity of the cobble roads (Removes the feeling that Rockhill just had a roadwork crew come through and make a fresh road)
- Moves the spawns back to beds to encourage less "gamey" roleplay

**PICS**
image
image
image

**ROADS**
image
image
image
image
image

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I don't really agree with removing the planks above in the roofs. Makes it easier for everyong to traverse and leads to nice chasings of a rogue or a stalking archer shooting from above.

**Review by Optimism333 — COMMENTED** [review]
Post some screenshots of the changes, if you wouldn't mind.

**Comment by SaintBurgher** [comment]
> Post some screenshots of the changes, if you wouldn't mind.

Done

**Comment by SaintBurgher** [comment]
**OVERVIEW**
image

**Review by Optimism333 — APPROVED** [review]
Let's get it in. Rockhill real estate being more affordable included... though we still really need to just give towners houses.

**Pull request merged**
