### PR TITLE
Niteman tweaks (mostly toward Nightmatrons)

### PR DESCRIPTION
**Pull request by OctusGit**
## About The Pull Request

- Moves nightman/matrons to nobles, similar to the merchant. Gives them their own flag that doesn't share Jester (Lmao)
- The nightman leather jacket now works for females, tweaked restrictions on some races that it doesn't look well on.
- Removed nightman knife skill and their hunting knife. Changed with a coin pouch for holding their funds.

## Why It's Good For The Game

Giving the nightman his own flag and actual department flag is just consistent coding and fixing overall incorrect code. Leather jacket is mostly to have a unique clothing item that isn't exactly like the queen's dress. Lastly knife skill is useless and the coin pouch is much more appreciated. They don't really need knife skills when they have level 4 wrestling and unarmed. Their whole focus is hand to hand, knife is garbo.

dreamseeker_IHgUJELo24

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Review by Optimism333 — COMMENTED** [review]
Certainly would NOT say knife is garbo, but if you think that a coin pouch would leave them better off, that's quite fine.

Any reason you took aasimar off the allowed race list for the jacket? They can be nitemen/nitematrons as well.

**Comment by ThePainkiller** [comment]
Know what, you could instead swap knife skill and knife for a cudgel and maces 2. It'd help him more than a pouch of coins tbh.

**Review by Optimism333 — COMMENTED** [review]
Would still like an answer as to why aasimar have been removed from the allowed races for the jacket, given that they can also play as nitemen/nitematrons.

**Comment by OctusGit** [comment]
> Would still like an answer as to why aasimar have been removed from the allowed races for the jacket, given that they can also play as nitemen/nitematrons.

Oh, mostly was worried female sprites wouldnt work on them anymore. However im sure it will be fine and use the male sprites since their the same bodytype (I think???)

**Comment by OctusGit** [comment]
> Know what, you could instead swap knife skill and knife for a cudgel and maces 2. It'd help him more than a pouch of coins tbh.

Id prefer they didnt have a cudgel and just had the coin pouch instead. If they really want protection, they have their unarmed abilities, or they can hire help.

**Review by Optimism333 — APPROVED** [review]
Don't really have any remaining objections to this. A rare instance when we're removing a weapon skill on a role and giving them a utility item instead. And they do have pretty good unarmed, so we can see how it pans out.

**Pull request merged**
