### PR TITLE
Inquisitor stuff

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request

Originally fem!Inquisitor and fem!Adept, now throwing some class stuff at the wall to see what sticks.

## Why It's Good For The Game

If I've already made ruler and consort unisex, I figure I might as well go whole hog and make these ones unisex too. There was going to be other Inquisitor classes in the game that could, in theory, be women. But I didn't really feel like adding them, because I didn't personally agree with the vision.

This isn't stopping that vision from being realized (it's a one-line code change), but I figure that until it happens, it'd be fun to play an evil German woman and her muscular girlboss goon.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
> Dova didn't want them to be women and planned female subclasses. This is his work and I am inclined to agree that they should remain male only.

Then he's free to change it back when he implements said female subclasses. This is an open-source codebase.

**Comment by BadAtThisGame302** [comment]
> > Dova didn't want them to be women and planned female subclasses. This is his work and I am inclined to agree that they should remain male only.
> 
> 
> 
> Then he's free to change it back when he implements said female subclasses. This is an open-source codebase.

I think a better solution is to just make Adepts both genders and keep Inquisitors male. For now.

**Comment by lavillastrangiato** [comment]
> I think a better solution is to just make Adepts both genders and keep Inquisitors male. For now.
And when are these hypothetical classes going to be added to the Inquisitor?

**Comment by BadAtThisGame302** [comment]
> > Dova didn't want them to be women and planned female subclasses. This is his work and I am inclined to agree that they should remain male only.
> 
> 
> 
> Then he's free to change it back when he implements said female subclasses. This is an open-source codebase.

It's not really productive if one person does something only if another person reverts it back a few days later or going back and forth on an issue.

**Comment by NPC1314** [comment]
Mmm I have to say I don't feel its a good idea to change Dovas concept for the inqusition, having some genderlocked sections doesnt actually harm anything either, gives a little flavor, something to be envious about.

Perhaps add battlenuns instead as fem only adept (not multiclass pls)?  I made the clothes/armor ages ago, just gathering dust, could be fun.

**Comment by lavillastrangiato** [comment]
I don't think hemming and hawing over someone's vision when they haven't updated their vision in four months after making all of these plans to add these things to it is really a good argument.

There's no lore to support male-only Inquisitors and Adepts, Grenzelhoft is never mentioned as being especially patriarchal compared to Enigma.

As for a revert, once again, I highly doubt that this is going to happen in a matter of a few days given it's been months since the class was touched. I've made my standards quite clear; if there's someone adding female-only classes to Inquisitor, *then* the restriction to the witch-hunter type can be added back. It's a pretty straightforward exchange.

**Comment by ThePainkiller** [comment]
> > Dova didn't want them to be women and planned female subclasses. This is his work and I am inclined to agree that they should remain male only.
> 
> Then he's free to change it back when he implements said female subclasses. This is an open-source codebase.

I don't think this is the right mindset to have, pookie. "Fuck it up now and let it pass, and if someone has an issue they'll patch it out later" is not a way we want to ever proceed, code-wise. It's just not right. If a PR isn't ever included, that means it can be held off indefinitely until a PROPER code gets introduced, that will require no further changes or patchings, or "going back on decisions".

The less we "go back in decisions", the better, more cohesive we'll be. It also adds to the legitimacy of whatever gets merged, rather than lazymerging then lazyfixing, we have a higher scrutiny with what gets accepted and what not, so we can vouch that every PR that DOES get merged is because it was simply that good to be included.

**Comment by 1N7Slayer** [comment]
Nobody owns the code they contribute, this is the nature of the Creative Commons/Open Source license. Why should we have to rely on someone to come out of inactivity to update what is effectively dead code? Not a rhetorical question, a genuine one I would ask to be directly answered.

**Comment by Tipy1802** [comment]
>  It also harms no one to make the class unisex.

It also harms no one to keep it male only, especially when that was the original vision

**Comment by 1N7Slayer** [comment]
> > It also harms no one to make the class unisex.
> 
> It also harms no one to keep it male only, especially when that was the original vision

The original vision is a scalped Lifeweb ripoff. Not even a good one because at least Lifeweb has female inquisitors.

**Comment by 1N7Slayer** [comment]
Additionally, Vanderlin has been reported to be keeping Psydonian Inquisitors. There is no choice but to diverge.

**Review by DovaKitty — CHANGES_REQUESTED** [review]
Hey,

I'm sure Vanderlin opening up the Inquisition to most races and both genders has ruffled some feathers here too. I'm glad I caught this PR before it could be merged (since nobody reached out on the discord to me about this, figures).

It is true I have not added anything to the Inquisition in a few months, and that's mainly due to me being conscripted by the Project Lead to work on Archivist and the book system (which is much more difficult to code than Inquisition). That has taken much of my dev time, up until my vacation which I have gotten back from.

In light of this PR and its implications, I will be putting finishing the archive PR on hiatus until my next Inquisition update is done. This will contain a female-only Inquisitor subclass for Amazon Inquisitor, and a female-only Adept subclass with Psydonian antimagic nuns.

The issue this PR and Vanderlin's implementation will run into is that there will be unisex subclasses (main adept, grenz Inquis) and female-only subclasses, but no male-only subclasses, creating an imbalance. As has been said in this thread already, there is no 'putting the genie back in the bottle' on this. There is no chance this change would be reverted after I'm done working on those subclasses.

If you would like to work on Amazon Inquisitor and Adept nun and get them done before I do with them being good, that would be a great solution for what this PR is trying to accomplish. Failing that, I do not want this merged.

**Comment by lavillastrangiato** [comment]
@DovaKitty Sounds good. I mentioned it up there in my original comment, but I didn't really want to add the Zybantu Inquisitors and the Amazon Inquisitors because to me, frankly, having Zybantine Psydonians and Amazon Psydonians didn't make a lot of sense to me (Zybantu moreso, in the context of the lore).

If you'd like to throw up some changes on this branch, I'd be happy to show off some ideas (or just fast subclass coding) for Adept and Inquisitor.

**Pull request closed without merging**
