### PR TITLE
No Ruler Required to Start the Round + Hand Can Be Ruler

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request

See title. The Hand is registered as the "Regent" of Rockhill, to indicate that they're just there to take care of things while the royal couple is away on business.

I'm willing to accept constructive criticism on the exact mechanics of this.

## Why It's Good For The Game

Nobody really likes that we have to have a King to start the game (unless you have a really sweet gimmick in mind and you want to play ruler). Similarly, it's kind of weird that the King's Top Guy can't be regent while the king is away, right?

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by 1N7Slayer** [comment]
Holy shit, Dwarf king (regent) is real.

**Comment by BadAtThisGame302** [comment]
What if you made Queen latejoinable, teehee.... hehehe... what if that happened... wait a minute...

**Comment by lavillastrangiato** [comment]
> What if you made Queen latejoinable, teehee.... hehehe... what if that happened... wait a minute...

Would love to do it. It will be mildly annoying to test, however.

**Comment by NPC1314** [comment]
This seems to work reasonably well?
Perhaps the reserve crown should be mapped in and added to the vault to enable making laws and such  ( not sure if the replacement crown actually works though,. would like to avoid dupe of the real crown for now but the function is kinda important)

**Comment by BadAtThisGame302** [comment]
> This seems to work reasonably well? Perhaps the reserve crown should be mapped in and added to the vault to enable making laws and such ( not sure if the replacement crown actually works though,. would like to avoid dupe of the real crown for now but the function is kinda important)

You need to be crowned to make anything but an announcement on the throne, so you'd need a Priest to coronate you.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
