### PR TITLE
Peasant and Woodcutter Changes and Some Legendary Pilgrim Rebalancing (Balance, Stats, Equipment)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
I made some changes to peasant and legendary peasant to better facilitate independent farming, or helping the soilsons without needing to steal tools.

I also changed some legendary pilgrim classes to be less restrictive on allowed races, and touched up their gear and stats.

### Peasant Changes ###
- Peasants get weak (1) flail skill, same as Soilsons
- Peasants start with a sickle, hoe, and pitchfork
- Their peasant knife has been moved into their satchel

### Woodcutter Changes ###
- Woodcutter has had its +2 to strength reduced to +1 (Most noncombat and craftsmen roles really shouldn't go above +1 unless they're legendary, and with the addition of legendary roles to the town... this had to get axed. My apologies, woodcutter enjoyers)
- Woodcutter +1 to constitution replaced with +1 to endurance (additional stamina is more important and fitting for someone who chops trees for a living)
- Woodcutter has had its -1 to speed removed
- Woodcutter unarmed and wrestling has been increased from weak (1) to average (2)

### Legendary Peasant Changes ###
- All races can play this role now. Previously it was limited only to humens and elves
- The role has had its weak (1) axes/maces removed, and replaced with weak (1) flail skill
- Legendary peasant has been given a backpack with more seed variety (Instead of just wheat and apples, they have wheat, apple, potato, cabbage, and onion)
- Legendary peasants now start with a cloth coif and a basic gambeson
- Legendary peasants now start with a sickle, hoe, and pitchfork
- Legendary peasants now start with a proper pair of boots, a belt, and a mid-level wealth coin pouch (mirroring other legendary noncombat pilgrim roles)

Screenshot (441)
Screenshot (435)

### Legendary Miner Changes ###
- Gave the legendary miner a proper belt, instead of a rope belt

### Legendary Carpenter Changes ###
- All races can play this role now. Previously it was limited only to humens, elves, and half-elves
- The description has been retouched: "A true artisan in the field of woodcraft, likely having been formally trained by a guild. A master carpenter knows well how to transform wood into anything from furniture, fortifications, to entire structures."
- The Dendor robe has been swapped out for a leather jacket
- Stats bonuses have been reduced (Previously): +2 Strength, +3 Endurance, +1 Constitution, +2 Intelligence and +1 Speed, (Now): +2 Strength, +2 Endurance, +1 Intelligence

Screenshot (436)
Screenshot (437)

## Why It's Good For The Game
Some of the restrictions on these roles really weren't necessary in my opinion. I can see an argument for leaving legendary miner and mason as dwarf exclusives, but farmer and carpenter being so heavily restricted seemed unnecessary.

Other than that, QOL is good, and some of these roles definitely needed rebalancing or at least minor retouches.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
If you're gonna gimp legendary peasant out of its fork, you can give them level 2 flails for the thresher then, since it doesn't make sense they get polearms 2 without their signature polearm (the fork)

**Comment by Optimism333** [comment]
> If you're gonna gimp legendary peasant out of its fork, you can give them level 2 flails for the thresher then, since it doesn't make sense they get polearms 2 without their signature polearm (the fork)

Used the code you suggested to give both peasant and legendary peasant a pitchfork in their hands.

**Comment by Cre77** [comment]
don't forget to update the assassin peasant disguise pls

**Comment by Optimism333** [comment]
> don't forget to update the assassin peasant disguise pls

Good catch, will do that.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
