### PR TITLE
Magick PR 2 Electric Boogaloo

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Ports the Longstrider spell that negates slowdown

Tweaks haste/spitfire/arcane bolt/arcyne wall/message

Ports the Azure Peak icons from this PR, https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/657

## Why It's Good For The Game

Adds a new spell + fixes + new icons + tweaks

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
not sure on all the new icons, would prefer the old ones to not be deleted, just _old treatment, these new ones don´t do the roll up correctly I think? Anyways, safe up, dont delete those icons.

**Comment by Tipy1802** [comment]
Can you give a TLDR of the changes to the spells for code illiterate people?

**Comment by BadAtThisGame302** [comment]
> Can you give a TLDR of the changes to the spells for code illiterate people?

Adds Longstrider which negates tile slowdown.

Gives more speed to the spitfire projectile.

Increases arcyne bolt damage but reduces speed by one.

Makes arcyne wall 10 seconds instead of 20

Makes haste cost 1 less point, require less charge-up time 

Now makes message not always show who is sending the message, only if one passes the check will they understand who it's coming from.

**Comment by BadAtThisGame302** [comment]
> not sure on all the new icons, would prefer the old ones to not be deleted, just _old treatment, these new ones don´t do the roll up correctly I think? Anyways, safe up, dont delete those icons.

Brought them back.

**Review by NPC1314 — APPROVED** [review]
We wont be getting any feedback so might as well, noticed there still were a couple deletions but saved them, whatever.

**Pull request merged**
