### PR TITLE
New Zybantu Class + extra master pilgrims

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Adds a Zybantu Emir (title can be worked on) to all races and genders, that is a sort of Grenzelhoft Count, with some Mercator items aswell as kitted out in various golden/Zybantine items.

Adds the Master Carpenter and Grandmaster Mason files on the .dme, making them available to selection on the pilgrim tab.

Makes all the rare pilgrim classes, Grenzel Count/Travelling Merchant/Zybantu Emir more rare than guaranteed.

Makes the Grandmaster Mason Dwarf only and gives him a steel axe, since he used one that does not exist anymore.

Grammar checks on descriptions.

## Why It's Good For The Game

Files had two extra master pilgrims that weren't selectable, now they are. 

Also a nice Zybantine Emir(?) that can spark all sorts of roleplay with his backing from back home.

Plus the grammar and making rare classes slightly more rare than always appearing.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
Do you have a screenshot of the zybantu guy.

**Comment by ThePainkiller** [comment]
Why does a supposed merchant have a rider longsword, and is skilled on a multitude of weapons? This feels like Merchant Pilgrim powercreep.

**Comment by BadAtThisGame302** [comment]
> Why does a supposed merchant have a rider longsword, and is skilled on a multitude of weapons? This feels like Merchant Pilgrim powercreep.

I didn't add that and it's not my PR to balance travelling Merchant so..

**Review by Optimism333 — APPROVED** [review]
Looks acceptable. Emir basically being a mirror of Grenzelhoft noble in gear and skills, but with a different cultural background and language flavor.

**Comment by sanshoom** [comment]
men get a circlet while chicks don’t. truly bleak.

**Review by Stutternov — APPROVED** [review]

**Comment by ThePainkiller** [comment]
...So this class is literally just "Hearthfelt Lord but Zybantu"?

**Comment by sanshoom** [comment]
> ...So this class is literally just "Hearthfelt Lord but Zybantu"?

its grenzie noble but zybantu

**Pull request merged**
