### PR TITLE
Vampire Lord bugfix and runtime squashing

### PR DESCRIPTION
**Pull request by ThePainkiller**
# DUSTING MAKES ME FEEL GOOD

Vampire Lord at roundstart will no longer get instantly dusted when walking under the sun. They instead start a timer, in which they accumulate seconds being under the sun (displaying a message every 5 seconds to remind them that they're on open space and subjected to the light of the sun [^1] and once this timer meets its threshold (increased with each vampire lord level by ascending), finally dusts them with a gruesome scream and dying message! Unless you're a fully ascended Vampire Lord, in which case you've conquered the sun and Astrata no longer has any power over you! **Ave Domine Noctipotēns!**[^2]

### Tresholds before being dusted are:
- Roundstart Vampire Lord: 15 seconds
- Vampire Lord level 1: 30 seconds
- Vampire Lord level 2: 1 minute
- Vampire Lord level 3: 1 minute and 30 seconds
- Vampire Lord level 4:
kars-jojo

# Bugfixes:

- Fixes some runtimes in code whenever someone died or got dusted by simple life checks, or checking their appropiate parent callbacks to prevent runtimes due to null parent
- Uncomments testing mode dear god don't do this ever again
- Makes dun manor the forced map for testing
- QoL: Vampires now lose 0.5 vitae points per life tick rather than 1, as vitae has become finite on a per-mob basis.

## Why It's Good For The Game

- Fixes vampire lord level 0 getting instantly ashed under the sun
- Vampire levels now properly add more time under the sun before you get dusted, with often reminders about being under the light of sun
- Fixes runtimes, backend that nobody else cares to contribute fixes for :)
- No need to uncomment testing mode for yourself when localtesting to avoid needing a forced ruler blahblah
- Testing on the map we're all used to by now

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

[^1]: Two messages displayed after 10 seconds under the sun, with the "phew" message when going back inside
  V_LORD_FIX

[^2]: How it looks like to succeed.
  image

### CODE REVIEW

**Comment by sanshoom** [comment]
Hey man, I'd love to merge this, but I'll only do it if the vampire lord dusts no matter what level he is.

Cheers, sanshoom.

**Comment by Optimism333** [comment]
> Hey man, I'd love to merge this, but I'll only do it if the vampire lord dusts no matter what level he is.
> 
> Cheers, sanshoom.

Shush, you

**Comment by ThePainkiller** [comment]
Linters about the fucking test compile option can suck my veiny cock, I'm tempted to comment out that message just to let it run.

**Comment by NPC1314** [comment]
Linking the define testing to the VL stuff is unnecessary, #897 does the exact same thing, if you remove that, it can go to testing right away

**Review by Optimism333 — APPROVED** [review]
Been in testing a while, author says it's good to go... let's get it in.

**Pull request merged**
