### PR TITLE
The Levy Finally Arrives (Content, Balance)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
Revives #544, and finally adds selectable garrison classes. Currently there are FOUR to choose from.

### Misc ###
- Garrison archer slots reduced from 2 to 0, they are now part of the broader garrison class selection
- Garrison slots increased from 5 to 8
- Adds garrison classes, currently: Footman, Pikeman, Archer, and Fencer
- New garrison description: "You are a soldier in the ruler's garrison. Your experience, training, and equipment may vary... but you are the first line of defense against the horrors that encroach on Rockhill."

### Meet The Footman ###
https://github.com/user-attachments/assets/76ed643c-c579-436b-bca7-4ccc8c664405

The footman is the bread and butter of the garrison. Good stats, good flexibility in weapon skills, and the most starting armor.
- Stats: +1 Strength, +2 Endurance, +1 Constitution
- Armor Training: Medium Armor
- Starting Armor: Iron cuirass over Haubergeon, Gorget, and Nasal Helmet
- Main Skills: Shields, Axes/Maces, Swords
- Starting Weapon(s): Iron Messer and Iron Mace

### Meet The Pikeman ###
https://github.com/user-attachments/assets/1de15b54-309a-4f34-a70d-85543453cb93

The pikeman is the heavy hitter of the garrison, essentially filling the niche of a lesser version of a royal guard with higher strength and training in weapons with reach advantage, but slower speed and less skill flexibility.
- Stats: +2 Strength, +1 Endurance, +1 Constitution, -1 Speed
- Armor Training: Medium Armor
- Starting Armor: Haubergeon over Gambeson, Gorget, and Kettle Helmet
- Main skills: Polearms
- Starting Weapon(s): Spear or Bardiche, Iron Messer

### Meet The Garrison Archer ###
https://github.com/user-attachments/assets/1ca43c84-3c2c-4052-a0ef-720586b5e8de

Wait... don't you already know this one? Anyways, garrison archers fill the skirmisher niche of the garrison, trained in both bows and crossbows, as well as being handy with knives and daggers. However, they have the least armor and need to rely on keeping away from enemies and dodge expert to stay safe.
- Stats: +2 Perception, +1 Endurance, +1 Speed
- Armor Training: None (Dodge Expert)
- Starting Armor: Gambeson, Leather Bracers, Steel Chain Coif
- Main skills: Bows, Crossbows, Knives
- Starting Weapon(s): Bow and Steel Dagger

### Meet The Fencer ###
https://github.com/user-attachments/assets/95f41d3f-4399-4f5a-b380-ad9225cce597

The fencer is the quickest class in the garrison. Now boasting the highest speed stat among the levy, it's capable of running down most opponents and slicing them to bits with a rapier.
- Stats: +2 Speed, +1 Endurance
- Armor Training: None (Dodge Expert)
- Starting Armor: Iron Chain Shirt, Gorget, and Bracers
- Main skills: Swords, Knives
- Starting Weapon(s): Rapier

## Why It's Good For The Game
More garrison classes allows for a variety of playstyles and the ability to tailor what kind of guard a player wants to be. I believe all of these classes are reasonably balanced, and will be fun additions to change up how guard is played.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Optimism333** [comment]
Please don't update the branch if feedback is going to be requested. It makes it difficult for me to do it locally (I have to do it directly on Github if that happens). Thanks much!

**Comment by Optimism333** [comment]
Updated the footman and pikeman to have haubergeon (like garrison guards had before), rather than the iron chain shirt

**Comment by ThePainkiller** [comment]
Let me know when this one's ready for a testmerge and we will try it live

**Comment by Optimism333** [comment]
> Let me know when this one's ready for a testmerge and we will try it live

Should be good to put in for a test merge! What's the worst that could happen...

**Comment by 1N7Slayer** [comment]
opinion: RNG'd weapons/armor is evil as hell and we should move away from this game design. billhook is a steel spear so don't give them even the slightest chance of it, tbh

looks great otherwise, no other balance/design concerns

**Comment by Optimism333** [comment]
> opinion: RNG'd weapons/armor is evil as hell and we should move away from this game design. footman should just have mace+messer on both belt slots, easy enough. billhook is a steel spear so don't give the pikeman even the slightest chance of it, tbh
> 
> looks great otherwise, no other balance/design concerns

Removed the chance at a billhook per your feedback. I'm gonna wait a bit and see on the feedback is on footmen before changing them. Personally I like the randomization, but if a majority of players hate it I'll remove it.

**Comment by Optimism333** [comment]
### A Few Changes ###
- Rather than 1 random iron weapon, footman gets a guaranteed iron messer and an iron mace
- Pikeman gets an iron sword as a sidearm
- Archer gets a gambeson rather than hide armor
- Fencer has had average shield skill removed

**Comment by NPC1314** [comment]
Testing gone well, do any final tweaks if you want and well merge

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
