### PR TITLE
Update CentCom.dmm

### PR DESCRIPTION
**Pull request by Piston1937**
## About The Pull Request

This will help me and the other event admins gear up event characters much faster than manualy spawning in items. It's also a place to collect event gear over time and can be expanded to add small event areas! 
## Why It's Good For The Game

Because it means I don't have to spend 20 minutes spawning in items each time I want to play and event character 
## Pre-Merge Checklist

- [N ] You tested this on a local server.
- [? ] This code did not runtime during testing.
- [? ] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Correct me if I'm wrong but I believe you just deleted the "cargo shuttle" landing dock.

**Comment by Piston1937** [comment]
I was told everything in the top side was unneeded.  Do I need to replace the cargo shuttle dock?

**Comment by ThePainkiller** [comment]
> I was told everything in the top side was unneeded. Do I need to replace the cargo shuttle dock?

The lava maze might be useless, yes, but your modifications cover only that place, there was no reason to eliminate the shuttle, and it will cause complications with imports as there will be no landing for the shuttle to come and go.

Leave the centcomm shuttle and every other landmark there intact, please, or you'll royally fuck up the Merchant.

**Comment by Piston1937** [comment]
Okay How do I revert it?

**Comment by Piston1937** [comment]
nevermind. Found it.  Opened a different version, copy and pasted the boat place to the map should fix it.

**Comment by ThePainkiller** [comment]
> Okay How do I revert it?
> 
> Or do I create a new branch and copy paste without removing the shuttle water area?

1. Rename your map to anything else
2. Grab a copy of current Centcomm Map from main repo and slap it on the appropiate folder
3. Open StrongDMM
4. Open both maps, your "asdjashd" renamed map (from this PR) and the redownloaded Centcomm map
5. Go to your edited map
6. Press 3 to enter grab mode
7. Click drag to select the entire centcomm area with your changes, CTRL + C
8. Switch the tab of StrongDMM to the current Centcomm map
9. Place your mouse on the lowest left corner square
10. Press CTRL + V

Tadah, you copied your changes on top of the map without losing anything and without destroying the landing pod etcetera

**Comment by Piston1937** [comment]
> > Okay How do I revert it?
> > Or do I create a new branch and copy paste without removing the shuttle water area?
> 
>     1. Rename your map to anything else
> 
>     2. Grab a copy of current Centcomm Map from main repo and slap it on the appropiate folder
> 
>     3. Open StrongDMM
> 
>     4. Open both maps, your "asdjashd" renamed map (from this PR) and the redownloaded Centcomm map
> 
>     5. Go to your edited map
> 
>     6. Press 3 to enter grab mode
> 
>     7. Click drag to select the entire centcomm area with your changes, CTRL + C
> 
>     8. Switch the tab of StrongDMM to the current Centcomm map
> 
>     9. Place your mouse on the lowest left corner square
> 
>     10. Press CTRL + V
> 
>     11. Save Centcomm.dmm
> 
>     12. Delete your renamed map
> 
>     13. Push the commit
> 
> 
> Tadah, you copied your changes on top of the map without losing anything and without destroying the landing pod etcetera

Thank you.  I did it in reverse, grabbing the boat from the main branch map and slapping it in mine but should be the same thing.... Unless it's entirely dependant on being in that exact spot

**Comment by NPC1314** [comment]
Stale, putting it out of its misery.

**Pull request closed without merging**
