### PR TITLE
Arcane Knowledge trait

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Grants the Arcane knowledge trait which does nothing but alert the player they know about various occult or creatures of the world

Priest
Acolyte
Templar
Inquisitor
Adept

Court Mage
Archivist

Witch Hunter

## Why It's Good For The Game

Request by staff

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
don’t forget to add this to witch hunter, cleric, and paladin.

**Comment by BadAtThisGame302** [comment]
> don’t forget to add this to witch hunter, cleric, and paladin.

I will add Witch Hunter which I totally forgot, don't know about Cleric and Paladin though.

**Comment by sanshoom** [comment]
Wouldn’t clerics and paladins know about what an occultist item is? They’re adventurers, and have probably seen more than an acolyte who has been stuck inside a church for their entire life TBH.

**Comment by BadAtThisGame302** [comment]
> Wouldn’t clerics and paladins know about what an occultist item is? They’re religiously-empowered adventurers, and have probably seen more than an acolyte who has been stuck inside a church for their entire life TBH.

I've been told by staff that the drifters except Witch Hunter shall not get the trait.

**Comment by ThePainkiller** [comment]
Is there a future use planned for this trait? As it stands it's just a funny text to add when examining yourself, but mechanically does nothing. Might be best to turn the PR into a WIP until the intended mechanic gets added along with it rather than introduce a loose perk with no actual functionality.

**Comment by BadAtThisGame302** [comment]
> Is there a future use planned for this trait? As it stands it's just a funny text to add when examining yourself, but mechanically does nothing. Might be best to turn the PR into a WIP until the intended mechanic gets added along with it rather than introduce a loose perk with no actual functionality.

The entire point is that it is an examinanle text.

**Comment by ThePainkiller** [comment]
> The entire point is that it is an examinanle text.

That's not how it works, only you yourself can see this text when you click on your skills, others have no way of knowing you have this perk lol
Why introduce a perk for something that can be handled purely RP side, too?

**Comment by BadAtThisGame302** [comment]
> > The entire point is that it is an examinanle text.
> 
> That's not how it works, only you yourself can see this text when you click on your skills, others have no way of knowing you have this perk lol Why introduce a perk for something that can be handled purely RP side, too?

Yes, an examinable text for yourself, I was asked to do this by the community manager, take your complaints to Saint not me.

**Comment by BadAtThisGame302** [comment]
Right, I'm closing this because I can't be bothered with the conflicts + everyone seems to have forgotten about this PR. If you want me to re-make it ping me on the discord.

**Pull request closed without merging**
