### PR TITLE
Dwarf trait Poison Resistance & Poison fixes/tweaks

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

Various ideas been thrown around, this one fits well enough and is practical and not just a gimmick.
Makes dwarfs very resistant to poisons, more to natural ones like berries, less to alchemical stronger ones, so its not immunity.
Its still significant.

Adds a little challenge to the crutch that is poison bolts and makes assassins who favor poisoning drinks have to try other avenues for dwarf targets (or just up the dose I guess)

Rugged, sturdy bodies fits, nothing in the lore contradicts it AFAIK, and Optimism has some ideas on how to make it include alcohol partially so you can have drunken dwarfs that we all love.

EDIT
So, about the poison fixes. The alchemy has changed metabolism rates making poisons not work right, so I added fixes to this. Added some notes on the testng, also revealed some overlooked aspects, so

* Poison metabolism rates and damage tweaked so berrypoison acts as non-lethal (just outside crit with one dose but utterly helpless beyond crawling) and alchemical poison as lethal.
* Doses defined as 5u for ingested (one swig of a bottle) and 2u for a projectile. Otherwise their relartive balance makes little sense, its much harder to get someone to drink poison than shoot them,  and projectiles casue damage on their own too.
* Adds new poison projectile type, the potent poison one. With lower dose (2u) its still pretty harsh, might need to be removed possibly but lets try it. 2u should work ok, 3u is too good.
* Crafting recipes added so you can make poison projectiles from alchemical or refined berry poison too. Pour your poisons in a bucket or something, have arrow near, craft, just like the raw berry verison
* Poison berries had triple nutrition of non poison ones, fixed
* TG poison killers ice removed, wasnt balanced for RT, if you want to add instadeath poison again just do a subtype of strong poison and make metabolism ten times faster, but its a terrible idea.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Optimism333** [comment]
Neat stuff! Will likely look into adding an alcohol tolerance variable and have the dwarves have much higher tolerance than most.

**Comment by ThePainkiller** [comment]
We don't use cyanide on our code, and I suggest putting this PR on hold until Alchemy gets a fullmerge (which will happen in a couple days, if not tomorrow), as it adds a strong poison variant that will require these resistance changes.
The diluting changes that I'm pushing on my PR can be later merged with no issue, I can solve those conflicts when it comes to them. But it will also require a rewrite of this code as well.
All in all, excellent idea (and followup idea on alcohol tolerance!!!!), but terribly unfortunate timing for this to merge.

**Comment by NPC1314** [comment]
Hey it can wait, the little dudes been without if for half a year, they can wait couple weeks more. Ill convert to draft for now.

**Comment by ThePainkiller** [comment]
Alchemy is full merged, if you can solve merge conflicts we can totally fullmerge this one now.

**Comment by NPC1314** [comment]
While we wait for that lets do a little test.

**Review by ThePainkiller — APPROVED** [review]
Good call on lowering metabolization rate on poisons

**Pull request merged**
