### PR TITLE
Fix Troll eating Prosthetic Arm Runtime

### PR DESCRIPTION
**Pull request by InsightfulParasite**
## About The Pull Request
There was a roundstart runtime due to a troll eating a prosthetic arm. The arm would be consumed but then the attacking target proc would continue to apply damage despite the item being deleted. I reworked the code a bit to fix this issue.

UniqueAttack proc now prevents the following attacking code if it returns TRUE. This should prevent damage to already destroyed objects.
The Troll targeting a wooden arm for consumption ill fix in another PR.
image

tweak: rogueanimals.dm

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
I trust this helps but can you post screenshot of in-game localtesting not showing up the runtime on bog troll trying to attack it to make sure?

**Comment by InsightfulParasite** [comment]
> I trust this helps but can you post screenshot of in-game localtesting not showing up the runtime on bog troll trying to attack it to make sure?
Gotcha Gotcha, The runtime usually happens on the DAKKAtown map because a troll was placed near a prosthetic arm. 
image
Looking back maybe i should add a thing to prevent trolls from eating prosthetic arms if the arm being eaten is technically "Treasure". 
I'm going to add a quick PickyEater() Proc to prevent trolls from eating wooden arms.
The reason I'm making this a separate proc is so that some monsters can override this and just consume everything regardless of status or become even pickier eaters.
IMAGE OF RUNTIME AFTER PICKY EATER PROC
image
I can separate the picky eater proc to a separate PR so its not like, baked into the fix and can be test merged seperately.

**Comment by ThePainkiller** [comment]
Does this PR require merging the troll dismember mechanic first, or is it not reliant on it?

**Comment by InsightfulParasite** [comment]
> Does this PR require merging the troll dismember mechanic first, or is it not reliant on it?

No its not reliant. The eating fix is a seperate line of code.

**Review by ThePainkiller — APPROVED** [review]

**Pull request merged**
