### PR TITLE
Sets Humen, Half-Elf and Tiefling men to use the "Medium" bodytype, instead of their "Tall".

### PR DESCRIPTION
**Pull request by saltprjak**
## About The Pull Request

Tones down obscene World of Warcraft-tier dimorphism by changing the sprites of humen, half-elf and tiefling men. This effectively puts them at eye-level with dark elf men and elven women while still making them a pixel taller than their own women, and shorter than Aasimar and wood elf men by a pixel.
Additionally shaves off medium height bodyhair to make it in line with the current bodies aesthetically, and fixes an offset mistake with the head.
image
Humen King between an Elf Hand and an Aasimar Captain.
image
EDIT: now also alters medium body sprites in line with the tall body textures.

## Why It's Good For The Game

Makes tall races and monsters like orcs stand out a little more, undoes some legacy vril from the aesthetic.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
The shortening's not happening brother.

**Comment by sanshoom** [comment]
Peak

**Comment by Cre77** [comment]
> The shortening's not happening brother.

quiet, serf, short kings are in court

**Comment by Optimism333** [comment]
> This also seems to make the effected races no longer be muscular, which is pretty lame. Moreso doesn't make that much sense for humans in particular since they're a rather physically capable race, up there with Aasimar and dwarves.
> 
> At least for humans, can you add a muscular medium height version for them?

Humens are neither exceptionally physically capable or incapable. They are the median race without any inherent advantages or disadvantages. 

Personally I think them having a body as visibly muscular as an orc or aasimar (both of whom are creatures that would be stronger on average) is odd, and this makes more sense for them visually.

Though I suppose that does come down to a matter of opinion.

**Comment by BadAtThisGame302** [comment]
Humans should stay where the are, Half-Elves make sense seeing as human males are tall and Elvish women short, or Elvish males tall and humen women short. And Tiefs I don't much particularly care for.

**Comment by Optimism333** [comment]
> Humans should stay where the are, Half-Elves make sense seeing as human males are tall and Elvish women short, or Elvish males tall and humen women short. And Tiefs I don't much particularly care for.

Elven men are just as tall as humen men, and elven women are TALLER than humen women. This equating to half-elves being shorter than humens on average does not make sense. If humens aren't getting shrunk, half-elves should not be shrunk either.

**Comment by Cre77** [comment]
There is nothing in the game, nor popular fantasy stereotype, to point toward humans being intended to be the "tallest" race. The sprites for non-dwarf males are all based off the MEDIUM bodytype, everything above is offset a pixel with specifically a "taller" look in mind. 
I believe them being set to the tallest bodytype was an oversights on Ray's part during Enigma, since now RT2, of all places, HAS /imperial/ humans set to the medium body - and I believe the OG roguetown had them such as well. But there are also NORTHERN (something they're called here also) humans there that are just that, taller. While southern humans, funnily, are the short bodytype. I think "baseline" humans either got lost during the code ownership transition, or Ray purposefully made them the dominant ones.
As for muscularity - there is no reason to have all humans be natty, not with women looking like THAT alongside (women are medium bodytype (which is still shorter than male medium), mind, and elven women were such too before I upped it). Combat roles are still a minority, and even then - they wouldn't be be shredded like SOME are nowadays. This also only serves to detract from orcs and aasimar visually, making them just different-colored humans.

**Comment by Cre77** [comment]
> > > This also seems to make the effected races no longer be muscular, which is pretty lame. Moreso doesn't make that much sense for humans in particular since they're a rather physically capable race, up there with Aasimar and dwarves.
> > > At least for humans, can you add a muscular medium height version for them?
> > 
> > 
> > Humens are neither exceptionally physically capable or incapable. They are the median race without any inherent advantages or disadvantages.
> > Personally I think them having a body as visibly muscular as an orc or aasimar (both of whom are creatures that would be stronger on average) is odd, and the change in this pr makes more sense for them visually.
> > Though I suppose that does come down to a matter of opinion. The height difference alone wouldn't be the worst thing.
> 
> I say they're physically capable because human males have +1 constitution and endurance, which is the highest outside of dwarves and aasimar. Tieflings, elves, and half elves all do not have physical bonuses outside speed and dark elves only have +1 to one or the other.

But one point in CON and END won't make everyone a direct descendant to Conan the Barbarian. It simply doesn't make sense for every humanoid to be sculpted - especially when their physical stats are very much inconsequential compared to Dwarves and Aasimar.

**Comment by Cre77** [comment]
> > > > > This also seems to make the effected races no longer be muscular, which is pretty lame. Moreso doesn't make that much sense for humans in particular since they're a rather physically capable race, up there with Aasimar and dwarves.
> > > > > At least for humans, can you add a muscular medium height version for them?
> > > > 
> > > > 
> > > > Humens are neither exceptionally physically capable or incapable. They are the median race without any inherent advantages or disadvantages.
> > > > Personally I think them having a body as visibly muscular as an orc or aasimar (both of whom are creatures that would be stronger on average) is odd, and the change in this pr makes more sense for them visually.
> > > > Though I suppose that does come down to a matter of opinion. The height difference alone wouldn't be the worst thing.
> > > 
> > > 
> > > I say they're physically capable because human males have +1 constitution and endurance, which is the highest outside of dwarves and aasimar. Tieflings, elves, and half elves all do not have physical bonuses outside speed and dark elves only have +1 to one or the other.
> > 
> > 
> > But one point in CON and END won't make everyone a direct descendant to Conan the Barbarian. It simply doesn't make sense for every humanoid to be sculpted - especially when their physical stats are very much inconsequential compared to Dwarves and Aasimar.
> 
> They don't really look that muscular to be called Conan. Humans already used a different look compared to Aasimar which has them being muscular but not ripped, which I think would be better than making everyone look rather unathletic considering the times the period takes place in, and how the majority of people would work physical jobs.
> 
> (If you're wondering what the differences between the human and aasimar sprites are, it's mostly that Aasimar have a six pack while humans along with tieflings and half elves just have some definition. The medium bodytype by contrast is just a completely flat stomach.)
> 
> The current tiefling, half elf, and human bodytype. Considered the 'tall' bodytype. image
> 
> The current aasimar bodytype. Considered the 'muscular tall' bodytype. image
> 
> Currently unused but I believe used to be the young adult bodytype, and would now replace tieflings, half elves, and humans. Considered the 'medium' bodytype. image

okay, granted - i made a version of the dmi with the mt's texturing. but i'll still leave the decision there for maintainers.
image

**Comment by Optimism333** [comment]
> > > > > > This also seems to make the effected races no longer be muscular, which is pretty lame. Moreso doesn't make that much sense for humans in particular since they're a rather physically capable race, up there with Aasimar and dwarves.
> > > > > > At least for humans, can you add a muscular medium height version for them?
> > > > > 
> > > > > 
> > > > > Humens are neither exceptionally physically capable or incapable. They are the median race without any inherent advantages or disadvantages.
> > > > > Personally I think them having a body as visibly muscular as an orc or aasimar (both of whom are creatures that would be stronger on average) is odd, and the change in this pr makes more sense for them visually.
> > > > > Though I suppose that does come down to a matter of opinion. The height difference alone wouldn't be the worst thing.
> > > > 
> > > > 
> > > > I say they're physically capable because human males have +1 constitution and endurance, which is the highest outside of dwarves and aasimar. Tieflings, elves, and half elves all do not have physical bonuses outside speed and dark elves only have +1 to one or the other.
> > > 
> > > 
> > > But one point in CON and END won't make everyone a direct descendant to Conan the Barbarian. It simply doesn't make sense for every humanoid to be sculpted - especially when their physical stats are very much inconsequential compared to Dwarves and Aasimar.
> > 
> > 
> > They don't really look that muscular to be called Conan. Humans already used a different look compared to Aasimar which has them being muscular but not ripped, which I think would be better than making everyone look rather unathletic considering the times the period takes place in, and how the majority of people would work physical jobs.
> > (If you're wondering what the differences between the human and aasimar sprites are, it's mostly that Aasimar have a six pack while humans along with tieflings and half elves just have some definition. The medium bodytype by contrast is just a completely flat stomach.)
> > The current tiefling, half elf, and human bodytype. Considered the 'tall' bodytype. image
> > The current aasimar bodytype. Considered the 'muscular tall' bodytype. image
> > Currently unused but I believe used to be the young adult bodytype, and would now replace tieflings, half elves, and humans. Considered the 'medium' bodytype. image
> 
> okay, granted - i made a version of the dmi with the mt's texturing. but i'll still leave the decision there for maintainers. image

I think that's a fair compromise

**Comment by Cre77** [comment]
for future review reference: this has been discussed and greenlit by guayo and the mythic "focus group"
image

**Comment by Catalaria** [comment]
As the spriter of these bodytypes, I'm with cre7 with these ones. 
Humens should be smaller. Anyone well wary of the entire deal "Northern" was meant to imply is well knowledged it was some supremacist BS Zeth had. 
Please, bring your change to the masses. However may be against it, they just don't know what they need in life.

**Comment by Stutternov** [comment]
Way late asking; have you tested armor sprites with these changes to ensure no odd clipping or issues arise from it?

**Comment by Cre77** [comment]
> Way late asking; have you tested armor sprites with these changes to ensure no odd clipping or issues arise from it?

yes, i have - just like i did with making elven women Tall. Everything works, clothing, injuries, face details. testing it is also how i initially found out the unedited medium body had the head a pixel lower than its supposed to be.

**Review by Optimism333 — APPROVED** [review]
Guayo gave it the green light, and I believe we can at least try it. If it proves very unpopular, we can always revert it.

Edit: After the conflicts are fixed.

**Comment by ThePainkiller** [comment]
God I wish I was a tyrant to outright veto this, they're manletifying humen just for the sake of taller elves.....

**Comment by Cre77** [comment]
conflicts resolved RAHHHH

**Comment by NPC1314** [comment]
If it aint broken don't fix it.

There is nothing wrong with the visuals right now in sprite size, I never heard anyone complain that they think the aesthetics needs smaller mobs. Even if theres no unintended issues at the end of the day it seems unneeded and can only do harm, even if the average player might not notice if you literally reverse the posterior and head sections of the sprites.

**Review by Optimism333 — APPROVED** [review]
I really don't believe trying out a bit more visual distinction between the races is going to cause that much harm.

No one was greatly clamoring for elven women to be taller by a pixel in #399, but that was merged in the spirit of providing more visual distinction between the races, as was #412. I believe we can at least give this pr a test merge and see what the feedback is.

**Comment by ThePainkiller** [comment]
Elves are not just taller, they're also WIDER, holy shit that pilgrim bladesinger was ENORMOUS

**Comment by Cre77** [comment]
> Elves are not just taller, they're also WIDER, holy shit that pilgrim bladesinger was ENORMOUS

that's because of their armor specifically, elves share most of the female outline
image

**Comment by Cre77** [comment]
happy 1 month anniversary to this

**Review by Optimism333 — COMMENTED** [review]
It's a little disappointing that much of the opposition to this after the compromise (which kept humens with their muscle definition) has been outright incorrect statements or some bizarre dread at humen males losing one pixel of height.

As it stands right now all this pr would do is make humen, tiefling, and half-elf males the same size humans are in pretty much every other ss13 setting (29 pixels high as opposed to 30). Elf males would be a singular pixel taller while remaining lanky, and aasimar of both sexed would be a single pixel taller.

Someone needs to make a decision on this pr already rather than ignoring it and pretending it doesn't exist, regardless. It's been up for a whole month, this is getting silly.

**Comment by Mogelix** [comment]
Guayo is for it, the nobles are for it, it should happen.

**Comment by Stutternov** [comment]
Going to activate executive action and just TM it as every time I've talked about it this PR has gotten a shrug.

I'm indifferent so it'll be tested for a day or two. If community likes  it, or merely sees no difference. it'll get merged.

**Comment by NPC1314** [comment]
Fair enough

**Comment by SilvernKell** [comment]
i preferred it before. 
it just looks stubby-legged.

**Comment by Mogelix** [comment]
I barely notice it. I think it's good.

**Comment by SaintBurgher** [comment]
Barely notice a difference so that means this is good in my eyes lol

**Comment by ThePainkiller** [comment]
Good to fullmerge this one then? It's been approved by Opti long ago already, so...

**Pull request merged**
