### PR TITLE
Update loom.dm

### PR DESCRIPTION
**Pull request by TheMrBakit**
updating the Loom so it has a use

## About The Pull Request

This pull has for goal to make the Loom useable as a cloth-making machine
## Why It's Good For The Game
It will allow to cloth a lot of fibers at once

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by TheMrBakit** [comment]
this allows to make fibers faster than right-clicking the craft button. it's a quality of life thing

**Comment by NPC1314** [comment]
Nice, good first PR gotta say (if it works)

**Comment by TheMrBakit** [comment]
i've tested it right now and it seems to work

**Comment by TheMrBakit** [comment]
image

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
