### PR TITLE
Female Elf Speed Tweak (Balance)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
Female elves had insane synergy with speed and/or dodge focused roles, to the point that it was a bit ludicrous given the buffs to speed's usefulness as a stat. This pr pulls their speed bonus back just a little, and gives them a point of endurance in exchange.

### Changes ###
- Female elf speed bonus reduced from +3 to +2
- Female elf endurance increased from -1 to 0

## Why It's Good For The Game
Slightly curtails the heights which elven speed could reach, though those heights still remain high. Standardizes racial bonuses at +2 maximum for any given stat.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
Female elves will disappear.. in five days.

**Review by DovaKitty — APPROVED** [review]
Two-thousand yils ago, the great and noble Hero with a name now Forgotten cursed Elvenkind with mortality. Todae, his work becomes complete.

**Comment by 1N7Slayer** [comment]
Elf stats are still +3 here in the array.

**Comment by Optimism333** [comment]
I'm leaving the changes here for now. If someone wants to put forth a more radical change, can be done in another pr.

**Review by ThePainkiller — APPROVED** [review]
Between my nerf to swift and this, I'm glad we're sinking just how good SPD classes are overall into more balanced territory

**Pull request merged**
