### PR TITLE
Beer gut providence

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

Issues with old one
* Its up one level making passers by unable to notice easily if its alive or not
* its gigantic, titanic, you can't see people
* it fails to pull people in and fails to keep people inside the location in contact

Port the one from Ratwood and adds various stuff from Drunken Saiga inn because I can't be arsed to make yet another one
Because its general layout is much better. Also some QoL with stockload in kitchen.
Needs some polishing obviously.

Inn players been complaining about the issues since this map was added, its time to do something about it so playing inn is more fun again.

https://github.com/user-attachments/assets/bf5f627f-d74e-493e-9be9-d38510e8fc68

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I don't think the Ratwood, furry-esque (no offense) Inn fits in with the Stonekeep vibe. I think the second and third floor need to be adjusted. Not sure about the basement but I like the ground floor changes.

Also door leading to wall.
image

**Comment by NPC1314** [comment]
Layout is immensely better, Ill do a vidya. Theres no actual furry content in it.

**Comment by BadAtThisGame302** [comment]
> Layout is immensely better, Ill do a vidya. Theres no actual furry content in it.

I obviously didn't mean that it has furry content in a literal sense. I mean furry-esque in the artistic point of view. With how it looks.

**Comment by NPC1314** [comment]
Lets see how it does in a test then.

**Comment by lavillastrangiato** [comment]
Hmmm.

I dunno how I feel about this one. I think the critiques of the inn are totally valid. On the other hand, I almost feel like this version of the inn is too _rich_. Most "rich" areas in the game's maps usually feel a little tatty and mouldering in their luxury; something that used to be nice, but ends up feeling tarnished and ill-kept. The inn was no exception. Sure, it's comfortable and there's no rats and lice in the room (yet), but it's dusty and threadbare. 

I think what BadAtThisGame is saying is that this inn is optimised to create more of a comfortable feeling for primo ERP vibes. You mentioned it obviously needs a few tweaks, so I'm just throwing my two cents in for what makes it feel off to me.

Also, I was contemplating putting the mercenary's guild in the inn somewhere again to make room for a library so that messed with my plans a bit :(

**Comment by NPC1314** [comment]
Not sure why the mercs should take up space in the inn, part of the inn function is to provide lockable storage and good qualitry sleep areas for a wide array of people, reserving several rooms for mercs who may or may not even be played or ever visit isn't the best idea.

Theres plenty of space to the side in the basement though, them having a small area there wouldnt impact anything negatively.

**Pull request merged**
