### PR TITLE
HAMLET GAMING

### PR DESCRIPTION
**Pull request by AceVX**
## About The Pull Request

Updates Rougehamlet by @LankyMF to suit the current game. Mostly technical bugfixes left over from Lanky's absence and minor updates to keep up with the game as it stands today along with some changes left in the design notes. (Also cleans up the formatting of the book of law)

- Removes bum fight club and replaces with Feldsher's clinic in the alley

- Fixes rock spawning turfs below z level 1 blocking stairs

- Adds several street lamps to the Church Courtyard

- Swaps the locations of Garrison bunks and town jail replacing with "Drunk tank" facing the sparring yard, moving the Dungeoneer to a "Royal Retinue" role in the keep.

- Fixes throne bugs

- Adds a possible Veteran's starting position to neighbor where the Garrison archers spawn, somewhat distinguishing the roles of "The Watch" responsible to man the gates within The Garrison 

## Why It's Good For The Game

**_THE MAP IS NOT READY FOR PLAY_**

A lowpop map, incredibly efficient its with its space in the town, making it a hub in the center of a large map full of activities and PVE focused areas for players to explore. The map gives off a vibe of decay and mystery very well. 

I've made sure to walk through every building in game to ensure no more mystery boulders block Z-levels on the stairs, but confined myself to town edits and had a walk through them all.

##**TODO:**
Replace shambling corpse mobs with a "Plague cultist"  RT npc or something similar

Sewage moat slowly kills you with the current body absorption of reagents with the "Misc Liquid pools" update

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

image
image
image

### CODE REVIEW

**Comment by DAKKA-WAAAGH** [comment]
Make sure to include in-game testing images so we know you fully tested it.

**Comment by AceVX** [comment]
Sure, I'll put up some screenshots here in a bit

**Comment by AceVX** [comment]
As is, yes, it uses default RT Z-levels for forest, bog and Mt Decap

**Comment by AceVX** [comment]
I used to know how to squash commits but oh well

**Comment by NPC1314** [comment]
Essentially looks good, map still needs significant testing before live but its a step in the right direction.
Doing my own fixes/additions on the same map and will add them when this is in to minimize clashes.
In any case map might be fit for live test sooner than expected.

**Comment by AceVX** [comment]
Making some changes and re-opening.

**Comment by AceVX** [comment]
MapDiffBot is appeased at last. Praise be.

**Comment by Stutternov** [comment]
Going to try and get map rotation working this weekend; I really like the idea of having this map in.

**Comment by AceVX** [comment]
It's a great map and uses space so efficiently. The manor I'm absolutely in love with too.

**Comment by NPC1314** [comment]
Its a good map but even after a massive overhaul I done some issues remain, suggest using the devlog to keep track of it during testing. What Im saying is this should be merged, the overhaul too, but don't expect it to run smoothly at once, so a full rotation setup migth be more work than needed right now, a one day manual test could suffice.

A test in the weekend would be great though, its much better than RogueTown in its design.

**Pull request merged**
