### PR TITLE
Roguecave updated

### PR DESCRIPTION
**Pull request by Dorodomki**
## About The Pull Request

removes the gold spawners from the cave in murderwoods, adds a mini dungeon with 3 tribal orcs, 4 goblins

## Why It's Good For The Game
removes some powergaming that has been happening for quite a while and adds a mini dungeon to the game where you can risk a death for some balanced loot like orc/goblin heads, poor money pouches, iron dagger, copper dagger/axe, cosmetic clothes 

image

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Mojamble** [comment]
Does the gold still spawn? I'd also be concerned about like- people leading the enemies out.

**Comment by Dorodomki** [comment]
they will have to delve deep into the caves + lure one enemy isn't simple and can work 1 time maybe


no you can't get gold from there but only other materials

**Comment by Mojamble** [comment]
Either it needs gold and hostiles or no gold and no hostiles. I think this is a bad change. Pls.

**Comment by Dorodomki** [comment]
mojamble your opinion is interesting but im ignoring it, the pr is fine

**Comment by ThePainkiller** [comment]
No it's honestly not and I, at least I, personally, feel this is a step in the worst kind of direction possible and will vehemently stand against any locations for static loot like we're a FO13 server.

These kind of map spots:
1. Invalidate blacksmiths
2. Enforces a meta for equipment
3. Makes people beeline straight to these locations for loot
4. Encourages non-adventurers to even gun for this loot because they could turn their characters into fighters by lootrushing these locations and hitting wooden dummies
5. Brings us by design closer to FO13 "dungeons" or loot maps that create too much individuality and drive focus away from roleplay into a pure PVE scenario
6. Sets a bad example if we approve one of these PR's, as people WILL hang on these logic gates to try and inject more slop into the game, which will eventually dillute it into something not pleasant at all.

I'd like the opinion of other maintainers on this matter, but from me it's gonna be a no. No armors and weapons on random locations, no matter how well guarded they are by pre-spawned NPC's which, AS WELL, are bad for processing and something we want to avoid as much as we can for various reasons (we do not have any procs to sleep their AI's)

**Pull request closed without merging**
