### PR TITLE
Murderwood Drifter QOL Changes (Braziers, Bridge, Maneater/Mantrap Reduction)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
Since a fix for the torch dropping hasn't been found yet, I'm bringing this pr as a temporary solution. I have also added a way to ford the river without extinguishing a torch in the process.

### Mapping Changes ###
Screenshot (345)
- Adds braziers to drifter spawn points, removed spawn points that were making some drifters spawn in water

image
- Adds a broken bridge that can be leapt across to avoid fording the river

### Maneater/Mantrap Changes ###
- Reduces the weighted value on maneaters and mantraps in the woods from 1 to 0.25, will adjust further if necessary. Unfortunately there is no way to local test this change

## Why It's Good For The Game
- Workaround for a bug until it can be solved, slightly improved the traveling experience for drifters by reducing instances of the torch instantly being extinguished due to no fault of their own.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Optimism333** [comment]
I wasn't able to fully test the bridge, because the forest map z-level didn't load? But I copied it almost exactly from the Dakka town bridge and believe it should work.

**Comment by ThePainkiller** [comment]
Bit iffy about merging this one with that comment, I hope this doesn't fuck up our murderwoods like we had with the town...

**Comment by Optimism333** [comment]
> Bit iffy about merging this one with that comment, I hope this doesn't fuck up our murderwoods like we had with the town...

The worst thing that could happen with the bridge is that it doesn't work.

**Comment by Coastfront** [comment]
Rain over sand, Winds within stone; Certain things do not belong in their company.

I do not believe it is intentional for maneaters or mantraps to spawn inside of the bandit camp.
Not even just on the road out; Literally inside of the walls, & even right-outside of the door.

**Comment by Optimism333** [comment]
Made a more comprehensive fix in #769

**Comment by Optimism333** [comment]
> Rain over sand, Winds within stone; Certain things do not belong in their company.
> 
> I do not believe it is intentional for maneaters or mantraps to spawn inside of the bandit camp. Not even just on the road out; Literally inside of the walls, & even right-outside of the door.

Attempting to address that in #770

**Pull request closed without merging**
