### PR TITLE
Aasimar Female Buff (Cosmetic)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request

This pull is a combination of work from two different prs, linked below:
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/31
https://github.com/Blackstone-SS13/BLACKSTONE/pull/987

Without being able to look at the code from BladeburstNINJA and SELFHELL, I doubt I would have been able to figure this out. So a big thanks to both of those pr authors.

- This pr ports the sprites for a new bodytype, known as "ft_muscular"

image

image

image

- I have applied this new bodytype to female aasimar by default, but it opens the possibility that it could be applied to other races in the future.
- Some uniquely female clothing has received sprite updates to have a unique fit for the new body (the rest use male sprites): 
image
image

- The spritework above is from SELFHELL's pr, and is not my work. All I did was a small touchup to the side sprites of the chainkini.
- **To-Do:** The silk dress still needs to be updated. generic dress fits could be slightly improved. (Will do this in a follow-up pr)

## Why It's Good For The Game

- Follows the trend of #399 in applying more visual differences between the races.
- It makes female aasimar look more thematically appropriate for their lore as godcrafted soldiers, rather than having an hourglass figure.

## Did U Test It
- I did some local testing and clothing seemed to fit as intended. The code also didn't appear to runtime or break anything.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
i wait with bated breath

**Comment by Optimism333** [comment]
@ThePainkiller Merged main, so this is no longer out of date. Could you remove the out of date label when you have a chance?

Would be much appreciated.

**Comment by ThePainkiller** [comment]
Have you tested Aasimar females wearing clothing with and without boob window? Won't their breasts clip out of clothing because they use male sprites for clothing?

**Comment by Optimism333** [comment]
> Have you tested Aasimar females wearing clothing with and without boob window? Won't their breasts clip out of clothing because they use male sprites for clothing?

I didn't see any behavior like that in testing. Here's a common shirt from a side view.

image

**Comment by Optimism333** [comment]
I'm going to close this and open a new pr with the additional sprite revisions.

I spent a good bit of the day tweaking sprites, and improved the fits for:

generic dress, bartender dress, sexy dress, silk dress, armored dress, nun robe

**Pull request closed without merging**
