### PR TITLE
All my homies hate the feldsher cage

### PR DESCRIPTION
**Pull request by Plaguewalker**
## About The Pull Request

Disables the feldsher cage from being spawned in with at random

## Why It's Good For The Game
Because, it could be placed in the same closet that spawns in the doctors key rather than being randomly bestowed upon in the lobby.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by casualspacestation14enjoyer** [comment]
dont make PRs from your main fork branch, also secondly i hope youre using github desktop because that suspiciously looks like you just uploaded the file to the fork... but if you add it to the closet in this PR i wont have any complaints

**Comment by Plaguewalker** [comment]
> dont make PRs from your main fork branch, also secondly i hope youre using github desktop because that suspiciously looks like you just uploaded the file to the fork... but if you add it to the closet in this PR i wont have any complaints

Nobody genuinely likes the cage, and I'm not a mapper. It shouldn't impede the main loadout of the class, and secondly this is how I've done minor one to two line code edits. Usually when doing bigger projects I start fresh.

**Comment by casualspacestation14enjoyer** [comment]
> > dont make PRs from your main fork branch, also secondly i hope youre using github desktop because that suspiciously looks like you just uploaded the file to the fork... but if you add it to the closet in this PR i wont have any complaints
> 
> Nobody genuinely likes the cage, and I'm not a mapper. It shouldn't impede the main loadout of the class, and secondly this is how I've done minor one to two line code edits. Usually when doing bigger projects I start fresh.

ok fair enough but its still just placing one item

**Comment by Plaguewalker** [comment]
> > > dont make PRs from your main fork branch, also secondly i hope youre using github desktop because that suspiciously looks like you just uploaded the file to the fork... but if you add it to the closet in this PR i wont have any complaints
> > 
> > 
> > Nobody genuinely likes the cage, and I'm not a mapper. It shouldn't impede the main loadout of the class, and secondly this is how I've done minor one to two line code edits. Usually when doing bigger projects I start fresh.
> 
> ok fair enough but its still just placing one item

You're more then welcome to do it seeing as I by no stretch am a mapper nor do I want to actually touch the tools for that then somehow accidentally delete something

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
