### PR TITLE
Barracks Remodel

### PR DESCRIPTION
**Pull request by Max-023**
## About The Pull Request
Remodels the barracks to be more more pleasant to be in and be used. The mercenary's building has been knocked down to make way for a garrison training yard as well as more greenery for the townsfolk, with the mercenaries forced to make camp outside the town (get a job ya bums). The armory has also been expanded in its options of iron, with the steel weaponry being removed to compensate. Additional uniform parts are also now in the basement storage so that those brought on can look proper (but not fully kitted).

## Why It's Good For The Game
The garrison currently is not pleasant at all to use and can be more trouble than it's worth to be in. The living quarters are much too small as well so often fuller guard rosters end up bottlenecked with the 3 beds they were given for 8 folk. The yard additionally gives room for RP, training with the squires (who finally get their own room), and a place for recruits to be drilled with the weapons they are to use.

The armory expansion also means guard can have more variety with what they choose to use in a round, and making it more appealing to raid the armory if someone wants to get something that works. All options are only iron, but it is up to the guard to get upgrades. A whetstone has also been added in the armory to make sure all blades are at least sharpened.

image_2024-06-20_123719466

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Why this change in the Keep?
image

**Comment by BadAtThisGame302** [comment]
Door leads to wall.
image

**Comment by BadAtThisGame302** [comment]
Brazer on a door.
image

**Comment by Max-023** [comment]
> Why this change in the Keep? image

Likely a result from merging the RG room and patching the conflict. I'll fix it when I get home.

**Comment by Max-023** [comment]
> Door leads to wall. image

Ah, forgot about that side door. I'll take care of it.

**Comment by Max-023** [comment]
> Brazer on a door. image

Lmao, not sure how I missed that. Good catch.

**Comment by guayitoo** [comment]
https://cdn.discordapp.com/attachments/1231424257511260201/1252790857778729000/image.png?ex=66737fe8&is=66722e68&hm=911ba4f93e39b8ce9760993ece03c19bc7e5a27227a1283d7acda150f1cacd71&

Front door is broken, leads to a black void, has to manually delete it and add a turf on it so people can walk thru.

https://cdn.discordapp.com/attachments/1231424257511260201/1252791520113721404/image.png?ex=66738086&is=66722f06&hm=e6ec5f27e4232b6523bfcfedabc2dc5394518ec6f4b002f37e1ca2350dc5cbbe&

**Comment by guayitoo** [comment]
https://cdn.discordapp.com/attachments/1231424257511260201/1252791774657904680/image.png?ex=667380c2&is=66722f42&hm=17087008f117fac1ec4ed2f6b8df7c6d59f66b9c28d725405b6fefc200d9bb06&

Stone walls instead of stairs.

https://cdn.discordapp.com/attachments/1231424257511260201/1252791872401969182/image.png?ex=667380da&is=66722f5a&hm=b1828e077d1553cbcdb7f6501116084395134133503651db3051c8f3f551be72&

**Comment by guayitoo** [comment]
https://cdn.discordapp.com/attachments/1231424257511260201/1252791929347772506/image.png?ex=667380e7&is=66722f67&hm=4ce3c13fdfcb997cd854b39f560887a7010cc1121c696ef57a7186d54d0072af&

Odd positioning/lack of movement here for the downstairs and a stone wall blocking the stair way.

Had to remove it manually as an admin so people can navigate thru there.

https://cdn.discordapp.com/attachments/1231424257511260201/1252792139029676083/image.png?ex=66738119&is=66722f99&hm=689a4dfd82d08f944885eb82be08482d6979c2bff714f65b14fb83dab7fb5635&

**Comment by guayitoo** [comment]
https://cdn.discordapp.com/attachments/1231424257511260201/1252792274337923125/image.png?ex=66738139&is=66722fb9&hm=639731e784021b94e7368dab04a19007695b583d86ae9284997cfdf05e85f860&

This door was unopenable via garrison keys.

**Comment by guayitoo** [comment]
https://media.discordapp.net/attachments/1231424257511260201/1252793215829016588/image.png?ex=6673821a&is=6672309a&hm=7dff4a3438c420cb82c348ec5ee78f5de8af7c33707e8fdfaf3a2d38ba9d2fa2&=&format=webp&quality=lossless&width=266&height=385

This doorway has a wall inside of it.

**Comment by guayitoo** [comment]
https://cdn.discordapp.com/attachments/1215877244208025661/1252793429763686494/image.png?ex=6673824d&is=667230cd&hm=4abcefccd27a8aaced60bcb518c682a99163356851c8831d8dff5109ba754377&

Keys do not work here.

**Comment by guayitoo** [comment]
https://media.discordapp.net/attachments/1215877244208025661/1252794091406889031/image.png?ex=667382eb&is=6672316b&hm=524122bf93ec5756fc9ca0d9b3502d160627c1af5bfbb3005c6bc8a829fb519f&=&format=webp&quality=lossless&width=768&height=738

Complete Darkness in the armory/no lighting.

**Comment by RoboticVodka** [comment]
The Mercenary camp could do with a palisade fence around it then just a single door or some such by the road and you can just make use of the currently existing key and door. Bit silly for there to be nothing to even slightly delay someone coming in to steal things or kill you in your sleep.

**Comment by guayitoo** [comment]
https://cdn.discordapp.com/attachments/1246144322039189555/1252820512481083402/image.png?ex=66739b86&is=66724a06&hm=05a48d4b10effb4cf55892206a6e57a4b9cfffff53cc60def5c5bad74f905ee8&

These bars have walls within t hem, blocking the view.

**Comment by CormanQuewye** [comment]
I honestly really like these barracks. It's major issues for me are:

- Stuff others have brought up (key issues, walls blocking doors, lacking of sufficient lighting);
- I feel as if this should be BEHIND the moat and connected to the outside of the keep's wall. It'd make sense, if the keep were under siege that the garrison and its supplies would be in a better position to defend;
- Certain aspects to make it feel more lived in. More banners, a kitchen, a fireplace by wall.
- It is WAY larger than it needs to be.

The good:
- It feels like an actual set of barracks rather than a prison with some haphazardly added living quarters.
- Has a training yard.
- Has a good assortment of equipment, stuff like gambeson and leather bracers, the sort of things guards will never end up buying anyway so it's nice that it'll give them more use (and also not force every guard to sit in a queue for steel bracers).

**Comment by Max-023** [comment]
> https://cdn.discordapp.com/attachments/1231424257511260201/1252792274337923125/image.png?ex=66738139&is=66722fb9&hm=639731e784021b94e7368dab04a19007695b583d86ae9284997cfdf05e85f860&
> 
> This door was unopenable via garrison keys.

Could you specify which door this is? The link is bunked and I cannot find the door in Strong.dmm.

**Comment by Max-023** [comment]
> https://cdn.discordapp.com/attachments/1215877244208025661/1252793429763686494/image.png?ex=6673824d&is=667230cd&hm=4abcefccd27a8aaced60bcb518c682a99163356851c8831d8dff5109ba754377&
> 
> Keys do not work here.

Same with this one. All the other issues I was able to catch.

**Comment by Max-023** [comment]
> * I feel as if this should be BEHIND the moat and connected to the outside of the keep's wall. It'd make sense, if the keep were under siege that the garrison and its supplies would be in a better position to defend;

This one would be a major adjustment to make, but possible. The issue would be that the public holding would have to be changed to be separate, which could lead to it being defunct due to no one watching it.

> * Certain aspects to make it feel more lived in. More banners, a kitchen, a fireplace by wall.

Very possible. I'll see about adding more.

> * It is WAY larger than it needs to be.

Ironically, the building itself is the same size. It was just so horribly inefficient that most of it is blocked off.

> * There's only one bathroom. They serve no purpose, but realistically... copy the bathroom stalls from the current barracks. It's silly to imagine a retine of ten or so people all having to wait on each other, each morning. And add a wash barrel to it, you nasty person, you.
I can see about adding stalls downstairs. The main floor is too crowded when I tried to do that exact thing.

**Comment by CormanQuewye** [comment]
> > * I feel as if this should be BEHIND the moat and connected to the outside of the keep's wall. It'd make sense, if the keep were under siege that the garrison and its supplies would be in a better position to defend;
> 
> This one would be a major adjustment to make, but possible. The issue would be that the public holding would have to be changed to be separate, which could lead to it being defunct due to no one watching it.
> 
> > * Certain aspects to make it feel more lived in. More banners, a kitchen, a fireplace by wall.
> 
> Very possible. I'll see about adding more.
> 
> > * It is WAY larger than it needs to be.
> 
> Ironically, the building itself is the same size. It was just so horribly inefficient that most of it is blocked off.
> 
> > * There's only one bathroom. They serve no purpose, but realistically... copy the bathroom stalls from the current barracks. It's silly to imagine a retine of ten or so people all having to wait on each other, each morning. And add a wash barrel to it, you nasty person, you.
> 
> I can see about adding stalls downstairs. The main floor is too crowded when I tried to do that exact thing.

One final thing (this is a me thing). I haven't seen what the mercenary's guild looks like (seeing as this remodel changes it or just moves it), but please keep it with a reception area and... *please* add more scrolls, papyrus, and a bulletin board to the reception area to allow me to receptionmaxx as a mercenary and post contracts up, I'd kiss you.

**Review by Stutternov — APPROVED** [review]

**Comment by NPC1314** [comment]
Execution was sloppy, advice is to test it more thoroughly before PRing it next time, but, the ideas and concepts
in the remodel are pretty great aesthetics wise. A few issues with traffic flow but solved it with some minor adjustments in the final PR, and the huge pile of weapons in armory a bit excessive, but overall it has a charm to it the old one really lacked.

TL:dr: Nice stuff, please test a bit more next time

**Pull request merged**
