### PR TITLE
Commit

### PR DESCRIPTION
**Pull request by WWWWW-Git**
## About The Pull Request

Implements new sprites into the game with armor and crafting code.

## Why It's Good For The Game

Its cool stuff.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Dorodomki** [comment]
need previews of the sprites ingame and icons buddy

**Comment by Dorodomki** [comment]
agh awesome all good

**Review by Optimism333 — COMMENTED** [review]
Please add screenshots of the new sprites back to the body of this pr.

Want to know why Pig opposes this as well, before moving forward with a review.

**Review by Optimism333 — COMMENTED** [review]
Thanks for providing the sprite previews. Want to talk with Pig about what's wrong with this before moving forward, but I don't personally see an issue.

**Comment by Optimism333** [comment]
> > Please add screenshots of the new sprites into the body of this pr.
> > Want to know why Pig opposes this as well, before moving forward.
> 
> frog kettle klappvisor halfvisor onion totod wickercloak menears elfears briarhelm beak bogcowl boggardarmor boggardcowl
> 
> Le sigh here they all are. If Pig doesn't like the way they're being implemented codewise I'll accept that but Spritewise they're fine.

**Comment by Optimism333** [comment]
Oops, lol. Misclick

**Review by Optimism333 — COMMENTED** [review]
Alright, so the gist of it is the following. Some of these sprites are really iffy in quality: 

- The first two helmets are fine, imo
- Bascinet with the visor inverted doesn't look right
- Next helmet looks... alright? I'm not quite sure what it's supposed to be with that massive visor
- The onion helmet just looks bizarre, I'm not a fan of it
- I don't know how I feel about that great helmet, the additions to the sides look off. Is it supposed to be cloth? Decoration?
- The grass cloak and the ear necklaces look good and are neat ideas, no complaints there
- Helmet with a face on it is goofy, but I kind of like the idea
- Griffith helmet looks weird, particularly on the front and back sprites. The side bits look like helmet lights
- Not really a fan of the bog clothing either, to be honest. It just looks off

The ones I'd be willing to throw in as is:
- First two helmets
- Fourth helmet
- Grass cloak and ear necklaces

**Comment by NPC1314** [comment]
> Alright, so the gist of it is the following. Some of these sprites are really iffy in quality:
> 
> * The first two helmets are fine, imo
> * Bascinet with the visor inverted doesn't look right
> * Fourth helmet looks... alright? I'm not quite sure what it's supposed to be with that massive visor
> * The onion helmet just looks bizarre, I'm not a fan of it
> * I don't know how I feel about that great helmet, the additions to the sides look off. Is it supposed to be cloth? Decoration?
> * The grass cloak and the ear necklaces look good and are neat ideas, no complaints there
> * Helmet with a face on it is goofy, could go either way on this one, dunno
> * Griffith helmet looks weird, particularly on the front and back sprites. The side bits look like helmet lights
> * Not really a fan of the bog clothing either, to be honest. It just looks off
> 
> The ones I'd be willing to throw in as is:
> 
> * First two helmets
> * Fourth helmet
> * Grass cloak and ear necklaces
> 
> I don't want to add the rest as is, personally. But I'll ping Dromkii for a second opinion.

more or less in line with my view. Ill add.
The beak helmet is just
sinfulhelmets
 a lazy resprite of the noc helmet. 
The Totod one is kinda interesting yeah but needs some work.

**Comment by Optimism333** [comment]
> > Alright, so the gist of it is the following. Some of these sprites are really iffy in quality:
> > 
> > * The first two helmets are fine, imo
> > * Bascinet with the visor inverted doesn't look right
> > * Fourth helmet looks... alright? I'm not quite sure what it's supposed to be with that massive visor
> > * The onion helmet just looks bizarre, I'm not a fan of it
> > * I don't know how I feel about that great helmet, the additions to the sides look off. Is it supposed to be cloth? Decoration?
> > * The grass cloak and the ear necklaces look good and are neat ideas, no complaints there
> > * Helmet with a face on it is goofy, could go either way on this one, dunno
> > * Griffith helmet looks weird, particularly on the front and back sprites. The side bits look like helmet lights
> > * Not really a fan of the bog clothing either, to be honest. It just looks off
> > 
> > The ones I'd be willing to throw in as is:
> > 
> > * First two helmets
> > * Fourth helmet
> > * Grass cloak and ear necklaces
> > 
> > I don't want to add the rest as is, personally. But I'll ping Dromkii for a second opinion.
> 
> > > Alright, so the gist of it is the following. Some of these sprites are really iffy in quality:
> > > 
> > > * The first two helmets are fine, imo
> > > * Bascinet with the visor inverted doesn't look right
> > > * Fourth helmet looks... alright? I'm not quite sure what it's supposed to be with that massive visor
> > > * The onion helmet just looks bizarre, I'm not a fan of it
> > > * I don't know how I feel about that great helmet, the additions to the sides look off. Is it supposed to be cloth? Decoration?
> > > * The grass cloak and the ear necklaces look good and are neat ideas, no complaints there
> > > * Helmet with a face on it is goofy, could go either way on this one, dunno
> > > * Griffith helmet looks weird, particularly on the front and back sprites. The side bits look like helmet lights
> > > * Not really a fan of the bog clothing either, to be honest. It just looks off
> > > 
> > > The ones I'd be willing to throw in as is:
> > > 
> > > * First two helmets
> > > * Fourth helmet
> > > * Grass cloak and ear necklaces
> > > 
> > > I don't want to add the rest as is, personally. But I'll ping Dromkii for a second opinion.
> > 
> > 
> > more or less in line with my view. Ill add. The beak helmet is just sinfulhelmets a lazy resprite of the noc helmet. (minor edits like this of unique gear is obv bad, devalues the unique thing) The Totod one is kinda interesting yeah but needs some work.
> 
> Respectfully, neither of you know what you're talking about. Drom, the sprite maintainer himself, signed off on these sprites, its already been greenlit by him. The PR has been up for over 2 weeks. Just merge it.

I've asked him to do another review based on my concerns and Pig's concerns. If you're unwilling to take feedback from Pig or myself, we can wait to see what he says.

**Pull request closed without merging**
