### PR TITLE
Beginning of Squire Classes (READY)

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Makes three classes for the Squire.

Sword
Spear
Flail

## Why It's Good For The Game

More class selections as agreed with most of the community is far better than being given random equipment. And what better way to try my hand at one with the role that's one of the forgotten ones.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
I feel like losing medium armor training is a massive nerf for them, even making sense given the theme of the class
We could uh, bring this to discussion to see what people have to say about it

**Review by Optimism333 — COMMENTED** [review]
I have some qualms with some of the descriptions, and the loss of medium armor as well.

I'm not quite sure why the squire needs subclasses? Aside from starting gear and flavor, the effect might be a bit lost on them. Regular garrison members need it because it defines a specialty that they have trained weapon skills in. 

Squires can get up to skilled in any weapon skill they choose by using a training dummy, though. They already have the flexibility to train up to garrison levels in whatever weapon class they want.

**Comment by anything86** [comment]
Starting with a steel flail seems a bit unreasonable, as it is straight up able to go through masterwork steel plate even at 10 strenght and should by virtue of that be considered a special weapon.  Coupled with the fact the squire can easily train shields to Skilled as well eliminates any weakness there very quickly, and ends up making this competitive if not outright better than most garrison guard classes.

I'm not sure even a downgrade to an iron flail would change my mind on this, since it keeps all of the armor penetration, but that's technically an issue with the flail weapons as a whole rather than the Squire. In the end, I'd say at least downgrade the starting flail to iron.

**Comment by BadAtThisGame302** [comment]
> I have some qualms with some of the descriptions, and the loss of medium armor as well.

What are your issues? I can give them back the medium armor if you want. And what descriptions are an issue?

> I'm not quite sure why the squire needs subclasses? Aside from starting gear and flavor, the effect might be a bit lost on them. Regular garrison members need it because it defines a specialty that they have trained weapon skills in, with other weapon skills unable to exceed average on a training dummy.

Because I wanted to try my hand out at making subclasses for a relatively forgotten role and after this one is denied or accepted I'll move on to Hand or RG.

**Comment by BadAtThisGame302** [comment]
> Starting with a steel flail seems a bit unreasonable, as it is straight up able to go through masterwork steel plate even at 10 strenght and should by virtue of that be considered a special weapon. Coupled with the fact the squire can easily train shields to Skilled as well eliminates any weakness there very quickly, and ends up making this competitive if not outright better than most garrison guard classes.
> 
> I'm not sure even a downgrade to an iron flail would change my mind on this, since it keeps all of the armor penetration, but that's technically an issue with the flail weapons as a whole rather than the Squire. In the end, I'd say at least downgrade the starting flail to iron.

Downgraded it for now. Feel free to say if you have any other concerns.

**Comment by BadAtThisGame302** [comment]
> Otherwise, these do look nice and flavourful, but I've never really used a flail/whip, but I'd imagine the speed bonus on flail would be better used on lancer to keep 2 tile distance and teach people abuse using the reach spear to their advantage.

Sure, I can do that.

**Comment by Optimism333** [comment]
> > I have some qualms with some of the descriptions, and the loss of medium armor as well.
> 
> What are your issues? I can give them back the medium armor if you want. And what descriptions are an issue?
> 
> > I'm not quite sure why the squire needs subclasses? Aside from starting gear and flavor, the effect might be a bit lost on them. Regular garrison members need it because it defines a specialty that they have trained weapon skills in, with other weapon skills unable to exceed average on a training dummy.
> 
> Because I wanted to try my hand out at making subclasses for a relatively forgotten role and after this one is denied or accepted I'll move on to Hand or RG.

I really just don't feel like squire needs subclasses. It feels counterintuitive since it's the generalist garrison trainee role that can get up to skilled in any weapon they want. Hence, they can pick up any weapon in the armory and train up with it.

The main reason garrison guards get subclasses is because they can't do that. They are specialists, due to training constraints.

I wouldn't call squire forgotten, either. I gave them a touchup relatively recently, but the only change I think they really need is to spawn with an iron sword instead of the random list that might give them a copper dagger (lol).

Royal Guards having subclasses could be interesting? I think it's more justifiable than having them for squires.

**Comment by BadAtThisGame302** [comment]
> > > I have some qualms with some of the descriptions, and the loss of medium armor as well.
> 
> > 
> 
> > What are your issues? I can give them back the medium armor if you want. And what descriptions are an issue?
> 
> > 
> 
> > > I'm not quite sure why the squire needs subclasses? Aside from starting gear and flavor, the effect might be a bit lost on them. Regular garrison members need it because it defines a specialty that they have trained weapon skills in, with other weapon skills unable to exceed average on a training dummy.
> 
> > 
> 
> > Because I wanted to try my hand out at making subclasses for a relatively forgotten role and after this one is denied or accepted I'll move on to Hand or RG.
> 
> 
> 
> I really just don't think squire needs subclasses. It feels counterintuitive since it's the generalist garrison trainee role that can get up to skilled in any weapon they want. Hence, they can pick up any weapon in the armory and train up to skilled with it.
> 
> 
> 
> The main reason garrison guards get subclasses is because they can't do that. They are specialists, due to training constraints.
> 
> 
> 
> I wouldn't call squire forgotten, either. I gave them a touchup relatively recently, but the only change I think they really need is to spawn with an iron sword instead of the random list that might give them a copper dagger (lol).
> 
> 
> 
> Royal Guards having subclasses could be interesting? Certainly it's more justifiable than having them for squires.

Alright then, I'm closing this PR seeing it won't be merged.

**Pull request closed without merging**
