### PR TITLE
Demotes the swordmaster to hedge knight after repeated failures to bring honor to the Empire.

### PR DESCRIPTION
**Pull request by 1N7Slayer**
## About The Pull Request

In seriousness this brings the class in line with the other rares for balance. It's a full plate coverage class anyway, it can suffer the one and only nerf it ever needs after this point.

If maints want this role to have other additional skills please make suggestions: I noticed it's very short on a skill array, oddly.

## Why It's Good For The Game

Consistency of game design good. I will lose respect for anyone who unironically stoops to go, "nooo not my special snowflake grenzelhofterino role" to defend the state of rare drifters on the game.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Review by Optimism333 — APPROVED** [review]
If someone else hadn't done it, I would have done it myself. This has needed to be done for quite a while.

Maybe in the future we can add a swordmaster, but it absolutely will not have plate armor, and it should not come before there is some sort of restriction on the number of rare drifters that can appear in a round.

**Review by ThePainkiller — APPROVED** [review]
I'll be honest, it doesn't make any difference for just one level, and you have a point. No other rare class has 5 skill on any weapon, this was the only snowflake one that did, and this should bring them on par with Royal Guard and every other rare drifter class.

**Comment by sanshoom** [comment]
> I'll be honest, it doesn't make any difference for just one level, and you have a point. No other rare class has 5 skill on any weapon, this was the only snowflake one that did, and this should bring them on par with Royal Guard and every other rare drifter class.

sentinel has a 5 in archery btw.

**Comment by Optimism333** [comment]
> > I'll be honest, it doesn't make any difference for just one level, and you have a point. No other rare class has 5 skill on any weapon, this was the only snowflake one that did, and this should bring them on par with Royal Guard and every other rare drifter class.
> 
> sentinel has a 5 in archery btw.

Being addressed in #736

**Pull request merged**
