### PR TITLE
A Less Evil PR (0 PQ Minimum For Most Combat Adventurer Roles, Important Town Roles)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
- Adds PQ minimum requirement of 0 to most adventurer combat classes and some additional important town roles (Queen, Captain, Veteran, Mayor, Templar, and Priest)
- Warrior is the only combat adventurer that can be played regardless of pq level
- PQ will now function as a reward in the drifter class rolling system. The pick probability is now the base pick chance, plus your PQ divided by 2, leading to a maximum of 50 additional pick probability.

## Why It's Good For The Game
- The 0 minimum PQ on most adventurer combat classes makes getting pq nuked more impactful, as a shoddy player can't just respawn as a rogue or assassin and go fragging
- The 0 minimum PQ on more important town roles means people who get nuked will be locked out of more roles, but new players are given the benefit of the doubt and not locked off from anything unless they fuck up
- Offers a reward to players with high pq, and an incentive to raise pq without outright locking any content off.

I'm sure this is not a perfect system, but it's a compromise that allows new players to engage with content and locks people who have earned negative pq out of more roles.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Make Templar a 50 PQ as well please, as I'm coding a silver longsword for them

**Comment by Grongoth** [comment]
good change. zased change.
zizo approves. i would also say templar should get a PQ requirement as well.

**Comment by Optimism333** [comment]
Dropped the requirements to 15 pq for rares, 30 for extremely rare one-slot roles

**Comment by sanshoom** [comment]
zased

**Comment by Optimism333** [comment]
> > Dropped the requirements to 15 pq for rares, 30 for extremely rare one-slot roles
> 
> Also, why are swordmasters classified as extremely rare but other race unique ones such as bladesinger and longbeard aren't?

Swordmasters are the only rare class that gets a "master" weapon skill

**Comment by sanshoom** [comment]
Why are you reverting the PQ back to 0?? this PR is gonna be useless now 😭 I understand vaquero being at 0, but.. longbeard? bladesinger? swordmaster? the heartfelt lord and hand?? Give them back their 15 PQ minimum, it genuinely is not hard to reach if you can actually roleplay properly.

BTW People can't actually play the crusader adventurer role, it's been disabled for months now (no clue why)

**Comment by Optimism333** [comment]
> Why are you reverting the PQ back to 0?? this PR is gonna be useless now 😭 I understand vaquero being at 0, but.. longbeard? bladesinger? swordmaster? the heartfelt lord and hand?? Give them back their 15 PQ minimum, it genuinely is not hard to reach if you can actually roleplay properly.
> 
> BTW People can't actually play the crusader adventurer role, it's been disabled for months now (no clue why)

After discussions with the other staff I came to the conclusion that given we're in a time period when we're trying to attract more new players, forcing them to meet a PQ ceiling in order to engage with content isn't fun.

Enforcing a strict minimum floor where all these roles get cut off if you fall below 0 PQ due to getting in trouble is more fair, and it gives new players the benefit of the doubt.

**Comment by BadAtThisGame302** [comment]
> > Why are you reverting the PQ back to 0?? this PR is gonna be useless now 😭 I understand vaquero being at 0, but.. longbeard? bladesinger? swordmaster? the heartfelt lord and hand?? Give them back their 15 PQ minimum, it genuinely is not hard to reach if you can actually roleplay properly.
> 
> > 
> 
> > BTW People can't actually play the crusader adventurer role, it's been disabled for months now (no clue why)
> 
> 
> 
> After discussions with the other staff and players I came to the conclusion that given we're in a time period when we're trying to attract more new players, forcing them to meet a PQ ceiling in order to engage with content is counterintuitive, and it's not really fun imo.
> 
> 
> 
> Enforcing a strict minimum floor where all these roles get cut off if you fall below 0 PQ is more fair, and it punishes problem players more severely while giving players who are just new the benefit of the doubt.

Adding a minimum of 0 sure, but not removing the slightly higher minimum of 2 (lol) for roles that can change rounds due to their strength or influence.

**Comment by Optimism333** [comment]
This pr still has some work that needs to be done. I'm going to experiment with implementing an idea that Dova suggested, making PQ serve as a variable that increases your chance to roll rare drifter classes.

I will try to get to it this week if I have time.

**Comment by 1N7Slayer** [comment]
its next week now king...

I would just set rare classes to 15 PQ. Player quality is just a metric for "how well you get along with others", rather than necessarily representative for anything else. Setting the more major responsibility roles at 10, and moderate responsibility at 5, would be just fine. Setting warrior/rogue/ranger/etc at 0 would be acceptable, too.

**Comment by Optimism333** [comment]
This pr should be finished. PQ will now function as a reward for rare class rolling.

The formula is the class' base pick rate (15 for example), with the player's pq added divided by 2. A player with maximum pq at 100 will have 50 higher pick rate on most rare classes... leading to a total of 65 pick rate chance for rare classes.

The number can continue to be adjusted as needed, but this pr is done for now.

**Review by ThePainkiller — APPROVED** [review]
We love Opti in this house

**Pull request merged**
