### PR TITLE
Murderwoods

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

At some point maneaters and mancatchers got yeeted from spawnpool in forest. Reenables this.

Mapgen edit so cant be localtested.

Also two latejoin adv spawn spots added to bog

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by AceVX** [comment]
Make murderwoods dangerous again oooraaah

**Review by Optimism333 — APPROVED** [review]
Bring murder back to the murderwoods...

**Review by ThePainkiller — APPROVED** [review]
Let's pray this makes the forests more dangerous like they used to be before open source

**Comment by NPC1314** [comment]
If it turns out to be poo we know which mapgen to edit now at least, could tweak it all sorts of ways I guess but we gotta start somewhere

**Comment by Zoeycore** [comment]
Could be fine with much lower spawnrates, but rn it feels quite bad.

The Murderwoods already has no reason to go there, outside of RP or spawning as Drifter. This change only amplifies that, and just makes RPing/PvPing in this zone pretty unbearable.

**Comment by ThePainkiller** [comment]
The murderwoods were never a good place to RP, historically, it's always been a place that you try to exit as fast as you can to reach town or you'll get mugged by bandits or kidnapped by vampires.
Do they spawn TOO often? If so we can adjust the numbers on a later PR but unfortunately this is something we cannot test on localtesting and only ever works on live.

**Pull request merged**
