### PR TITLE
Raytown/Roguetown Map Updates

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request

Updates and adds fun little goodies to Raytown.
BIG EDITS:
- Bathhouse
- Keep
- Church
- Merchant's House

EDITS NOT VISIBLE IN PICTURES
- The veteran now spawns in the garrison basement, and the dungeoneer spawns in the Keep
- Some clothing has been added to various closets, mostly in the farm
- Signs and doors have been marked as what they are, for the most part

[An Imgur album for the edits, since these files are all fucking massive despite me saving them as jpegs](https://imgur.com/a/9hEsIft)

## Why It's Good For The Game

Map changes good. Additions of newly-added QOL to old maps also good.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by bowlofcereal** [comment]
image

This doesn't make much sense. Why are you required to go through the private keep bath in order to get to the vault or the cells?

If we want the bath I recommend either expanding a spot for it to the south or finding a way to make a pathway that goes through there that isn't that obtrusive.

**Comment by AceVX** [comment]
I'm not sold on these changes tbh. Updating the map to reflect today is for sure needed but these rooms are same-y and just plain rectangular rooms.

**Comment by ThePainkiller** [comment]
I'm sure the butlers would appreciate a less "having to go all around a fence to fetch water for the kitchen" route, and one that also makes it easier for them to water plants with. Mayhaps a side door as well?

image

**Comment by lavillastrangiato** [comment]
@bowlofcereal come on bro
image

**Comment by lavillastrangiato** [comment]
Updates:
Stupid spot to put the well anyway. Shouldn't be gardening like crazy.
image
Statue :)
image

**Comment by NPC1314** [comment]
Two questions, whats the church changes?

And the vet, shouldnt they be spawning with the mayor and peasants? Also isnt Terminus Est the dungeoneers sword?

**Comment by bowlofcereal** [comment]
> @bowlofcereal come on bro image you even CUT OFF THE LOWER HALLWAY in your image

It seems completely counter-intuitive for the fastest route to the vault to be removed completely and force people who want to rush through it to go through the *private bath* to do so. It just seems like poor placement to me.

Regarding other things though, why is the *veteran* getting the Terminus Est, the Dungeoneer's sword? I don't know why he's spawning in the garrison basement, either. If anything he should spawn with the Mayor, which is probably something I should've rectified to bring in line with Dun changes myself when doing my overhaul mapping.

I also don't like how the Keep has had its spawns removed from the Throne Room since we specifically moved spawns back to the Throne Room on Dun Manor to make it easier for round-start orders to be delivered...

image

I'd also like to know what this is. Is this just a free break-in entrance for bandits to metarush to get into the Keep? The Keep is supposed to be one of the most well-defended places on the map and yet this seems like it just.. lets people walk right in if they have a lockpick and a dream.

I'd also like to see the church changes as well as the bath-house basement on a personal side-note because they have not been shown in this PR. Where were the private baths moved too, since the stairs leading down in the main room are completely missing? Do the stairs that lead into the kitchen area lead down there now?

> I'm not sold on these changes tbh. Updating the map to reflect today is for sure needed but these rooms are same-y and just plain rectangular rooms.
> 
> They look like the cookie cutter colonist rooms I'd build in rimworld lol

I also agree with this. The bath-house upstairs is just a bunch of big rectangle rooms. Doesn't really feel lived-in either.

I don't mean to nitpick or anything, but considering I am currently the only one up until this point that has been maintaining and updating Raytown to keep it up-to-date, I feel opinionated on changes made to it.

**Comment by ThePainkiller** [comment]
You could put it on the middle so you have one extra place to plant crops :3

image

**Comment by lavillastrangiato** [comment]
@ThePainkiller it wasn't perfectly centered so i didn't do it originally but trve

**Comment by lavillastrangiato** [comment]
~New~ updates:
- Back alley to the bathhouse
- Steward gets a sick fur rug
- Dust and other ensoulification
- Deleted Terminus from the veteran's room, oops.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
