### PR TITLE
Dark Elf Jobs, once more from the top

### PR DESCRIPTION
**Pull request by Plaguewalker**
## About The Pull Request
I readjusted the original pull #95 to avoid the listing nonsense, along with using a more up to date files. That one was my own mistake

The jobs are still the same as listed in the original PR barring any tiefling edits, included as well are archivist and weaponsmith as I missed them originally.

## Pre-Merge Checklist
- [X] You tested this on a local server.
- [x] This code did not runtime during testing.
- [X] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I personally don't think drow integration in the Mage or Archivist is a good idea, the smiths and the other towner roles I suppose are peasants so it doesn't matter at the end of the day.

**Comment by SELFHELL** [comment]
tbh adding drow to a bunch of stuff kinda ruins the whole... ostracized from most society bit

**Comment by Plaguewalker** [comment]
> tbh adding drow to a bunch of stuff kinda ruins the whole... ostracized from most society bit

A majority of the roles added to em are low tier things barring at most acolyte and court, but as well the same could be said for tieflings with their pariah status but they have more roles than drow at their disposal.

**Comment by Plaguewalker** [comment]
> no noble or keep roles. otherwise its fine.

If I make a counter point drow have dungoneer already which by extension is classed as a keep role

**Comment by guayitoo** [comment]
> > no noble or keep roles. otherwise its fine.
> 
> If I may make a counter point drow have dungoneer already which by extension is classed as a keep role along with merchant being a noble role.

I think the idea of a Drow being put in a position of servitude which is usually looked down upon fits their oppressed state.

Having them be a guard or royal guard & otherwise part of the protection wouldn't make much sense.

**Comment by BadAtThisGame302** [comment]
> > no noble or keep roles. otherwise its fine.
> 
> 
> 
> If I may make a counter point drow have dungoneer already which by extension is classed as a keep role along with merchant being a noble role.

The Merchant is a person sent from the Guild to represent them, they have some leniency.

And I personally made the Drow be Dungeoneers simply because of their nature or therein perceived as such (sadists, torturers, etc.)

Though they rule both the garrison and keep dungeons I suppose they like every other guard have a manor key.

**Comment by Optimism333** [comment]
> > no noble or keep roles. otherwise its fine.
> 
> If I may make a counter point drow have dungoneer already which by extension is classed as a keep role along with merchant being a noble role.

That's plenty already, given the other prs that have opened up more roles for them. With this pr on top of that, they'll have access to most common town roles, dungeoneer, and merchant. 

Other roles more involved with the keep and the King's direct circle staying locked off is fine.

**Comment by Plaguewalker** [comment]
> > > no noble or keep roles. otherwise its fine.
> > 
> > 
> > If I may make a counter point drow have dungoneer already which by extension is classed as a keep role along with merchant being a noble role.
> 
> That's plenty already, given the other prs that have opened up more roles for them. With this pr on top of that, they'll have access to most common town roles, dungeoneer, and merchant.
> 
> Other roles more involved with the keep and the King's direct circle staying locked off is fine.

I'm

**Comment by Plaguewalker** [comment]
Redoing this once more because my methods for it are clunky

**Pull request closed without merging**
