### PR TITLE
Misc Antag Fixes

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

* Deadites loses ability to understand what people say (except Hellspeak..? Maytbe?)

* Deadites lose the ability to use the various verbal emotes like moan and whistle etc because its silly
obv means they cant talk either. Theyll do zombie moan and theyll like it.

* Fixes issues with the species selector for VL, probably. Just brute forces it to select a new human subrace called vampire, worked fine for aasimar and tiefs in testing. B-but my elf VL well I think its more important to not have it break.
If you wanna add back elf VL without breaking stuff be my guest.

* Fixes VL silver curse not going away as it should, probably. Likely cause is the new subtype of silver curse, code doesnt handle subtypes well, just changed it to the old working one, could work.

* Fixes VL night vision not working with regen

* Removes IAA and Clown Ops

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
> don’t deadites use moan for their zombie groans?

nah they use zombie moan, an special emote I made for them, they just output "x moans" but its not a *moan emote.
This is to stop sexy moan zombs now and forever, amongst other abuses (theres plenty )

**Comment by 1N7Slayer** [comment]
CLOWN OPS IS GONE??? FUCK ITS OVER

**Comment by BadAtThisGame302** [comment]
This breaks VL's and they aren't pale anymore.

**Review by Optimism333 — COMMENTED** [review]
Sounds like it might need a bit more tweaking on the vampire side before a proper merge.

**Comment by NPC1314** [comment]
Biting seems unlkely, its more probably its due to the wound PR, this doesnt touch any of that.
Paleness though yeah, Ill take a look.

**Review by Optimism333 — APPROVED** [review]

**Pull request merged**
