### PR TITLE
Roguetown Map Major Changes Pt1 (Village/Basin, Inner Town, etc)

### PR DESCRIPTION
**Pull request by bowlofcereal**
## About The Pull Request

**_!!THIS PR IS OPEN FOR DISCUSSION!!_**

Overhauls multiple parts of Roguetown.dmm to bring it more up to speed with other modern maps as well as tweaks and adds a few personal flavor picks.

I want all of our maps to stay up-to-date and the best versions they can possibly be, and I've made my intentions known in previous PRs that I am going to start doing this.

_**I will be adding pictures as I work on different parts of the map to save myself the headache of trying to do it all at once, so they'll be placed in the comments below.**_

## Why It's Good For The Game

Roguetown.dmm gets very little love in terms of support and maintenance and I intend to rectify that whenever I have time to do edits. This is the second part of a decent chunk of edits I will be doing, which will hopefully cook up into something good at the very end.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by bowlofcereal** [comment]
Alright, so I'm pretty much done doing my edits to the village area. I've mostly moved things around, made things tidier and added some more homes on the outskirts area of town on the south. 

I'll be posting my inner city changes once I'm fully done with them before moving on to the western side of the basin.

--------------------------------------------------------------------------------------------------------------------------------------------

The village area, Z:2
image

The village area, Z:3
image

The village area, Z:4
image

Z:1, one of the townhouses has a basement
image

**Comment by bowlofcereal** [comment]
Okay, should be mostly done with most of the major inner changes for this part. The whole guildhall update and steward office move will be done in a different PR to preserve my sanity. The last part will be adding a few flavor things like buildings or rundown areas to the western side of the basin, and maybe reorganize or just wipe the old merc camp out.

-----------------------------------------------

New stalls (The steward has the keys for the stalls)
image

Townhouse replacing old stalls
image
Upper floor
image

Reorganized parts of the church (ill add the bedsheets after, just noticed lol)
image

Reorganized the attic area to be storage with a little sneaky room for the puritan/inquisitor to live in, going with the "moved in and refurbished the attic" style here
image

Temporary guildhall placement until I do the big overhaul in PT2, this will have to do for now
image

Extra sewage access area
image
The lower area of the access
image

Almost forgot! I changed up the bottom floor of the chapel as well. The puddle room has been retrofitted into a basement storage, while the room with the thresher has been turned into a room for spare amulets (with space for more to be added if they ever get sprited for the rest of the pantheon). The stairwell in the confession area leads downwards..
image
... into a side passage into the crypts
image

------------------------

That's all for the inner section of Rockhill for now. I'll begin working on the western section soon, if not right after I post this comment.

Suggestions are welcome! You can either ping me in my map thread on the discord or just in the mapping channel directly, I don't really care. A lot of things i've done here were all suggestions that i've modified for my own interest.

**Comment by bowlofcereal** [comment]
And yes all of the places are properly roofed and zoned correctly. Sorry if I didn't make that clear in the last post.

**Comment by bowlofcereal** [comment]
Didn't do much for the western side, since I would rather keep this space empty since from what i've seen people like to build over here, and I don't want to encroach on people's freedoms to make their own homes if they desire. This will stay relatively empty save for the guard tower i've placed to keep an eye on the most travelled path to-and-from the town.

The land
image

Tower
image
image

Since I don't have much else I really intend to do in this part of the overhaul i'll be marking this as ready for a review and do a localtest to ensure it is functional.

Suggestions are still open for anyone who thinks I should change anything up.

**Comment by AceVX** [comment]
Good stuff. I always thought the Stalls being near the merchant just made more sense for a market center. Looks great.

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
