### PR TITLE
Porting Ratwood's custom descriptions 2, electric boogaloo

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request

A big ol' port of Ratwood Vale's custom descriptions/flavour text stuff. Basically, it gives you a list of traits to select from to MadLibs a description on your character on examine.

Support for traits like heterochromia and body markings have been added, but are not fully implemented. The menu exists and needs to be uncommented in preferences.dm.

image
image

## Why It's Good For The Game

More flavour text, more RP options, more interactivity with the game world.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
Very ambitious, considered focusing on just the descriptors and leave out all the other stuff, gradients, sprite accessories and such?

**Review by NPC1314 — APPROVED** [review]
Lets see how it works

**Comment by Optimism333** [comment]
Was on the fence about porting this at first, but you did a good job sanitizing it. And I actually like how the descriptor inputs turned out!

Screenshot (261)

**Comment by NPC1314** [comment]
Was missing proper credits, the feature was made by Azarak on https://github.com/Rotwood-Vale/Ratwood-Keep/pull/491

**Pull request merged**
