### PR TITLE
Praying Overhaul

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About The Pull Request

Depending on your patron you'll now have different prayer requirements.
Followers of the Ten need to pray near a psycross.
Followers of inhumen patron need to pray outside of the view of the Gods (psycrosses).
Followers of the Forgotten God need to pray in a church like normal. (Get it? Because Psydon is old? So he uses old mechanics? Okay, well at least *I* thought I was clever with that one...)

## Why It's Good For The Game

Praying code is dumb. I'll probably fix more of it.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Would be good to add fluff `to_chat` prompts for people that attempt to pray in situations they cannot. Stuff like:

- _"I need a nearby psycross for my prayers to be heard."_
- _"That accursed cross won't let me commune with the Forbidden One!"_
- "I can only pray within the confines of a holy place."

Having `return`s that do nothing but you get no message why what you tried failed makes it unintuitive for the future

**Comment by Stutternov** [comment]
Seems Feedback was listened to, marking for test merge. I'm iffy on it but I think it's a good idea so let's give it a whirl.

**Comment by Mogelix** [comment]
image
For the sake of fluff, this should really be changed from psycross to pancross for worshippers of the divine pantheon. That's what the actual cross is called ICly and not in code.
image
If we go forward with this, someone really has to consider the effects on the Church. We are out here FIENDING for people to even interact with the church at all and this cross in the town square makes it possible for praying people to just ignore it entirely.

The 'Forgotten God'-worshippers needing to pray in the Church I still believe is really nonsense. That is not their church. The roleplay around Forgotten God-worship should be that it is a foreign religion and they don't feel at home in the local church.

I think Forgotten God praying should only require a psycross amulet on their person, and pantheon worshippers should be also allowed to worship anywhere _if_ they have an amulet. This way, god-botherers (people who start with amulets, devout followers) can pray at the church or using their amulet but everyone who doesn't keep an amulet on them at all times will go to church to pray.

Sorry for the mountain of critique, I hope it comes across constructive, I think this is a positive change just maybe in the wrong direction.

**Comment by NPC1314** [comment]
Mogelix raises some good points not gonna lie

**Comment by casualspacestation14enjoyer** [comment]
> image For the sake of fluff, this should really be changed from psycross to pancross for worshippers of the divine pantheon. That's what the actual cross is called ICly and not in code. image If we go forward with this, someone really has to consider the effects on the Church. We are out here FIENDING for people to even interact with the church at all and this cross in the town square makes it possible for praying people to just ignore it entirely. This might be a good or a bad thing but I fear for the worst. At the very least, new pancrosses should be constructable but only spawn within the Church at roundstart.
> 
> The 'Forgotten God'-worshippers needing to pray in the Church I still believe is really nonsense. That is not their church. The roleplay around Forgotten God-worship should be that it is a foreign religion and they don't feel at home in the local church. I think Forgotten God praying should only require a psycross amulet on their person.
> 
> Pantheon worshippers should be also allowed to worship anywhere _if_ they have an amulet of their patron. This way, god-botherers (people who start with amulets, devout followers) can pray at the church or using their amulet but everyone who doesn't keep an amulet on them at all times will go to church to pray.
> 
> Sorry for the mountain of critique, I hope it comes across constructive, I think this is a positive change just maybe in the wrong direction.

Devout Followers for some fucking reason no longer spawn with the amulet of their patron.

**Comment by casualspacestation14enjoyer** [comment]
Anyway... the feedback from Mogelix has been implemented (in some way).

Psydon worshippers need a psycross on their neck to pray, pantheon worshippers need to be in the church OR near a psycross to pray.

Zizoids are the same.
That is all.

**Comment by NPC1314** [comment]
Seems its about time to fullmerge this, checking back in 12 hours or something to see if theres any developments and if not its time to smash butan.

**Review by Optimism333 — APPROVED** [review]
I think we can try this tentatively. If the cross at the execution platform ends up being an issue, we can remove it later.

Overall I think the added flexibility to when and how you can give prayer is good.

**Review by ThePainkiller — APPROVED** [review]
Changes addressed, people should go to church more often.

**Pull request merged**
