### PR TITLE
[MAP] Reorganizes the Church

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request

- Flips the Graveyard and the Inquisitor Cell positioning
- Moves kitchen and "sick bay" to the other side of the church (gives them more room too)
- Removes Catholic confessional (no one used it)

## Why It's Good For The Game

- Makes the Graveyard more central (hopefully leading to it being more relevant and used)
- Moves the Inquisitor Cells to the far side of the church (no more hearing screaming, shitting, and pissing from the middle of the town)
- Increases the sickbay size as well as the kitchen size

**PICS**
image
image

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I've seen the confessional be used. Why remove it?

**Comment by sanshoom** [comment]
This shit feels awkward I won't lie, but it's fine. Re-add the confessional though.

**Comment by SaintBurgher** [comment]
> I've seen the confessional be used. Why remove it?



> This shit feels awkward I won't lie, but it's fine. Re-add the confessional though.

Here, I made it functional even.

image

**Review by Optimism333 — COMMENTED** [review]
Get your feedback in, if you have any protests to make.

Otherwise I will likely move to approve this sooner rather than later. Most of the changes look good, particularly the expansion of the church kitchen, and the confessional has been returned, which addressed the most significant complaint.

**Review by Optimism333 — APPROVED** [review]
Let's move this along...

**Pull request merged**
