### PR TITLE
Re-adds majority of Merchant roundstart items from Roguetown to Dakkatown

### PR DESCRIPTION
**Pull request by bowlofcereal**
## About The Pull Request

Adds back most of the items that the Merchant lost from the mapchange to Dakkatown that they are not able to get naturally (such as the cloaks)

## Why It's Good For The Game

The Merchant got shafted pretty badly with the map change-- I know that these things were added to the Roguetown merchant while Dakka was in development but I still think Merchant could definitely use the help. It's not good when the server has to BEG people to play Merchant in order for the game to start because people find it so boring. I hope this on top of the future additions to the GOLDFACE will help re-incentivize some interest in retaining peoples interest so we aren't stuck in the lobby-loop for 10 minutes each roundstart.

Bottom Floor
merchant1

Top Floor
merchant2

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by DAKKA-WAAAGH** [comment]
The commentary on the merchant role isn't necessary, but yeah -- things changed quickly while the map was in development!

I believe these changes will help people enjoy the role more, so they're acceptable changes to me.

**Comment by Stutternov** [comment]
Recent map changes on the map, update the PR for review.

**Comment by bowlofcereal** [comment]
@Stutternov conflict should be dealt with

**Comment by Stutternov** [comment]
zased?

going to merge once compiles

**Pull request merged**
