### PR TITLE
Removes drifters way better than the last PR

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Nukes the drifter queue, brings back adventurers and pilgrims + moves Assassin to pilgrim because examining a noble and seeing "Humen Adventurer" when noble is on pilgrim is a dead giveaway.

Adventurers have 10 slots
Pilgrims have unlimited.

## Why It's Good For The Game

Open Discord.
See hate on drifters.
Cry.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Optimism333** [comment]
Adventurers show up twice on the role selection screen. Not really a serious issue, but a bit of an eyesore:

Screenshot (445)

**Comment by BadAtThisGame302** [comment]
> Adventurers show up twice on the role selection screen. Not really a serious issue, but a bit of an eyesore:
> 
> Screenshot (445)

Check files changed honey

**Comment by ThePainkiller** [comment]
# BASED

Have the assassin disguises been properly affected so they don't get meta'd easily?

**Comment by BadAtThisGame302** [comment]
> # BASED
> Have the assassin disguises been properly affected so they don't get meta'd easily?

Yes, Assassin was relegated to pilgrim so his disguises work.

**Comment by bowlofcereal** [comment]
he-is

**Review by NPC1314 — APPROVED** [review]
Now just to fix medical

**Pull request merged**
