### PR TITLE
Swaps the Steward and the Garrison Buildings + Adds Royal Stable

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request

- Moves the Garrison building + Armory into town (in the old Steward's building)
- Moves the Steward's and warehouse into the old Garrison building (gives them their own entrances)
- Adds the Royal Stables

## Why It's Good For The Game
This has been long talked about but no one has done it. After discussing with Guayo and the Nobles we decided that this makes sense:

- The Steward's office is woefully unprotected out in the center of the town; their is a roundstart ritual of going there, locking things down, and grabbing the keys (hopefully this should stop that)
- There is still a meister in the same spot; however, the Steward has a lever to close it off and make you come to their office if they feel the need to
- The Garrison is often an unwelcome presence that swarms the royals within the manor; this gives them their own building where they can do what they need to do while also still allowing them to enter the walls/manor from their usual way
- The king can PERSONALLY choose who he wants to guard the keep and these guards can then stay within the wall lodging (it has not been changed).
- The royal stables are added for fluff at the request of Guayo; it comes with some lodging for that drifter you hire to run it too!

**GARRISON**
Z1
image
Z2
image
Z3
image

**STEWARD'S**
Z1
image
Z2
image
Z3
image

**STABLES**
Z2
image
Z3
image

**TOWN MEISTER/STOCKLOAD**
image

**ARMORY -> ARENA**
image

**MANOR FORTIFICATION**
Z4
68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f3830313237333533342f33313533313538303433392f6d2f5f6d6170735f6d61705f66696c65735f64756e5f6d616e6f725f

**NEW OFFICES**
image

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
I will wait until I see the maps for my final verdict (esp. as this is a draft) but my instincts tell me it's going to be abysmal dogshit to have a bank account or stockpile locked between the keep gate.

**Comment by SaintBurgher** [comment]
> I will wait until I see the maps for my final verdict (esp. as this is a draft) but my instincts tell me it's going to be abysmal dogshit to have a bank account or stockpile locked between the keep gate.

lemme cook.......

**Comment by ThePainkiller** [comment]
Not only that, but literally moving the armory OUTSIDE of the keep??????? Saint, PLEASE, you were doing really good map changes and now _this_ 💀

**Comment by SaintBurgher** [comment]
> Not only that, but literally moving the armory OUTSIDE of the keep??????? Saint, PLEASE, you were doing really good map changes and now _this_ 💀

The Garrison was outside the Keep in the original map. Many preferred it that way and asked me to PR this.

**Comment by Mogelix** [comment]
Every other map is like this. Raytown, Dakkatown, they have all had an external garrison house. My only wish is that the town meister is kept approximately where it is in the middle of the town and not attached to the keep.

**Comment by Cre77** [comment]
not sure if i like the stewardry being so safe and sheltered now, but the garrison change is 100 - both in terms of placing guards closer to their "objective", and making the manor a less secure, traffic-heavy area

**Comment by bowlofcereal** [comment]
image

Uhh...

**Comment by SaintBurgher** [comment]
> image
> 
> Uhh...

Read the PR in it's entirety challenge GO!

**Comment by SaintBurgher** [comment]
I should note:

The Garrison still has a presence within the Keep through the gatehouse. Guards can still enter and stay here if they wish to guard the manor.

image

**Comment by bowlofcereal** [comment]
> > Uhh...
> 
> Read the PR in it's entirety challenge GO! image 376391527-50f8714c-5048-4481-af9f-29df764650f3

:(

**Comment by BadAtThisGame302** [comment]
Should remove their manor key and let them only access their walls, tis peak.

**Review by Optimism333 — COMMENTED** [review]
I'll give this a lookover and put it in tomorrow after any finishing touches are done.

I've heard some disgruntled voices, but not too many. Can always make more changes down the line.

**Comment by NPC1314** [comment]
Its too expansive to theorycraft pros and cons, its a good enough concept to get a testmerge so we know whats what.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
