### PR TITLE
Adds a mechanic for jobs to have a chance to spawn as nobility, implements it on various roles.

### PR DESCRIPTION
**Pull request by iloveyoulots**
## About The Pull Request

-Adds a random chance for roles to receive the noble fate.
**-'Noble' status for the following roles has been adjusted:**

- Barkeep (0% > 20%)
- Confessor (0% > 5%)
- Squire (0% > 5%)
- Sheriff (100% > 75%)
- Royal Guard (0% > 45%)
- Merchant (100% > 50%)
- Feldsher (100% > 80%)

## Why It's Good For The Game

The status of certain roles as 'noble' was contended and often ignored.  This is the case due to the overabundance of nobility outside of the Garrison, and lack of nobility within it. With the garrison being stocked with noblemen, they should reasonably act in a way protective of their fellow nobles. 

This adds historical accuracy to the game, alongside giving people more roleplay opportunities.

Also, with the 'chance' to be a noble, a creative roleplayer who was caught by the guards can now claim that they are a noble and receive lighter punishment, with the players having a harder time metagaming whether or not they are lying. 

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
# Big, rotund, and massive **NO**.

Not only do we already have a Noble towner position, and enough nobility, it makes absolutely zero sense for people like a **Bartender** to be nobility, far worse than it'd have a higher chance than a SQUIRE which, by definition of the english meaning of that word, IS SUPPOSED to be nobility, or the son of a noble, training under a knight.

RNG would mean that players who play a static will sometimes be a noble and sometimes not, which feels like shit for those with a grounded past. On the other hand, rolling noble will most certainly lead to people to abuse and flaunt their status as if they were on equal parts as the Prince/Princess roles.

Lastly, this being approved would also influx more **(wrongly)** pitched ideas that, since they have noble trait, they should gain free points on sword skill and riding skill (a thing I'm having to tolerate from Merchant players after the Malum update is that they want sword skills comparable to combat pilgrims)

The only thing I agree with this PR is giving a `prob()` on Squire being a noble, if not outright just giving the trait to them. Other than that, this has my full veto.

**Comment by Mogelix** [comment]
On one hand, the randomness is an interesting idea that could be a boon to rounds. If noble status was somehow able to be recognized and meaningful, it would be cool for the 'power dynamic' of the town to vary round-round. On the other hand, as things stand noble status rarely matters much: guards are rarely (consciously) acting differently to commoners and nobles.

**Comment by BadAtThisGame302** [comment]
I prefer Squire and RG getting a chance to be nobles but that's it, no confessor, no barkeep, no removing the Captain's or Merchant's chance, maybe the Feldsher's but other than that with some changes the PR is fine.

**Comment by ThePainkiller** [comment]
> Towners have 5 slots, the Barkeep has 1. If your solution is not to remove Towner's ability to spawn as noble, you should not critique me for adding it to Barkeep, who is a man that in-lore clearly owns land.

I was referring to the Noble job. The job called "Noble", which is among the towner category of pilgrim roles. A job called "Noble". Which spawns with noble trait, a rich pouch and a gilded sword. **Noble.** Not _"towners who are noble"_. [This](https://github.com/Darkrp-community/OpenKeep/blob/main/code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/noble.dm) kind of noble. We don't have those. I don't even know which "land" you refer to belongs to the barkeep for all of the keep and its surrounding areas are exclusive property of the King.

> RNG is already present for various other aspects of character creation such as antagonist status, this point is largely made irrelevant by that fact. If you would like, feel free to code a toggle for this feature, so people can reduce their chances to 0% if they do not want to be a noble.

Your counterpoint goes moot the moment you realize you **have** to sign up as antag for it to even happen, and if you do, it's either because the person does not play a static, or they only play exclusively antag. This is a coinflip as a chance for literal character background made up on the spot.
 
> You say this like it is a bad thing.

Because it **is** a bad thing. We have no in-game capability of nobility being discerned in any way beyond how they dress, and even so, some forego their entire attire as heirs sometimes. **You can't check other people's traits.** People would either be bluffing and lying or outright being ignored of their noble status.
 
> This is the intent, it will lead to a distinction between the social castes. Guards will understand that the King's family is quite obviously above a minor noble, and as such would always treat them with greater authority. This is a basic roleplaying expectation anyone playing an important role like guard should grasp.

Again, **no in-game way to tell who has the noble trait or not**. Even if you spawned them with like a unique necklace or ring to signify status, my answer would still be no. This would render the Noble role moot, which is intended exclusively for nobility RP (diplomatic visits, strengthen relationships, marry to a prince/princess, become the new queen to depose the actual because she's infertile, etc)

> The conflict generated is meant to be interpersonal, for people who enjoy being 'snooty' as a minor noble, flaunting the small difference in status they have. It will also allow cunning men who already hold positions of minor authority to rise to the throne in a time of crisis, as they will have a more legitimate claim with nobility applied.

We all know in practicality this will not play out at all like this on a normal round. The Bartender would have no proof that he's noble, and why would a noble be working as a fucking food server is beyond me. All it requires is talking things out and making up your background verbally, while not using it to try and wave authority or nepotism otherwise people will most likely laugh at you and ignore the ramblings of someone who screams "I. AM. A NOBLE! I AM A NOBLE!"

**Comment by Mojamble** [comment]
Nope. Nope nope nope. Do not. Bad.

**Comment by lavillastrangiato** [comment]
Not really a fan mostly because I enjoy a consistent status on my statics (I know, what a fuckin' weirdo). I think you have a good point about a shifting power dynamic but I think there are different ways to create a shifting power dynamic in the roleplay that could come from more long-term, well, roleplay.

**Comment by 1N7Slayer** [comment]
hard no. enforced roleplay/fluff randomness is not good, bro. more excusable in the format we already possess for mechanical stat variance, but having roleplay variance for nobility status would be ridiculous. how would anyone be able to tell, even, especially considering that people EXPECT the feldsher, out of character, to be a dedicated noble whom you must show respect for?

20% chance they're just a bumfuck tradesman? that'd be absurd. most of what i feel has been covered by painkiller already, so seriously, i stand in opposition to this PR as it stands

**Comment by NanakoAC** [comment]
interesting viewpoints here, i just wanna add my two cents:

Not everyone, i might even say not most people, are capable of easily adapting on the fly to new roleplay conditions. Its common to have a character planned in advance, and i think having a key detail of your character randomised like this is sketchy

Nobles also do seem to be just better in many ways and thats a bit of a problem too. That seems to be the main reason you want to make it random. If people could just choose to be a noble, they always would be, and we'd end up with a town full of nobles and no peasants

I don't think randomisation is the best way to do this, I'd venture one of two alternative possibilities:

1. A whitelist. Only let people play noble if they've proven themselves to be competent roleplayers, and picking it would probably come with extra expectations on player conduct. I've played on servers in the past where heads of staff on a space station were whitelisted, and it had good positive effects. Heads of staff came with extra expectations, obviously like being required to be a leader, but also a mentor, to teach other people in their domain how to do things.  They were held more stringently to the rules, and given less leeway, expected to set a good example for other players

2. Mechanical downsides. Perhaps being a noble means you have to earn and pay more taxes, or have a lot more demands and expectations on your time. Enough that people would voluntarily choose not-noble quite often to get a break from it

**Comment by Stutternov** [comment]
devs that are active didn't seem onboard with it, general feedback seems to be negative. i gave my opinion myself on this during pr's making that i actually felt there are too many nobility/nobility aligned roles (not slots, but roles themselves).

seems at least some people agree with that notion, or at least don't wish to expand it more. so - going to be declining based on dev reviews + community feedback given so far. 

(plus the pr is still conflicting..)

**Pull request closed without merging**
