### PR TITLE
FAITHENING: 1

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

Implements devotion limits to the following jobs:
CLERIC
PALADIN
TEMPLAR

Removes the Eorascurse spell
Replaces it with a better one.

Couple other misc changes

Credit to the now defunct Blackstone for the devotion code rewrite.

## Why It's Good For The Game

At the moment, Clerics and Paladins are OBJECTIVE upgrades to acolytes/priests; having the ability to use ALL the same spells while running around with plate armor and maces/swords. This fixes that issue by capping their devotion/progression.

Giving Templar Spells: Always planned by me, wanted to do it in this PR so that they wouldn't be acolyte+ for a week or two

Eora Spell Rework: Eora's Curse was lazy and I made it last minute, this is slightly higher effort.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Why would eora long-range poison you with LETHAL, UNFIGHTABLE amounts of poison? Anyone not carrying a waterskin is literally dead in seconds with that much berry poison

Also I don't believe that:
1. these changes will balance church classes on the right direction
2. this improves spell-assigning code in any way, it just ain't as modular and feels like a salt nerf to Clerics

**Comment by SELFHELL** [comment]
Already addressed these points on discord, but to restate

Limiting the Spells of Armored/Combat roles gives more importance to Acolytes/Priest, since random drifters wont be an objective upgrade anymore.

The Eora Curse was intented to be used as a PUNISHMENT, but the buffs associated with the drunk/high status effects lead to it being used exclusively for buffing. Adding poison ensures that its a proper curse.

**Comment by SELFHELL** [comment]
Should be good to merge at this point

**Comment by Optimism333** [comment]
What devotion spells will clerics, paladins, and templars be able to use? Will it only be the first tier spell for all of them?

**Ex:** lesser miracle for Astra

**Comment by NPC1314** [comment]
Overall seems like sound concept but PR description does lack some details on the caps and what spells the classes get exactly so a summary would be nice, thats the very details thats the centre of the PR but its lacking in the overview.
Testmerge IMO but the summary is needed.

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
