### PR TITLE
Turns treestumps into tables

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

Huh? Why, I hear you ask.

* Because Making tables in the forest so you can do tablecraft stuff is kinda silly. Repairing leather armor should be more about sewing or needles or such, than grinding carpentr y to build a table.
* Because I used treestumps as tables before (admittedly chainsawed but hey)
* Because also allows seeing people on the other side (and throw stuff at them or shoot them)

Also fixes the annoying displacement of sprite and move block, I truly despise floating sprites of any stripe, but move blockers offset is the worst.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
ngl based dendorite buff

**Comment by assortedbeads** [comment]
🧎‍♀️🧎‍♀️🧎‍♀️🧎‍♀️🧎‍♀️ I KNEEL

**Review by ThePainkiller — APPROVED** [review]
I feel like the ancient log structure shouldn't have been a table (could be more of a chair) but an overall well received PR.

**Comment by NPC1314** [comment]
Not a bad idea!

**Pull request merged**
