### PR TITLE
Assassin/hunted

### PR DESCRIPTION
**Pull request by DovaKitty**
## About The Pull Request
* Reworks Assassin to be a proper antagonist, with the goal of hunting down and trapping the souls of their targets in the name of Graggar.
* Assassins now wear the guise of a non-combat migrant rather than having static gear. They can be disguised as fishers, miners, woodcutters, hunters or nobles.
* The Assassin's belt can hold two normal sized items instead of three small ones, and at roundstart holds their new dagger and a 1u vial of lethal poison.
* Adds a 'Hunted' vice, which makes you a target for assassins, and uneasy around characters in masks. Danger is around every corner.
* Assassins have a verb in their memory tab that gives them a list of all those with the Hunted vice.
* Adds the profane dagger, a dagger unique to the assassin's work.
* The profane dagger speaks through the souls of long-dead victims. Non-assassins find the voices unsettling. The dagger knows its targets, and will let the assassin know who they are, even if the target is hidden by a disguise.
* The profane dagger has the ability to trap souls of those marked for death by the Hunted vice. Stabbing someone targeted while they are in crit or dead will activate the magic. Instead of going to the underworld or becoming free spirits, they are locked within its grasp.
* Trapping a soul earns the assassin a triumph, repairs the dagger and resharpens it (imagine trying to get a blacksmith to repair your cult dagger).
* Trapped souls can see in the dark and examine as ghosts can. They can speak through the dagger, to its wielder and to any other trapped spirits. They can also go back to the lobby by spending one triumph.
* The profane dagger does more damage than other daggers, but still significantly less than two handed weapons.
* Holy servants of Necra can destroy profane daggers using their rites. Doing so frees all the souls trapped within, sending them to the lobby. Every soul saved this way earns the Necrite a triumph.
* Assassin is no longer a random chance to roll, as they are integral to making sure that the 'Hunted' vice is not overpowered. Assassin has also received small buff to stats to make up for the loss of roundstart armor. 

## Why It's Good For The Game
The PR reworks assassin from a renamed mercenary into a properly interesting class that creates conflict for the round.

This PR has aspects that will need to be tested ingame through testmerging and feedback. I have tested it as much as I am able on a localhost, but some mechanics require other players to function. In the future there are mechanics I would like to add to Assassin, such as making characters for death in-round and more varied gear.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
This will certainly require a testmerge to check the soul binding qualities of the dagger, if it stores properly souls, and if they can talk (and be heard by others, or just the assassin)
The damage values on the dagger are fine and I'm ok with it being self repairing, it's an antag with a unique item and it should be a cut (heh) above the rest

**Comment by DovaKitty** [comment]
Screenshot 2024-07-14 170552
New profane dagger sprite by Dromkii.

**Comment by SaintBurgher** [comment]
If you are in the dagger at round-end you cannot access OOC. Also if you examine the assassin they are labeled as "Class-Pick" and not an actual class.

**Comment by Stutternov** [comment]
Going to be temp de-test merged due to conflicts with trait.dm. Malum PR also is modifying the same file, so take the down time to update.

Should be re-test merged later tomorrow (or today, depending on time) if Malum PR doesn't thrown errors anyway.

**Comment by DovaKitty** [comment]
> If you are in the dagger at round-end you cannot access OOC. Also if you examine the assassin they are labeled as "Class-Pick" and not an actual class.

I'll be fixing this in a follow-up PR once this is merged. Might be a little involved.

**Comment by Stutternov** [comment]
> > If you are in the dagger at round-end you cannot access OOC. Also if you examine the assassin they are labeled as "Class-Pick" and not an actual class.
> 
> I'll be fixing this in a follow-up PR once this is merged. Might be a little involved.

Good time to merge then.

**Pull request merged**
