### PR TITLE
Changes Steward's Clothes to use Kingdom's Colors

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request

- Stewards Tunic/Chemise now use Kingdom Primary Color
- Steward's Chaperon now uses Kingdom Secondary Color
- Chaperon lightened to look better with the color system

## Why It's Good For The Game
Some people were saying that their random colored clothing doesn't make much sense.  This brings them in line with other roles that wear the kingdom colors and also makes them easily distinguishable from Towner Nobles.

**PICS**
_Teal primary & Magenta Secondary_
image
image

**CHAPERON CHANGES**
image
image

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by SaintBurgher** [comment]
This is ready. Ignore the embarrassing amount of commits and the fact that I merge conflicted my own PR.

**Comment by SaintBurgher** [comment]
Should the shirt be primary and the hat be secondary?

**Comment by SaintBurgher** [comment]
Converting this to draft. I’m going to make the chaperon grayscale a bit better and switch the coloring of the shirts.

**Comment by NPC1314** [comment]
For gameplay reasons it might make some sense, perhaps, but the queen isnt forced to wear kingdom colored drsses, does the Hand? Guy is a noble, doing a civilian job, him wearing uniform is a little weird.

Butler got their colored vest, that works well mostly, maybe do the same and just do 1 piece of court color clothing instead of both head and suit?

Is all minor stuff but worth keeping in mind when toying with the setup, drip is more important for a non combat noble thant color coordination, but a compromise might be possible.

**Comment by BadAtThisGame302** [comment]
> For gameplay reasons it might make some sense, perhaps, but the queen isnt forced to wear kingdom colored drsses, does the Hand? Guy is a noble, doing a civilian job, him wearing uniform is a little weird.
> 
> 
> 
> Butler got their colored vest, that works well mostly, maybe do the same and just do 1 piece of court color clothing instead of both head and suit? (In effect, maybe just do color coordinated hat first?)
> 
> 
> 
> Like the screenshots in the old PR looked a lot cooler than these I think.
> 
> 
> 
> Is all minor stuff but worth keeping in mind when toying with the setup, drip is more important for a non combat noble thant color coordination, but a compromise might be possible.

Hand spawns with a shirt that changes color depending on lord colors. Steward spawned with a tabard that used to change color depending on lord colors. Guards, RGs, Captain, Butler/Maid. Court Mage and Queen are the only ones that don't change because one wears a padded dress that has 2 colors green and purple and would need sprite work to allow for lord color selection and the other is the Mage robe that could easily be changed to lord colors.

**Review by NPC1314 — APPROVED** [review]
lets do this then

**Pull request merged**
