### PR TITLE
Brand New Decorated Helmet Type And New Blackoak Armor Sprites

### PR DESCRIPTION
**Pull request by WWWWW-Git**
## About The Pull Request

Adds a new decorated helmet type, the Decorated Bascinet as well as two new decorations for all decorated helmets. Also resprites Blackoak armor to be more Elvish in appearance.

## Why It's Good For The Game

It is cool and adds more roleplaying possibilities. Also this is the last Armor PR im doing until Drom is done.

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
Well sized, well presented PR, like the pics. There is no issues in format or presentation, good work!

One thing is those decorated helmets, two things strike me looking at them, they look kind of high brow so to speak,
like the decoration is a bit high up
The second is saturation, they do have the same issue w slightly oversaturated colors on the decoration as your first batches had. Lemme explain
 
hatts
Left side I put some of the best hat sprites we got, the main thing I wanna point out is just the contrast/saturation. If you dont see anything, squint a little, you'll see the decor stuff stands out a bit more than it should.

Same with onmobs, you can see what I mean on this SS (I have no context to wtfs going on, the only other sprite with saturation issues in the SS tho is the moon gobbo, helmet should be
 more in line with the other clothes sprites anyways).
PROBLEM

You're obv working with overlays of the decorations copy pasting over various helmet sprites, I sugges making a copy of that overlay set and just tweak dwon saturation say 20% and up shading say 10% in photoshop or something and test how it looks, I suspect it will look very nice.

**Review by ThePainkiller — APPROVED** [review]

**Comment by NPC1314** [comment]
With the edits I think the sprites pass the bar, I was told it will be folded into #828  to avoid conflicts so recommend waiting on that, no objections on the contents.

**Comment by NPC1314** [comment]
Noticed theres a minor issue, you repathed the merc helmet and armor to the rare types, that are only meant for roles that doesn't always spawn, theyre too strong to use on regular mercenaries.

We are in the middle of restructuring the helmet and armor file anyways so I copied over the new item code stuff here and slotted it in for maximum efficiency.

Only thing not ported are the sprites and the crafting recipes, so while waiting for the queue to clear you can shave off the changes to code/modules/jobs/job_types/roguetown/other/merc_classes/blackoak.dm and code/modules/clothing/rogueclothes/armor.dm and code/modules/clothing/rogueclothes/hats.dm
ie keep the recipes and the sprites, rest is just a hindrance now.

They'll just cause you conflicts and all that stuff is already in the pipeline. If you need tips on how to do that very fast and easy let me know.

**Comment by NPC1314** [comment]
look maybe I could just add your stuff to the refactor this one time, your timing on this PR has been a bit unfortunate, mid refactor of the very files, big sprite update and backend code rework at the same time.

This way your stuff get in, drawback is people can't track your contribution correctly in GitHub, your call how you wanna proceed.
A couple sprite file conflicts isnt that big a deal, if you use export and branches you can sort this in ten minutes tops but if you dont know how it can be  a pain.

**Pull request closed without merging**
