### PR TITLE
Dark Elf Job Updates

### PR DESCRIPTION
**Pull request by Plaguewalker**
## About The Pull Request
It gives dark elves a long overdue update granting them a larger amount of roles upon round start, along with finally granting tieflings guard roles, along with updating minor town roles.

##Changes
Added Dark Elf to:
Cook
Butcher
soilson
barkeep
blacksmith
Prisoner
monk
Court mage 

EDIT: Removing tiefling
EDIT 2: Soilson is getting a buff too I guess.
## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Tiefling guard feels like it makes no sense, considering their pariah status
I like the dark elf choices, and I'm guessing the INT buff for male soilsons is due to crafting issues, but it should be worth mentioning on the PR so that people don't fault you for doing sneaky unrelated buffs.

**Comment by Optimism333** [comment]
Agree with the above. Not a fan of having tieflings in the guard. The dark elf changes look fine

**Comment by Plaguewalker** [comment]
> Tiefling guard feels like it makes no sense, considering their pariah status I like the dark elf choices, and I'm guessing the INT buff for male soilsons is due to crafting issues, but it should be worth mentioning on the PR so that people don't fault you for doing sneaky unrelated buffs.

I actually didn't touch the stats.

**Comment by Optimism333** [comment]
> > Tiefling guard feels like it makes no sense, considering their pariah status I like the dark elf choices, and I'm guessing the INT buff for male soilsons is due to crafting issues, but it should be worth mentioning on the PR so that people don't fault you for doing sneaky unrelated buffs.
> 
> I actually didn't touch the stats. I might've used a week or two older file so that ones on me if it changed the stats.



> > Tiefling guard feels like it makes no sense, considering their pariah status I like the dark elf choices, and I'm guessing the INT buff for male soilsons is due to crafting issues, but it should be worth mentioning on the PR so that people don't fault you for doing sneaky unrelated buffs.
> 
> I actually didn't touch the stats. I might've used a week or two older file so that ones on me if it changed the stats.

Seems something changed them, yeah.

image

**Comment by Plaguewalker** [comment]
> > > Tiefling guard feels like it makes no sense, considering their pariah status I like the dark elf choices, and I'm guessing the INT buff for male soilsons is due to crafting issues, but it should be worth mentioning on the PR so that people don't fault you for doing sneaky unrelated buffs.
> > 
> > 
> > I actually didn't touch the stats. I might've used a week or two older file so that ones on me if it changed the stats.
> 
> > > Tiefling guard feels like it makes no sense, considering their pariah status I like the dark elf choices, and I'm guessing the INT buff for male soilsons is due to crafting issues, but it should be worth mentioning on the PR so that people don't fault you for doing sneaky unrelated buffs.
> > 
> > 
> > I actually didn't touch the stats. I might've used a week or two older file so that ones on me if it changed the stats.
> 
> Seems something changed them, yeah.
> 
> image

That's genuinely new to me. All I did was add the race options to the roles, I'll double check things then and get a new main downloaded.

**Comment by Plaguewalker** [comment]
Yeah, turns out due to the older file still having the older stat allocation that's why it is the way it is.

**Comment by BadAtThisGame302** [comment]
Why are you reverting the changes I made in my PR and adding extra humen/elf and changing the order around.

Clearly you didn't update the master on your branch.

Humen
Elf
Half-Elf
Dwarf
Tiefling
Drow
Aasimar

**Comment by Plaguewalker** [comment]
> Why are you reverting the changes I made in my PR and adding extra humen/elf and changing the order around.
> 
> Clearly you didn't update the master on your branch.
> 
> Humen Elf Half-Elf Dwarf Tiefling Drow Aasimar
Because, I even said that the files were edited before the map update

**Pull request closed without merging**
