### PR TITLE
[MDB IGNORE] Fix a large number of code quality issues, update CI pipeline

### PR DESCRIPTION
**Pull request by noelle-lavenza**
## About The Pull Request
Fixes a bunch of runtimes and code quality issues found via CI and local testing. Also makes CI and unit tests actually work.

I'm probably going to split this up into a few smaller PRs, since some parts of this are riskier than others, and I can't possibly test every single thing fixed.

## Why It's Good For The Game
This will make sure stuff isn't broken by new PRs.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
I was going to review something for once and then I saw this and decided not to.

**Comment by 0nemore** [comment]
image
real.

**Comment by ThePainkiller** [comment]
> 
> 
> 

You're maintainer and this PR touches a lot of systems inherent to the game, so good luck herma! Make sure we don't get backdoored :)

**Comment by NPC1314** [comment]
Anything else getting split off? Its still a cool 3 million added files and 800K deletions, almost all is the switch to TGM for maps I take it.

Splitting off the map conversions and fixing of the mapgen to its own would be make it a bit more manageable, that could be tested in isolation from the other stuff.

**Comment by NPC1314** [comment]
First part successful, will be interesting to see where the numbers land once updated to main.

**Comment by NPC1314** [comment]
Local tested, compiled, no errors detected.
Ready to come out of draft?

**Review by hermaplusplus — APPROVED** [review]
Lots of awesome changes 👍

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
