### PR TITLE
Gives Feldsher a keyring with an additional manor key

### PR DESCRIPTION
**Pull request by saltprjak**
## About The Pull Request

Title. They now get access to the manor like a proper NOBLE, alongside their previous doctor key

## Why It's Good For The Game

They have a NOBLE trait, they have their own house, a bank account with phat stacks, and they're the only surgeon in the the entire town - they shouldn't be banging on the door of their own benefactor to answer a house call

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Merchant and Niteman looking through the Keep barred windoor in tears.

**Comment by Cre77** [comment]
> Merchant and Niteman looking through the Keep barred windoor in tears.

good, fuck em
also optimism has no problem with this, for the record

**Review by Optimism333 — COMMENTED** [review]
There hasn't really been much feedback on this, or any major objections... gonna give it a little bump to encourage eyes on it.

If no complaints are voiced, I'll approve it once the conflict is resolved.

**Comment by Cre77** [comment]
> There hasn't really been much feedback on this, or any major objections... gonna give it a little bump to encourage eyes on it.
> 
> If no complaints are voiced, I'll approve it once the conflict is resolved.

resolved

**Review by Optimism333 — APPROVED** [review]
Well, there were no complaints. Should be an easy enough revert if it causes any issues.

Let's see how it goes.

**Pull request merged**
