### PR TITLE
Allows Dwarf Niteman/matron/maiden

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request
See title.

## Why It's Good For The Game
We allow Dwarves to be EVERYTHING else and we even allow Dark Elf in the guard... Time for dwarves to man the baths.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I'm racist against Dwarves + they SUCK IN BED!! Downvoted -1.

**Comment by NPC1314** [comment]
Guck the dwarves and kill the drow, seems about right, can't resist a TM

**Comment by sanshoom** [comment]
I don’t want an ugly little midget as a niteman.

**Comment by BadAtThisGame302** [comment]
> I don’t want an ugly little midget as a niteman.

TRUE....

**Comment by AceVX** [comment]
Blocked. Blocked. Blocked. None of you are free of sin.

**Comment by sanshoom** [comment]
A dwarf nitematron has no dress when they spawn in BTW.

**Comment by Cre77** [comment]
**[PR sponsored by FAT ZACKEL]**

**Comment by NPC1314** [comment]
Fix that night matron dress issue and you good
Honestly give the dwarf nigthman a unique hat too bc its cool and more unique drip is nice, if you can find something suitable that doesnt make him look like a steward or merchant

**Comment by SaintBurgher** [comment]
I DID NOT MEAN TO CLOSE IT

**Comment by SaintBurgher** [comment]
> Fix that night matron dress issue and you good Honestly give the dwarf nigthman a unique hat too bc its cool and more unique drip is nice, if you can find something suitable that doesnt make him look like a steward or merchant

image

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
