### PR TITLE
Aasimar, Tiefling underwear fix

### PR DESCRIPTION
**Pull request by saltprjak**
## About The Pull Request

Puts underwear back on tiefling and aasimar men. Prior to this, admin-spawned and newly-created characters would have underwear with no character sprite. This could be fixed by saving and reloading the character, but this fix will at least prevent people from getting flashbanged by pintle.
image

## Why It's Good For The Game

cover them up slut

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
The tiefling one doesn't fit, seems uneven + you can see the tip of his dick.

**Comment by Cre77** [comment]
> The tiefling one doesn't fit, seems uneven + you can see the tip of his dick.

it's not the dick, it's the tail peeking out from between the legs. The sprite appears behind the character, and shows up in the leg gap.
image

**Comment by BadAtThisGame302** [comment]
> > The tiefling one doesn't fit, seems uneven + you can see the tip of his dick.
> 
> it's not the dick, it's the tail peeking out from between the legs. The sprite appears behind the character, and shows up in the leg gap. Humans and tieflings share body and underwear sprites, they're just colored differently. image

Yet another reason to hate tieflings then, got it!

**Comment by Cre77** [comment]
> Yet another reason to hate tieflings then, got it!

🤝

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
