### PR TITLE
Maybe Fix Dodge (Bugfix)

### LINKED ISSUE #834: [Bug]: Heavy (wbalance = -1) weapons have the opposite intended behaviour against Dodge
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

Dun Manor

### Describe the issue

Weapons tagged as heavy have a much higher hit chance against dodge compared to lighter counterparts, resulting in skewed dodge rates when using them specifically. This happens due to a mistake in the roguetownprocs.dm dodge code, where it attempts to multiply two negative numbers (one of them being the wbalance var which is -1) to reach a positive one:
```
			if(I.wbalance < 0 && L.STASPD > U.STASPD) //nme weapon is slow, so its easier to dodge if we're faster
				prob2defend = prob2defend + ( I.wbalance * ((U.STASPD - L.STASPD) * -10) )

```
Tested in-game.

### How to reproduce

Have dodge on, have someone slower hit you with a cudgel, observe the dodge chance. Repeat with an iron mace.

### Round ID

_No response_

### Staff ckey

_No response_

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
It turns out the calculation that was supposed to make large and slow weapons (like halberds) less likely to hit dodging opponents if they were faster... was actually making it easier.

This attempts to fix that problem, so it works as intended. I tested locally and I seemed to hit a dodger with a halberd less frequently with this change, but it's difficult to be certain. Hopefully this fix works correctly.

## Why It's Good For The Game
More consistent intended behavior for dodge. Should hopefully close #834.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Running some math on simulator, and localtesting this small change myself, without changes I dodged an orc warchief with a halberd as a 13 SPD bard with dodge expert at a 76% (he has like 14 fucking speed who the fuck balanced these ones), and with these changes...that number remained the same. I do not know if this is because they do not have a mind or anything. Testmerging just to test results on live through player feedback.

**Comment by Optimism333** [comment]
> Running some math on simulator, and localtesting this small change myself, without changes I dodged an orc warchief with a halberd as a 13 SPD bard with dodge expert at a 76% (he has like 14 fucking speed who the fuck balanced these ones), and with these changes...that number remained the same. I do not know if this is because they do not have a mind or anything. Testmerging just to test results on live through player feedback.

A test would be best. I wasn't able to test this locally as well as I wanted. HOPEFULLY it works...

**Comment by ThePainkiller** [comment]
At least two players have reported this worked on live, or seemingly does better than before, so I'm inclined to believe :)

**Comment by Optimism333** [comment]
> At least two players have reported this worked on live, or seemingly does better than before, so I'm inclined to believe :)

Excellent...

**Review by NPC1314 — APPROVED** [review]
Two feedback that it works is plenty on this small a change IMO, I'd call the test succesful at least.

**Comment by NPC1314** [comment]
Mostly it will mean the dodge builds hits the 95% cap on dodging vs all weapons with the unwieldy modifier or somesuch, so a boost for dodge play

**Pull request merged**
