### PR TITLE
Shades Emerge [DONE?]

### PR DESCRIPTION
**Pull request by InsightfulParasite**
## About The Pull Request
Using a icon donated by 7sin on discord the shades are now here. Shades are undead that are immune to projectiles and physical damage. I dont really know what the balancing of Stonekeep monsters is so ill have to ask.

ALSO adds a new reagent called **UNDEAD ASH** that drops from shades. This is to encourage alchemy coders.

tweaks dendors tamebeast to not apply to undead so shades will not be tamed by dendor.
tweaks silver dagger to apply additional fire damage to undead simplemobs.
adds a touch attack that does not apply wounds.

ISSUES

- [ ] Balancing has not been reviewed by stonekeep balancers.
- [x] Has not had a final test to see if the no bleeding code is working.
- [x] Needs another test of how fast a silver dagger kills them.
- [ ] They currently do not eat corpses so that may result in a mess.

add: shade.dm
add: new reagent called undeadash that can be harvested from the ash piles shades drop.
add: stonekeep_shade.dmi
tweak: silver dagger
tweak: dendor tamebeast

## Why It's Good For The Game
I was told that they would be good for events.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Any updates on testing if shades can bleed?

**Comment by InsightfulParasite** [comment]
> Any updates on testing if shades can bleed?

Oh sorry i didnt notice this until today. Yes the shades bleeding blood thing was fixed though i did need to make a consideration in living.dm
	if(HAS_TRAIT(src, TRAIT_SIMPLE_WOUNDS) && !HAS_TRAIT(src, TRAIT_BLOODLOSS_IMMUNE))
		// You dont have any blood and your not bloodloss immune? Dead.
i dont know if mobs use bloodloss immune for anything or if its only used on carbons. But i felt like this SORT OF solves it unless there is unforseen consequences im not aware of.
I was planning on making their body eat be dusting the corpse but i can skip that since its not essential. Right now they ignore corpses and gain wound but dont bleed out.

**Comment by ThePainkiller** [comment]
Do shades actually keep fleeing from you if lit on fire via torches? That change was too good to pass, and I'm afraid it might be tied to bloodloss code (NPC's flee from you if they're bleeding or near crit)

**Comment by InsightfulParasite** [comment]
> Do shades actually keep fleeing from you if lit on fire via torches? That change was too good to pass, and I'm afraid it might be tied to bloodloss code (NPC's flee from you if they're bleeding or near crit)

Oh no that was actually a automated action change

```
/mob/living/simple_animal/hostile/retaliate/rogue/shade/handle_automated_action()
	if(on_fire)
		retreat_distance = 10
		minimum_distance = 10
	else
		retreat_distance = initial(retreat_distance)
		minimum_distance = initial(minimum_distance)
	return ..()
```

**Comment by InsightfulParasite** [comment]
I can take another video of fighting them. When hit with a torch they instantly run so they are pretty easy if you know to set them on fire.

**Comment by ThePainkiller** [comment]
Nah it's fine, I'm glad that change was kept, is this good enough to merge now then?

**Review by ThePainkiller — APPROVED** [review]

**Comment by InsightfulParasite** [comment]
> Nah it's fine, I'm glad that change was kept, is this good enough to merge now then?

Yeah its good. Shades still cant be spawned normally so right now they can only appear in admin events. Later PR's may change that.

**Pull request merged**
