### PR TITLE
Possible Sounding

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request

Testing the preload ambience option button from https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/331
Doesn't break anything but can't detect any difference in localtest. Could work on live though.

It works. Credit to https://github.com/EvenInDeathIStillServe.

Added testing the compression, 0 quality was too noticeable for my ears so trying qual 2 (was 5)
Also remvoed the new guitar track for night, its been tested a while and not generally liked, I agree it leans too heavy into guitar blues/jazz or something.
The added area sounds do actualize the issue with area sounds in general, each new track puts more lag strain on load so might need to rollback on adding more, we will see what testing reveals.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
132520140_1819953248159459_5703014254377232972_n

**Comment by EvenInDeathIStillServe** [comment]
It would be a lot more effective to straight up compress the music files down to more reasonable sizes. Some of the songs in the files were upwards of **11MB**.

This PR went in at roughly the same time as the preload command, so I can't really say which was responsible, but complaints about lagging off cliffs pretty much disappeared entirely after they went through.

https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/330

**Comment by NPC1314** [comment]
> It would be a lot more effective to straight up compress the music files down to more reasonable sizes. Some of the songs in the files were upwards of **11MB**.
> 
> This PR went in at roughly the same time as the preload command, so I can't really say which was responsible, but complaints about lagging off cliffs pretty much disappeared entirely after they went through.
> 
> [GeneralPantsuIsBadAtCoding/Azure-Peak#330](https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/330)
> 
> I just went through Audacity and set the quality to 0. Absolutely no difference at all in playback.

The testing we done showed this does work but with the old compression its several minutes of preloading so the compression thing is likely the more important part, since its a manual button most players wont ever press it anyways.

Thanks for the tip

**Comment by NPC1314** [comment]
I made a version thats supposed to preload the tracks automatically. Localtest doesn't yield any insights, it doesnt cause any harm though. Lets see if it works

**Comment by NPC1314** [comment]
With no feedback or metrics to go on its impossible to tell whether the SS solution worked ok, so just reverting to the tested and proven button thing coupled with lower ambient sampling quality.

Good for merge, no more testing will be done.

**Review by Optimism333 — APPROVED** [review]

**Pull request merged**
