### PR TITLE
Revival Sickness

### PR DESCRIPTION
**Pull request by SELFHELL**
## About The Pull Request

By popular demand I have basically halved decay time and added a temporary debuff for being revived.

## Why It's Good For The Game

Fights the hugbox,
Death should be punishing, and those who die shouldn't be able to get right back into a fight after being revived. Also RP opportunities and whatever.

Probably will need a TM or two.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Review by Optimism333 — COMMENTED** [review]
25 minutes might be a little harsh on the length of the debuff. Perhaps 15 minutes? That would already be more than long enough to ensure that someone won't get revived and be able jump right back into a fight.

**Comment by Cre77** [comment]
this is the first time i've heard of anyone complaining revival is too prevalent - coupled with a lot of mobs straight up gibbing people, and antags decapping. very much against this

**Comment by ThePainkiller** [comment]
We literally upped the timers months ago because people were complaining players rot too fast, and revival was impossible as they zombified themselves before ever reaching a priest. Why a revert now?

**Comment by Mogelix** [comment]
> this is the first time i've heard of anyone complaining revival is too prevalent - coupled with priests being a rarity, a lot of mobs straight up gibbing people, and antags decapping. very much against making corpses decay faster, but i like revival sickness

Just going to say this to pre-empt anyone accusing me of being part of a church cabal shooting down this PR: I'm actually _for_ making corpses decay faster. 

Personally, I think people take church revivals basically for granted, death isn't treated dramatically as death in roleplay. Definitely shorten the duration of revival sickness though, please, ten-fifteen minutes should really suffice.

**Comment by NPC1314** [comment]
A malus for being revived seems reasonable, rot timer is not a slam dunk though, seems like not adressing the core issue.
Better setup IMO is using permanent maluses. Being revived -1 in all stats, permanent.

Even more important is a permanent cost to priest to strongly encourage them to not do it without good reason, if theres no real cost it will always remain trivial, to make actions meaningful you need to adress the core, which is zero true cost of revival.

Give them -1 perma strength and gib them once they reach 0 and you'll see priests hesitate to revive people who never come by the temple.

Priests should be able to revive when its dramatically appropriate, not be cucked by a rot timer, but it shouldnt be free, thats the real issue.

**Comment by NPC1314** [comment]
25 minutes or whatever is pretty long but yeah its not the real issue here, adjusting rot timer is secondary at best unless you set it to something ludicrous like 3 minutes to make it a race against time (even then people will just craft a chest and game it so dud unless you blacklist the rot timer pausing by chests, another big sidetrack really, focus should be on the costs.)

Could also flip things, give the revived a pemranent -1 to everything, give priest a bigger malus but temporary.
Lots of configurations, needs some thought to make this good and not a bandaid

**Review by Optimism333 — COMMENTED** [review]
This has been sitting here for a while, so I thought I'd give it a bump.

If you wouldn't mind, axe the changes to corpse rotting. Let's give this a test with just revival sickness as a compromise.

We'll see what the feedback is.

**Comment by Optimism333** [comment]
Test merge should be in next round. We'll see how it goes.

**Comment by Dagonlives** [comment]
I play priest a lot.

I'm not in favor of getting a -1 strength sap, though some other cost being associated with resurrection is fine.  Say a hefty sum of coin, or having to offer a gold item or a player blood tithe, that sort of thing.

The problem with putting the cost personally on the caster is you'll still get drifter hordes threatening to kill you for not resurrecting their dumb friend who never comes to pray.  

The cost needs to be a neutral one that can be justifiably used to deny services.  If you make it a -1 strength malus on the priest permanently, you still get the result of "Res this player or I kill you' and then you will get future demands you are unable to protect from at all because of this permanently stacking debuff you are dealing with. The cost must be bourne by the one SEEKING to be resurrected, not by the one performing it.  Or it's just being bullied for not being medbay bot all over again. 

Resurrection sickness itself is fine, but I suggest 10-15 minutes.  A round is 2 hours long average, and 30 minutes would just be too long to not be playing the game.  We don't want to create excessive waiting to get into the action, but death should have more sting.

**Comment by NPC1314** [comment]
> I play priest a lot.
> 
> I'm not in favor of getting a -1 strength sap, though some other cost being associated with resurrection is fine. Say a hefty sum of coin, or having to offer a gold item or a player blood tithe, that sort of thing.
> 
> The problem with putting the cost personally on the caster is you'll still get drifter hordes threatening to kill you for not resurrecting their dumb friend who never comes to pray. A lot of players are stuck in treating the church like a medbay bot, and the way to get around that is to ensure they bear the cost, not the 'medbay'.
> 
> The cost needs to be a neutral one that can be justifiably used to deny services. If you make it a -1 strength malus on the priest permanently, you still get the result of "Res this player or I kill you' and then you will get future demands you are unable to protect from at all because of this permanently stacking debuff you are dealing with. The cost must be borne by the one SEEKING to be resurrected, not by the one performing it. Or it's just being bullied for not being medbay bot all over again with the added sting of having your character becoming increasingly incapable as time goes on.
> 
> Resurrection sickness itself is fine, but I suggest 10-15 minutes. A round is 2 hours long average, and 30 minutes would just be too long to not be playing the game. We don't want to create excessive waiting to get into the action, but death should have more sting.

I hear you, still, state of this server when randos roll in and gank the priest for not being a revive vendor =/
A coin cost can be tested, anyways, this has shrunk to just a 15 min revive debuff, I think cut off 5 mins at least from rot timer is next step IMO.

**Comment by NPC1314** [comment]
It does what it says on the tin, it works as intended, lets take the W and move on.

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
