### PR TITLE
Disables Drifter Queueing; Pilgrims Re-Added (Return to Tradition)

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request

Basically disables the drifter system and restores the pilgrim system. This is mostly in attempt to fix bandit and - the fact we get so many issues with drifter.

Basically restores it to how it was prior to PR by doing this; drafting for now till I can test it.

Also - ported the PQ slot thing but unsure if we'll use it; doubt it would be useful but I guess it gives a way of rewarding good PQ pilgrim players maybe.

## Why It's Good For The Game

Bandit is fucked and the drifter PR was a terrible idea given Blackstone abandoned it with tons of bugs to the point every server doesn't even use it anymore.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by AceMcLazer** [comment]
Sad but necessary

**Comment by DAKKA-WAAAGH** [comment]
> Sad but necessary

Agreed. There are surely better solutions that we can approach later.

**Comment by Plaguewalker** [comment]
Should've been sooner but I agree

**Comment by sanshoom** [comment]
FINALLY.

**Comment by Stutternov** [comment]
Was tested and seems to work, can't confirm if this fixes bandit (can't find out local test wise) or not but I can confirm it doesn't fuck with adventurer/pilgrim spawns.

**Comment by Stutternov** [comment]
Had issues, need to fix

**Comment by Stutternov** [comment]
Nmv don't know how to fix without porting a huge amount of files from elsewhere; someone else's do it.

**Pull request closed without merging**
