### PR TITLE
Inn Tweaks and Remapping

### PR DESCRIPTION
**Pull request by OctusGit**
## About The Pull Request

Inn remap, added a cellar and cellar room for storage and private meetings. Bar is wider allowing for keepers to have more space and movement when working, added two extra mugs since three was very little. Kitchen now has more places to store foods and barrels. Added spare inn keys to the meeting room since most shops have spares for hires.

Inn room windows walled off, to make using them safer, encourage people to pay for a room. Added extra window to the top floor to help rogues and thieves still get in and out of the inn with enough preparation. 

Fixed a zone area in the south stairs portion of the inn (market area), Hunt room balcony now works with its respected key, and balcony can now be locked like all the other tavern doors.

StrongDMM_2KPEIPRuZF

StrongDMM_jb7nZuNytf

## Why It's Good For The Game

some oversights fixes here and there, mostly expanding the inn to make it more enjoyable to run, and also encourage safety given its in the heart of town.  

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by YuiY1997** [comment]
Hey so there's another mapping PR being merged. Mind if I add the changes from this one into mine so that I can submit this and the graveyard and market PR ( https://github.com/Darkrp-community/OpenKeep/pull/26 )? This will make sure that both of our changes are kept and neither of us will have to redo the work if one of ours gets merged. Otherwise they will overwrite each other and someone will have to make their changes again.

**Comment by NPC1314** [comment]
> Hey so there's another mapping PR being merged. Mind if I add the changes from this one into mine so that I can submit this and the graveyard and market PR ( #26 )? This will make sure that both of our changes are kept and neither of us will have to redo the work if one of ours gets merged. Otherwise they will overwrite each other and someone will have to make their changes again.

Thats not a great idea, keep your map PRs localized. Update your branch so you got the latest mapfile and copy paste the mapped area over when PR is greenlit and you avoid overwrites for sure.

**Comment by OctusGit** [comment]
> Hey so there's another mapping PR being merged. Mind if I add the changes from this one into mine so that I can submit this and the graveyard and market PR ( #26 )? This will make sure that both of our changes are kept and neither of us will have to redo the work if one of ours gets merged. Otherwise they will overwrite each other and someone will have to make their changes again.

Its fine, I can fix the merge issues when your PR gets merged. Would be wise to atomize PRs.

**Comment by NPC1314** [comment]
The inn looks good first impression but need to test it and maybe add elements from the food module, I'll get back to you in a couple days

**Comment by NPC1314** [comment]
Tested it, it seems solid. Would like if you can incorporate some planned stuff to the upper level, something along these lines, to avoid needing to change layout in any significant way soon.
kitchenstuff

**Comment by OctusGit** [comment]
> Tested it, it seems solid. Would like if you can incorporate some planned stuff to the upper level, something along these lines, to avoid needing to change layout in any significant way soon. kitchenstuff

Oh shittt this has alot of improvements, doing it rn

**Review by NPC1314 — APPROVED** [review]
Looks good. Any minor issues can be fixed in the food module prep mapping PR.
Should go in for testmerge after graveyard PR final merged and this branch updated.

**Pull request merged**
