### PR TITLE
Farming power up

### PR DESCRIPTION
**Pull request by NPC1314**
## About The Pull Request
Credit for the OG farm code https://github.com/Azarak

Basically #658 but modular and the cleaning part atomized away and some improvements.
Makes farming more interesting and better overall, though it doesnt fix the issues with economy being FUBAR
or Townies being pretty weak vs bandits or adventurers.

For clarity, port of this system, just like 658
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/158

TLdr 
Compost needed (bin can be built)
The farming tools getting new/old art fixing all the offset issues will be noticeable ofc.
Basically you cant have huge sprites look ok when backslottable currently.
new thresher based on medieval art, can be made into a military flail

https://github.com/user-attachments/assets/ae676389-f624-4dc3-9f36-36e58f911916

https://github.com/user-attachments/assets/62f5b2e7-4035-48ae-b91b-07d058f49c9b

https://github.com/user-attachments/assets/7f68038d-c82d-4200-85f6-e33fc3ec2b77

https://github.com/user-attachments/assets/2f42c294-b0a6-4d51-b576-4245d2e682f4

Changes just about every value associated with the plants and the tools and the tool art and the plant art to some degree.
Adds plough and compost and a less terrible layout for the toolroom soilsons Dunmanor.

Since map has to be edited, fixed the archivist spawn and maybe a fix for weaponsmith too. and the black tile in inn.
Also adds more clickable area for grass so cutting it is less cancer (no visual change)
And minor contrast increase to fibres so theyre a little bit more visible
Minor highlight to top of the darkest barrel bc holy heck low contrast dark is pain
Soilsons were missing the skill to use their threser, got lvl 2 like the rest, and were literally broke.
Even scum like adventurers get money, but soilsons nothing? No way buddy, no way.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by lavillastrangiato** [comment]
Jesus H. Christ, another PR where the Stonekeep-exclusive changes to a core SS13 gane mechanic are organised into a folder called "neu[mechanic]" instead of replacing the files, I am sure this will cause no headaches whatsoever with file cleanup in the future.

Also, please document the changes you're making in writing. I don't want to have to pore over videos again and again to write all this shit down on the wiki.

**Review by BadAtThisGame302 — APPROVED** [review]
A TM to see how this plays it in-game would be good. The changes look fine to me for now.

**Comment by Mogelix** [comment]
I'm pretty sure this broke making oatmeal with oats.
NVIDIA_Share_tKQ9X7VDdY
(Yes, the pot is boiling.)

**Comment by NPC1314** [comment]
> I'm pretty sure this broke making oatmeal with oats. ![NVIDIA_Share_tKQ9X7VDdY](https://private-user-
Can't have that, it shall be the last fix for the night, let there be oatmeal once more

**Comment by NPC1314** [comment]
Latest updates included riding piggies to the bog, slicable onions and much, much more (not really)

**Comment by AceVX** [comment]
Love this update. Something's up with the apple trees, though

**Comment by NPC1314** [comment]
> Love this update. Something's up with the apple trees, though
Specific issue? Cursory look doesnt reveal any issues with the code for it

**Comment by NPC1314** [comment]
giving up on fixing the thresher for now, back to instant threshing of a hundred chaff =(

**Review by ThePainkiller — CHANGES_REQUESTED** [review]
Forgot one

**Review by ThePainkiller — APPROVED** [review]
Enigma eating good now.

**Pull request merged**
