### PR TITLE
Farm Soilson Key Problem

### PR DESCRIPTION
**Pull request by k0n1n**
## About The Pull Request

I took a look at the key problem and saw that the lockid is set to the elder and not to the soilson and I fixed the skills that were changed to 1 and reverted them back to 2. I'm learning to use all of this, but if you want to remove the keys I placed on the map on my other PR, feel free to do so.

## Why It's Good For The Game

All the soilsons that spawn late game will no longer have to break the farm door or the palisades to enter the farm.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Review by ThePainkiller — APPROVED** [review]
Thanks for also solving the captain keys issue.

**Comment by k0n1n** [comment]
> Thanks for also solving the captain keys issue.

No problem, I'm happy to help even though I don't have extensive coding knowledge. I don't know why the PR came with three files, as I only added keys.dm and soilson.dm. I'm learning how to work with all of this and with Git. Maybe I added it without noticing, or it was already added because of a previous PR I made.

**Comment by NPC1314** [comment]
With the total map conversion  its a good idea to remove the map part of this and update it so it can be merged

**Comment by NPC1314** [comment]
Obsolete due to the key issues solved etc, closing.

**Pull request closed without merging**
