### PR TITLE
Raytown Adjustments: I've Procrastinated Long Enough

### PR DESCRIPTION
**Pull request by bowlofcereal**
## About The Pull Request

Finishes a couple of my adjustments to Raytown to bring it up to the modern age. This is pt2. After this i'm going to only really do tweaks and changes at the requests of other people, as dealing with this map is a pain in the ass but having variety is good.

## Why It's Good For The Game

Finishing what I did good

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by bowlofcereal** [comment]
this space is now empty again.
image

welcome back guildhouse
image
image
image

nuked the powercrept armory
image

added some inquis flavor from the inquis prs
image

gave the magician the alchemy lab proper
image

slight changes to the stewardry, nothing major just some nitpick changes
image
image
image


**the farms also have their proper equipment now in line with the farming PR**

**Comment by bowlofcereal** [comment]
this should be good for review and then implementation. there wasn't much left to do besides the guildhouse, and i decided moving the stewardry would be pointless.

**Comment by bowlofcereal** [comment]
image

slapped down a small mason camp like dun manor, because why not?

**Comment by ThePainkiller** [comment]
> image
> 
> slapped down a small mason camp like dun manor, because why not?

My only beef is that this mason camp completely fucked over my main building place when I go pilgrim 😭 This is literally such a good spot to build, it's an entrance to town guaranteed to get clients and attention, and now it's just a pit stop for masons to be on their way to mine just...bare meters away

**Comment by bowlofcereal** [comment]
uhm... no idea why we suddenly spiked to 117k additions

**Comment by bowlofcereal** [comment]
Yeah for the sake of avoiding ever having that happen again i'm done with this PR. It's ready to be merged and i'll just do the rest in a separate PR without having to risk it exploding

**Comment by ThePainkiller** [comment]
I really want to put merging this on hold until I manage to make mapvote work because oh my god I need Raytown back so badly

**Review by ThePainkiller — APPROVED** [review]
Let's merge for now and whenever I get some free time off-work, I'll work on a working mapvote system so we can actually play this map.

**Pull request merged**
