### PR TITLE
Bye Bye Beggars: Operation Triple B

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Removes the 3 NPC beggars from Roguetown

## Why It's Good For The Game

Sorry, nobody is able to have fun due to two out of four antags using them as bloodbags/sacrifices (VL and Zizocult accordingly) So, the brainless muts are gone

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by sanshoom** [comment]
LAME AS HELL.

**Comment by 1N7Slayer** [comment]
BASED

**Comment by ThePainkiller** [comment]
To be honest, they sort of add flavor to the town as the designated local crackheads but in the other hand... yes, vampires have been gaming them too much for free blood reserves and it fucking sucks.
Trying to be fair and not let my hatred of powergaming vampires affect my judgement, this sounds like a good PR, I'll defer to what the rest of the team has to say about it.

**Review by ThePainkiller — APPROVED** [review]
Until a way to make it so that vampires can't have a steady supply of Vitae to ascend and whatnot, this will work as a bandaid fix for a bigger issue, for now.

**Pull request merged**
