### PR TITLE
zizo cult ritual additions, rebalances and such

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About The Pull Request

rebalances the call ritual
new stun thingy for zizoid cult
new heal ritual
new bad omen ritual (NEEDS A HUMAN SACRIFICE TO KILL............)

## Why It's Good For The Game

i like things not being fuckijng USELESSS

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by Cre77** [comment]
can we have more than 3 cultists at a time

**Comment by ThePainkiller** [comment]
> can we have more than 3 cultists at a time

I second this, at least four cultist max would be good, willing to go as high as five even

**Comment by casualspacestation14enjoyer** [comment]
failing  checks dont actually have anything to do with compiling, shit is just weird

**Comment by casualspacestation14enjoyer** [comment]
> 02- proc args with var/ code/modules/antagonists/roguetown/villain/zizocult.dm:/proc/heartache(var/mob/user, var/turf/C) code/modules/antagonists/roguetown/villain/zizocult.dm:/proc/fleshmend(var/mob/user, var/turf/C) code/modules/antagonists/roguetown/villain/zizocult.dm:/proc/badomenzizo(var/mob/user, var/turf/C)
> 
> Can't do much with the linter blocking approve button.

It compiles fine and I have no idea how to fix this.

**Comment by casualspacestation14enjoyer** [comment]
ok nvm i know how to fiix this

**Review by Optimism333 — COMMENTED** [review]
This need anything else, or is it good to go?

**Review by NPC1314 — APPROVED** [review]

**Pull request merged**
