### PR TITLE
Reading update

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Dwarf Ranger and Bombadier get Reading 2 like Longbeard

Bladesinger and Sentinel got Reading 2 + 1 from Elf natural reading

Vaquero gets Reading 1

Ranger gets Reading 1

Treasure Hunter gets Reading 1

Warrior gets a 66% chance for Reading 1, else he gets Reading 2

Fisher/Hunter/Miner and Woodcutter all get Reading 1 to line up with the rest of the peasants like Carpenter/Smith etc.

Swashbuckler gets Reading 1

Legendary Fisher/Miner and Mason all get Reading 1 since their non-legendary counterparts got Reading 1

## Why It's Good For The Game

In my opinion, most of these align with other already established skills, aswell as allowing players more freedom to have the ability to RP as literate or prefer to stay iliterate, or perhaps craft a book to bump them up a few levels to allow for them to understand books/scrolls etc. 

If anyone has any complaints or wants me to get specific on any addition, let me know.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Personally against warrior reading, give them a 33% chance to have reading 1 at the very most tbh

Not sure why fisher/miner/hunter get reading, since smiths, carpenters, masons, merchants etc. are actual educated fellas unlike people who just cast a line to fish or poachers that live off the land

**Comment by NPC1314** [comment]
There needs to be some sort of discussion on who can read and not and why. Maybe nobles can help with that one

**Comment by cornercube** [comment]
> There needs to be some sort of discussion on who can read and not and why. Maybe nobles can help with that one

people who need reading the most are the ones who need to interact with vending machines the most, to load and offload from the stockpile
those with low combat skills could justify reading if its lore-worthy
dumb muscle probably doesnt need reading

**Comment by NPC1314** [comment]
> > There needs to be some sort of discussion on who can read and not and why. Maybe nobles can help with that one
> 
> people who need reading the most are the ones who need to interact with vending machines the most, to load and offload from the stockpile those with low combat skills could justify reading if its lore-worthy dumb muscle probably doesnt need reading

I'd agree, but where to draw the line is the question, warrior adventurers getting reading does set the bar at somewhere close to "Everyone except barbarians?" more or less. Though maybe thats fine w the new book system? It does scrub out a old divide between readers and not readers so a bit cautious, ideally the focus group could put some meat on this bone.

**Pull request merged**
