### PR TITLE
Drifter Changes Part Deux

### PR DESCRIPTION
**Pull request by CormanQuewye**
## About The Pull Request

Removes the class choice roll for all drifter classes excluding assassino. Removes pick limit on non-magical and non-nobility classes. After discussion with a dev and being informed that heavy armour training is meant to be rare, drifter classes that have this trait have retained their pick limit (albeit slightly increased in some cases).

- Physicker's limit has gone up from 1 to 3.
- Blacksmith Drifter no longer has a choice roll.
- Vaquero and Sentinel no longer have a limit.
- Vaquero's sword skill was lowered to 3, Sentinel's bow lowered to 4.
- Sentinel's stats have been massively nerfed (now +1 speed, +2 perception instead of their prior bonus to nearly every stat)
- Witchhunter's slot limit increased to 2.
- Freelancer's slot limit increased to 3.
- Bladesinger's slot limit increased to 2.
- Swordmaster (kept at a limit of 1) buffed to be Master at swordmanship. I also removed their -1 to speed and added a +1 to intelligence (so their new stat change is 2 strength, 1 intelligence).
- Longbeard is the protagaonist, so they're kept at a limit of 1.

There are things I'm unhappy with here. Personally, what I love about fantasy is variety and the exploration of concepts. We have that in the form of forgotten ancient tech, sky merchants with their balloons, and colorful (albeit historically inspired) realms other than the main one. So, if this gets approved, I'll likely be following it up with the addition of a few classes that are toned down versions of their limited, plate-wearing kin.

## Why It's Good For The Game

The drifter class rolling gamifies what's meant to be a roleplay server. It incentivises looking for fights and pushing for frag situations when you get a 'rare' class due to wanting to use its capabilities. This removes the rolling and removes the limit on any class that doesn't have heavy armour training, isn't magical, and isn't nobility. (Excluding Assassino due to being an antag).

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

### CODE REVIEW

**Comment by Optimism333** [comment]
This is a little less insane, but please stop trying to add more bladesingers and lancers.

We don't need more plate armor trained bums, and now you've been by a dev that they're supposed to be rare, yet you're still trying to add more.

**Comment by Mojamble** [comment]
I think this is a really really poor idea. Rare classes are rare for a reason - much like Opti said, we don't need more fully armored plate wearing goons who can influence the entire round. The same goes for the doctor slots - you're just going to make feldsher worthless.

**Comment by DAKKA-WAAAGH** [comment]
This is too much for the server balance to handle, this needs to be toned WAY down before even being close to acceptable.

**Comment by CormanQuewye** [comment]
> This is a little less insane, but please stop trying to add more bladesingers and lancers.
> 
> We don't need more plate armor trained bums, and now you've been told by a dev that they're supposed to be rare, yet you're still trying to add more.

Friend, adding more is not mutually exclusive with rare. Warrior has better stats than either. Stabbing ignores plate armour. Often, if you have a smith at work, you'll have the guards wearing a better mixed set than just 'plate'. And yes, I spoke to a dev, they were given these changes and said that they would give it a re-review when they had the time and this would be adjusted.

If you understand the basics of combat I assure you, you can beat a bladesinger with a spear and 3 in polearms. This is criticism lacking an understanding of code, balance, or combat. By your very logic, I need to delete warrior because they can walk up to a Smith and outrank royal guards.

Worse is that I keep hearing this repeated but people refuse or cannot put into words *why*. It seems more like a reflex than anything thought through.



> I think this is a really really poor idea. Rare classes are rare for a reason - much like Opti said, we don't need more fully armored plate wearing goons who can influence the entire round. The same goes for the doctor slots - you're just going to make feldsher worthless.

Right, we should have unbalanced classes for people to fixate on fragging. I will also make sure to delete paladins and clerics altogether because they make feldsher worthless /s.



> This is too much for the server balance to handle, this needs to be toned WAY down before even being close to acceptable.

Friend, could you explain which part is unbalanced? People keep bringing up balance but refuse to actually point things out which... ya know. I'm all for criticism, but saying 'balance' isn't criticism, because I don't get to understand what you mean. If anything, this is way more balanced than before. Skills and stats have been lowered, picks have been made consistent instead of RNG.

If your point is that this is... somehow less balanced? Then, alright, enjoy knowing that CURRENTLY Sentinel starts with a mount, Master at Bows, and ("strength", 1) ("constitution", 1) ("endurance", 1) ("perception", 4). The thing I lowered. Is your issue that I... increased Bladesinger's slots by 1 and Lancer's by 2?

If you're going to light your torches, at least be consistent and tell me what the exact issues are first.

**Comment by Optimism333** [comment]
> > This is a little less insane, but please stop trying to add more bladesingers and lancers.
> > We don't need more plate armor trained bums, and now you've been told by a dev that they're supposed to be rare, yet you're still trying to add more.
> 
> Friend, adding more is not mutually exclusive with rare. Warrior has better stats than either. Stabbing ignores plate armour. Often, if you have a smith at work, you'll have the guards wearing a better mixed set than just 'plate'. And yes, I spoke to a dev, they were given these changes and said that they would give it a re-review when they had the time and this would be adjusted.
> 
"Adding more is not mutually exclusive with rare"? It literally IS, what are you talking about. That makes a rare role more common.

I already told you, I do not care if you consider them weaker than a warrior. If you think warrior outshines bladesinger and lancer somehow, balance them so they don't. Keep the slot limit at one.

I don't know what you're on, saying that these classes aren't that good. They both get an expert level combat skill, that's nothing to scoff at. It's the same training level as a royal guard in town, above the regular garrison.

**Comment by Mojamble** [comment]
what does any of that mean at all

**Comment by CormanQuewye** [comment]
> > > This is a little less insane, but please stop trying to add more bladesingers and lancers.
> > > We don't need more plate armor trained bums, and now you've been told by a dev that they're supposed to be rare, yet you're still trying to add more.
> > 
> > 
> > Friend, adding more is not mutually exclusive with rare. Warrior has better stats than either. Stabbing ignores plate armour. Often, if you have a smith at work, you'll have the guards wearing a better mixed set than just 'plate'. And yes, I spoke to a dev, they were given these changes and said that they would give it a re-review when they had the time and this would be adjusted.
> 
> "Adding more is not mutually exclusive with rare"? It literally IS, what are you talking about. That makes a rare role more common.
> 
> I already told you, I do not care if you consider them weaker than a warrior. If you think warrior outshines bladesinger and lancer somehow, balance them so they don't in another pr. Keep the slot limit at one.
> 
> I don't know what you're on, saying that these classes aren't that good. They both get an expert level combat skill, that's nothing to scoff at. It's the same training level as a royal guard in town, above the regular garrison.

It's not my opinion, it's the literal code. Barbarian and Warrior are stronger. So, thus, this is what I mean when I speak of balance. You don't actually care about balance if your response is: 'nerf barbarian and warrior then!' Why would I nerf them instead of just add what totals to three plate slots? That's not balance. That you arbritarily wanting something.

And I can't believe I have to do this again, but basic garrison stats: ("strength", 1) ("perception", 1 ("endurance", 1) ("constitution", 1). Higher than Lancer or Bladesinger. Should I also nerf the garrison? Yes, Lancer has *one* more level in polearms than garrison, but they also have a stat average increase of ONE versus the garrison's of FOUR. And they get paid.

This isn't an opinion, this is taken from the code. If you want balance? Sure! Balance is great. But you don't. You started arguing from a premise that lacked base in knowledge of combat or the code of these changes, and are now sticking to your guns, come hell or high water.

**Comment by Max-023** [comment]
> > This is a little less insane, but please stop trying to add more bladesingers and lancers.
> > We don't need more plate armor trained bums, and now you've been told by a dev that they're supposed to be rare, yet you're still trying to add more.
> 
> Friend, adding more is not mutually exclusive with rare. Warrior has better stats than either. Stabbing ignores plate armour. Often, if you have a smith at work, you'll have the guards wearing a better mixed set than just 'plate'. And yes, I spoke to a dev, they were given these changes and said that they would give it a re-review when they had the time and this would be adjusted.

As someone who has played a thorough amount of guard rounds, this is not true. Most guard don't have anything beyond the standard kit they spawn with due to adventurers, now drifters, coming in and taking up all the steel. This is especially the case since the best armor guard can wear before they get crippled with speed is scalemail, which is just significantly shittier half-plate. This is especially the case when the pop isn't super high, as rarely anyone volunteers to mine so there isn't anyone making armor or weapons.

> If you understand the basics of combat I assure you, you can beat a bladesinger with a spear and 3 in polearms. This is criticism lacking an understanding of code, balance, or combat. By your very logic, I need to delete warrior because they can walk up to a Smith and outrank royal guards.

Don't open a PR talking about a mechanic that 'gamifies' the experience and then dissuade criticism that is exactly that, gamifying the experience to add justification. Sure, a bladesinger that isn't parrying can be killed through mouth aim, but the criticism is that having a bunch of bladesingers (who are clad in visually distinct plate) takes them out of the experience. Nothing about how easy it is to frag said bladesingers is going to properly address that concern.

And ESPECIALLY don't try to lecture someone on something you clearly know nothing about. Warrior gets shittier skills compared to the GARRISON guard when it comes to martial combat, and the stats are also slated to the guard outside 1 extra STR the warrior gets. Even when it comes to armor, they share the same weaknesses the guard have (face and legs) so all you need is to just leg aim with a mace and cripple them. The warrior isn't this big bad man that can punk anyone and everyone, they are just a strong dude with a sword, shield, and *maybe* a chestplate and pauldrons.

> Worse is that I keep hearing this repeated but people refuse or cannot put into words _why_. It seems more like a reflex than anything thought through.

This is what I consider the root of the problem and the apparent disconnect you have with pretty much everyone else. You aren't on an island of understanding surrounded by a sea of ignorance, you just have a different perspective. This is shown by your lack of understanding regarding town roles and their condition, as well as your adamancy that warrior is somehow problematic despite being one of the most generic roles in the game.

Balance keeps being brought up because as it currently stands, there are way too many combat roles running around and this PR only exacerbates that. It also ignores the thematic purpose of the some of the roles, like the sentinel being a scout from the elven kingdoms sent to survey the situation on enigma, and just artificially just unlocks them for many to play. And the intent is to....make the roles less frag incentivizing? Because they have rarity? This is not only a blatant assumption with no evidence to support such a claim, but your response is just throw more into the mix. This oversaturation doesn't suddenly make combat less illustrious, it just means more people get to run around with the flashy shit and use it.

Your attitude is not only extremely combative but your engagement with others has been nothing short of openly hostile and dismissive of their issues, chalking it up to them just blatantly being wrong. I recommend taking a step back and reflect on yourself for a moment before coming back, because this ain't it.

**Comment by Optimism333** [comment]
Yeah okay, pal. You only are looking at stats to determine these power levels you've stuck in your mind, and I even said in the previous post if you think they're overshadowed in stats, those can be adjusted. I simply disagree with the slot increase.

Not reading the rest of that rambling. You can enjoy your downvote and I will get on with my day, unless you remove the slot increase.

Sorry your slight backpedal of your last pr wasn't any more popular.

**Comment by sanshoom** [comment]
hey on a slightly related note, we should have atleast one more paladin slot TBH.

**Comment by CormanQuewye** [comment]
> > > This is a little less insane, but please stop trying to add more bladesingers and lancers.
> > > We don't need more plate armor trained bums, and now you've been told by a dev that they're supposed to be rare, yet you're still trying to add more.
> > 
> > 
> > Friend, adding more is not mutually exclusive with rare. Warrior has better stats than either. Stabbing ignores plate armour. Often, if you have a smith at work, you'll have the guards wearing a better mixed set than just 'plate'. And yes, I spoke to a dev, they were given these changes and said that they would give it a re-review when they had the time and this would be adjusted.
> 
> As someone who has played a thorough amount of guard rounds, this is not true. Most guard don't have anything beyond the standard kit they spawn with due to adventurers, now drifters, coming in and taking up all the steel. This is especially the case since the best armor guard can wear before they get crippled with speed is scalemail, which is just significantly shittier half-plate. This is especially the case when the pop isn't super high, as rarely anyone volunteers to mine so there isn't anyone making armor or weapons.
> 
> > If you understand the basics of combat I assure you, you can beat a bladesinger with a spear and 3 in polearms. This is criticism lacking an understanding of code, balance, or combat. By your very logic, I need to delete warrior because they can walk up to a Smith and outrank royal guards.
> 
> Don't open a PR talking about a mechanic that 'gamifies' the experience and then dissuade criticism that is exactly that, gamifying the experience to add justification. Sure, a bladesinger that isn't parrying can be killed through mouth aim, but the criticism is that having a bunch of bladesingers (who are clad in visually distinct plate) takes them out of the experience. Nothing about how easy it is to frag said bladesingers is going to properly address that concern.
> 
> And ESPECIALLY don't try to lecture someone on something you clearly know nothing about. Warrior gets shittier skills compared to the GARRISON guard when it comes to martial combat, and the stats are also slated to the guard outside 1 extra STR the warrior gets. Even when it comes to armor, they share the same weaknesses the guard have (face and legs) so all you need is to just leg aim with a mace and cripple them. The warrior isn't this big bad man that can punk anyone and everyone, they are just a strong dude with a sword, shield, and _maybe_ a chestplate and pauldrons.
> 
> > Worse is that I keep hearing this repeated but people refuse or cannot put into words _why_. It seems more like a reflex than anything thought through.
> 
> This is what I consider the root of the problem and the apparent disconnect you have with pretty much everyone else. You aren't on an island of understanding surrounded by a sea of ignorance, you just have a different perspective. This is shown by your lack of understanding regarding town roles and their condition, as well as your adamancy that warrior is somehow problematic despite being one of the most generic roles in the game.
> 
> Balance keeps being brought up because as it currently stands, there are way too many combat roles running around and this PR only exacerbates that. It also ignores the thematic purpose of the some of the roles, like the sentinel being a scout from the elven kingdoms sent to survey the situation on enigma, and just artificially just unlocks them for many to play. And the intent is to....make the roles less frag incentivizing? Because they have rarity? This is not only a blatant assumption with no evidence to support such a claim, but your response is just throw more into the mix. This oversaturation doesn't suddenly make combat less illustrious, it just means more people get to run around with the flashy shit and use it.
> 
> Your attitude is not only extremely combative but your engagement with others has been nothing short of openly hostile and dismissive of their issues, chalking it up to them just blatantly being wrong. I recommend taking a step back and reflect on yourself for a moment before coming back, because this ain't it.

First of all: I did not 'dissuade criticism' I brought up criticism utilizing false information. I also didn't say 'warrior is stronger than a garrison guard'. I showed the Warriors and Barbarians stats versus the Rares... Warriors and Barbarian HEAVILY outclassing them in stats. If someone brings up incorrect information and then promptly asserts they're right, be telling them they're wrong it's dissuasion. This PR is a follow up to a previously made PR that I closed because if **actual criticism backed by code**.

I also never said Warrior was overpowered. Look up, it was @Optimism333 who was attempting to make the argument that I should nerf warrior. You're getting wires crossed. I said warrior was fine, just stronger than most rares, which I have zero issue with. At no point have I complained about warrior, I've done the exact opposite and made the argument that people are exaggerating the combat potential of drifters because they don't understand combat.

Yes, my attitude is combatative. It's hard not to be when people come in aggressively swinging pitchfork and torch, spreading misinformation, while doing little-to-nothing when it comes to contributing the conversation. There's not a hint of: 'this is the coded and design reason this is problematic'. There's incessant throwing of aggressive misinformation and complaining for the sake of it. In discord's dms, I've been polite, because the devs have responded politely and with proper criticism. If people start combatative, I will reply in kind.

And I ask: if your issue is 'there are too many combat drifters' this changes things how? The amount of drifters will remain the same, it just broadens options. That's it. Is one more bladesinger truly the deal breaker or is this just a quickly sprung up excuse so that people who were shown to be incorrect to have a last hill to stand on? I nerfed Sentinel, Bandits are currently broken, or is Vaquero the issue? The light armored, sword 3 class?

My issue is misinformation and lack of basis for criticism from most of people flooding, people who don't look at code, don't assist with the project, don't do combat, but feel right at home aggressively demeaning something which isn't even final.

**Comment by bowlofcereal** [comment]
This is absolutely ridiculous and is just going to make you have even more drifter NPCs sitting around doing nothing and not contributing to RP or anything of value. Its just going to make the growing problem of 75% of the server being adventurers even worse.

**Comment by CormanQuewye** [comment]
> This is absolutely ridiculous and is just going to make you have even more drifter NPCs sitting around doing nothing and not contributing to RP or anything of value. Its just going to make the growing problem of 75% of the server being adventurers even worse.

Right. Could you explain you reasoning? Why would this increase the amount of drifter players?

**Comment by ThePainkiller** [comment]
# Hi, dev here. Reviewing.
- Removing rollchances so that every job is unlocked from the start: Makes the 20 triumph buy to unlock everything moot, No.
- 2 Bladesinger slots: No.
- INT to Swordmaster: No.
- Infinite Vaqueros: **NO.**
- 2 Lancer slots: No.
- Infinite Sentinels with nerfs to the ground: **Partial NO.** The only thing I agree with is lowering bow level by one.
- Infinite Swashbucklers: **NO.**
- 2 Witchunter slots: _Could be convinced_, not as impactful as the rest of the changes.
- 3 Physickers: Like I said on the other PR, maximum of **TWO** and I'm being generous, otherwise **No.**

Rare roles should stay limited, and as powerful as they are (their stats reflect their rarity after all), with some minor adjustments. Plate-wearing Drifter classes are limited to 1 slot already (Paladin, Longbeard). Barbarians have the STR and weapon skills to make up for the fact they're supposed to be stark naked (no armor training means they'll fall off balance while wearing one), and if they can't parry or dodge, they will be decapped in two swings of a blade. Same for Amazons, which are the speedier but slightly less buff version of them.

Remember as well that the more self-sufficient we make drifters, the less RP we'll see in the town, because everyone will just rather live their own life on the woods/mountains than interact with towners, which is the main hub for players to live, meet up on, and interact with other players. We want a sandbox of mutual cooperation or at least negative interactions (e.g at least have Rogues stealing from merchant towners roles), not a sandbox of individualists that each do their own mini village with friends and never talk to anyone else for the rest of the Week (i.e, Round).

I see you complain about Warrior being "OP" yet this PR doesn't target them at all in any way other than "I buy armor from smiths become better than royal guard" (again, Royal Guard has been buffed by yours truly, and Warrior has been nerfed by yours truly as well so to be less powerful than a town guard while not completely useless in combat). If a roundstart Town Guard and a roundstart Warrior buy the exact same equipment pieces, the Town Guard will still have 1 level higher weapon skills than them, and be overall better. Plate armor is weak to stabs, but you can mix and match with chainmail which protects against it, to eliminate the bervor meta to protect the neck against decaps now that stabbing the throat is also a valid strat, and allow better minmaxing of protections through carefully selecting your armor pieces against whatever you will be against.

## The whole thread has also gotten quite heated and I must remind everyone to try and be civil at least when expressing your opinions on whether this is a good or bad idea. No matter how illogical decisions by contributors might be, remember in the end what matters is being accepted by devs or approved by maintainers.

In the end, decisions of balance apply to us, devs. Remember every PR is a **suggestion** we **may** or **may not** agree with, and in this dev's suggestion, 95% of chances are a big no from me.

The only reason I'm not closing the PR outright is because it's still **my** decision being expressed here, just from **ONE** dev, and **not the whole team's**. I'll wait to see what other devs say about this on this thread and then communicate the maintainers about it to reach a conclussion.

**Comment by CormanQuewye** [comment]
> # Hi, dev here. Reviewing.
> * Removing rollchances so that every job is unlocked from the start: Makes the 20 triumph buy to unlock everything moot, No.
> * 2 Bladesinger slots: No.
> * INT to Swordmaster: No.
> * Infinite Vaqueros: **NO.**
> * 2 Lancer slots: No.
> * Infinite Sentinels with nerfs to the ground: **Partial NO.** The only thing I agree with is lowering bow level by one.
> * Infinite Swashbucklers: **NO.**
> * 2 Witchunter slots: _Could be convinced_, not as impactful as the rest of the changes.
> * 3 Physickers: Like I said on the other PR, maximum of **TWO** and I'm being generous, otherwise **No.**
> 
> Rare roles should stay limited, and as powerful as they are (their stats reflect their rarity after all), with some minor adjustments. Plate-wearing Drifter classes are limited to 1 slot already (Paladin, Longbeard). Barbarians have the STR and weapon skills to make up for the fact they're supposed to be stark naked (no armor training means they'll fall off balance while wearing one), and if they can't parry or dodge, they will be decapped in two swings of a blade. Same for Amazons, which are the speedier but slightly less buff version of them.
> 
> Remember as well that the more self-sufficient we make drifters, the less RP we'll see in the town, because everyone will just rather live their own life on the woods/mountains than interact with towners, which is the main hub for players to live, meet up on, and interact with other players. We want a sandbox of mutual cooperation or at least negative interactions (e.g at least have Rogues stealing from merchant towners roles), not a sandbox of individualists that each do their own mini village with friends and never talk to anyone else for the rest of the Week (i.e, Round).
> 
> I see you complain about Warrior being "OP" yet this PR doesn't target them at all in any way other than "I buy armor from smiths become better than royal guard" (again, Royal Guard has been buffed by yours truly, and Warrior has been nerfed by yours truly as well so to be less powerful than a town guard while not completely useless in combat). If a roundstart Town Guard and a roundstart Warrior buy the exact same equipment pieces, the Town Guard will still have 1 level higher weapon skills than them, and be overall better. Plate armor is weak to stabs, but you can mix and match with chainmail which protects against it, to eliminate the bervor meta to protect the neck against decaps now that stabbing the throat is also a valid strat, and allow better minmaxing of protections through carefully selecting your armor pieces against whatever you will be against.
> 
> ## The whole thread has also gotten quite heated and I must remind everyone to try and be civil at least when expressing your opinions on whether this is a good or bad idea. No matter how illogical decisions by contributors might be, remember in the end what matters is being accepted by devs or approved by maintainers.
> In the end, decisions of balance apply to us, devs. Remember every PR is a **suggestion** we **may** or **may not** agree with, and in this dev's suggestion, 95% of chances are a big no from me.
> 
> The only reason I'm not closing the PR outright is because it's still **my** decision being expressed here, just from **ONE** dev, and **not the whole team's**. I'll wait to see what other devs say about this on this thread and then communicate the maintainers about it to reach a conclussion.

I never said Warrior was OP, what I said was when discussing balance of the rares, you have to compare them to the base classes. Warrior outranks most of the rares. This isn't an issue for me, I think I've had to mention this thrice now. So, then, why are classes like Vaquero locked and limited? And furthermore, why does Sentinel essentially get a buff to every stat?

**Comment by sanshoom** [comment]
i just gotta say. 20 triumphs to unlock all classes is too fuckin much

**Comment by ThePainkiller** [comment]
> I never said Warrior was OP, what I said was when discussing balance of the rares, you have to compare them to the base classes. Warrior outranks most of the rares. This isn't an issue for me, I think I've had to mention this thrice now. So, then, why are classes like Vaquero locked and limited? And furthermore, why does Sentinel essentially get a buff to every stat?

Warriors don't outrank anyone but non-combat classes, and I'm further adjusting them as we speak.

> This doesn't make drifters more self-sufficient, as the most self-sufficient drifters are base class drifters, so I don't see this as much of a point against this change.

Every class can become self sufficient with enough practice. We want inter-cooperation between roles, with clearly defined specializations, without completely cucking people out of enjoyment if their "party composition" or present players are missing one essential cog in the bigger wheel.

> The nerfs I made to Sentinel didn't _nerf them to the ground_ it gave them stat bonuses in line with the rest of the rares. Should I have buffed rares then, because their stats aren't that great.

Stats do not determine everything in regards of balance, skills and the fact they pre-spawn with a mount do. They are still in tune with the rest of the rares and get the stats for it, while players themselves have complained about not even being able to do twig floors with a 10 INT Sentinel. Gonna repeat it until you understand it, they are rare, and still got the stats and skills to be considered rare. They are rare because they get these superior stats, and they get these superior stats **because** they are rare.

> I don't want to sound mean, but the points you're making contradict what's in the code itself.

Yes that's exactly why I'm working so hard, coding myself to rectify the messy balance we have right now, to a standard that I'm trying to reach a consensus with fellow devs with. Just because it's this way in code RIGHT NOW, doesn't mean it's set in stone, case in point you being allowed to make a pull request to change stuff, and case in point me denying it by having a more thorough approach to it.

> And I do not get why adding one intelligence to swordmaster is an issue. As it currently stands, they get a plus two to strength and a minus one to speed. Warrior (which has been what I primarily compared it to since the concept of balance requires a base position to compare from) gets a plus two strength, plus one endurance, plus one speed. And I'll repeat this again, because people keep putting words in my mouth: I don't think Warrior is OP, but it outranks a good chunk of the rares and is just as strong as many others. Ironbeard and Sentinel (before my nerf) are the only that really compare.

Warrior has a niche as a **purely** oriented combat class. Intelligence is for both learned people, or crafters. We want Warriors to be nigh unable to craft shit to take away their self sustainability, and make them require a party or talk to others in order to get food or any tools done or whatever. I'm literally in fact giving them a -1 INT the same as barbarian, and taking some proficiencies that do not belong in them for that matter. Rest of the rares are getting touch ups as well, like Swordmasters actually getting master at swords, plus other changes that will INDIRECTLY impact them (armor rebalance, wounds caused, weapon rebalance, etc) that is still on the works by yours truly.

> This gets funnier, for example, when you compare Rogue to Swashbuckler, Swashbuckler is a rare but they are codewise just a weaker Rogue. So going: **'NO'** to unlimited swashbucklers 'ruining balance' is beyond comprehension when Rogue is the same thing, but better, and unlimited.

Rogue is a soft antag role, and we want as many of them as possible to wreck havoc, steal, and be nuissances to deal with. Swashbucklers rarely, if ever, act like proper pirates, and usually do their own shit on and about. I'll see about either making it a non-rare option, hence making them unlimited slots, but know that also a full on Drifter PR is on the way to disable the queue system so this will be a non-issue down the line.

> EDIT: to compact my thoughts better, the reason I'm making this PR is that the drifter class separation feels extremely arbritary. Most rares are weaker than base classes, some have better equipment others worse, there's the godawful random roll which the only point I've seen for keeping is to give the triumph system (which itself is riddled with issues) a purpose.

Again, these things **WILL** and **ARE** currently **BEING** worked on. We also want to not rely on that triumph system whose cost is too steep for the buggy state of the system as it is right now. We have higher priority things to fix first, than start applying unrestricted balance changes based on personal opinion as a bandaid fix "for the time being".

**Comment by CormanQuewye** [comment]
> > I never said Warrior was OP, what I said was when discussing balance of the rares, you have to compare them to the base classes. Warrior outranks most of the rares. This isn't an issue for me, I think I've had to mention this thrice now. So, then, why are classes like Vaquero locked and limited? And furthermore, why does Sentinel essentially get a buff to every stat?
> 
> Warriors don't outrank anyone but non-combat classes, and I'm further adjusting them as we speak.
> 
> > This doesn't make drifters more self-sufficient, as the most self-sufficient drifters are base class drifters, so I don't see this as much of a point against this change.
> 
> Every class can become self sufficient with enough practice. We want inter-cooperation between roles, with clearly defined specializations, without completely cucking people out of enjoyment if their "party composition" or present players are missing one essential cog in the bigger wheel.
> 
> > The nerfs I made to Sentinel didn't _nerf them to the ground_ it gave them stat bonuses in line with the rest of the rares. Should I have buffed rares then, because their stats aren't that great.
> 
> Stats do not determine everything in regards of balance, skills and the fact they pre-spawn with a mount do. They are still in tune with the rest of the rares and get the stats for it, while players themselves have complained about not even being able to do twig floors with a 10 INT Sentinel. Gonna repeat it until you understand it, they are rare, and still got the stats and skills to be considered rare. They are rare because they get these superior stats, and they get these superior stats **because** they are rare.
> 
> > I don't want to sound mean, but the points you're making contradict what's in the code itself.
> 
> Yes that's exactly why I'm working so hard, coding myself to rectify the messy balance we have right now, to a standard that I'm trying to reach a consensus with fellow devs with. Just because it's this way in code RIGHT NOW, doesn't mean it's set in stone, case in point you being allowed to make a pull request to change stuff, and case in point me denying it by having a more thorough approach to it.
> 
> > And I do not get why adding one intelligence to swordmaster is an issue. As it currently stands, they get a plus two to strength and a minus one to speed. Warrior (which has been what I primarily compared it to since the concept of balance requires a base position to compare from) gets a plus two strength, plus one endurance, plus one speed. And I'll repeat this again, because people keep putting words in my mouth: I don't think Warrior is OP, but it outranks a good chunk of the rares and is just as strong as many others. Ironbeard and Sentinel (before my nerf) are the only that really compare.
> 
> Warrior has a niche as a **purely** oriented combat class. Intelligence is for both learned people, or crafters. We want Warriors to be nigh unable to craft shit to take away their self sustainability, and make them require a party or talk to others in order to get food or any tools done or whatever. I'm literally in fact giving them a -1 INT the same as barbarian, and taking some proficiencies that do not belong in them for that matter. Rest of the rares are getting touch ups as well, like Swordmasters actually getting master at swords, plus other changes that will INDIRECTLY impact them (armor rebalance, wounds caused, weapon rebalance, etc) that is still on the works by yours truly.
> 
> > This gets funnier, for example, when you compare Rogue to Swashbuckler, Swashbuckler is a rare but they are codewise just a weaker Rogue. So going: **'NO'** to unlimited swashbucklers 'ruining balance' is beyond comprehension when Rogue is the same thing, but better, and unlimited.
> 
> Rogue is a soft antag role, and we want as many of them as possible to wreck havoc, steal, and be nuissances to deal with. Swashbucklers rarely, if ever, act like proper pirates, and usually do their own shit on and about. I'll see about either making it a non-rare option, hence making them unlimited slots, but know that also a full on Drifter PR is on the way to disable the queue system so this will be a non-issue down the line.
> 
> > EDIT: to compact my thoughts better, the reason I'm making this PR is that the drifter class separation feels extremely arbritary. Most rares are weaker than base classes, some have better equipment others worse, there's the godawful random roll which the only point I've seen for keeping is to give the triumph system (which itself is riddled with issues) a purpose.
> 
> Again, these things **WILL** and **ARE** currently **BEING** worked on. We also want to not rely on that triumph system whose cost is too steep for the buggy state of the system as it is right now. We have higher priority things to fix first, than start applying unrestricted balance changes based on personal opinion as a bandaid fix "for the time being".

Certainly, if stats required more rolls instead of pure checks on whose is higher (e.g. sprinting into someone with higher con) and combat being reworked so heavy armor isn't nigh useless I wouldn't disagree, however, Tt keep thing succinct: I do not in the slightest doubt that you're working on fantastic changes, but I cannot work on unimplemented ideas. 

The RNG leads to the rare classes being played less due to it lead to inconsistency with a person's vision of their character's background, leading to people playing these mostly as 'one shots' or not using them at all even when given the option.

And to conclude changes I made are simple and easily undone and would allow for a larger sample size to compare the rares to the base classes.

**Comment by Stutternov** [comment]
I'm finally just getting around to looking through this, some input:

- Physickers recently have had their slots upped to 2. I think having 2 is a fair compromise as they tend to go underutilized as is.
- I could be convinced to have an extra bladesinger or witchhunter but others, such as Vaquero, is better limited to its current slots. +3 speed with those skills is STRONGER than people realize.
- I could also be convinced on the Swordmaster change, but I would actually prefer if it was also locked to middle age or old as it's a role implied to have a large amount of experience with swords.

Overall, I think the slot increases are a bit much and actually just contribute to the issue of having tons of classes that are worthless with little difference to one another. Having strong rare ones is good, and the slots - I believe - re-open if the prior filler dies. So, I don't think it's fully needed to up slots on sentinel, vaquero, etc.

**Comment by Stutternov** [comment]
Right; given the conflicts on the branch along with the period of no changes, going to close this.

Drifter is being touched anyway (and wave drifter system disabled, returning to old pilgrim system likely) so we'll see how it goes. Some changes that were asked for here have been done since PR creation or may be planned.

**Pull request closed without merging**
