### PR TITLE
Minor QOL changes

### PR DESCRIPTION
**Pull request by lavillastrangiato**
## About The Pull Request

Have you ever thought, "this mechanic/design choice is really annoying and kind of a hassle"? Worry not! Now some things are slightly less annoying or difficult.

- You can make smoking pipes with two sticks instead of a log
- You can make zigs with parchment instead of scrolls
- Apples now take 20 minutes to rot. IRL, apples take a pretty long time to rot out in the open!
- Some seeds have descriptions that identify it on examine
- A bar of soap is now in the Dun Manor keep and the bathhouse, like in Dakkatown.
- The Keep on Dun Manor has some changes to its kitchen, west wing, and west courtyard to look less tight and a little more even.

image

## Why It's Good For The Game

Why do pipes need an entire log? Why do zigs need scrolls? I can't fix seed names, but I can at least make them identifiable.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Cre77** [comment]
can you make zig rollies craftable out of parchment as well (not just scrolls) and place some more freely-accessible paper and feathers around kthx :3c

**Comment by lavillastrangiato** [comment]
@Cre77 Sure!

**Comment by lavillastrangiato** [comment]
Everything seems to work but the water barrel reagent increases, and renaming seeds.
image
The code:
image

Here's the seeds:
image
image
image
image

Weirdly, the names do show in StrongDMM!
image

I think it's because there's technically two paths for these, hydroponics.dm and hydroponics/roguetown.dm, but let's give it a shot with both files.

**Comment by CormanQuewye** [comment]
Add in being able to choose to craft the westman's pipe instead of it being random and I'll love you forever.

**Comment by NPC1314** [comment]
This will be up for testmerge next in the queue, but dont do anything just yet. Once the TM is merged, copy paste the new kitchen you made onto the latest map, but that wont be for another 24 hours at least.

**Comment by lavillastrangiato** [comment]
Going to close this because ewww map conflicts uehhghugugh. The other changes will be back soon, though.

**Pull request closed without merging**
