### PR TITLE
minor sewing changes, ADDS DYE STATION

### PR DESCRIPTION
**Pull request by YuiY1997**
## About The Pull Request

adds a dye station and makes dresses easier to craft

Pictures in  the comments

## Why It's Good For The Game

This allows you to dye clothes with a new craftable dye station. More drip is better.

Also dresses were difficult 4, which was definitely too high for non-protective gear that was not fancy.

I think that in the future we might want to make it so only the merchant has access to the dye barrel and it is mapped directly into their shop, but we'll see how this goes!

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by YuiY1997** [comment]
keep in mind the structure still needs to be mapped in

**Comment by YuiY1997** [comment]
I am unsure how to spawn this in to show that it works, but it's ported directly from hearthstone where it does work.

**Comment by YuiY1997** [comment]
forgot icons just a second

**Comment by YuiY1997** [comment]
icons added!

**Comment by YuiY1997** [comment]
since these are mapped I should make them craftable

**Comment by YuiY1997** [comment]
ROGUEWORLD (18+) 2024-09-23 040028

ROGUEWORLD (18+) 2024-09-23 040112

No idea why it's saying the compile is failing on github because it works perfectly fine in game

**Comment by YuiY1997** [comment]
I forgot to push the DME that included the new file. Fixed! Good to go!

**Comment by YuiY1997** [comment]
has anyone taken a look at this?

**Comment by ThePainkiller** [comment]
Can you take out of that list anything that does NOT have a white or greyscale version of itself? Dying gambesons by using innate BYOND `color` var will really make some sprites ugly as shit.

**Review by Optimism333 — COMMENTED** [review]
The difficulty of dress crafting being lowered is definitely good. Address Nicholas' concerns about the colors on certain items and I think this could make a fine addition to the server.

**Comment by YuiY1997** [comment]
@NPC1314 

How do I fix the merge conflict on the sprite?

**Comment by YuiY1997** [comment]
@NPC131

4 I didn't know how to conventionally fix the merge conflcit, so I just took the current structures.dmi file and overwrote the one I made, then added the new sprites.

It sitll says there is a merge conflict, but the file should be up to date.

**Pull request closed without merging**
