### PR TITLE
Mass Sprite Update for alot of different items

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
### All of these sprites are of Takyon69 from Blackstone.

New Waterskin sprites for onmob and the item.

New grimdark apple tree sprites

Various new tables like the long table and the reinforced one aswell as a new floorhatch

New water bin, barrels, chairs and palisades to name a few

## Why It's Good For The Game

A breath of fresh air into the game with new quality and better sprites from Takyon, because it's a shame to let all these go lost due to Blackstone's death.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by NPC1314** [comment]
Waterskin, crops, floorhatch and palisades looks good, several of the others less so, esp. oversaturation being a issue (while crops are desaturated) and a few recent additions being overwritten for no gain. Would have been clearer with a before and after pic.

Those replacement sprites seems ok, the rest shouldnt be replacements, just alt versions IMO, full replacing sprites shouldnt be done if its not crystal clear its just an upgrade (like waterskin).

**Comment by BadAtThisGame302** [comment]
> Waterskin, crops, floorhatch and palisades looks good, several of the others less so, esp. oversaturation being a issue (while crops are desaturated) and a few recent additions being overwritten for no gain. Would have been clearer with a before and after pic.
> 
> Those replacement sprites seems ok, the rest shouldnt be replacements, just alt versions IMO, full replacing sprites shouldnt be done if its not crystal clear its just an upgrade (like waterskin).

What sprites do you not want.

**Comment by ThePainkiller** [comment]
Honestly I love all of them and they look as an improvement over their original, just by reshading the wood colors, it has my okay

**Comment by NPC1314** [comment]
Rebel has posted in discord about the need for screenshots in PRs, keep it in mind please, because putting the work of screenshotting changes on the reviewer is kinda annoying and makes me wonder if you tested how it looks ingame compared to the replaced icons.  Its far from just wood palette changes, see the pic below.

Below are the issues specified, please adress.
review

**Comment by NPC1314** [comment]
stale, marked for death

**Pull request closed without merging**
