### PR TITLE
Dun manor Decorations and general rework

### PR DESCRIPTION
**Pull request by Dorodomki**
## About The Pull Request

this pr reworks dun manor almost entirely starting with balances on the ore gathering on the mines, more tiles have been added while most of the goblins got deleted for server performance and rare ore tiles have been removed for balance, mount decap is for that kind of ore runs.

- most of the update info are on the commits of the pr but things to note are the change of the stall keys from the merchant, now they are back on the steward storage since these keys  and structures are owned by the king, not by the merchant who is a competitor against the town artisans, other note is the replacement of the butcher farm key for the soilson key that works, the farm key doesn't open anything

- the fortification of the village by making it harder to rush on PVE events, isn't something complicated infiltrate into the town and any competent rogue/thief can do it but this keeps the villagers like the butcher and soilsons more safe and allows the guards to take the defenses of the town a bit more near to the players instead of be stuck into the gates 

- adds the dakkatown ship to the latejoin bridge, this ship was needed into the map and looks awesome as hell, reworked it a bit with the addition of veils and a broken wheel to make it non functional yet the best looking latejoin spawn

- smithy QOL adds copper ores and ingots to the smithy in the makers guild, the apprentices get 2 beds now and the forges are more near for PEAK efficiency (truly no but is more comfortable) 

- clothes! adds clothes to some houses for drip and inmersion sense, the mayor, masons, smiths, soilsons get randomized clothes in their closet, one pair of thighs and shirt, the towner departments get the half of it being a shirt or a pair of thighs, they didn't have enough coin for the two 

 - garrison rebalance, the actual garrison armory was ported from OG map and that one was over buffed by the old garrison players with steel gear, to note i had to remove 6 steel hauberks, 5 gambesons, 4 steel helmets and camouflaged steel weapons like a polemace and war flails where the guards don't get one skill point to use them, their new balance includes the addition of only iron tier gear on weaponry and spare/old armors such as iron skullcaps, iron chainmaille and gorgets while it also gives them a bonus such as leather gloves and thorn needles and cloth to supply themselves with something related to first aid, their role is fight, protect and survive the fight is something they need to keep protecting the town and the citizens, their new gear allows that and the steel is a luxury the king, steward, captain and rarely the smiths have to give to them, if there aren't smiths and their starting steel gear is broken they can get the iron replacements before obtain new gear made out of steel, iron or copper.

- water, water, water!, adds more water sources to the map, currently the only ways to obtain clear drinkable water are the village river and the wells, i added some mineral water sources that are inside the caves and other that is from the mount decap 

- removes silver gadders, in the graveyard was a silver dagger for anyone to grab, replaced it with an amulet of necra and deleted it since is a very good weapon for the first to grab

- masons QOL adds one blacksmith key more so the two masons can have their way to drop resources in the makers guild and moves the barrel of water on the dinner hall, it was too far away on the lower floor exit

-water part 2, adds buckets for the wells, i thought the people stole these buckets but they weren't mapped 

## Why It's Good For The Game

big improvements were made 

<details><summary>Details</summary>
<p>
screenshots of the map 

mason mine
image
image
image

dakkatown ship latejoin

image
image
image
image

village 

image

garrison armory

image
image

maker's guild 

image

</p>
</details> 

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Ickysoup** [comment]
Can you add random clothes to the closets in the Princes and or King's room? The variety would be welcomed.

**Comment by Dorodomki** [comment]
> Can you add random clothes to the closets in the Princes and or King's room? The variety would be welcomed.

suggestion applied and they get tunics + the king gets royal purple clothes

**Comment by lavillastrangiato** [comment]
image
The stuff I highlighted in red is, unfortunately, ugly as hell. It's also unnecessary and kind of takes away from work that a mason can already do. I would suggest getting rid of it.

**Comment by Dorodomki** [comment]
> image The stuff I highlighted in red is, unfortunately, ugly as hell. It's also unnecessary and kind of takes away from work that a mason can already do. I would suggest getting rid of it.

i made that "paper fortification" so the masons and carpenters don't have to spend over 15 minutes doing something that wouldn't protect against anything even when is a joke

that palisade is to allow the garrison roam the village without be stuck into the gate and see who wants to come into the village first

and then into the town, mainly to protect the soilsons and butcher, mayor in a better way without make it boring for the garrison players and avoid drifters getting inside the village to steal or kill unarmed peasants

**Comment by lavillastrangiato** [comment]
How are they stuck in the village? They're perfectly free to go and patrol outside, the gate's not exactly making it better or worse to patrol.

Again, I don't even mind the watchtower, it's a cute little addition, but the palisades there look cluttered and clash with the bridge/general surroundings of the outskirts.

**Comment by NPC1314** [comment]
This is pretty hard to overview and has some controversial bits, with how poor our mapping system is for conflicts and the need to TM stuff smaller mapping PRs are a lot easier to manage. 

Splitting off say the adding buckets and little tweaks to the village would be my pick, so we can merge the current TM map PR, finish off the manor in #574 and add the general little tweak on top of that, before moving on to the other stuff, barracks being the next point of interest.

**Comment by NPC1314** [comment]
It's gettings its TM

**Comment by NPC1314** [comment]
actually no since the new centcom change will conflict with TM, remove it before we can go ahead

**Review by NPC1314 — APPROVED** [review]
Overwrites almost all fixed, Ill sort the few remaining.

**Pull request merged**
