### PR TITLE
Immortal Aasimar (Customization change)

### PR DESCRIPTION
**Pull request by Optimism333**
## About The Pull Request
- Aasimar now have a single age selection: "Immortal"
- It gives no stat negatives or bonuses, same as the default "Adult" age for other races
- "Immortal" has been added to the acceptable ages for the Veteran role, as well as other roles that had age restrictions: (Garrison Guard, Royal Guard, Nitemaiden, Mayor, etc)
- To balance this, aasimar veterans have higher strength but lower mental bonuses, and a malus to speed instead of a bonus (can further adjust as necessary)
- Cleaned up some code redundancies (mostly removed acceptable age lists from jobs that are intended to be open to all ages, it was an unnecessary check)
- Removed stubble from aasimar (it looked particularly horrendous on necral male aasimar), it seems more fitting for them to have clean shaven faces

Screenshot (195)

Screenshot (196)

Screenshot (198)

## Why It's Good For The Game
- Continues the work of bringing aasimar further in line with their lore
- Stubble looked terrible on necral aasimar, and it seemed better to just throw it in the trash. The golem soldiers shall have clean shaven faces (they can't grow beards anyways, so it made little sense)

## Did You Test It
- Did some brief tests and all seemed alright. Age selections for aasimar and other races in character selection behaved as normal, nothing runtimed

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
This brings into question if their advanced age modifies anything, as people of old age usually get modifiers for skills (+1 weapon skills or practical knowledge skills like blacksmithing in the case of blacksmith) BUT lowered stats. Boon variable calculation also makes it so that old people get 80% of the boon a normal adult would get out of how they're already learned and get extra skill levels. Would their "immortal" age need to be adjusted as well for these two particular age balance related scenarios?

**Comment by Optimism333** [comment]
> This brings into question if their advanced age modifies anything, as people of old age usually get modifiers for skills (+1 weapon skills or practical knowledge skills like blacksmithing in the case of blacksmith) BUT lowered stats. Boon variable calculation also makes it so that old people get 80% of the boon a normal adult would get out of how they're already learned and get extra skill levels. Would their "immortal" age need to be adjusted as well for these two particular age balance related scenarios?

Currently "Immortal" for aasimar functions like "Adult" for other races. It's just their default age, with no skill or stat increases/penalties.

The only difference is it is also allowed in certain jobs that are locked for other races unless they are middle-aged or above (Mayor, Veteran).

This shouldn't be a serious balance concern for Mayor, as that one has already been revised and rebalanced in a previous pr. But since this would allow them into Veteran, I had to modify the stats to try not to make it too overpowered.

If we add racial perks or other things to differentiate our races, perhaps "Immortal" could have some flavor effects.

**Comment by ThePainkiller** [comment]
> Currently "Immortal" for aasimar functions like "Adult" for other races. It's just their default age, with no skill or stat increases/penalties.
 
> The only difference is it also allows aasimar into certain jobs that are locked for other races unless they are middle-aged or above (Mayor, Veteran).

> This shouldn't be a serious balance concern for Mayor, as that one has already been revised and rebalanced in a previous pr. But since this would allow them into Veteran, I had to modify the stats to try not to make it too overpowered.

> Let me know if that answered your question.

My only unanswered question is "should they be included on the learning penalty due to being people who lived larger-than-dynasties lifespans as well as old people do?"

**Comment by Optimism333** [comment]
> > Currently "Immortal" for aasimar functions like "Adult" for other races. It's just their default age, with no skill or stat increases/penalties.
> 
> > The only difference is it also allows aasimar into certain jobs that are locked for other races unless they are middle-aged or above (Mayor, Veteran).
> 
> > This shouldn't be a serious balance concern for Mayor, as that one has already been revised and rebalanced in a previous pr. But since this would allow them into Veteran, I had to modify the stats to try not to make it too overpowered.
> 
> > Let me know if that answered your question.
> 
> My only unanswered question is "should they be included on the learning penalty due to being people who lived larger-than-dynasties lifespans as well as old people do?"

Ah, I think I understand. I didn't quite know what code you were referring to at first, you meant this, right?

image

I would say yes, that's probably fair. If you can put it into a review, I'll be happy to apply it.

**Comment by ThePainkiller** [comment]
> Ah, I think I understand. I didn't quite know what code you were referring to at first, you meant this, right?
> image
> 
> If so I would say yes, that's probably fair. If you can put it in a review, or show me how that'd be done, I'll be happy to apply it.
> 
> I'm not quite sure how to rewrite this line so it checks for both "Old" and "Immortal".

Nah, if they aren't getting any extra skill levels nor stats due to their race beyond the inherent racial bonuses, I don't see a reason to punish them further with 20% less boon experience tbh

**Comment by Optimism333** [comment]
Removed the lines altering the bandit and vampire lord page to atomize this pr, and I now have a better idea of what those lines are for.

**Review by ThePainkiller — APPROVED** [review]
Good flavor, sorry for putting this on the backburner for this long

**Comment by Optimism333** [comment]
> Good flavor, sorry for putting this on the backburner for this long

No worries!

**Pull request merged**
